### ISSUE TITLE
Add Congestion Control to Hysteria V.2

### ISSUE THREAD

**Issue by ellahmezar** [apernet/hysteria#1010]
Hi ,
Hope you're doing great .
Please add congestion control [ BBR , CUBIC , NEW-RENO ] to both server and client config for hysteria 2  . It will be great if we choose this manually .
Many thanks and wish you the best !

**Comment by haruue** [comment]
Hello,

BBR congestion control is already supported in Hysteria. To enable BBR, you may set the `ignoreClientBandwidth` in the server config or remove the `bandwidth` in the client config, as appropriate. For further details, please refer to our documentation:

+ https://hysteria.network/docs/advanced/Full-Server-Config/#ignore-client-bandwidth
+ https://hysteria.network/docs/advanced/Full-Client-Config/#bandwidth

Regarding the inclusion of the CUBIC and NEW_RENO congestion control algorithms, could you please provide us with specific use cases or scenarios where you believe the addition of these algorithms would significantly benefit Hysteria users?

**Comment by ellahmezar** [comment]
Hi @haruue 
Hope you're fine .
For using BBR in server side ,  What should I do ? just I set  [ ignoreClientBandwidth = true ] and no changes in bandwidth items in server ? [ up = 1gbps and down= 1gbps ]
Many thanks

**Comment by haruue** [comment]
> For using BBR in server side , What should I do ? just I set [ ignoreClientBandwidth = true ] and no changes in bandwidth items in server ? [ up = 1gbps and down= 1gbps ]

Yes.

Please check our document: 

> `ignoreClientBandwidth` is a special option that, when enabled, makes the server to disregard any bandwidth hints set by clients, **opting to use a more traditional congestion control algorithm (currently BBR) instead.** This effectively overrides any bandwidth values set by clients in both directions.

https://hysteria.network/docs/advanced/Full-Server-Config/#ignore-client-bandwidth

**Comment by haruue** [comment]
And note that the `bandwidth` in the server config will also be ignored if `ignoreClientBandwidth` is set to true. In other words, it won't act as a speed limiter in BBR mode.

**Comment by tobyxdd** [comment]
We already have BBR and that's the default. No plans for cubic or new reno though, as I don't really see a reason why anyone should choose those legacy algorithms over BBR.
