### ISSUE TITLE
It is recommended to change the configuration file format in homebrew to yaml

### ISSUE THREAD

**Issue by maoxikun** [apernet/hysteria#1028]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It is recommended to change the config.json configuration file to config.yaml.

**Describe alternatives you've considered**
It is recommended to change the config.json configuration file to config.yaml.

**Additional context**
The configuration file in the official one-click install script uses the yaml format.

**Comment by haruue** [comment]
Hello,

The Hysteria Formula in the homebrew is not maintained by us.

I checked the [commit history][1] in the [homebrew-core][2] repo, it seems like the current maintainer is @chenrui333. Maybe you can contact with them for more help.

[1]: https://github.com/Homebrew/homebrew-core/commits/master/Formula/h/hysteria.rb
[2]: https://github.com/Homebrew/homebrew-core

**Comment by maoxikun** [comment]
Thanks.

**Comment by chenrui333** [comment]
thanks @maoxikun, should be fixed via https://github.com/Homebrew/homebrew-core/pull/170341
