### ISSUE TITLE
[AlmaLinux] Unit file hysteria-server.service does not exist. 

### ISSUE THREAD

**Issue by lyjnb14** [apernet/hysteria#1029]
[root@alpha-3cd93aefda ~]# systemctl start hysteria-server.service
Failed to start hysteria-server.service: Unit hysteria-server.service not found.
[root@alpha-3cd93aefda ~]#  systemctl enable hysteria-server.service
Failed to enable unit: Unit file hysteria-server.service does not exist.

**Comment by haruue** [comment]
报错是没有 hysteria-server.service 这个 unit。 你用的什么系统？ 运行安装脚本之后有什么输出？

**Comment by lyjnb14** [comment]
> 报错是没有 hysteria-server.service 这个 unit。 你用的什么系统？ 运行安装脚本之后有什么输出？

系统是Linux ，运行完脚本以后我就正常输入systemctl start hysteria-server.service

**Comment by lyjnb14** [comment]
> 您好， 您需要提供以下信息：
> 
> 1. 您使用的 Linux 系统「发行版名称」与「版本号」。 如果您不知道如何获取这些信息， 请执行以下命令， 然后把输出贴出来（截图也可以）。
> 
> ```
> cat /etc/os-release
> cat /etc/lsb-release
> cat /proc/version
> ```
> 
> 2. 执行安装脚本之后输出的信息， 如果您在之前执行安装脚本时未保留输出， 你可以重新运行一次， 并把输出贴上来。

[root@alpha-3cd93aefda ~]# cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.6 (Sky Tiger)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.6 (Sky Tiger)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"


执行后输出信息：
Install /etc/systemd/system/hysteria-server.service ... ok
Install /etc/systemd/system/hysteria-server@.service ... ok

Congratulation! Hysteria 2 has been successfully installed on your server.

What's next?

        + Take a look at the differences between Hysteria 2 and Hysteria 1 at https://hysteria.network/docs/misc/2-vs-1/
        + Check out the quick server config guide at https://hysteria.network/docs/getting-started/Server/
        + Edit server config file at /etc/hysteria/config.yaml
        + Start your hysteria server with systemctl start hysteria-server.service
        + Configure hysteria start on system boot with systemctl enable hysteria-server.service

[root@alpha-3cd93aefda ~]# openssl req -x509 -nodes -newkey ec:<(openssl ecparam -name prime256v1) -keyout /etc/hysteria/server.key -out /etc/hysteria/server.crt -subj "/CN=bing.com" -days 36500 && sudo chown hysteria /etc/hysteria/server.key && sudo chown hysteria /etc/hysteria/server.crt
Generating an EC private key
writing new private key to '/etc/hysteria/server.key'
-----
[root@alpha-3cd93aefda ~]# systemctl start hysteria-server.service
Failed to start hysteria-server.service: Unit hysteria-server.service not found.
[root@alpha-3cd93aefda ~]# systemctl enable hysteria-server.service
Failed to enable unit: Unit file hysteria-server.service does not exist.

**Comment by haruue** [comment]
感谢提供信息。
我们的安装脚本尚未针对此发行版 `AlmaLinux 8.6` 进行过测试。 我们会安排测试来研究兼容性问题。
此外， 如果你是刚开了个 VPS 并且对发行版无特定要求， 我建议你直接去后台重装成 Debian 12 以快速解决问题。

**Comment by lyjnb14** [comment]
> 感谢提供信息。 我们的安装脚本尚未针对此发行版 `AlmaLinux 8.6` 进行过测试。 我们会安排测试来研究兼容性问题。 此外， 如果你是刚开了个 VPS 并且对发行版无特定要求， 我建议你直接去后台重装成 Debian 12 以快速解决问题。

请问支持的linux有那些

**Comment by lyjnb14** [comment]
> 感谢提供信息。 我们的安装脚本尚未针对此发行版 `AlmaLinux 8.6` 进行过测试。 我们会安排测试来研究兼容性问题。 此外， 如果你是刚开了个 VPS 并且对发行版无特定要求， 我建议你直接去后台重装成 Debian 12 以快速解决问题。
Debian 12  怎么安装hysteria2

**Comment by lyjnb14** [comment]
> 感谢提供信息。 我们的安装脚本尚未针对此发行版 `AlmaLinux 8.6` 进行过测试。 我们会安排测试来研究兼容性问题。 此外， 如果你是刚开了个 VPS 并且对发行版无特定要求， 我建议你直接去后台重装成 Debian 12 以快速解决问题。

我重装Debian12 后输入安装指令显示
root@alpha-3cd93aefda:~# bash <(curl -fsSL https://get.hy2.sh/)
-bash: curl: command not found
请问这怎么解决

**Comment by haruue** [comment]
> 我重装Debian12 后输入安装指令显示 root@alpha-3cd93aefda:~# bash <(curl -fsSL https://get.hy2.sh/) -bash: curl: command not found 请问这怎么解决

你需要执行

```
apt update && apt install -y curl
```

**Comment by lyjnb14** [comment]
> > 我重装Debian12 后输入安装指令显示 root@alpha-3cd93aefda:~# bash <(curl -fsSL https://get.hy2.sh/) -bash: curl: command not found 请问这怎么解决
> 
> 你需要执行
> 
> ```
> apt update && apt install -y curl
> ```
> 
> 然后再次重新执行安装脚本。

还是无法运行脚本

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Apr  9 06:40:04 2024 from 39.128.100.28
-bash: .: /etc/profile.d/bash_completion.sh: cannot execute binary file
root@alpha-3cd93aefda:~# apt update && apt install -y curl
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:4 http://security.debian.org/debian-security bookworm-security/main Sources [86.6 kB]
Get:5 http://security.debian.org/debian-security bookworm-security/non-free-firmware Sources [796 B]
Get:6 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [150 kB]
Get:7 http://security.debian.org/debian-security bookworm-security/main Translation-en [90.3 kB]
Get:8 http://security.debian.org/debian-security bookworm-security/non-free-firmware amd64 Packages [688 B]
Get:9 http://deb.debian.org/debian bookworm/non-free-firmware Sources [6,168 B]
Get:10 http://deb.debian.org/debian bookworm/main Sources [9,489 kB]
Get:11 http://deb.debian.org/debian bookworm/main amd64 Packages [8,786 kB]
Get:12 http://deb.debian.org/debian bookworm/main Translation-en [6,109 kB]
Get:13 http://deb.debian.org/debian bookworm/non-free-firmware amd64 Packages [6,208 B]
Get:14 http://deb.debian.org/debian bookworm-updates/main Sources.diff/Index [9,483 B]
Ign:14 http://deb.debian.org/debian bookworm-updates/main Sources.diff/Index
Get:15 http://deb.debian.org/debian bookworm-updates/main amd64 Packages.diff/Index [9,483 B]
Get:16 http://deb.debian.org/debian bookworm-updates/main Translation-en.diff/Index [9,483 B]
Get:17 http://deb.debian.org/debian bookworm-updates/main amd64 Packages T-2023-12-29-1403.39-F-2023-08-26-1408.20.pdiff [7,638 B]
Get:17 http://deb.debian.org/debian bookworm-updates/main amd64 Packages T-2023-12-29-1403.39-F-2023-08-26-1408.20.pdiff [7,638 B]
Get:18 http://deb.debian.org/debian bookworm-updates/main Translation-en T-2023-12-29-1403.39-F-2023-08-26-1408.20.pdiff [10.4 kB]
Get:18 http://deb.debian.org/debian bookworm-updates/main Translation-en T-2023-12-29-1403.39-F-2023-08-26-1408.20.pdiff [10.4 kB]
Get:19 http://deb.debian.org/debian bookworm-updates/non-free-firmware Sources [2,076 B]
Get:20 http://deb.debian.org/debian bookworm-updates/non-free-firmware amd64 Packages [616 B]
Get:21 http://deb.debian.org/debian bookworm-updates/non-free-firmware Translation-en [384 B]
Get:22 http://deb.debian.org/debian bookworm-updates/main Sources [17.4 kB]
Get:23 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [12.7 kB]
Get:24 http://deb.debian.org/debian bookworm-updates/main Translation-en [13.8 kB]
Fetched 25.1 MB in 3s (8,119 kB/s)              
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
79 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Repository 'http://deb.debian.org/debian bookworm InRelease' changed its 'Version' value from '12.1' to '12.5'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcurl3-gnutls libcurl4
The following NEW packages will be installed:
  curl libcurl4
The following packages will be upgraded:
  libcurl3-gnutls
1 upgraded, 2 newly installed, 0 to remove and 78 not upgraded.
Need to get 1,090 kB of archives.
After this operation, 1,371 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 libcurl4 amd64 7.88.1-10+deb12u5 [390 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 curl amd64 7.88.1-10+deb12u5 [315 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 libcurl3-gnutls amd64 7.88.1-10+deb12u5 [385 kB]
Fetched 1,090 kB in 0s (24.1 MB/s)   
Selecting previously unselected package libcurl4:amd64.
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'laptop-detect' is missing final newline
E: Sub-process /usr/bin/dpkg returned an error code (2)
root@alpha-3cd93aefda:~# bash <(curl -fsSL https://get.hy2.sh/)
-bash: curl: command not found

**Comment by haruue** [comment]
```
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'laptop-detect' is missing final newline
```

网上能搜到这个问题， 但是我从来没遇到。
要不你再重装一下试试。 
顺便你用的啥 VPS 商啊， 这种给人感觉通常是网络原因导致的， 因为 Debian 默认通过 http 而不是 https 下载包。

**Comment by lyjnb14** [comment]
> ```
> dpkg: unrecoverable fatal error, aborting:
>  files list file for package 'laptop-detect' is missing final newline
> ```
> 
> 网上能搜到这个问题， 但是我从来没遇到。 要不你再重装一下试试。 顺便你用的啥 VPS 商啊， 这种给人感觉通常是网络原因导致的， 因为 Debian 默认通过 http 而不是 https 下载包。

vps是alphavps的德国线路 被坑了哎 好的我再重装试试
