### ISSUE TITLE
关于hysteria2报大量的"error": "too many open streams

### ISSUE THREAD

**Issue by kuangyezhifeng** [apernet/hysteria#1037]
**描述问题**
[root@localhost ~]# tail -f /var/log/messages
查看系统日志显示大量的"error": "too many open streams

**如何复现**
不好复现

**预期行为**
我想知道的是这个是hy2程序问题，还是系统文件连接数开的不够大，我已经设置了最大的文件打开连接数了,还是报错了
vim /etc/sysctl.conf
fs.file-max = 655360
sysctl -p

* hard nofile 655360 #任何用户可以打开的最大句柄数(超过会报错)
* soft nofile 655360 #任何用户可以打开的最大句柄数(超过会警告)
* hard nproc 655360 #任何用户可用的最大进程数量(超过会报错)
* soft nproc 655360 #任何用户可用的最大进程数量(超过会警告)

**日志**
 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59688", "reqAddr": "23.109.225.228:5859", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59534", "reqAddr": "173.0.10.147:6323", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59382", "reqAddr": "45.41.172.206:5949", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:58986", "reqAddr": "89.116.78.168:5779", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59696", "reqAddr": "154.29.232.184:6844", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59710", "reqAddr": "104.239.77.18:5741", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59100", "reqAddr": "43.228.237.162:6108", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59900", "reqAddr": "206.41.172.116:6676", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59940", "reqAddr": "154.85.124.141:6002", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:59852", "reqAddr": "185.242.93.219:8559", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:58792", "reqAddr": "104.239.7.105:6509", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:36654", "reqAddr": "119.42.38.56:6238", "error": "too many open streams"}
Apr 14 04:31:47 localhost hysteria2: 2024-04-14T04:31:47+08:00#011#033[33mWARN#033[0m#011SOCKS5 TCP error#011{"addr": "127.0.0.1:36794", "reqAddr": "45.131.9

**设备和操作系统**
linux  centos7 

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by tobyxdd** [comment]
https://hysteria.network/zh/docs/advanced/Full-Server-Config/#:~:text=maxIdleTimeout%3A%2030s-,maxIncomingStreams,-%3A%201024

**Comment by zhost001** [comment]
系统的事情,ubuntu我调了后就没有提示了

echo "ulimit -SHn 102400" >> /etc/rc.local
cat >> /etc/security/limits.conf << EOF
*           soft   nofile       655350
*           hard  nofile       655350
*           soft   memlock      262144
*           hard  memlock      262144
EOF
sysctl -w vm.nr_hugepages=256
sed -i '1s/^/vm.nr_hugepages=256\n/' /etc/sysctl.conf

echo "ulimit -n 99999" >> /etc/profile
echo "ulimit -Sn 99999" >> /etc/profile
echo "ulimit -Hn 99999" >> /etc/profile
echo "ulimit -u unlimited" >> /etc/profile
echo "ulimit -d unlimited" >> /etc/profile
echo "ulimit -m unlimited" >> /etc/profile
echo "ulimit -s unlimited" >> /etc/profile
echo "ulimit -t unlimited" >> /etc/profile
echo "ulimit -v unlimited" >> /etc/profile
