### ISSUE TITLE
权限问题导致systemctl start启动失败

### ISSUE THREAD

**Issue by 46319943** [apernet/hysteria#1040]
**Describe the bug**
使用Root账户在letsencrypt注册证书之后，证书私钥文件权限是只有所有用户可以读取，这就导致服务在以hysteria的组和用户启动的时候，无法读取证书文件。
然而，这个错误并不会在服务启动的时候显示。客户端连接失败的时候，也不会在服务端显示，只会在客户端显示。当使用第三方客户端进行连接的时候，甚至不会提示错误，从而造成了错误定位困难。
相似的情况也在 https://github.com/apernet/hysteria/issues/793 中出现

希望在文档中能够明确提示这个权限问题，同时让该错误能够在服务端显示，避免错误难以定位。

hysteria客户端显示错误：
```
failed to initialize client     {"error": "connect error: INTERNAL_ERROR (remote): open /etc/letsencrypt/live/***/fullchain.pem: permission denied
```

hysteria服务端显示无任何错误，但客户端无法连接：
```
INFO        server mode
INFO        server up and running        {"listen": ":443"}
```

**Comment by haruue** [comment]
感谢报告这个问题。
在 c4993f8dd1c0e54599d39706dc0a71a5fb51d725 中， 读取证书被推迟到了客户端握手时， 这应该是导致这个问题的原因。
我们会在启动的时候额外加个检查。
