### ISSUE TITLE
[FR] Hysteria API to sync users

### ISSUE THREAD

**Issue by UbiVPN** [apernet/hysteria#1043]
**Is your feature request related to a problem? Please describe.**
Need to sync users to Hysteria server.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I have been following this project for a long time. The proxy tool is very useful, but it does not support syncing users to the Hysteria server side. It feels inconvenient, and although I can find other methods, they are not as direct as official support.

**Comment by haruue** [comment]
Looks like you are a VPN provider? 

Please take a look at our [External Authentication API](https://hysteria.network/docs/advanced/Full-Server-Config/#authentication) and [Traffic Stats API](https://hysteria.network/docs/advanced/Traffic-Stats-API/), which are designed for VPN providers.

With these APIs, you can forward Hysteria's auth request to your VPN backend to auth users or kick connected users offline, without syncing any of your user information to Hysteria.
