### ISSUE TITLE
 failed to initialize client  sendmsg: invalid argument

### ISSUE THREAD

**Issue by sajjadintel** [apernet/hysteria#1044]
**Describe the bug**
When I try to run hysteria as client on centos 7 I get this error:
```
2024-04-16T14:27:18+08:00       INFO    client mode
2024-04-16T14:27:18+08:00       FATAL   failed to initialize client     {"error": "connect error: INTERNAL_ERROR (local): write udp [::]:58109->91.107.3.1:47613: sendmsg: invalid argument"}
You have mail in /var/spool/mail/root
```

client config:
```
server: hy.ddddd.us:47612

auth: 2Vy56kcDHnQaujZ6kyCcnPn29q

bandwidth:
  up: 400 mbps
  down: 400 mbps

socks5:
  listen: 127.0.0.1:1080

http:
  listen: 127.0.0.1:8081
```

**Device and Operating System**
Centos 7

**Comment by haruue** [comment]
Hello, CentOS 7 will reach its end of life (EOL) in as soon as 2 months. If you are just buying a new VPS instance, it is recommended to upgrade to CentOS Stream 9 or any other modern Linux distro likes Debian 12.
