### ISSUE TITLE
搭了好几台服务器，AWS的，都出现这个问题

### ISSUE THREAD

**Issue by wolf5418** [apernet/hysteria#1051]
win10 V2RAY启动服务(2024/04/21 20:21:22)...
2024-04-21T20:21:22+08:00	[34mINFO[0m	client mode
2024-04-21T20:21:22+08:00	[31mFATAL[0m	failed to read client config	{"error": "While parsing config: yaml: invalid trailing UTF-8 octet"}
2024-04-21T20:21:22+08:00	[34mINFO[0m	client mode
2024-04-21T20:21:22+08:00	[31mFATAL[0m	failed to read client config	{"error": "While parsing config: yaml: invalid trailing UTF-8 octet"}

服务端正常运行
Apr 21 12:16:08 ip-172-31-6-116 systemd[1]: Started Hysteria Server Service (config.yaml).
Apr 21 12:16:08 ip-172-31-6-116 hysteria[79035]: 2024-04-21T12:16:08Z        INFO        server mode
Apr 21 12:16:08 ip-172-31-6-116 hysteria[79035]: 2024-04-21T12:16:08Z        INFO        server up and running        {"listen": ":443"}
root@ip-172-31-6-116:~# iptables -I INPUT -p tcp --dport 443 -j ACCEPT
root@ip-172-31-6-116:~# systemctl status hysteria-server.service
● hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-04-21 12:16:08 UTC; 2min 37s ago
   Main PID: 79035 (hysteria)
      Tasks: 4 (limit: 2263)
     Memory: 5.7M
        CPU: 34ms
     CGroup: /system.slice/hysteria-server.service
             └─79035 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml

Apr 21 12:16:08 ip-172-31-6-116 systemd[1]: Started Hysteria Server Service (config.yaml).
Apr 21 12:16:08 ip-172-31-6-116 hysteria[79035]: 2024-04-21T12:16:08Z        INFO        server mode
Apr 21 12:16:08 ip-172-31-6-116 hysteria[79035]: 2024-04-21T12:16:08Z        INFO        server up and running        {"listen": ":443"}

**Comment by haruue** [comment]
您的客户端配置文件（包括注释内容）里是有汉字或者全角标点符号（例如全角的冒号 `：` 或者引号 `“”`）吗？ 

Windows 上的编码问题对于新手来说非常复杂。 

如果您知道如何编码转换， 可以先把客户端配置文件的编码转换成 `UTF-8 without BOM` 再启动客户端试试。 

如果您不懂如何转换编码或者没有相应的工具， 通常来说， 把配置文件中的汉字全部删掉可以解决问题。 

如果您觉得是全角标点导致的问题， 也可以把文件内容粘贴上来（可以删掉服务器地址和密码等敏感信息）， 我们可以帮您检查是否有这类错误。

**Comment by wolf5418** [comment]
非常感谢你，你这个提醒太重要了，我删除了之前油管教程上客户端的中文字，然后把服务端上的监听端口前的#也删掉，终于可以用了，万分感激，祝好
