### ISSUE TITLE
Centos7 6.8.7 kernel, install the latest version hysteria2, prompt: chcon invalid mode:/etc/systemd/system, how to solve it?

### ISSUE THREAD

**Issue by UsaMrs** [apernet/hysteria#1060]
Centos7 6.8.7 kernel, install the latest version hysteria2, prompt: chcon invalid mode:/etc/systemd/system, how to solve it?

**Comment by UsaMrs** [comment]
![212](https://github.com/apernet/hysteria/assets/153491533/63b27c1f-f2f7-42e0-a419-f53ae9089536)

**Comment by haruue** [comment]
Hello,

Please try the following command

```
FORCE_NO_SELINUX=1 bash <(curl -fsSL https://get.hy2.sh/)
```
