### ISSUE TITLE
hy2客户端配置ACL问题

### ISSUE THREAD

**Issue by 0xlau** [apernet/hysteria#1068]
**你的功能请求是否与某个问题有关？**
在hy1的时候，只要在服务器配置好，客户端我使用的是Furious，可以正常自动绕过CN
在hy2的时候，就无法自动绕过CN，如何配置？

**描述你希望的解决方案**
hy2能够通过客户端直接绕过CN

**有没有其他替代方案**
第一种方法：回退到hy1
第二种方法：使用第三方客户端将hy2流量转发到客户端，再由客户端转发出去，但太麻烦了

**Comment by haruue** [comment]
您好。
很遗憾， 官方 Hysteria 客户端不再打算支持 ACL。 
请参考 https://github.com/apernet/hysteria/issues/1058#issuecomment-2075032812 了解开发团队作出这个决定的原因。
建议用支持 ACL/路由功能 的第三方客户端， 或者 SwitchyOmega 等支持分流规则的浏览器代理插件， 如果你使用 TPROXY/REDIRECT/TUN， ipset/nftables/系统路由表 也可用于绕过 CN IP。
