### ISSUE TITLE
too many open streams

### ISSUE THREAD

**Issue by karimi12** [apernet/hysteria#1073]
**Describe the bug**
i got `too many open streams` then connection dropped

**To Reproduce*
I shared my server with 50 persons

**Expected behavior**
after this error server to connections 

**Logs**
 SOCKS5 TCP error        {"addr": "127.0.0.1:60102", "reqAddr": "159.69.46.45:6072", "error": "too many open streams"}

**Device and Operating System**
Ubuntu 20

**Additional context**

**Comment by tobyxdd** [comment]
Try increasing `maxIncomingStreams`:

https://hysteria.network/docs/advanced/Full-Server-Config/#quic-parameters:~:text=maxIdleTimeout%3A%2030s-,maxIncomingStreams,-%3A%201024

**Comment by finalvpn** [comment]
I have the same problem. I have increased it to 1000000 still getting this error
