### ISSUE TITLE
[Bug]: 域名系统解析

### ISSUE THREAD

**Issue by ghost** [apernet/hysteria#1077]
**描述问题**

当服务器的配置文件不包含任何 resolver 配置时，系统默认解析器并没有任何解析缓存。

**如何复现**

```bash
ls -l /etc/resolv.conf

lrwxrwxrwx 1 root root 39 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
```

```bash
resolvectl status

Global
           Protocols: +LLMNR +mDNS +DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub
  Current DNS Server: 2606:4700:4700::1111#cloudflare-dns.com
         DNS Servers: 2606:4700:4700::1111#cloudflare-dns.com 1.1.1.1#cloudflare-dns.com
Fallback DNS Servers: 2001:4860:4860::8888#dns.google 8.8.8.8#dns.google
```

```bash
resolvectl show-cache

Scope protocol=llmnr family=AF_INET6 ifindex=2 ifname=eth0
No entries.
Scope protocol=llmnr family=AF_INET ifindex=2 ifname=eth0
No entries.
Scope protocol=dns
No entries.
```

**预期行为**
理应有解析缓存。

**日志**
无

**设备和操作系统**
hysteria 2.4.3-1
linux 6.8.9.arch1-2

**额外信息**
另外请给[文档示例](https://v2.hysteria.network/docs/advanced/Full-Server-Config/#resolver)添加注释，~~因为这是 QUIC 协议，我以为 type 必须是 udp，下文只填写 dns over https 导致报错~~
```yaml
resolver:
  type: udp #支持的类型：tcp, udp, tls, https
```
没有阅读源码，不确定是否可以同时填写多个类型

**Comment by haruue** [comment]
您好， 我们的绝大部分文档都有中文版本： https://v2.hysteria.network/zh/docs/advanced/Full-Server-Config/

关于 `resolver` 下的 `type` 字段， 请先阅读文档顶部的 [「在客户端和服务端配置中的多处都有 "类型选择" 的配置格式」](https://v2.hysteria.network/zh/docs/advanced/Full-Server-Config/#:~:text=%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%92%8C%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%B8%AD%E7%9A%84%E5%A4%9A%E5%A4%84%E9%83%BD%E6%9C%89%20%22%E7%B1%BB%E5%9E%8B%E9%80%89%E6%8B%A9%22%20%E7%9A%84%E9%85%8D%E7%BD%AE%E6%A0%BC%E5%BC%8F) 相关说明。

关于 resolvectl 的解析缓存问题， 只有当您使用 `systemd-resolved` （没记错的话是 `127.0.0.53` 我几乎没用过这个）进行解析时， 才会使用您提及的解析缓存。

**Comment by haruue** [comment]
您好， 我们对您的配置进行了测试。

+ hysteria 服务端没有指定 `resolver` 选项
+ `systemd-resolved` 已启动。
+ `/etc/resolve.conf` 是指向 `../run/systemd/resolve/stub-resolv.conf` 的符号链接， 且
+ `/etc/resolve.conf` 包含 `nameserver 127.0.0.53` 。

这种情况下 `resolvectl show-cache` 是能正常输出客户端请求的域名的 DNS 缓存内容的。
