### ISSUE TITLE
关于最大带宽设置客户端与服务端有一方设0的情况的疑问

### ISSUE THREAD

**Issue by CodingMoeButa** [apernet/hysteria#1081]
关联Issue：#https://github.com/2dust/v2rayN/issues/5091

根据文档，如果客户端和服务端双方都不设置最大带宽的话，会使用BBR算法；如果最大带宽设为0，意味着不限制。

有一个疑问是，设置0的情况，和不设置的情况，是否属于相同的情形？

当客户端或服务端中一方设了限制，另一方设0做无限制，那么最终生效的限制是有限制的一方设定的限制吗？还是说这种情况就用BBR了？

如果是双方都设0呢？还能Brutal吗？

**Comment by haruue** [comment]
https://hysteria.network/zh/docs/advanced/Full-Server-Config/#_6

首先， 「设置为 0」和「不设置」是等价的。 但是， 「客户端设置为 0」与「服务端设置为 0」行为不同。

设计上「带宽」是以客户端的设置为 **基准**， 然后服务端的设置来 **限制** 客户端能设置到多少， 因此
+ 客户端设置为 0： 客户端不知道自己的带宽是多少。 这种情况下一定是用 BBR。
+ 服务端设置为 0： 不对客户端设置的带宽进行限制。 这种情况下如果客户端设置了带宽， 就是按照客户端的设置来。

特别地， 如果服务端开启了 `ignoreClientBandwidth`， 就是无视客户端的设置， 一律视为「客户端设置为 0」的情况， 因此也是一定用 BBR。

最后来回答你问的几个问题

> 有一个疑问是，设置0的情况，和不设置的情况，是否属于相同的情形？
是相同的情形。

> 当客户端或服务端中一方设了限制，另一方设0做无限制，那么最终生效的限制是有限制的一方设定的限制吗？还是说这种情况就用BBR了？
+ 如果客户端不限制（设置为 0）， 那么一定是 BBR。
+ 如果服务端不限制（设置为 0）， 那么客户端的设置生效。

> 如果是双方都设0呢？还能Brutal吗？
双方设置为 0 的情况下一定是 BBR。

**Comment by haruue** [comment]
我觉得主要是客户端和服务端都有单独的「带宽」章节，然后分别作出了解释。
https://hysteria.network/zh/docs/advanced/Full-Server-Config/#_4
https://hysteria.network/zh/docs/advanced/Full-Client-Config/#_5
看起来放在一起的话会更加直观， 或许我们可以考虑增加一个图表来说明这个选项的作用。

**Comment by us254** [comment]
1:  If neither the client nor the server sets a maximum bandwidth, use BBR.

2:  If one party sets a limit and the other sets no limit (0), use the limit set by the party with the limit.

3:  If both parties set the maximum bandwidth to 0 (no limit), use BBR.

4:  Only use Brutal when both parties have a specific bandwidth limit set, and use the minimum of the two limits.

**Comment by us254** [comment]
1. Client MaxTx = 0 and Server has a specific MaxRx: Use BBR. This is because the client does not impose any specific limit, making BBR the suitable adaptive algorithm.

2. Server MaxRx = 0 and Client has a specific MaxTx: Client's MaxTx takes effect, use Brutal with that value.

3. Both Client and Server set specific limits: Use Brutal with the minimum of the two values.

4. Both Client and Server set MaxTx and MaxRx to 0: Use BBR.

**Comment by us254** [comment]
![a7feeffb-b40f-4cf9-9d3a-a0a281482707](https://github.com/apernet/hysteria/assets/88821507/9249f282-8b4a-450b-8af0-674cb111d113)

**Comment by tobyxdd** [comment]
@us254 很不错，我打算做一个类似的流程图加到官方文档
