### ISSUE TITLE
暴露真实 IP

### ISSUE THREAD

**Issue by GrainStar** [apernet/hysteria#1082]
**IP暴露**
在 https://ipcheck.ing/ 检查泄露真实地址，同时 ipip.net 也是。未使用其它如 NextDNS 代理
![2](https://github.com/apernet/hysteria/assets/49580223/2d24ee10-6216-4aa7-a1cb-97242e3b3e99)

Mac: Sonoma 14.4.1
Sing-box: 1.8.13(221)

**Comment by haruue** [comment]
您好。
看起来你只是用了一个支持国内外分流的第三方客户端。

如需更多帮助， 请提供以下信息， 然后重新打开这个 issue：

1. 你的客户端配置（如果是第三方客户端， 请提供第三方客户端的配置）
2. 你的服务端配置
3. 你使用的客户端的名称（第三方客户端的情况）和版本
4. 你的浏览器连接到客户端的方式（例如 SOCKS5、 透明代理等）

**Comment by GrainStar** [comment]
原来如此！ 感谢解答
