### ISSUE TITLE
hysteria>failed to parse client config   {"error": "1 error(s) decoding:\n\n* 'obfs' expected a map, got 'string'"}

### ISSUE THREAD

**Issue by Sakura-Hui-li** [apernet/hysteria#1083]
在Windows上安装hysteria客户端是提示
hysteria>failed to parse client config   {"error": "1 error(s) decoding:\n\n* 'obfs' expected a map, got 'string'"}，这个改怎么处理
![image](https://github.com/apernet/hysteria/assets/76513591/7ded98b4-cb64-4d79-86c4-002adf934943)

**Comment by haruue** [comment]
您好

这个问题通常是用 Hysteria 1 配置文件启动 Hysteria 2 所导致的。

请注意 Hysteria 1 和 Hysteria 2 完全不兼容。

如果您是从机场获得的配置文件， 请从此处下载 Hysteria 1 的最终版本（不会再更新）： https://github.com/apernet/hysteria/releases/tag/v1.3.5

如果您是自己搭建的服务器， 您可能阅读了已经过时的 Hysteria 1 教程， 我建议您寻找最新的 Hysteria 2 教程。

**Comment by Sakura-Hui-li** [comment]
好的，感谢您的耐心解答，好像是两个版本没有对应上


象龟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apernet/hysteria"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 晚上6:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apernet/hysteria] hysteria&gt;failed to parse client config   {"error": "1 error(s) decoding:\n\n* 'obfs' expected a map, got 'string'"} (Issue #1083)





 
您好
 
这个问题通常是用 Hysteria 1 配置文件启动 Hysteria 2 所导致的。
 
请注意 Hysteria 1 和 Hysteria 2 完全不兼容。
 
如果您是从机场获得的配置文件， 请从此处下载 Hysteria 1 的最终版本（不会再更新）： https://github.com/apernet/hysteria/releases/tag/v1.3.5
 
如果您是自己搭建的服务器， 您可能阅读了已经过时的 Hysteria 1 教程， 我建议您寻找最新的 Hysteria 2 教程。

**Comment by Sakura-Hui-li** [comment]
您好，这个是因为hysteria 1启用不了吗







象龟
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "apernet/hysteria"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 晚上7:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apernet/hysteria] hysteria&gt;failed to parse client config   {"error": "1 error(s) decoding:\n\n* 'obfs' expected a map, got 'string'"} (Issue #1083)





 
Closed #1083 as completed.

**Comment by haruue** [comment]
> 这个是因为hysteria 1启用不了吗

Hysteria 1 只能启动 Hysteria 1 的配置文件， Hysteria 2 只能启动 Hysteria 2 的配置文件。 不支持混用。

您下载了 Hysteria 2 的程序， 但是您的配置文件是 Hysteria 1 的格式， 所以看到了这个错误。

如果您需要更多帮助， 可以把您使用的配置文件贴上来（可以将服务器名称和密码删除）。
