### ISSUE TITLE
Hysteria 2 使用几天会出现failed， (code=killed, signal=KILL) 要使用systemctl start hysteria-server.service 会恢复正常，请问这是为什么啊

### ISSUE THREAD

**Issue by lin878583** [apernet/hysteria#1086]
![8888](https://github.com/apernet/hysteria/assets/168949164/36489339-4ddf-4b59-94f5-6e96eaf147d8)
![9999](https://github.com/apernet/hysteria/assets/168949164/3dc4c4f8-c892-4b5d-98ea-38ae8b856d7e)
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
Attach logs from the client/server when the error occurs.

**Device and Operating System**
What are you using it on.

**Additional context**

**Comment by haruue** [comment]
您好

#1085 
要确认您当前使用的版本， 请执行

```
/usr/local/bin/hysteria version
```

这条命令的输出中的 `Version:` 后面的是您正使用的版本号。

要回退到 `v2.4.1` ， 请在服务器上执行这条命令

```
bash <(curl -fsSL https://get.hy2.sh/) --version v2.4.1
```

正在运行的 hysteria 服务将会被自动重启。

**Comment by lin878583** [comment]
> 您好
> 
> #1085
> 
> > 通常是内存占用过多被系统 LMK 了。
> > v2.4.3 在部分环境下有内存泄漏问题， 可以试试回退到 [v2.4.1](https://github.com/apernet/hysteria/releases/tag/app%2Fv2.4.1) 。
> 
> 要确认您当前使用的版本， 请执行
> 
> ```
> /usr/local/bin/hysteria version
> ```
> 
> 这条命令的输出中的 `Version:` 后面的是您正使用的版本号。
> 
> 要回退到 `v2.4.1` ， 请在服务器上执行这条命令
> 
> ```
> bash <(curl -fsSL https://get.hy2.sh/) --version v2.4.1
> ```
> 
> 正在运行的 hysteria 服务将会被自动重启。

太感谢啦！！！
