### ISSUE TITLE
connect error: http3: parsing frame failed: timeout: no recent network activity

### ISSUE THREAD

**Issue by sangsangde3** [apernet/hysteria#1095]
客户端频繁断连，报错信息为connect error: http3: parsing frame failed: timeout: no recent network activity，开启了混淆

**Comment by sangsangde3** [comment]
相同客户端配置下手机热点的客户端可以正常使用，不会断连

**Comment by sangsangde3** [comment]
这是我的客户端配置
server: host_ip+port
auth: password

bandwidth:
  up: 500 mbps
  down: 500 mbps

obfs:
  type: salamander
  salamander:
    password: password

tls:
  sni: bing.com
  insecure: true #使用自签时需要改成true

socks5:
  listen: 127.0.0.1:1080
http:
  listen: 127.0.0.1:8080

**Comment by shakibamoshiri** [comment]
I happened to see this error when my ISP has throttled UDP/QUIC but not fully blocked.  
Changing the client network/ISP showed the issue was network not hy2

**Comment by wlh1024** [comment]
> 據網路上可獲知的公開信息可以知道的是，如果您居住在中國大陸，且使用的是聯通的寬帶，就會發生您所遇到的情形。 除此之外，一些中國大陸商業網路防火牆會將混淆後的UDP流量歸類爲 「其他UDP流量」或者「未知UDP流量」。 所以基於上述兩點可獲知的訊息，請您試試看，不要開啓混淆功能再試試看會不會發生同樣的問題。另外SNI請不要設定爲bing這種不太正常的網站，您可以選擇一些其他網域名稱。

我尝试过不开混淆，仍然会出现这种问题

**Comment by sangsangde3** [comment]
> 據網路上可獲知的公開信息可以知道的是，如果您居住在中國大陸，且使用的是聯通的寬帶，就會發生您所遇到的情形。 除此之外，一些中國大陸商業網路防火牆會將混淆後的UDP流量歸類爲 「其他UDP流量」或者「未知UDP流量」。 所以基於上述兩點可獲知的訊息，請您試試看，不要開啓混淆功能再試試看會不會發生同樣的問題。另外SNI請不要設定爲bing這種不太正常的網站，您可以選擇一些其他網域名稱。

有可能是端口被墙了吗？

**Comment by sangsangde3** [comment]
统一回复，是端口被封了，设置下端口跳跃就可以了，参考https://v2.hysteria.network/zh/docs/advanced/Port-Hopping/
