### ISSUE TITLE
Traffic was blocked

### ISSUE THREAD

**Issue by ghargha** [apernet/hysteria#1097]
Hello,

I use Hysteria 2, latest version. It was good till yesterday that the traffic was blocked by some ISPs. 

The VPS server itself is fine and returns the ping.

what should I do?

**Comment by shakibamoshiri** [comment]
Hi
you can find another ISP, or if you used ipv4, try ipv6
also it is better to ask such a question in Telegram groups not as an issue here

**Comment by ghargha** [comment]
Really? good comment but I know I can change to another ISP.

I asked here for the creators to investigate against such an intelligent firewall, so let them to anwer!

**Comment by tobyxdd** [comment]
What are we supposed to "investigate" when you never mentioned which server, which ISP, or even which country you are from

**Comment by ghargha** [comment]
> What are we supposed to "investigate" when you never mentioned which server, which ISP, or even which country you are from

I am sure it makes no difference for you (as a user) because you will make general comments like above such as changing the ISP. It's clear that the Iran Firewall detects the UDP packets, because the server itself is fine and not blocked.

**Comment by tobyxdd** [comment]
Then why are you posting at all? Stop wasting everyone's time
