### ISSUE TITLE
建议增加一个name属性，用于后端区分不同的Hysteria节点

### ISSUE THREAD

**Issue by ListenV** [apernet/hysteria#1099]
**你的功能请求是否与某个问题有关？**

后端想要区分不同的Hysteria节点

**描述你希望的解决方案**

能否在服务端配置文件中增加一个可选配置 `name` 属性
并在使用 `HTTP 验证` 时，将 `name` 属性添加到请求 json 中
这样后端就可以根据 name 来区分不同的 Hysteria 节点

**有没有其他替代方案**

其他的方案就只能通过节点IP去分辨，但这样要麻烦一点

**额外信息**

无

**Comment by tobyxdd** [comment]
可以配置成不同的 URL 啊

**Comment by shakibamoshiri** [comment]
if you run a backend with hy2, you can separate your incoming traffic via userid .  
in user-level authentication (e.g `hy2://userid:pass@address:port/etc`) you can use a **prefix** and handle the traffic for each node/category/etc

for example you have three nodes for
 - android 
 - iphone
 - mac/win

then you create there prefixes accordingly 
- `a`
- `i`
- `mw`

now your backend will receive 

 - ip - `a`userid:pass - tx (it comes from android node)
 - ip - `i`userid:pass - tx (it comes from iphone node)
 - ip  - `nw`userid:pass -tx (it comes from mac/win node)


and URLs are:

 - hy2://`a`userid:pass@address:port/etc
 - hy2://`i`userid:pass@address:port/etc
 - hy2://`nw`userid:pass@address:port/etc

**Comment by haruue** [comment]
@shakibamoshiri
This issue is discussing about external authentication API
https://hysteria.network/docs/advanced/Full-Server-Config/#http-authentication

**Comment by shakibamoshiri** [comment]
> @shakibamoshiri This issue is discussing about external authentication API https://hysteria.network/docs/advanced/Full-Server-Config/#http-authentication

I am using external auth API and I managing multi nodes . I have three servers that had iptable-port-forwarding to hy2 server.  

```bash

client -----> [ hop 1.1 ] ------
                                |
client -----> [ hop 1.2 ] ------+----> [ hop 2 (hy2 server) ]
                                |
client -----> [ hop 1.3 ] ------
```


The backend needed to distinguish who is coming from which server ?  I solved it using the way I mentioned , is my solution wrong ? is there a better one ?

**Comment by shakibamoshiri** [comment]
sorry, my bad if i misunderstood the questions,
to distinguish hy2 nodes when I request for traffic API  , each node has ether a public or private IP so each node can be separated by a domain or its IP.

if you want to store meta-data for each node, you can update the JSON response from each hy2 node before saving to a database.

**Comment by haruue** [comment]
@shakibamoshiri 

I assume the OP is an owner of a commercial proxy provider (like ExpressVPN). In this case, each user is assigned exactly one username and password, which can be used to connect to a list of services ("nodes"). The backend can use the names of the nodes to limit which username can be used to connect to certain nodes (for "Lite" or "Premium" subscriptions), or to apply a certain fee rate when stats traffic.

The solution provided by Toby is good enough. You can just set this parameter in the url path or query, like `http://your.backend.com/auth?node=node-lax-1`.

**Comment by ListenV** [comment]
明白了，感谢各位的回复
