### ISSUE TITLE
QUIC无法连接

### ISSUE THREAD

**Issue by HoCooo** [apernet/hysteria#1107]
**日志**
[UDP] Closed with error: ERR_IDLE_CLOSE (SGNGTCP2ErrorDomain:-238)

**设备和操作系统**
Surge/IOS

**Comment by haruue** [comment]
您好。
您给出的日志并非由 Hysteria 产生， 因此我们无法为您解释它的含义。
建议您联系 Surge 社群或者客户支持， 以获取关于此日志的更多信息。

**Comment by david9991** [comment]
@HoCooo 我也有同样的问题，解决了吗？
