### ISSUE TITLE
服务端outbounds中bindDevice使用wg创建的接口无法开机启动

### ISSUE THREAD

**Issue by maoxikun** [apernet/hysteria#1108]
**描述问题**
服务端outbounds使用bindDevice绑定wg创建的接口时，重启系统之后hysteria无法启动成功

**如何复现**
服务端使用`sudo systemctl enable hysteria-server.service`设置开机启动，然后重启系统，配置如下：
```yaml
listen: :4444
tls:
  cert: /etc/hysteria/xxx.crt
  key: /etc/hysteria/xxx.key
bandwidth:
  up: 1 gbps
  down: 1 gbps
auth:
  type: password
  password: xxxxxxxx
acl:
  inline:
    - wg4(geosite:cn)
    - wg4(geoip:cn)
    - direct(all)
outbounds:
  - name: wg4
    type: direct
    direct:
      mode: 46
      bindDevice: wg1
  - name: wg6
    type: direct
    direct:
      mode: 64
      bindDevice: wg1
masquerade:
  type: proxy
  proxy:
    url: https://www.xxxxx.com
```

**预期行为**
hysteria正常启动

**日志**
```log
× hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-05-30 04:56:21 CST; 14s ago
   Duration: 310ms
    Process: 393 ExecStart=/usr/local/bin/hysteria server --config /etc/hysteria/config.yaml (code=exited, status=1/FAILURE)
   Main PID: 393 (code=exited, status=1/FAILURE)
        CPU: 42ms

May 30 04:56:21 xxx systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
May 30 04:56:21 xxx hysteria[393]: 2024-05-30T04:56:21+08:00        INFO        server mode
May 30 04:56:21 xxx hysteria[393]: 2024-05-30T04:56:21+08:00        FATAL        failed to load server config        {"error": "route ip+net: no such network interface"}
May 30 04:56:21 xxx systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
May 30 04:56:21 xxx systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
```

**设备和操作系统**
`Linux xxx 6.1.0-21-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux`

**额外信息**
1、在开机启动失败之后使用`sudo systemctl restart hysteria-server.service`重启hysteria能正常启动，显示日志如下：
```log
● hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-05-30 04:57:39 CST; 9s ago
   Main PID: 933 (hysteria)
      Tasks: 5 (limit: 2349)
     Memory: 130.6M
        CPU: 538ms
     CGroup: /system.slice/hysteria-server.service
             └─933 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml

May 30 04:57:39 xxx systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
May 30 04:57:39 xxx hysteria[933]: 2024-05-30T04:57:39+08:00        INFO        server mode
May 30 04:57:40 xxx hysteria[933]: 2024-05-30T04:57:40+08:00        INFO        server up and running        {"listen": ":4444"}
```

**Comment by haruue** [comment]
目前在 Hysteria 启动时会验证 `bindDevice` 填写的设备名称是否存在， 并在不存在时报错退出。 这通常可以帮助用户快速发现配置文件中的问题（而不是等首次请求之后才发现）， 参考之前载入证书相关的 issue， 我不认为更改这一行为是个好主意。

既然你用 systemd 启动 hysteria， 我建议让 systemd 帮你调整服务启动顺序。

创建 `/etc/systemd/system/hysteria-server.service.d/override.conf` （或者使用 `systemctl edit hysteria-server.service` 并根据英文注释操作）， 然后写入以下内容

```ini
[Unit]
Wants=sys-subsystem-net-devices-wg1.device
After=sys-subsystem-net-devices-wg1.device
```

如果你有多个 wg 接口要等待， 可以用空格分开同时指定

```
[Unit]
Wants=sys-subsystem-net-devices-wg1.device sys-subsystem-net-devices-wg2.device
After=sys-subsystem-net-devices-wg1.device sys-subsystem-net-devices-wg2.device
```

只要对应接口已启动， 你也可以从 `systemctl list-units | cat` 的输出中找到上面的 `.device`。 你也可以用 `systemctl status 'sys-subsystem-net-devices-wg1.device'` 验证你是否正确填写这个 .device。 如果当前这个接口已启动， 你会看到下面的输出

```
● sys-subsystem-net-devices-wg1.device - /sys/subsystem/net/devices/wg1
     Loaded: loaded
     Active: active (plugged) since Thu 2024-05-30 10:51:56 HKT; 3min 40s ago
     Device: /sys/devices/virtual/net/wg1
```

**Comment by maoxikun** [comment]
> 目前在 Hysteria 启动时会验证 `bindDevice` 填写的设备名称是否存在， 并在不存在时报错退出。 这通常可以帮助用户快速发现配置文件中的问题（而不是等首次请求之后才发现）， 参考之前载入证书相关的 issue， 我不认为更改这一行为是个好主意。
> 
> 既然你用 systemd 启动 hysteria， 我建议让 systemd 帮你调整服务启动顺序。
> 
> 创建 `/etc/systemd/system/hysteria-server.service.d/override.conf` （或者使用 `systemctl edit hysteria-server.service` 并根据英文注释操作）， 然后写入以下内容
> 
> ```ini
> [Unit]
> Wants=sys-subsystem-net-devices-wg1.device
> After=sys-subsystem-net-devices-wg1.device
> ```
> 
> 如果你有多个 wg 接口要等待， 可以用空格分开同时指定
> 
> ```ini
> [Unit]
> Wants=sys-subsystem-net-devices-wg1.device sys-subsystem-net-devices-wg2.device
> After=sys-subsystem-net-devices-wg1.device sys-subsystem-net-devices-wg2.device
> ```
> 
> 只要对应接口已启动， 你也可以从 `systemctl list-units | cat` 的输出中找到上面的 `.device`。 你也可以用 `systemctl status 'sys-subsystem-net-devices-wg1.device'` 验证你是否正确填写这个 .device。 如果当前这个接口已启动， 你会看到下面的输出
> 
> ```
> ● sys-subsystem-net-devices-wg1.device - /sys/subsystem/net/devices/wg1
>      Loaded: loaded
>      Active: active (plugged) since Thu 2024-05-30 10:51:56 HKT; 3min 40s ago
>      Device: /sys/devices/virtual/net/wg1
> ```

感谢解答，已解决
