### ISSUE TITLE
FFmpeg Error

### ISSUE THREAD

**Issue by pundoo** [apernet/hysteria#1109]
**Describe the bug**
FFmpeg throws the following error, when requesting through hysteria :
```
[tls @ 000001aedf626700] Error in the pull function.
[tls @ 000001aedf626700] IO error: End of file
[in#0 @ 000001aedf60a580] Error opening input: End of file
Error opening input file http://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4.
Error opening input files: End of file
```

**To Reproduce**
** standard http client
```
set HTTP_PROXY=http://127.0.0.1:1080
ffmpeg -i "https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4" -c copy out.mp4
```

**Expected behavior**
Tunnel HTTP CONNECT w/o immediately closing.

**Logs**
```
2024-05-30T13:36:29+00:00       ←[35mDEBUG←[0m  HTTP CONNECT request    {"addr": "127.0.0.1:29170", "reqAddr": "sample-videos.com:443"}
2024-05-30T13:36:29+00:00       ←[35mDEBUG←[0m  HTTP CONNECT closed     {"addr": "127.0.0.1:29170", "reqAddr": "sample-videos.com:443"}
```

**Device and Operating System**
 Windows 10 PRO (v21H2)

**Additional context**
Works for HTTP**S** sites on Browser. FFmpeg works with other http proxy clients (such as Xray).

**Comment by haruue** [comment]
I can reproduce this, but it seems like ffmpeg actively closed the connection after sending ClientHello. 
We will investigate further.

[ffmpeg-httpconnect.pcap.gz](https://github.com/apernet/hysteria/files/15501173/ffmpeg-httpconnect.pcap.gz)

**Comment by haruue** [comment]
I have addressed the issue and am fixing it now.
