### ISSUE TITLE
内存泄露，hysteria进程被Kill

### ISSUE THREAD

**Issue by yjtortor** [apernet/hysteria#1113]
主机系统 Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux 256m内存
 sysctl -w net.core.rmem_max=8777216
 sysctl -w net.core.wmem_max=8777216
设置了缓存8m
hysteria 2.4.4
开了动态端口和混淆，客户端openwrt开了负载均衡，过一段时间老是内存爆，然后进程老给kill掉
Jun  2 10:08:58 vps32202917 kernel: [3449577.801097] bash invoked oom-killer: gfp_mask=0x7080c0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), nodemask=(null), order=1, oom_score_adj=0
Jun  2 10:08:58 vps32202917 kernel: [3449577.805403] bash cpuset=/ mems_allowed=0
Jun  2 10:08:58 vps32202917 kernel: [3449577.806792] CPU: 0 PID: 5402 Comm: bash Not tainted 4.19.0-5-amd64 #1 Debian 4.19.37-5+deb10u2
Jun  2 10:08:58 vps32202917 kernel: [3449577.808124] Hardware name: Red Hat KVM, BIOS 1.16.0-4.module_el8.9.0+3659+9c8643f3 04/01/2014
Jun  2 10:08:58 vps32202917 kernel: [3449577.809590] Call Trace:
Jun  2 10:08:58 vps32202917 kernel: [3449577.811078]  dump_stack+0x5c/0x80
Jun  2 10:08:58 vps32202917 kernel: [3449577.812391]  dump_header+0x6b/0x283
Jun  2 10:08:58 vps32202917 kernel: [3449577.813753]  oom_kill_process.cold.29+0xb/0x1cf
Jun  2 10:08:58 vps32202917 kernel: [3449577.814996]  ? oom_badness+0x23/0x130
Jun  2 10:08:58 vps32202917 kernel: [3449577.816188]  out_of_memory+0x1a5/0x440
Jun  2 10:08:58 vps32202917 kernel: [3449577.817426]  __alloc_pages_slowpath+0xbd8/0xcb0
Jun  2 10:08:58 vps32202917 kernel: [3449577.818731]  ? __schedule+0x2aa/0x870
Jun  2 10:08:58 vps32202917 kernel: [3449577.820020]  __alloc_pages_nodemask+0x28b/0x2b0
Jun  2 10:08:58 vps32202917 kernel: [3449577.821234]  __get_free_pages+0xd/0x30
Jun  2 10:08:58 vps32202917 kernel: [3449577.822413]  pgd_alloc+0x38/0x200
Jun  2 10:08:58 vps32202917 kernel: [3449577.823538]  mm_init+0x17e/0x260
Jun  2 10:08:58 vps32202917 kernel: [3449577.824728]  copy_process.part.37+0x1633/0x1d80
Jun  2 10:08:58 vps32202917 kernel: [3449577.825876]  _do_fork+0xf2/0x3f0
Jun  2 10:08:58 vps32202917 kernel: [3449577.827000]  ? __do_page_fault+0x26c/0x4f0
Jun  2 10:08:58 vps32202917 kernel: [3449577.828189]  do_syscall_64+0x53/0x110
Jun  2 10:08:58 vps32202917 kernel: [3449577.829383]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Jun  2 10:08:58 vps32202917 kernel: [3449577.830541] RIP: 0033:0x7f9a0727c7be
Jun  2 10:08:58 vps32202917 kernel: [3449577.831662] Code: Bad RIP value.
Jun  2 10:08:58 vps32202917 kernel: [3449577.832793] RSP: 002b:00007ffd1d10b480 EFLAGS: 00000246 ORIG_RAX: 0000000000000038
Jun  2 10:08:58 vps32202917 kernel: [3449577.834000] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00007f9a0727c7be
Jun  2 10:08:58 vps32202917 kernel: [3449577.835194] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000001200011
Jun  2 10:08:58 vps32202917 kernel: [3449577.836387] RBP: 0000000000000000 R08: 0000000000000000 R09: 00007f9a071b3740
Jun  2 10:08:58 vps32202917 kernel: [3449577.837580] R10: 00007f9a071b3a10 R11: 0000000000000246 R12: 00007ffd1d10b4d0
Jun  2 10:08:58 vps32202917 kernel: [3449577.838793] R13: 00007ffd1d10b550 R14: 000055a0ea44daa8 R15: 0000000000000000
Jun  2 10:08:58 vps32202917 kernel: [3449577.840049] Mem-Info:
Jun  2 10:08:58 vps32202917 kernel: [3449577.841223] active_anon:16936 inactive_anon:17143 isolated_anon:0
Jun  2 10:08:58 vps32202917 kernel: [3449577.841223]  active_file:224 inactive_file:253 isolated_file:33
Jun  2 10:08:58 vps32202917 kernel: [3449577.841223]  unevictable:0 dirty:0 writeback:0 unstable:0
Jun  2 10:08:58 vps32202917 kernel: [3449577.841223]  slab_reclaimable:6586 slab_unreclaimable:8002
Jun  2 10:08:58 vps32202917 kernel: [3449577.841223]  mapped:415 shmem:125 pagetables:445 bounce:0
Jun  2 10:08:58 vps32202917 kernel: [3449577.841223]  free:710 free_pcp:29 free_cma:0
Jun  2 10:08:58 vps32202917 kernel: [3449577.848529] Node 0 active_anon:67744kB inactive_anon:68572kB active_file:896kB inactive_file:1012kB unevictable:0kB isolated(anon):0kB isolated(file):132kB mapped:1660kB dirty:0kB writeback:0kB shmem:500kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
Jun  2 10:08:58 vps32202917 kernel: [3449577.852645] Node 0 DMA free:900kB min:136kB low:168kB high:200kB active_anon:1680kB inactive_anon:4916kB active_file:128kB inactive_file:88kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB kernel_stack:16kB pagetables:28kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.857030] lowmem_reserve[]: 0 186 186 186 186
Jun  2 10:08:58 vps32202917 kernel: [3449577.858501] Node 0 DMA32 free:1940kB min:1680kB low:2100kB high:2520kB active_anon:66064kB inactive_anon:63656kB active_file:784kB inactive_file:932kB unevictable:0kB writepending:0kB present:245612kB managed:220964kB mlocked:0kB kernel_stack:1552kB pagetables:1752kB bounce:0kB free_pcp:116kB local_pcp:116kB free_cma:0kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.863426] lowmem_reserve[]: 0 0 0 0 0
Jun  2 10:08:58 vps32202917 kernel: [3449577.864929] Node 0 DMA: 3*4kB (UM) 33*8kB (UMH) 39*16kB (UH) 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 900kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.868151] Node 0 DMA32: 112*4kB (UMEH) 48*8kB (UMEH) 70*16kB (UEH) 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 1952kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.871401] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.873189] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.874852] 858 total pagecache pages
Jun  2 10:08:58 vps32202917 kernel: [3449577.876543] 205 pages in swap cache
Jun  2 10:08:58 vps32202917 kernel: [3449577.878090] Swap cache stats: add 1378759, delete 1378554, find 13041543/13479189
Jun  2 10:08:58 vps32202917 kernel: [3449577.879724] Free swap  = 0kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.881294] Total swap = 65528kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.883096] 65401 pages RAM
Jun  2 10:08:58 vps32202917 kernel: [3449577.884794] 0 pages HighMem/MovableOnly
Jun  2 10:08:58 vps32202917 kernel: [3449577.886610] 6183 pages reserved
Jun  2 10:08:58 vps32202917 kernel: [3449577.888339] 0 pages hwpoisoned
Jun  2 10:08:58 vps32202917 kernel: [3449577.889942] Tasks state (memory values in pages):
Jun  2 10:08:58 vps32202917 kernel: [3449577.891657] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jun  2 10:08:58 vps32202917 kernel: [3449577.893417] [    198]     0   198    12161      175   122880     3270             0 systemd-journal
Jun  2 10:08:58 vps32202917 kernel: [3449577.895244] [    221]     0   221     5479        9    69632      228         -1000 systemd-udevd
Jun  2 10:08:58 vps32202917 kernel: [3449577.896867] [    289]   101   289    23270        5    86016      227             0 systemd-timesyn
Jun  2 10:08:58 vps32202917 kernel: [3449577.898712] [    293]     0   293     2021        0    45056      781             0 haveged
Jun  2 10:08:58 vps32202917 kernel: [3449577.900439] [    320]     0   320    56456       38    94208      478             0 rsyslogd
Jun  2 10:08:58 vps32202917 kernel: [3449577.902363] [    321]     0   321     4912       41    77824      246             0 systemd-logind
Jun  2 10:08:58 vps32202917 kernel: [3449577.904291] [    325]     0   325     2119       13    49152       44             0 cron
Jun  2 10:08:58 vps32202917 kernel: [3449577.906148] [    326]   104   326     2305      112    57344       76          -900 dbus-daemon
Jun  2 10:08:58 vps32202917 kernel: [3449577.908001] [    466]     0   466     3963       37    65536      180         -1000 sshd
Jun  2 10:08:58 vps32202917 kernel: [3449577.909941] [    844]     0   844     1403        0    53248       30             0 agetty
Jun  2 10:08:58 vps32202917 kernel: [3449577.911939] [   6124]     0  6124   462323      955   233472     2177             0 x-ui
Jun  2 10:08:58 vps32202917 kernel: [3449577.913923] [  22686]     0 22686   330859     3476   352256     4875             0 xray-linux-amd6
Jun  2 10:08:58 vps32202917 kernel: [3449577.915729] [  30228]     0 30228     5256        0    77824      319             0 systemd
Jun  2 10:08:58 vps32202917 kernel: [3449577.917458] [  30229]     0 30229    43402        9   106496      651             0 (sd-pam)
Jun  2 10:08:58 vps32202917 kernel: [3449577.919100] [  31849]     0 31849   311183      430   135168     1151             0 frps
Jun  2 10:08:58 vps32202917 kernel: [3449577.920804] [   4174]     0  4174     4150       44    65536      235             0 sshd
Jun  2 10:08:58 vps32202917 kernel: [3449577.922445] [   4294]     0  4294     1913      172    49152      139             0 bash
Jun  2 10:08:58 vps32202917 kernel: [3449577.924107] [   5007]   998  5007   327519    27467   339968      700             0 hysteria
Jun  2 10:08:58 vps32202917 kernel: [3449577.925787] [   5387]     0  5387     4111      248    73728        0             0 sshd
Jun  2 10:08:58 vps32202917 kernel: [3449577.927521] [   5393]   105  5393     3963      224    69632        0             0 sshd
Jun  2 10:08:58 vps32202917 kernel: [3449577.929160] [   5402]     0  5402     1682       59    49152        0             0 bash
Jun  2 10:08:58 vps32202917 kernel: [3449577.930799] [   5403]     0  5403   462323      955   233472     2177             0 x-ui
Jun  2 10:08:58 vps32202917 kernel: [3449577.932334] Out of memory: Kill process 5007 (hysteria) score 373 or sacrifice child
Jun  2 10:08:58 vps32202917 kernel: [3449577.933857] Killed process 5007 (hysteria) total-vm:1310076kB, anon-rss:109868kB, file-rss:0kB, shmem-rss:0kB
Jun  2 10:08:58 vps32202917 kernel: [3449577.944551] oom_reaper: reaped process 5007 (hysteria), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Jun  2 10:08:58 vps32202917 systemd[1]: hysteria-server.service: Main process exited, code=killed, status=9/KILL
Jun  2 10:08:58 vps32202917 systemd[1]: hysteria-server.service: Failed with result 'signal'.**描述问题**
请尽量清晰精准地描述你遇到的问题。

**如何复现**
复现问题的步骤。

**预期行为**
你认为修复后的行为应该是怎样的。

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
你在用什么设备和操作系统。

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by haruue** [comment]
您好。
256MB 内存也太少了， 硬盘够大的话要不加个 1GB 的 swap 吧。
根据上面的 log， Hysteria 在 OOM 的时候也才占用了 110MB 内存， 这还处于正常内存占用范围之内。

**Comment by ssd2077** [comment]
部分机会出现越跑占用越高，我也不知道为什么，反正我挂有探针，感觉占用高的时候，重启进程就恢复了。

**Comment by ssd2077** [comment]
或者，你可以试试sing-box当服务端。
