### ISSUE TITLE
2024-06-05 通过hy2的连接无法访问hy2官网，但是其他连接协议可以。

### ISSUE THREAD

**Issue by FlyRideR1986** [apernet/hysteria#1114]
**描述问题**
请尽量清晰精准地描述你遇到的问题。
2024-06-05 通过hy2的连接无法访问hy2官网，但是其他连接协议可以。
之前都是正常的，访问其他网页也是正常的，目前只发现hy2官网不行

**如何复现**
复现问题的步骤。
切换不同协议的，只有hy2协议无法连接hy2官网

**日志**
附上客户端/服务器端在错误发生前后的日志。

● hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-06-04 09:52:51 PDT; 3min 36s ago
   Main PID: 744 (hysteria)
      Tasks: 5 (limit: 1115)
     Memory: 27.1M
        CPU: 1.509s
     CGroup: /system.slice/hysteria-server.service
             └─744 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml

6月 04 09:52:51 clean-push-1.localdomain systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
6月 04 09:52:52 clean-push-1.localdomain hysteria[744]: 2024-06-04T09:52:52-07:00        INFO        server mode
6月 04 09:52:52 clean-push-1.localdomain hysteria[744]: 2024-06-04T09:52:52-07:00        INFO        server up and running        {"listen": ":40000"}
6月 04 09:53:25 clean-push-1.localdomain hysteria[744]: 2024-06-04T09:53:25-07:00        INFO        client connected        {"addr": "[隐藏一下我的ip]:41893", "id": "user", "tx": 31250000}                                                                                                   6月 04 09:54:15 clean-push-1.localdomain hysteria[744]: 2024-06-04T09:54:15-07:00        INFO        client connected        {"addr": "[隐藏一下我的ip]:48336", "id": "user", "tx": 31250000}                                                                                                   6月 04 09:54:40 clean-push-1.localdomain hysteria[744]: 2024-06-04T09:54:40-07:00        WARN        TCP error        {"addr": "[隐藏一下我的ip]:41893", "id": "user", "reqAddr": "59.24.3.174:443", "error": "dial tcp4 59.24.3.174:443: i/o timeout"}                                         6月 04 09:54:45 clean-push-1.localdomain hysteria[744]: 2024-06-04T09:54:45-07:00        WARN        TCP error        {"addr": "[隐藏一下我的ip]:48336", "id": "user", "reqAddr": "api.hy2.io:443", "error": "readfrom tcp4 隐藏一下我的节点ip:41342->104.21.69.135:443: timeout: no recent network activity"}
6月 04 09:54:45 clean-push-1.localdomain hysteria[744]: 2024-06-04T09:54:45-07:00        INFO        client disconnected        {"addr": "[隐藏一下我的ip]:48336", "id": "user", "error": "accepting stream failed: timeout: no recent network activity"}
6月 04 09:54:51 clean-push-1.localdomain hysteria[744]: 2024-06-04T09:54:51-07:00        WARN        TCP error        {"addr": "[隐藏一下我的ip]:41893", "id": "user", "reqAddr": "59.24.3.174:443", "error": "dial tcp4 59.24.3.174:443: i/o timeout"}

**设备和操作系统**
你在用什么设备和操作系统。
debian12 stable

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by haruue** [comment]
您好。

> `"reqAddr": "59.24.3.174:443"`

服务器端 `reqAddr` 是一个 IP 地址意味着您使用客户端侧解析（通常是使用透明代理模式的 redirect/tproxy/tun）， 并且解析出这个 IP 意味着您的 DNS 被污染了。

作为另一个知名的被 DNS 污染的域名， 您或许也无法访问 [中文维基百科](https://zh.wikipedia.org/) 。

目前我们观测到的是 v2.hysteria.network 已经被 GFW 加入 DNS 污染名单。

如果您没有做其它 DNS 机制， 可以用 hysteria 的端口转发功能转发国外的 DNS 到本地来用。

**Comment by FlyRideR1986** [comment]
后来更新到2.4.5后，问题解决了
