### ISSUE TITLE
2.4.5版本，无法访问部分网页，例如 https://v2.hysteria.network/zh/

### ISSUE THREAD

**Issue by FlyRideR1986** [apernet/hysteria#1118]
**描述问题**
今天发现使用hy2（2.4.5）协议无法访问 https://v2.hysteria.network/zh/
（但是其他主流网站可以，google，youtube都OK）

切换到其他协议（Vless+Reality），可以正常访问 https://v2.hysteria.network/zh/
请求网址:
https://v2.hysteria.network/zh/
请求方法:
GET
状态代码:
200 OK
远程地址:
**59.24.3.174:443**

**日志**
服务器端：
● hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; enabled; preset: enabled)
     Active: active (running) since Sat 2024-06-08 09:16:17 PDT; 5min ago
   Main PID: 737 (hysteria)
      Tasks: 5 (limit: 1115)
     Memory: 23.3M
        CPU: 2.115s
     CGroup: /system.slice/hysteria-server.service
             └─737 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml

6月 08 09:21:28 clean-push-1.localdomain hysteria[737]: 2024-06-08T09:21:28-07:00        WARN        TCP error        {"addr": "[隐藏我的ip]:40060", "id": "user", "reqAddr": "**59.24.3.174:443**", "error": "dial tcp4 59.24.3.174:443: i/o timeout"}
6月 08 09:21:43 clean-push-1.localdomain hysteria[737]: 2024-06-08T09:21:43-07:00        WARN        TCP error        {"addr": "[隐藏我的ip]:40060", "id": "user", "reqAddr": "**59.24.3.174:443**", "error": "dial tcp4 59.24.3.174:443: i/o timeout"}

**设备和操作系统**
debian12 stable

**Comment by tobyxdd** [comment]
DNS 污染

**Comment by FlyRideR1986** [comment]
> DNS 污染

同样是解析出59.24.3.174:443这个地址，同样的VPS，切换成其他Vlss或者Vmess协议就能访问到，这不太像DNS污染吧？DNS解析结果异常的话，应该是都打不开网站才对呀。

**Comment by tobyxdd** [comment]
不知道你是如何测试的，我这里测试这个 IP ping/80/443 都不通，这个 IP 也根本不是 Cloudflare 的 IP

**Comment by FlyRideR1986** [comment]
> 不知道你是如何测试的，我这里测试这个 IP ping/80/443 都不通，这个 IP 也根本不是 Cloudflare 的 IP

![image](https://github.com/apernet/hysteria/assets/31609725/80dbb17d-3234-4cee-b405-50c24d033251)
我只是发现hy2协议打不开后，切换成Vless+Reality协议，就能访问了，，，，
再切回hy2打不开，再切到vless就还是能打开

![image](https://github.com/apernet/hysteria/assets/31609725/34f8eab4-2cd1-4d44-95c0-34d9f93e8bcd)

**Comment by haruue** [comment]
https://github.com/apernet/hysteria/issues/1114#issuecomment-2148129787

上次就跟你说了。
判定 DNS 污染的原因是这个 IP 就是知名的 DNS 污染地址， 你 Google 一下就知道了。
你的网络配置中可能既有干净的 DNS ， 也有被污染的 DNS ， 所以一下返回正常的结果一下返回被污染的结果。
