### ISSUE TITLE
安装时出错

### ISSUE THREAD

**Issue by tanggo-why** [apernet/hysteria#1119]
bash <(curl -fsSL https://get.hy2.sh/)
63: note: SELinux is detected
63: warning: Failed to obtain SEContext of /etc/systemd/system
Checking for installed version ... not installed
Checking for latest version ... v2.4.5
Downloading hysteria binary: https://github.com/apernet/hysteria/releases/download/app/v2.4.5/hysteria-linux-amd64 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15.4M  100 15.4M    0     0  17.2M      0 --:--:-- --:--:-- --:--:-- 34.3M
Installing hysteria executable ... ok
Install /etc/hysteria/config.yaml ... ok
Creating user hysteria ... ok
Install /etc/systemd/system/hysteria-server.service ... ok
Install /etc/systemd/system/hysteria-server@.service ... ok

Congratulation! Hysteria 2 has been successfully installed on your server.

**Comment by haruue** [comment]
安装已经成功了。 那个 warning 无视即可。

**Comment by tanggo-why** [comment]
> 安装已经成功了。 那个警告无视即可。

但是在etc文件夹中并没有找到Hysteria2文件夹

**Comment by tanggo-why** [comment]
> 安装已经成功了。 那个警告无视即可。

你好！但是在etc文件夹中并没有找到Hysteria2

**Comment by tanggo-why** [comment]
> 安装已经成功了。 那个警告无视即可。
你好！但是etc文件夹中没有Hysteria2

**Comment by haruue** [comment]
> 但是etc文件夹中没有Hysteria2

Hysteria 2 的配置文件在 `/etc/hysteria/config.yaml` ， 也就是 `etc` 「文件夹」里的 `hysteria` 文件夹里的 `config.yaml` 。

**Comment by tanggo-why** [comment]
> Hysteria 2 的配置文件在`/etc/hysteria/config.yaml`，也就是`etc`“文件夹”里的`hysteria`文件夹里`config.yaml`。
![微信截图_20240610200020](https://github.com/apernet/hysteria/assets/172192810/5b542648-3c86-479a-9e23-ddb644447fe2)

etc里没有hysteria`这个文件夹

**Comment by tanggo-why** [comment]
root@C20240609102115:~# systemctl restart hysteria-server.service
root@C20240609102115:~# systemctl status hysteria-server.service
● hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-06-10 15:05:47 UTC; 8s ago
    Process: 2666 ExecStart=/usr/local/bin/hysteria server --config /etc/hysteria/config.yaml (code=exited, status=1/FAILURE)
   Main PID: 2666 (code=exited, status=1/FAILURE)
        CPU: 19ms

Jun 10 15:05:47 C20240609102115 systemd[1]: Started Hysteria Server Service (config.yaml).
Jun 10 15:05:47 C20240609102115 hysteria[2666]: 2024-06-10T15:05:47Z        INFO        server mode
Jun 10 15:05:47 C20240609102115 hysteria[2666]: 2024-06-10T15:05:47Z        FATAL        failed to load server config        {"error": "invalid config: listen: lookup udp/443#监听端口: unknown port"}
Jun 10 15:05:47 C20240609102115 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 15:05:47 C20240609102115 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
root@C20240609102115:~# 

这个问题怎么解决？求帮助

**Comment by haruue** [comment]
> Jun 10 15:05:47 C20240609102115 hysteria[2666]: 2024-06-10T15:05:47Z FATAL failed to load server config {"error": "invalid config: listen: lookup udp/443#监听端口: unknown port"}

你的配置文件里面有这样一行

```yaml
listen: :443#监听端口
```

你删掉了 `#监听端口` 前面的空格， 导致了这个问题， 请在 `#监听端口` 的注释前添加空格， 或者干脆删掉这个注释

```yaml
listen: :443#监听端口         # 报错
listen: :443 #监听端口        # OK
listen: :443                 # OK
```

**Comment by vipnet2021** [comment]
systemctl status hysteria-server.service 执行后为什么无法启动Hysteria2，请求帮助，跪谢
hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-11-10 23:32:23 CST; 2 days ago
   Duration: 56ms
   Main PID: 33695 (code=exited, status=1/FAILURE)
        CPU: 8ms

Nov 10 23:32:23 instance-20241109-1656 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Nov 10 23:32:23 instance-20241109-1656 hysteria[33695]: 2024-11-10T23:32:23+08:00        INFO        server mode
Nov 10 23:32:23 instance-20241109-1656 hysteria[33695]: 2024-11-10T23:32:23+08:00        FATAL        failed to parse server confi>
Nov 10 23:32:23 instance-20241109-1656 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 23:32:23 instance-20241109-1656 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.

**Comment by haruue** [comment]
@vipnet2021 

您好。 请用下面这个命令查询日志

```
journalctl --no-pager -e -u hysteria-server.service
```

然后既然你是 failed to parse server config ， 那你也直接把服务端配置文件发上来吧。

**Comment by vipnet2021** [comment]
感谢大神的回复：

您好。 这个命令查询日志journalctl --no-pager -e -u hysteria-server.service得到的是这些，配置文件见附件

感谢大神帮助查看下

Nov 10 22:59:05 instance-20241109-1656 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Nov 10 22:59:05 instance-20241109-1656 hysteria[21439]: 2024-11-10T22:59:05+08:00 INFO server mode
Nov 10 22:59:05 instance-20241109-1656 hysteria[21439]: 2024-11-10T22:59:05+08:00 FATAL failed to load server config {"error": "invalid config: listen: listen udp :443: bind: address already in use"}
Nov 10 22:59:05 instance-20241109-1656 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 22:59:05 instance-20241109-1656 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
Nov 10 22:59:07 instance-20241109-1656 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Nov 10 22:59:07 instance-20241109-1656 hysteria[21501]: 2024-11-10T22:59:07+08:00 INFO server mode
Nov 10 22:59:07 instance-20241109-1656 hysteria[21501]: 2024-11-10T22:59:07+08:00 FATAL failed to load server config {"error": "invalid config: listen: listen udp :443: bind: address already in use"}
Nov 10 22:59:07 instance-20241109-1656 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 22:59:07 instance-20241109-1656 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
Nov 10 22:59:54 instance-20241109-1656 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Nov 10 22:59:54 instance-20241109-1656 hysteria[21726]: 2024-11-10T22:59:54+08:00 INFO server mode
Nov 10 22:59:54 instance-20241109-1656 hysteria[21726]: 2024-11-10T22:59:54+08:00 FATAL failed to load server config {"error": "invalid config: listen: listen udp :443: bind: address already in use"}
Nov 10 22:59:54 instance-20241109-1656 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 22:59:54 instance-20241109-1656 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
Nov 10 23:13:22 instance-20241109-1656 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Nov 10 23:13:22 instance-20241109-1656 hysteria[26868]: 2024-11-10T23:13:22+08:00 INFO server mode
Nov 10 23:13:22 instance-20241109-1656 hysteria[26868]: 2024-11-10T23:13:22+08:00 FATAL failed to load server config {"error": "invalid config: listen: listen udp :443: bind: address already in use"}
Nov 10 23:13:22 instance-20241109-1656 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 23:13:22 instance-20241109-1656 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
Nov 10 23:26:28 instance-20241109-1656 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Nov 10 23:26:28 instance-20241109-1656 hysteria[31569]: 2024-11-10T23:26:28+08:00 INFO server mode
Nov 10 23:26:28 instance-20241109-1656 hysteria[31569]: 2024-11-10T23:26:28+08:00 FATAL failed to parse server config {"error": "1 error(s) decoding:\n\n* 'auth' expected a map, got 'string'"}
Nov 10 23:26:28 instance-20241109-1656 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 23:26:28 instance-20241109-1656 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
Nov 10 23:32:23 instance-20241109-1656 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Nov 10 23:32:23 instance-20241109-1656 hysteria[33695]: 2024-11-10T23:32:23+08:00 INFO server mode
Nov 10 23:32:23 instance-20241109-1656 hysteria[33695]: 2024-11-10T23:32:23+08:00 FATAL failed to parse server config {"error": "1 error(s) decoding:\n\n* 'auth' expected a map, got 'string'"}
Nov 10 23:32:23 instance-20241109-1656 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 23:32:23 instance-20241109-1656 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月13日 20:10 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [apernet/hysteria] 安装时出错 (Issue #1119) |

@vipnet2021

您好。 请用下面这个命令查询日志

journalctl --no-pager -e -u hysteria-server.service


然后既然你是 failed to parse server config ， 那你也直接把服务端配置文件发上来吧。

**Comment by haruue** [comment]
@vipnet2021 

> ```
> Nov 10 23:32:23 instance-20241109-1656 hysteria[33695]: 2024-11-10T23:32:23+08:00 FATAL failed to parse server config {"error": "1 error(s) decoding:\n\n* 'auth' expected a map, got 'string'"}
> ```

这个报错意味着你服务端配置中的 `auth` 选项格式不对， 请注意服务端和客户端 `auth` 选项的格式不同。 在使用密码的情况下， 服务端配置中的 `auth` 选项是这样的。

```yaml
auth:
  type: password
  password: Se7RAuFZ8Lzg
```

对应的客户端配置中的 `auth` 选项是这样的。

```yaml
auth: Se7RAuFZ8Lzg
```

> 配置文件见附件

没收到这个附件， 请避免使用邮件回复 GitHub Issue。

**Comment by vipnet2021** [comment]
你好，感谢指导，但问题是我的VPS是SSH通过KEY登录的，不是输入密码登录的，会不会和这个格式不符造成的。VPS装的是Ubuntu,安装完成后就直接安装 hysteria2了，就不知道你说的服务器配置格式是不是因为这样造成安装不上的，还是说在VPS中要找到哪个文件去查看格式是不是不同的，谢谢

**Comment by haruue** [comment]
@vipnet2021 

> 我的VPS是SSH通过KEY登录的，不是输入密码登录的，会不会和这个格式不符造成的

> VPS装的是Ubuntu,安装完成后就直接安装 hysteria2了

上面提及的 「Hysteria 服务端配置格式问题」 是你写（改）错了 Hysteria 服务端的配置文件。 它与你如何登录 VPS、 是否在安装好系统后立即安装 Hysteria 是无关的。 Hysteria 的认证密码与你服务器的登录密码也是无关的。

如果你是使用官方脚本安装 Hysteria， 服务端配置文件在服务器的 `/etc/hysteria/config.yaml` ， 你把这个文件的内容传上来， 我可以帮你检查问题出在哪里。

另外， 请注意， 在本 Issue 中发送的回复， 本 Issue 的作者（楼主）以及所有参与者都会收到提醒， 请另开新的 Issue 提问， 不要像这样在一个标记为「已解决」的 Issue 下搭车问问题。
