### ISSUE TITLE
box.com这个域名访问不了

### ISSUE THREAD

**Issue by uzzme** [apernet/hysteria#1121]
**描述问题**
同台服务器用Xray可以访问box.com域名，切换到hy2打开不了。

**Comment by tobyxdd** [comment]
DNS 污染

**Comment by uzzme** [comment]
这个域名是被GFW拦截的，按我的理解，默认就是需要代理的，现在是服务端请求不了这个域名，但服务器直接访问这个域名没问题，其它服务端比如xray可以正常请求。应该不是DNS污染的问题，是不是HY2跟BOX.COM有什么过节，特意拦截了这个域名？

**Comment by mega-optimus** [comment]
this domain does not suffer from ip blocking, nor dns pollution.

**Comment by uzzme** [comment]
> this domain does not suffer from ip blocking, nor dns pollution.

app.box.com

**Comment by mega-optimus** [comment]
> > this domain does not suffer from ip blocking, nor dns pollution.
> 
> app.box.com

ok, this suffers from dns pollution, but not ip blocking
