### ISSUE TITLE
Visible SNI

### ISSUE THREAD

**Issue by hossein1376** [apernet/hysteria#1122]
**Describe the bug**
I was inspecting packets while connected to Hysteria, and it seems like the browser (running at `172.19.0.1`) is sending Client Hello packets with viable SNI.

```
172.19.0.1	142.251.33.110	TLSv1.3	1889	Client Hello (SNI=www.youtube.com)
```

Disconnecting Hysteria and attempting to load the website again, no such packets were sent.  
My thinking is, even if GFW is not able to decrypt the traffic, it can pick up user is accessing websites they shouldn't be able to, and theoretically flag server's IP address. How valid is my concern?

**To Reproduce**
Filter by `tls.handshake.extensions_server_name`  in Wire Shark.

**Expected behavior**
No Client Hello packet being sent or it goes through Hysteria as well.

**Device and Operating System**
Client: Linux, NekoRay v3.6
Server: Linux, Hysteria v2.4.5

**Comment by tobyxdd** [comment]
This has nothing to do with hysteria. You should report this to the nekobox developers.
