### ISSUE TITLE
authentication method

### ISSUE THREAD

**Issue by ReturnFI** [apernet/hysteria#1127]
Hi,

I'm hoping to find an alternative authentication method to the current userpass configuration shown below, as the [Hiddify next ](https://github.com/hiddify/hiddify-next) is not compatible with this method:
Are there any other authentication methods that could be used instead of userpass that would be compatible with Hiddify?
```json
{
  "auth": {
    "type": "userpass",
    "userpass": {
      "default": "2Ks03mIW.....",
      "user2": "5Ks33fID......"
    }
  }
}
```
The specific issue lies with the `default:2Ks03mIW `part.

Currently, the incompatible URL looks like this:

`hy2://default:2Ks03mIW@11.11.11.11:1935?obfs=salamander&obfs-password=qOOU39foM4K&pinSHA256=sha256/.....SAHOjiasdOE=&insecure=1&sni=bing.com#default-IPv4`

The [repository ](https://github.com/ReturnFI/Hysteria2)I'm working on hysteria2
Thank you for your assistance.

**Comment by tobyxdd** [comment]
I'm not familiar with Hiddify. Why does it not support userpass? What authentication methods does it have?

**Comment by ReturnFI** [comment]
> I'm not familiar with Hiddify. Why does it not support userpass? What authentication methods does it have?

Hiddify next uses this method for authentication:

`hysteria2://0de3258d-6c31-4e4f-8d40-be753ff5ee0e@11.11.11.11:1935?hiddify=1&obfs=salamander&obfs-password=aLrXeJFGhaORnqp&sni=bing.com&insecure=1#Hysteria2`

And Hiddify manager also uses the singbox core to build hysteria2 and manage users.

However, I'm more interested in creating users and managing them within the hysteria2 core itself.

**Comment by tobyxdd** [comment]
This looks like password authentication. In fact, `userpass` in Hysteria is really the same as `password` except that the username and password are formatted as `user:pass` (separated by a colon). Maybe you can try URL-encoding the colon as `%3A` and see if it works on Hiddify.

**Comment by ReturnFI** [comment]
Great! Using URL encoding `%3A` worked perfectly.

Thank you for your assistance.❤️🙏🏻
