### ISSUE TITLE
hy2客户端的 socks5, udp不通

### ISSUE THREAD

**Issue by Jackchen0514** [apernet/hysteria#1128]
**描述问题**
外部直接连接hy2客户端的 socks5, udp是不通; 需要防火墙开启所有端口后， udp才通 
如果进行端口转发， 发现tcp可以， udp不行;
想问下这个socks5的udp有办法中转吗？

**Comment by haruue** [comment]
您好。

SOCKS5 的 UDP 不是监听于特定 UDP 端口的， 而是通过 TCP 接收 UDP ASSOCIATE 请求后， 开放随机 UDP 端口进行通信。 具体可参考 [RFC1928](https://datatracker.ietf.org/doc/html/rfc1928) （[由 Luyu Huang 提供的中文翻译](https://luyuhuang.tech/2020/08/27/rfc1928.html#udp-associate-%E8%AF%B7%E6%B1%82)）。

因此， 如果在运行 Hysteria 客户端的设备上， 有防火墙规则阻碍了 UDP 入站， 那么 SOCKS5 UDP 是无法正常使用的。
