### ISSUE TITLE
tun模式白名单模式

### ISSUE THREAD

**Issue by superway117** [apernet/hysteria#1138]
**你的功能请求是否与某个问题有关？**
功能需求，不是bug

**描述你希望的解决方案**
客户端开启tun模式，希望有个白名单机制，我需要通过客户端或者服务器端的配置，最好是客户端的配置来实现
- 指定ip的访问经过hysteria tun
- 指定域名的访问经过hysteria tun
- 其他不指定的ip、域名都默认不经过hysteria tun

**有没有其他替代方案**
可能openvpn里面有相关的解决方案，不确定，是否是通过本地route程序实现？

**Comment by tobyxdd** [comment]
这个可以也只能由本地路由表配置。请了解相关知识后在 tun 的 `route` 字段进行配置：

https://hysteria.network/zh/docs/advanced/Full-Client-Config/#tun:~:text=ffff%3Afff1/126-,route,-%3A
