### ISSUE TITLE
最新v2.5.0版本的windows 32位软件，谷歌浏览器始终无法下载，报病毒

### ISSUE THREAD

**Issue by shanghai20068** [apernet/hysteria#1139]
你好，最新v2.5.0版本的windows 32位软件，谷歌浏览器始终无法下载，报病毒。
尝试了5次，无论是否关闭浏览器的安全下载，都提示为病毒无法下载，即使下载进度完成，也显示失败。
![11](https://github.com/apernet/hysteria/assets/168880654/e086f0b2-9f64-41cf-a888-92521fdb4f4f)

**Comment by haruue** [comment]
首先 Chrome 这个报错是你电脑上安装的杀毒软件检测的而不是 Chrome 自己检测的。

用 VirusTotal 测试了下 2.5.0 的 hysteria-windows-386.exe 在绝大多数杀毒引擎都不会报毒， 包括 Microsoft。
https://www.virustotal.com/gui/file/7ed4478629ce30f56a9899f2bacc5ecbf6b8dd943a727cd62e704b1d4a08055e?nocache=1

但是实测这个文件会被 Windows Defender 报 `Trojan:Win32/Phonzy.B!ml`。
![image](https://github.com/apernet/hysteria/assets/13131972/b9e2ce47-ea9f-4855-a125-d037a936de3f)

**Comment by haruue** [comment]
另外 hysteria-windows-amd64-avx.exe 和 hysteria-windows-amd64.exe 都没被 Windows Defender 报毒。 
要不你用这两个吧， 这都 2024 年了没理由还用 386 版本的。
