### ISSUE TITLE
是否考虑支持listen多个port ?

### ISSUE THREAD

**Issue by abcfy2** [apernet/hysteria#1146]
**描述你希望的解决方案**

我这边运营商似乎会间歇性抽风，似乎会屏蔽国外某些范围的标准端口。具体表现就是某些时间段内一些标准端口如 80， 443，8080，8443等会阻断访问，但是其他端口不受影响，比如SSH还可以正常联通。

所以请求这个特性，希望 `listen`配置可以同时监听多个端口作为fallback，如 `listen: :443,:12345,[::]:9999` 等等，比如像这样支持 `,`分割多个监听端口，这样理论上应该可以兼容旧版本的配置

谢谢了

**Comment by haruue** [comment]
不会实现这种需求。 请去用 iptables / nftables 做端口转发， 和端口跳跃是一样的。
https://hysteria.network/zh/docs/advanced/Port-Hopping/#_3
