### ISSUE TITLE
如果服务器禁用udp是不是就无法使用了？

### ISSUE THREAD

**Issue by workmengxue** [apernet/hysteria#1154]
还是可以使用TCPsocket？

**Comment by haruue** [comment]
Hysteria 只支持 UDP。
如果服务器只支持 TCP 又想要用 brutal 拥塞控制， 可以试试 [tcp-brutal](https://github.com/apernet/tcp-brutal) 或者套一个 [udp-raw](https://github.com/wangyu-/udp2raw)。
