### ISSUE TITLE
Add TCP-Brutal to Hysteria2 for Enhanced GFW Evasion

### ISSUE THREAD

**Issue by zytakeshi** [apernet/hysteria#1157]
I am writing to request the addition of the TCP-Brutal protocol to Hysteria. It is said by others on telegram that based on recent observations, it appears that GFW (Great Firewall) has started marking IPs that generate significant UDP traffic over extended periods, not limited to specific UDP-based circumvention protocols. The marking occurs after a certain period rather than immediately. For instance, IPs changed 15 hours ago remain unmarked, while fixed IPs were marked within a specific timeframe earlier today.

The marking and blocking occur within a one-hour window from 15:30 to 16:30 GMT+9. Marked machines experience dropped UDP packets for any traffic sent from overseas to domestic IPs, regardless of the port or protocol, while TCP and ICMP traffic remain unaffected.

Given the difficulty in identifying specific protocols due to the vast volume of UDP traffic on public networks and the challenges of protocol header recognition (as most application-layer protocols based on UDP rely on ports rather than byte sequence for identification), it seems more likely that these measures are part of a strategy to mitigate overseas DDoS attacks (UDP Flood).

As such, we hypothesize that UDP-based circumvention protocols are still suitable for personal use, but further investigation is required to confirm whether specific probing mechanisms are in place.

To address these issues and adapt to the evolving network environment in China, we kindly request that the TCP-Brutal protocol be added to Hysteria. This addition would enhance the ability to bypass the current GFW strategies and ensure continued access for users in China.

Thank you for considering this request. We appreciate your efforts in maintaining and improving Hysteria and look forward to seeing this feature implemented.

**Comment by stqfdyr** [comment]
bad news 😭

**Comment by nxtreaming** [comment]
it's good news.  the significant UDP traffic should be marked and blocked. it's a bad and unfair design.

**Comment by stqfdyr** [comment]
> it's a good news. the significant UDP traffic should be marked and blocked. it's a bad and unfair design.

you're a 🤡

**Comment by nxtreaming** [comment]
You're a newbie

**Comment by tobyxdd** [comment]
Hysteria is not a TCP protocol to begin with, so it can't support a congestion control for TCP. With that being said it doesn't mean there won't ever be something similar to FakeTCP that Hysteria 1 had - we do plan to look into it, but it will never be a real TCP protocol.

There are a plethora of TCP protocols out there and the reason we made TCP Brutal is to integrate with them rather than reinvent a new wheel. If you really want TCP Brutal, I suggest you bring it to the attention of those devs.
