### ISSUE TITLE
从其服务器后Jul 17 02:48:57 debian systemd[1]: Started Hysteria Server Service (config.yaml). Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        server mode Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        server up and running        {"listen": ":443"} Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        maintenance        started background certificate maintenance        {"cache": "0xc00013dab0"} root@debian:~# 

### ISSUE THREAD

**Issue by like99168** [apernet/hysteria#1158]
Jul 17 02:48:57 debian systemd[1]: Started Hysteria Server Service (config.yaml).
Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        server mode
Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        server up and running        {"listen": ":443"}
Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        maintenance        started background certificate maintenance        {"cache": "0xc00013dab0"}
root@debian:~# 

您好，我每次重启服务器后就显示证书维护，有时候会自动恢复，有时候不会，请问这个我该如何处理，困扰很久的问题，谢谢您

**Comment by stqfdyr** [comment]
你这标题。。。。。。

**Comment by haruue** [comment]
您好， 您的日志所显示的是正常现象。 
如果你连不上， 请提供客户端日志。

**Comment by like99168** [comment]
结果是大规模的upd被阻断了，不是我一个人挂了

**Comment by like99168** [comment]
> 您好， 您的日志所显示的是正常现象。 如果你连不上， 请提供客户端日志。


日志如下最后的有链接记录是16号，之后就不行了。同一个服务器的reality协议是正产的，谢谢解答

Jul 16 07:11:46 debian hysteria[17929]: 2024-07-16T07:11:46-04:00        WARN        TCP error        {"addr": "157.107.91.103:51479", "id": "user", "reqAddr": "appboot.netflix.com:443", "error": "readfrom tcp4 103.103.245.142:54694->35.163.107.72:443: timeout: no recent network activity"}
Jul 16 07:11:46 debian hysteria[17929]: 2024-07-16T07:11:46-04:00        WARN        TCP error        {"addr": "157.107.91.103:51479", "id": "user", "reqAddr": "ipv4-c031-hkg001-ix.1.oca.nflxvideo.net:443", "error": "readfrom tcp4 103.103.245.142:50520->23.246.57.144:443: timeout: no recent network activity"}
Jul 16 07:11:46 debian hysteria[17929]: 2024-07-16T07:11:46-04:00        WARN        TCP error        {"addr": "157.107.91.103:51479", "id": "user", "reqAddr": "ipv4-c048-hkg001-ix.1.oca.nflxvideo.net:443", "error": "readfrom tcp4 103.103.245.142:38152->23.246.57.153:443: timeout: no recent network activity"}
Jul 16 21:16:04 debian hysteria[17929]: 2024-07-16T21:16:04-04:00        INFO        maintenance        advancing OCSP staple        {"identifiers": ["erics.ericool.me"], "from": "2024-07-20T12:27:58Z", "to": "2024-07-24T01:15:58Z"}
Jul 17 02:00:50 debian systemd[1]: Stopping Hysteria Server Service (config.yaml)...
Jul 17 02:00:50 debian systemd[1]: hysteria-server.service: Succeeded.
Jul 17 02:00:50 debian systemd[1]: Stopped Hysteria Server Service (config.yaml).
Jul 17 02:00:50 debian systemd[1]: hysteria-server.service: Consumed 45.341s CPU time.
Jul 17 02:00:50 debian systemd[1]: Started Hysteria Server Service (config.yaml).
Jul 17 02:00:50 debian hysteria[75221]: 2024-07-17T02:00:50-04:00        INFO        server mode
Jul 17 02:00:50 debian hysteria[75221]: 2024-07-17T02:00:50-04:00        INFO        maintenance        started background certificate maintenance        {"cache": "0xc0000d7960"}
Jul 17 02:00:50 debian hysteria[75221]: 2024-07-17T02:00:50-04:00        INFO        server up and running        {"listen": ":443"}
Jul 17 02:01:49 debian systemd[1]: Stopping Hysteria Server Service (config.yaml)...
Jul 17 02:01:49 debian systemd[1]: hysteria-server.service: Succeeded.
Jul 17 02:01:49 debian systemd[1]: Stopped Hysteria Server Service (config.yaml).
Jul 17 02:01:49 debian systemd[1]: Started Hysteria Server Service (config.yaml).
Jul 17 02:01:49 debian hysteria[75802]: 2024-07-17T02:01:49-04:00        INFO        server mode
Jul 17 02:01:49 debian hysteria[75802]: 2024-07-17T02:01:49-04:00        INFO        maintenance        started background certificate maintenance        {"cache": "0xc000193ab0"}
Jul 17 02:01:49 debian hysteria[75802]: 2024-07-17T02:01:49-04:00        INFO        server up and running        {"listen": ":443"}
Jul 17 02:48:57 debian systemd[1]: Stopping Hysteria Server Service (config.yaml)...
Jul 17 02:48:57 debian systemd[1]: hysteria-server.service: Succeeded.
Jul 17 02:48:57 debian systemd[1]: Stopped Hysteria Server Service (config.yaml).
Jul 17 02:48:57 debian systemd[1]: Started Hysteria Server Service (config.yaml).
Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        server mode
Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        server up and running        {"listen": ":443"}
Jul 17 02:48:57 debian hysteria[100397]: 2024-07-17T02:48:57-04:00        INFO        maintenance        started background certificate maintenance        {"cache": "0xc00013dab0"}
root@debian:~#
