### ISSUE TITLE
使用内置的acme获取证书时，缓存已签发的证书

### ISSUE THREAD

**Issue by giveup** [apernet/hysteria#1162]
**你的功能请求是否与某个问题有关？**
使用内置的acme获取证书时，首次启动可以按预期工作。但如果因为某些原因重启hysteria服务端时，这个时候letsencrypt会提示请求过于频繁。导致再也无法获取证书。经观察，发现正常启动时，配置的证书目录下并没有保存证书，所以可能是这个原因导致每次启动时都要获取证书，从而引起letsencrypt提示请求过于频繁。

**描述你希望的解决方案**
使用内置的acme获取证书时，保存已经签发的证书。避免每次启动获取证书。

**有没有其他替代方案**
无

**额外信息**
无

**Comment by haruue** [comment]
您好， 证书是带缓存的， 可能是你配置的证书目录没有写入权限导致证书没有留下来。 
如果你使用官方脚本安装， 不要配置证书目录， 证书会被保存到 `/var/lib/hysteria/acme` 。
