### ISSUE TITLE
服务端更新到2.5.0，感觉有问题

### ISSUE THREAD

**Issue by jymr92** [apernet/hysteria#1164]
纯粹使用感受说明，本人tg使用的多，以tg为例
加载视频很慢很慢很慢，说三遍，几乎卡死的感觉，tg就是不下载，进度一直是0。
但是打开浏览器又能正常使用，测速也正常。
回退到2.4.5后，有所改观。

服务器系统是 centos7 x86_64

**Comment by shakibamoshiri** [comment]
First  
make sure you do not have a proxy for your telegram , using a VPN and a proxy at the same time usually does not work with telegram or it becomes slow 

Second  
probably you should do a speedtest with both old and new version to see if there is any thing specious (test using hysteria client)
