### ISSUE TITLE
关于性能优化中：流控制接收窗口大小 设置的请教

### ISSUE THREAD

**Issue by wkr8501** [apernet/hysteria#1171]
quic:
  initStreamReceiveWindow: 26843545 
  maxStreamReceiveWindow: 26843545 
  initConnReceiveWindow: 67108864 
  maxConnReceiveWindow: 67108864

说明中提到 ”Hysteria 在客户端和服务器配置中都有以下 QUIC 流控制接收窗口参数“

请问这个参数若要生效，是要再服务端和客户段都设置，还是单独设置一端即可？

**Comment by haruue** [comment]
这个选项在接收端生效, 影响的是接收端流控。
若仅在客户端设置， 则仅对客户端接收（客户端下载）的流量有效。
若仅在服务端设置， 则仅对服务端接收（客户端上传）的流量有效。
