### ISSUE TITLE
Userpass isn't working

### ISSUE THREAD

**Issue by XuliGan4eg2006** [apernet/hysteria#1174]
My config looks like:
```
{
  "listen": ":444",
  "acme": {
    "domains": [
      "domain.com"
    ],
    "email": "user@gmail.com"
  },
  "auth": {
    "type": "userpass",
    "userpass": {
      "admin": "damnThatCrazy",
      "usernone": "Kdk342kmnnd"
    }
  },
  "masquerade": {
    "type": "proxy",
    "proxy": {
      "url": "https://habr.com/",
      "rewriteHost": true
    }
  }
}
```

But on attempt to connect I got no logs and no connection:
![image](https://github.com/user-attachments/assets/d6565b4b-dc08-4057-b0ea-81f0a414f220)

Is this my issue?

**Comment by codetang-2417** [comment]
This is because you included uppercase letters in the password (including uppercase letters in the username would result in the same issue).

**Comment by haruue** [comment]
@codetang-2417 Nope. Uppercase letters in the password won't cause this issue. Both username and password are case-sensitive. And at least we use a password that includes uppercase letters in our internal test.

**Comment by codetang-2417** [comment]
> @codetang-2417 Nope. Uppercase letters in the password won't cause this issue. Both username and password are case-sensitive. And at least we use a password that includes uppercase letters in our internal test.密码中的大写字母不会导致此问题。用户名和密码都区分大小写。而且至少在我们的内部测试中，我们使用了包含大写字母的密码。

我需要发送配置文件或者其他信息来找出问题吗？我仅仅只更改了用户名或者密码中的字母为大写，然后就无法正常工作了。
这是我的服务器端配置:

```
$ sudo cat /etc/hysteria/config.yaml 
listen: :8443 #监听端口

#使用自签证书 或者已有 ca 证书
#ca 证书
tls:
  cert: /home/me/fullchain.cer
  key: /home/me/hyperdns.com.key


auth:
  # 设置多用户
  type: userpass
  userpass:
    usrb23: k837dh1jd93j4d
    ubr3r: ik93ngt29shd92
    ubr3R: ik93ngt29shd92
    ubr3k: ik93ngt29shd92

masquerade:
  type: proxy
  proxy:
    url: https://bing.com #伪装网址
    rewriteHost: true
  listenHTTP: :80
  listenHTTPS: :8443

trafficStats:
  listen: :2140
  secret: Tdhuse24@

bandwidth:
  up: 20 mbps
  down: 50 mbps
```
其中 ubr3R 无法连通服务器

**Comment by haruue** [comment]
@codetang-2417 测试了下您提及的问题确实存在。

研究了下是 viper 的实现导致所有配置项的 key 被转换成小写， 所以用户名确实是不区分大小写的。
密码作为 value ， 仍然是区分大小写的。

参考： https://github.com/spf13/viper/issues/373

cc @tobyxdd

**Comment by Gor597** [comment]
Gor

**Comment by Gor597** [comment]
Gor

**Comment by Gor597** [comment]
https://github.com/user-attachments/assets/15956f15-d623-4e36-b905-26e772fdf74f
