### ISSUE TITLE
无法代理某些UDP包

### ISSUE THREAD

**Issue by LittleChest** [apernet/hysteria#1178]
**描述问题**

代理游戏的 UDP 包（例如 Minecraft Bedrock）时会出现部分丢包或完全丢包的情况

**如何复现**

1. 连接到节点 确保游戏被代理
2. 连接到服务器

**预期行为**

正常连接到服务器

**日志**

服务端：

```
Aug 10 02:31:13 G-Proxy hysteria[1840]: 2024-08-10T02:31:13+08:00        DEBUG        UDP request        {"addr": "[HIDDEN]:4737", "id": "user", "sessionID": 0, "reqAddr": "139.99.39.244:19132"}
Aug 10 02:32:20 G-Proxy hysteria[1840]: 2024-08-10T02:32:20+08:00        DEBUG        UDP closed        {"addr": "[HIDDEN]:4737", "id": "user", "sessionID": 0}
```
客户端：

```
02:32:20.159    Info: [UDP] 172.19.0.1:41888 --> geo.hivebedrock.network:19132 match  using 漏网之鱼[hysteria]
```

**设备和操作系统**

客户端：Clash Meta 2.15.0 on Android 14
服务端：Hysteria 2.5.0 amd64-avx on Debian 11.0

**额外信息**

TCP 连接正常
小型 UDP 包正常（例如 DNS 查询）
似乎与 https://github.com/apernet/hysteria/issues/733#issuecomment-1840324074 有关

**Comment by wen-long** [comment]
试试 
```
QUIC_GO_DISABLE_GSO=1
disablePathMTUDiscovery: true
```

**Comment by LittleChest** [comment]
> 试试
> 
> ```
> QUIC_GO_DISABLE_GSO=1
> disablePathMTUDiscovery: true
> ```

添加到配置文件吗 还是环境变量🤔

**Comment by LittleChest** [comment]
> 试试
> 
> ```
> QUIC_GO_DISABLE_GSO=1
> disablePathMTUDiscovery: true
> ```

添加`disablePathMTUDiscovery`就可以了 谢谢
