### ISSUE TITLE
开了sniff之后，访问域名带端口出问题

### ISSUE THREAD

**Issue by yrwy** [apernet/hysteria#1182]
**描述问题**
开了sniff之后，访问域名带端口出问题
比如访问 xxx.com:8080 
它会把整个访问的“xxx.com:8080”当成域名去解析，然后出现解析出错。
**设备和操作系统**
oracle arm64 ubuntu22.04 最新版本2.50的hysteria

**Comment by tobyxdd** [comment]
提供一下日志和你访问的方式

**Comment by tobyxdd** [comment]
不用了，能够复现

**Comment by yrwy** [comment]
还有个问题，如果客户端的配置添加的地址是ipv6的话，直接报错。
例如 2603:c022:8016:20ee:cf73:da88:f310:xxxx:443

2024-08-25T18:58:39+08:00	FATAL	failed to initialize client	{"error": "invalid config: server: lookup 2603:c022:8016:20ee:cf73:da88:f310:xxxx:443: no such host"}

**Comment by haruue** [comment]
> 还有个问题，如果客户端的配置添加的地址是ipv6的话，直接报错。 例如 2603:c022:8016:20ee:cf73:da88:f310:xxxx:443
> 
> 2024-08-25T18:58:39+08:00 FATAL failed to initialize client {"error": "invalid config: server: lookup 2603:c022:8016:20ee:cf73:da88:f310:xxxx:443: no such host"}

```
server: "[2603:c022:8016:20ee:cf73:da88:f310:xxxx]:443"
```
