### ISSUE TITLE
在google cloud platform上搭建时被认定为正在进行DoS攻击

### ISSUE THREAD

**Issue by zhishixiang** [apernet/hysteria#1186]
**描述问题**
在google cloud上搭建并使用hy2时收到了警告邮件，显示发现该主机正在进行DoS攻击，由于违反使用协议被停机。
<img width="308" alt="image" src="https://github.com/user-attachments/assets/fc6031f0-3179-40f6-9dff-7a540b70970c">

**如何复现**
在google cloud上搭建并正常使用，并没有搭建任何除hy2以外的服务

**预期行为**
希望能在wiki中附上如何向IDC解释这一行为的额外说明
![image](https://github.com/user-attachments/assets/6901154f-071d-4edc-96e4-790a5f7d1642)

**日志**
暂无

**设备和操作系统**
debian-12-bookworm x86_64

**额外信息**
暂无

**Comment by tcomil** [comment]
debian不好 建议用Rocky Linux

**Comment by pundoo** [comment]
由于端口跳跃，我在 Digitalocean 上也遇到了同样的问题。

**Comment by tobyxdd** [comment]
Google Cloud 就是有这个问题。理论上向客服申诉可以解决，但是建议直接换别家
