### ISSUE TITLE
Call of Duty20不走代理

### ISSUE THREAD

**Issue by tcomil** [apernet/hysteria#1187]
**Describe the bug**
COD20不走代理 显示的地区是hysyetia代理服务器的地区 但IP是本地IP
<img width="650" alt="image" src="https://github.com/user-attachments/assets/cce9ff80-ee47-44d9-a784-2cad9231f55e">

使用Win11自带的Xbox游玩 使用Clash Verge Rev 1.7.6

**Comment by tcomil** [comment]
打开TUN模式后 游戏显示代理服务器的IP了 但是无法游玩游戏 显示“无法与数据中心建立连接”

**Comment by tobyxdd** [comment]
请向 Clash Verge 反馈
