### ISSUE TITLE
masquerade 改进，sni 不匹配时直接拒绝TLS 握手

### ISSUE THREAD

**Issue by xf1** [apernet/hysteria#1189]
**你的功能请求是否与某个问题有关？**
使用 ip 直接访问会泄漏证书。
> curl -v --http3 https://127.0.0.1
> *   Trying 127.0.0.1:443...
> *  CAfile: /etc/ssl/certs/ca-certificates.crt
> *  CApath: none
> * Server certificate:
> *  subject: CN=example.com

**描述你希望的解决方案**
改成 caddy 默认或者 nginx 开启 ssl_reject_handshake 那样，sni 不对就拒绝握手，不发送证书。
>curl -v https://127.0.0.1
>*   Trying 127.0.0.1:443...
>* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
>* ALPN, offering h2
>* ALPN, offering http/1.1
>*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
>* TLSv1.0 (OUT), TLS header, Certificate Status (22):
>* TLSv1.3 (OUT), TLS handshake, Client hello (1):
>* TLSv1.2 (IN), TLS header, Unknown (21):
>* TLSv1.3 (IN), TLS alert, internal error (592):
>* error:0A000438:SSL routines::tlsv1 alert internal error
>* Closing connection 0
>curl: (35) error:0A000438:SSL routines::tlsv1 alert internal error

**有没有其他替代方案**

**额外信息**

**Comment by haruue** [comment]
测试了下 acme 是没有这个问题的， 看起来我们只需要参考 certmagic 给本地配置证书的情况加上相应逻辑即可。

**Comment by xf1** [comment]
我只测了用本地证书，一天没看 PR 都就绪，速度太快了，非常感谢！
