### ISSUE TITLE
客戶端無法連服務端區網內的設備(192.168.0.X)，小火箭可以連

### ISSUE THREAD

**Issue by kousyougi** [apernet/hysteria#1192]
**描述问题**
客戶端無法連服務端區網內的設備(192.168.0.X)

**如何复现**
用小火箭通過可以連進家裡區網內的設備(192.168.0.X)，
但用hysteria官網客戶端會time out。
所以hysteria服務端應該是沒擋，應該是客戶端在擋。

**Comment by haruue** [comment]
您好。

由於我們平時進行功能測試就是去連接區網（LAN）裏的設備， 因此通過您給出的信息我們無法復現這個問題。

考慮到您的服務端和客户端都開在本地， 不存在暴露公網 IPv4 的問題， 請提供以下額外信息：

* 服務器端配置文件
* 客户端配置文件
* 客户端連接失敗時的輸出
* 服務器端網絡配置
  * 若是 Linux 請提供 `ip address` 和 `ip route` 的輸出
  * 若是 macOS 請提供 `ifconfig` 和 `netstat -rn` 的輸出
  * 若是 Windows 請提供 `ipconfig /all` 和 `netstat -rn` 的輸出
* 客户端網絡配置（獲取方法同上）

**Comment by kousyougi** [comment]
抱歉

我這邊檢查完了，原來是我hysteria客戶端設定錯誤連到別的地方了。
測試 127.0.0.1 或 192.168.0.X 都沒問題。
