### ISSUE TITLE
android/arm64 compile failed

### ISSUE THREAD

**Issue by vahidx4r4x** [apernet/hysteria#1197]
Hi,
I want to compile source code for android/arm64
I already set env to android/arm64
but I get this error

```
$ python hyperbole.py build -r
fatal: Not a valid object name HEAD
F:\This Pc\Desktop\hysteria-master\hyperbole.py:179: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  app_date = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Building for android/arm64...
Traceback (most recent call last):
  File "F:\This Pc\Desktop\hysteria-master\hyperbole.py", line 513, in <module>
    main()
  File "F:\This Pc\Desktop\hysteria-master\hyperbole.py", line 493, in main
    cmd_build(args.pprof, args.release, args.race)
  File "F:\This Pc\Desktop\hysteria-master\hyperbole.py", line 216, in cmd_build
    os.environ.get("ANDROID_NDK_HOME")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Comment by haruue** [comment]
Hi there,

To build Hysteria with `HY_APP_PLATFORMS=android/arm64`, please have the Android NDK installed and set the `ANDROID_NDK_HOME`.

For an example of how to build Hysteria android/arm64 on Debian 12:

```bash
# Install Android SDK Manager
# If your distribution doesn't provide this package, you can also
# manually download it from 
# https://developer.android.com/studio#command-line-tools-only
apt update && apt install -y sdkmanager

# Install NDK (Side by side) 27.0.12077973 with sdkmanager
sdkmanager --install 'ndk;27.0.12077973'

# Set ANDROID_NDK_HOME to the <sdk>/ndk/<ndk-version>
export ANDROID_NDK_HOME=/opt/android-sdk/ndk/27.0.12077973

# Build hysteria
cd /path/to/hysteria-src
HY_APP_PLATFORMS=android/arm64 python3 hyperbole.py build
```

**Comment by vahidx4r4x** [comment]
> Hi there,
> 
> To build Hysteria with `HY_APP_PLATFORMS=android/arm64`, please have the Android NDK installed and set the `ANDROID_NDK_HOME`.
> 
> For an example of how to build Hysteria android/arm64 on Debian 12:
> 
> ```shell
> # Install Android SDK Manager
> # If your distribution doesn't provide this package, you can also
> # manually download it from 
> # https://developer.android.com/studio#command-line-tools-only
> apt update && apt install -y sdkmanager
> 
> # Install NDK (Side by side) 27.0.12077973 with sdkmanager
> sdkmanager --install 'ndk;27.0.12077973'
> 
> # Set ANDROID_NDK_HOME to the <sdk>/ndk/<ndk-version>
> export ANDROID_NDK_HOME=/opt/android-sdk/ndk/27.0.12077973
> 
> # Build hysteria
> cd /path/to/hysteria-src
> HY_APP_PLATFORMS=android/arm64 python3 hyperbole.py build
> ```

thanks that was helpful 
now im stuck at this error:

```
$ python hyperbole.py build -r
fatal: Not a valid object name HEAD
F:\This Pc\Desktop\hysteria-master\hyperbole.py:179: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  app_date = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
# runtime/cgo
cgo: C compiler "F:\\This" not found: exec: "F:\\This": executable file not found in %PATH%
Building for android/arm64...
Failed to build for android/arm64

```

**Comment by haruue** [comment]
> fatal: Not a valid object name HEAD

Instead of downloading an archive tarball from the release page, please use `git clone`. Or maybe you can use the following alternative build command (without versioning the built binary).

```
GOOS=android GOARCH=arm64 go build -o build/hysteria-android-arm64 ./app
```

**Comment by haruue** [comment]
> cgo: C compiler "F:\\This" not found: exec: "F:\\This": executable file not found in %PATH%

And this is because you have a space in your `ANDROID_NDK_HOME`. On the linux/bash, we use quotes like

```bash
export ANDROID_NDK_HOME="/path/with space in it/android-sdk/ndk/xxx"
```

I don't use Windows, maybe you can ask ChatGPT how to handle this.

**Comment by vahidx4r4x** [comment]
> > fatal: Not a valid object name HEAD
> 
> Instead of downloading an archive tarball from the release page, please use `git clone`. Or maybe you can use the following alternative build command (without versioning the built binary).
> 
> ```
> GOOS=android GOARCH=arm64 go build -o build/hysteria-android-arm64 ./app
> ```

I did use "" for specifying the PATH for ANDROID_NDK_HOME

**Comment by vahidx4r4x** [comment]
> > cgo: C compiler "F:\This" not found: exec: "F:\This": executable file not found in %PATH%
> 
> And this is because you have a space in your `ANDROID_NDK_HOME`. On the linux/bash, we use quotes like
> 
> ```shell
> export ANDROID_NDK_HOME="/path/with space in it/android-sdk/ndk/xxx"
> ```
> 
> I don't use Windows, maybe you can ask ChatGPT how to handle this.

This command gave me a file
I want to build the .apk file for nekobox app

**Comment by haruue** [comment]
> I want to build the .apk plugin file for nekobox app

Hello, 

For any questions related to third-party clients, please open a new issue in their own repo.

Please note that third-party clients are not maintained by us, nor are we familiar with their codebase.
