### ISSUE TITLE
0x0 Error Accepting Stream Failed

### ISSUE THREAD

**Issue by LeonG68** [apernet/hysteria#1224]
**Describe the bug**
After I connect to the VPN, I get a 0x0 error, which is not listed on the error logs.

"id": "user", "error": "accepting stream failed: Applicati
on error 0x0 (remote)"

**To Reproduce**
Use Clash Verge to connect to the vpn and wait. Then the error will pop up.

**Device and Operating System**
Ubuntu 22.04

**Comment by tobyxdd** [comment]
You did not provide full logs and steps to reproduce the problem.
