### ISSUE TITLE
伪装未生效，代理正常。

### ISSUE THREAD

**Issue by Yakumo127** [apernet/hysteria#1232]
**Describe the bug**

使用挂在cf上的域名 并配置dns 解析至服务器，未开启代理
代理正常，但是伪装未生效？

访问域名显示 ERR_CONNECTION_CLOSED 

已经使用chrome --origin-to-force-quic-on=your.site.com:443指令
可以正常访问github等被墙网站

**To Reproduce**.
访问域名“域名:443”

**Expected behavior**
跳转到www.bing.com

**Logs**
一直是这两条重复
Oct 20 07:38:34 racknerd-011b91 hysteria[2484304]: 2024-10-20T07:38:34-04:00        WARN        TCP error        {"addr": "222.22.222.212:6275", "id": "user", "reqAddr": "edge.microsoft.com:443", "error": "writeto tcp4 148.148.148.148:62898->204.79.197.239:443: read tcp4 148.148.148.148:62898->204.79.197.239:443: read: connection reset by peer"}
Oct 20 07:49:32 racknerd-011b91 hysteria[2502772]: 2024-10-20T07:49:32-04:00        WARN        TCP error        {"addr": "222.22.222.212:6146", "id": "user", "reqAddr": "域名:443", "error": "dial tcp4 148.148.148.148:443: connect: connection refused"}

**Device and Operating System**
hysteria2，ubuntu20.04

**Additional context**

**Comment by Yakumo127** [comment]
使用bash <(curl -fsSL https://get.hy2.sh/) 该脚本搭建

**Comment by Yakumo127** [comment]
服务端配置文件
listen: :443 #监听端口

#使用CA证书
acme:
  domains:
    - rn.111111.xyz #你的域名，需要先解析到服务器ip
  email: test@sharklasers.com

#使用自签证书
#tls:
#  cert: /etc/hysteria/server.crt
#  key: /etc/hysteria/server.key

auth:
  type: password
 # password:  #设置认证密码
  
masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com #伪装网址
    rewriteHost: true

**Comment by haruue** [comment]
您好。

我想问下你们是从看到哪里的教程， 这么多人伪装都是反代 bing。

我们 **不建议反代任何微软系网站**， 包括微软官网， bing， 或者 GitHub。 微软会认为您创建了一个外观与微软网站一致的「钓鱼网站」用于恶意获取用户登录凭据， 并给你的服务商发送滥用报告。 这可能会导致您的 VPS 被服务商封禁。

**Comment by Yakumo127** [comment]
> 您好。
> 
> 我想问下你们是从看到哪里的教程， 这么多人伪装都是反代 bing。
> 
> 我们 **不建议反代任何微软系网站**， 包括微软官网， bing， 或者 GitHub。 微软会认为您创建了一个外观与微软网站一致的「钓鱼网站」用于恶意获取用户登录凭据， 并给你的 VPS 提供商发送滥用报告。 这可能会导致您的 VPS 被提供商封禁。

在youtube上的一些教程，
我试过改成google.com 也是提示
Oct 20 07:38:34 racknerd-011b91 hysteria[2484304]: 2024-10-20T07:38:34-04:00 WARN TCP error {"addr": "222.22.222.212:6275", "id": "user", "reqAddr": "edge.microsoft.com:443", "error": "writeto tcp4 148.148.148.148:62898->204.79.197.239:443: read tcp4 148.148.148.148:62898->204.79.197.239:443: read: connection reset by peer"}
Oct 20 07:49:32 racknerd-011b91 hysteria[2502772]: 2024-10-20T07:49:32-04:00 WARN TCP error {"addr": "222.22.222.212:6146", "id": "user", "reqAddr": "域名:443", "error": "dial tcp4 148.148.148.148:443: connect: connection refused"}

**Comment by haruue** [comment]
```
Oct 20 07:49:32 racknerd-011b91 hysteria[2502772]: 2024-10-20T07:49:32-04:00 WARN TCP error {"addr": "222.22.222.212:6146", "id": "user", "reqAddr": "域名:443", "error": "dial tcp4 148.148.148.148:443: connect: connection refused"}
```

看起来这是因为你的浏览器在通过 socks5 代理， 通过 hysteria 客户端访问你的域名， 当浏览器的 socks5 代理生效时， 不会通过 QUIC 连接目标网站（即使设置了 `--origin-to-force-quic-on` 选项）

**Comment by Yakumo127** [comment]
> ```
> Oct 20 07:49:32 racknerd-011b91 hysteria[2502772]: 2024-10-20T07:49:32-04:00 WARN TCP error {"addr": "222.22.222.212:6146", "id": "user", "reqAddr": "域名:443", "error": "dial tcp4 148.148.148.148:443: connect: connection refused"}
> ```
> 
> 看起来这是因为你的浏览器在通过 socks5 代理， 通过 hysteria 客户端访问你的域名， 当浏览器的 socks5 代理生效时， 不会通过 QUIC 连接目标网站（即使设置了 `--origin-to-force-quic-on` 选项）

了解了感谢，我试下tun模式能否成功使用quic 链接目标网站

**Comment by haruue** [comment]
另外伪装反代 Google 仍然不合适。 
出于避免大量相同配置成为特征的考量， 我们不会推荐应该伪装反代什么网站。 
我之前在 Hysteria 群提及过应该如何选择伪装的网站， 我把这些内容复制到这里。

> 我个人建议配反代的话， 原则上尽量反代一些简单的， 墙内看起来内容合法网站。 避免交互复杂、 有大量用户生成的中文内容的网站。
> GitHub 上有很多在国内不合法的内容， 你反代个 GitHub 那不是找封么。。
> 还好没见到反代 Google Twitter YouTube 的。。

https://t.me/hysteria_github/78836/324651

**Comment by haruue** [comment]
> 我试下tun模式能否成功使用quic 链接目标网站

如果你只是要测试伪装是否工作， 我建议直接关掉代理进行测试。

**Comment by Yakumo127** [comment]
> 另外伪装反代 Google 仍然不合适。 出于避免大量相同配置成为特征的考量， 我们不会推荐应该伪装反代什么网站。 我之前在 Hysteria 群提及过应该如何选择伪装的网站， 我把这些内容复制到这里。
> 
> > 我个人建议配反代的话， 原则上尽量反代一些简单的， 墙内看起来内容合法网站。 避免交互复杂、 有大量用户生成的中文内容的网站。
> > GitHub 上有很多在国内不合法的内容， 你反代个 GitHub 那不是找封么。。
> > 还好没见到反代 Google Twitter YouTube 的。。
> 
> https://t.me/hysteria_github/78836/324651

只是根据youtube的教程设置的，只是权当测试，为了放置意外的错误，才没有对它的教程代码做更改，了解我这就试一下

**Comment by Yakumo127** [comment]
感谢，完美解决问题。看来确实是代理软件的问题，十分感谢。

> > 我试下tun模式能否成功使用quic 链接目标网站
> 
> 如果你只是要测试伪装是否工作， 我建议直接关掉代理进行测试。

十分感谢，伪装成功。看来确实是代理软件的问题
有点小小的疑惑，使用自己域名的伪装验证方法已经理解了，使用自签 tls 的方式，应当如何检查伪装是否生效呢？
十分感谢您的解惑

**Comment by haruue** [comment]
测试了下看起来 Chrome 的 `--ignore-certificate-errors` 对 QUIC 不起作用。 试图访问被 `--origin-to-force-quic-on` 限制了只能用 QUIC 去连接的网站， 且证书不被信任的情况下会提示 `ERR_QUIC_PROTOCOL_ERROR`， 而不是允许用户继续的普通 TLS 错误。

我怀疑 Chrome 这么设计是为了能够在任何 QUIC 错误（包括证书错误）发生时快速 fallback 到 TCP。

因此， 如果是用自签名证书， 可能只能手动将自签名的证书（或其根证书）手动安装到系统的可信任根证书列表中进行测试， 如果是直接使用伪装网站的域名， 可能还需要配置 hosts 以让 Chrome 向正确的服务器发送请求。

**Comment by Yakumo127** [comment]
辛苦了，感谢
________________________________
发件人: Haruue ***@***.***>
发送时间: 2024年10月24日 14:49
收件人: apernet/hysteria ***@***.***>
抄送: Yakumo127 ***@***.***>; Author ***@***.***>
主题: Re: [apernet/hysteria] 伪装未生效，代理正常。 (Issue #1232)


测试了下看起来 Chrome 的 --ignore-certificate-errors 对 QUIC 不起作用。 试图访问被 --origin-to-force-quic-on 限制了只能用 QUIC 去连接的网站， 且证书不被信任的情况下会提示 ERR_QUIC_PROTOCOL_ERROR， 而不是允许用户继续的普通 TLS 错误。

我怀疑 Chrome 这么设计是为了能够在任何 QUIC 错误（包括证书错误）发生时快速 fallback 到 TCP。

因此， 如果是用自签名证书， 可能只能手动将自签名的证书（或其根证书）手动安装到系统的可信任根证书列表中进行测试， 如果是直接使用伪装网站的域名， 可能还需要配置 hosts 以让 Chrome 向正确的服务器发送请求。

―

**Comment by aaaaaaaazmx** [comment]
> 您好。
> 
> 我想问下你们是从看到哪里的教程， 这么多人伪装都是反代 bing。
> 
> 我们 **不建议反代任何微软系网站**， 包括微软官网， bing， 或者 GitHub。 微软会认为您创建了一个外观与微软网站一致的「钓鱼网站」用于恶意获取用户登录凭据， 并给你的 VPS 提供商发送滥用报告。 这可能会导致您的 VPS 被提供商封禁。

所有的youtube搭建hy2的教程都用的bing.com

**Comment by ermzx** [comment]
反代自建的AList等网盘服务类似物也是个不错的选择
