### ISSUE TITLE
使用socks5出站时报错：unexpected EOF

### ISSUE THREAD

**Issue by wzhpro** [apernet/hysteria#1236]
**描述问题**
使用socks5出站时报错：unexpected EOF
使用direct出站时，一切正常
通过curl测试socks5代理正常
 curl https://www.gstatic.com/generate_204 -x socks5://127.0.0.1:40000 -vv

**如何复现**
1、使用warp的proxy模式，在服务器在40000端口开代理
2、hysteria2中配置
```yaml
outbounds:
  - name: cloudflare
    type: socks5
    socks5:
      addr: 127.0.0.1:40000
```
3、访问报错（见下面的日志）

**预期行为**
流量通过127.0.0.1:40000出站

**日志**
```
hysteria    | 2024-10-29T12:54:28ZWARNTCP error{"addr": "x.x.x.x:56922", "id": "user", "reqAddr": "speed.cloudflare.com:443", 
"error": "unexpected EOF"}
hysteria    | 2024-10-29T12:54:28ZWARNTCP error{"addr": "x.x.x.x:56922", "id": "user", "reqAddr": "speed.cloudflare.com:443", 
"error": "unexpected EOF"}
```

**设备和操作系统**
debian12 + Docker( tobyxdd/hysteria,network:host)

**额外信息**
无

**Comment by learninnng** [comment]
me too
`
2024-10-30T16:41:50+08:00       DEBUG   TCP request     {"addr": "127.0.0.1:33953", "id": "user", "reqAddr": "github.com:443"}
2024-10-30T16:41:50+08:00       WARN    TCP error       {"addr": "127.0.0.1:33953", "id": "user", "reqAddr": "github.com:443", "error": "unexpected EOF"}
`

**Comment by wzhpro** [comment]
我这2天研究了下，大概知道原因了
hysteria中的socks5实际上是socks5h，会通过代理解析域名。然而warp的socks5不支持解析域名，所以就出错了。
似乎目前无解，我临时用其他软件采用socks4来绕过该问题。

**Comment by qq565425677** [comment]
> 我这2天研究了下，大概知道原因了 hysteria中的socks5实际上是socks5h，会通过代理解析域名。然而warp的socks5不支持解析域名，所以就出错了。 似乎目前无解，我临时用其他软件采用socks4来绕过该问题。

我也遇到同样的问题了。不过我在网上搜索，看到过去有人用warp分流成功过，不知道以前的版本能不能行

**Comment by learninnng** [comment]
resolved,just use socks5 udp 2 socks5 tcp ,it's work.

**Comment by Asukaaaaaa** [comment]
牛的，之前一直不知道怎么解决，根据楼上的信息去问了下kimi，最后通过gost这个工具把socks5h转发到warp的socks5代理上终于访问成功了

[gost地址](https://latest.gost.run/)

转发的配置
```
{
  "services": [
    {
      "name": "socks5h_service",
      "addr": ":1080",
      "resolver": "my_resolver",
      "handler": {
        "type": "socks5",
        "chain": "to_socks5_chain"
      },
      "listener": {
        "type": "tcp"
      }
    }
  ],
  "chains": [
    {
      "name": "to_socks5_chain",
      "hops": [
        {
          "name": "hop_to_socks5",
          "nodes": [
            {
              "name": "socks5_server",
              "addr": "127.0.0.1:9999",
              "connector": {
                "type": "socks5"
              },
              "dialer": {
                "type": "tcp"
              }
            }
          ]
        }
      ]
    }
  ],
  "resolvers": [
    {
      "name": "my_resolver",
      "nameservers": [
        {
          "addr": "1.1.1.1"
        },
        {
          "addr": "8.8.8.8"
        }
      ]
    }
  ]
}
```
