### ISSUE TITLE
客户端运行一段时间后报错"error": "too many open streams"，需要重启后才能正常

### ISSUE THREAD

**Issue by qingyanbaby** [apernet/hysteria#1239]
**描述问题**
客户端运行一段时间后报错"error": "too many open streams"，客户端无法正常联网，需要重启后才能正常

**如何复现**
重启后，每天都会

**预期行为**
可以一直正常运行

**日志**
SOCKS5 TCP error        {"addr": "192.168.124.63:48770", "reqAddr": "142.250.114.91:443", "error": "too many open streams"}

**设备和操作系统**
ubuntu20.04

**额外信息**
无

**Comment by JiyongShi** [comment]
Windows 11
2.5.2最新版本
服务端quic设置默认值，同样问题

**Comment by tobyxdd** [comment]
一段时间是多长时间

这个问题是 2.5.2 特有还是老版本也存在

服务端提高 [`maxIncomingStreams`](https://hysteria.network/docs/advanced/Full-Server-Config/#quic-parameters) 到比如 4096 能否解决或者至少延长出现需要的时间

**Comment by JiyongShi** [comment]
服务端配置如下：
listen: :993

tls:
  cert: /etc/hysteria/server.crt
  key: /etc/hysteria/server.key

auth:
  type: password
  password: ***
  
masquerade:
  type: proxy
  proxy:
    url: https://***
    rewriteHost: true

quic:
  maxIncomingStreams: 10240 

客户端Windows 11 24H2补丁到最新，使用V2rayN最新版本，**core使用sing_box时（sing_box issues中有类似问题讨论，切换了sing_box最近的4个release及prerelease版本均有出现，时间长短不固定）**，快的时候几十分钟就会出现类似错误，日志缩略如下：
2024/11/02 09:52:41 系统代理设置改变 - ForcedChange
+0800 2024-11-02 10:09:41 ERROR [3932227499 472ms] inbound/http[http]: process connection from 127.0.0.1:60501: write tcp 127.0.0.1:7070->127.0.0.1:60501: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-11-02 10:09:58 ERROR [3482996578 481ms] inbound/http[http]: process connection from 127.0.0.1:60624: write tcp 127.0.0.1:7070->127.0.0.1:60624: wsasend: An established connection was aborted by the software in your host machine.
+0800 2024-11-02 10:11:47 ERROR [1960840719 785ms] inbound/http[http]: process connection from 127.0.0.1:61850: download: write tcp 127.0.0.1:7070->127.0.0.1:61850: wsasend: An existing connection was forcibly closed by the remote host. | upload: raw-read tcp 127.0.0.1:7070->127.0.0.1:61850: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:11:50 ERROR [4117706191 916ms] inbound/http[http]: process connection from 127.0.0.1:61875: upload: raw-read tcp 127.0.0.1:7070->127.0.0.1:61875: An existing connection was forcibly closed by the remote host. | download: write tcp 127.0.0.1:7070->127.0.0.1:61875: wsasend: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:13:36 ERROR [271241665 3.58s] inbound/http[http]: process connection from 127.0.0.1:62414: read http request: read tcp 127.0.0.1:7070->127.0.0.1:62414: wsarecv: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:19:38 ERROR [3092831199 6m17s] inbound/http[http]: process connection from 127.0.0.1:62357: upload: raw-read tcp 127.0.0.1:7070->127.0.0.1:62357: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:20:13 ERROR [1275046671 390ms] inbound/http[http]: process connection from 127.0.0.1:64832: upload: raw-read tcp 127.0.0.1:7070->127.0.0.1:64832: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:24:40 ERROR [2295559193 4m12s] inbound/http[http]: process connection from 127.0.0.1:64914: upload: raw-read tcp 127.0.0.1:7070->127.0.0.1:64914: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:25:58 ERROR [3807901022 1m9s] inbound/http[http]: process connection from 127.0.0.1:51121: upload: raw-read tcp 127.0.0.1:7070->127.0.0.1:51121: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:29:41 ERROR [2646391314 4m12s] inbound/http[http]: process connection from 127.0.0.1:51340: upload: raw-read tcp 127.0.0.1:7070->127.0.0.1:51340: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:34:42 ERROR [4021192317 4m12s] inbound/http[http]: process connection from 127.0.0.1:53610: upload: raw-read tcp 127.0.0.1:7070->127.0.0.1:53610: An existing connection was forcibly closed by the remote host.
+0800 2024-11-02 10:34:54 ERROR [2465028669 0ms] inbound/http[http]: process connection from 127.0.0.1:55398: too many open streams
+0800 2024-11-02 10:34:54 ERROR [2492130560 0ms] inbound/http[http]: process connection from 127.0.0.1:55399: too many open streams
+0800 2024-11-02 10:35:30 ERROR [4055782746 0ms] inbound/http[http]: process connection from 127.0.0.1:55492: too many open streams
+0800 2024-11-02 10:35:30 ERROR [3336833202 0ms] inbound/http[http]: process connection from 127.0.0.1:55493: too many open streams
+0800 2024-11-02 10:35:32 ERROR [3775372011 0ms] inbound/http[http]: process connection from 127.0.0.1:55495: too many open streams
+0800 2024-11-02 10:35:32 ERROR [586094375 0ms] inbound/http[http]: process connection from 127.0.0.1:55496: too many open streams
+0800 2024-11-02 10:35:35 ERROR [1229006980 1ms] inbound/http[http]: process connection from 127.0.0.1:55508: too many open streams

core使用 Hysteria 2.5.2时，配置如下
server: ***:993
auth: ***
bandwidth: 
  up: 30 mbps
  down: 200 mbps
socks5:
  listen: 0.0.0.0:7069 
http:
  listen: 0.0.0.0:7070 
tls:
  insecure: true
出现的时间间隔较长，一般在几个小时后出现，V2rayN日志滚动截断了，错误为楼主贴的错误

**Comment by JiyongShi** [comment]
qnap nas上，debian 12为基础的系统，docker方式运行hysteria 2.5.2，客户端配置同上，运行接近两天未发现类似问题

**Comment by tobyxdd** [comment]
要不你开启 [流量统计 API](https://hysteria.network/zh/docs/advanced/Traffic-Stats-API/)，利用 `/online` 接口观察一下连接数？看下是否是有的连接没有释放，越积越多导致的

**Comment by tobyxdd** [comment]
无视刚刚我发的那条（已经删了）。。那个接口统计的是连接数不是 stream 数，对调试这个问题没什么用

**Comment by qingyanbaby** [comment]
第二天断网，晚上没用，具体跑了多久不知道。我现在加大了服务端`maxIncomingStreams`和客户端的`ulimit`，明天看看情况

**Comment by qingyanbaby** [comment]
用的最新版。旧版没用过

**Comment by JiyongShi** [comment]
初步分析，应该是和服务端参数无关的：
1. windows v2rayn连接出问题的时候，另外一个nas上的docker内跑的hysteria 2.5.2正常
2. hysteria和sing_box出问题的时间间隔存在差异，这个可能和上游的quic包依赖存在关系

**Comment by qingyanbaby** [comment]
ubuntu调大本地的ulimit后，试了两三天，没有报这个错了
