### ISSUE TITLE
FR: Do not automatically exit the application if a network error occurs (当遇到网路错误时 不要自动退出程式)

### ISSUE THREAD

**Issue by smateoliu** [apernet/hysteria#1241]
**Is your feature request related to a problem? Please describe.**

Currently, if the user encounters a network error (for example: Failed to initialize client (Connection error: Timeout: No recent network activity), the application will not continue execution and exit automatically. (For example: Try to continue connecting to the server). This brings unnecessary management trouble to users when running it on routers.
目前，当使用者遭遇网路错误时（例如：failed to initialize client (connect error: timeout: no recent network activity) ) 程式会自动退出，而不是继续尝试重连。这使得使用者将其运行在路由器等设备上时，带来了不必要的管理麻烦。

**Describe the solution you'd like**

Provide a section in the configuration file to let the user decide what the application should do if a network error occurs. (Exit or continue running and try to connect to the server)
在设定档中为使用者提供一个选项，让使用者自行决定应用遭遇网路错误时的行为。（退出还是继续运行并尝试连接伺服器）

**Describe alternatives you've considered**

I think there is currently no better solution to this problem.
我认为对于这件事应该没有更好的选项了。

**Additional context**

To avoid unnecessary confusion, "Continue trying to connect to the server" should not be the default option. (But it should be an option in the configuration file for the user to choose)
为了造成不必要的困惑，“继续尝试连接到伺服器” 不应该为默认选择。（但应该是一个可在配置文件中供使用者选择的选项）

Hysteria should learn from sing-box project, They have fully considered this point. (provides a better user experience for running on routers)
Hysteria应该学习一下sing-box项目，它们已经充分考虑到了这一点。(为路由器使用者）

**Comment by tobyxdd** [comment]
https://hysteria.network/docs/advanced/Full-Client-Config/#lazy
