### ISSUE TITLE
最近支持SNI了，那么masquerade里能根据SNI来做反代吗

### ISSUE THREAD

**Issue by itvitv** [apernet/hysteria#1245]
现在masquerade里只能反代单一网站
能否根据SNI呢，比如
web1.xxx.com 反代到 192.168.1.1:8080
web2.xxx.com 反代到 192.168.1.2:8181
其他的都走默认网站
现在做反代，还要另外再开个程序，比如 nginx 或者 caddyserver

**Comment by haruue** [comment]
既然可以多开一个程序实现那就多开一个程序吧。 我们暂时还不打算把 Hysteria 打造成一款 [「小而美」][1] 的工具。

[1]: https://zh.wikipedia.org/wiki/%E5%BE%AE%E4%BF%A1
