### ISSUE TITLE
Can't connect: connect error: CRYPTO_ERROR 0x150 (remote): tls: internal error

### ISSUE THREAD

**Issue by orl0** [apernet/hysteria#1253]
**Describe the bug**
Once I updated server and client to 2.6.0 I got this issue

**Logs**
```
FATAL   failed to initialize client     {"error": "connect error: CRYPTO_ERROR 0x150 (remote): tls: internal error"}
```

**Device and Operating System**

Debian Linux server
OpenSUSE Linux desktop

**Additional context**

I downgraded server to 2.5.1 and this solved the issue

**Comment by haruue** [comment]
```
connect error: CRYPTO_ERROR 0x150 (remote): tls: internal error
```

This is caused by `sniGuard`, which added in [v2.5.2](https://github.com/apernet/hysteria/releases/tag/app%2Fv2.5.2).

> By default, the server now terminates the TLS handshake if the SNI sent by a client does not match the certificate. A new sniGuard option has been added to the tls section to control this behavior

You can find it in our docs [here](https://hysteria.network/docs/advanced/Full-Server-Config/#tls).

> ```yaml
> tls:
> # ...
> sniGuard: strict | disable | dns-san
> ```
> Verify the SNI provided by the client. Accept the connection only when it matches what's in the certificate. Terminate the TLS handshake otherwise.
> * Set to `strict` to enforce this behavior.
> * Set to `disable` to disable this entirely.
> * The default is `dns-san`, which enables this feature only when the certificate contains the "Subject Alternative Name" extension with a domain name in it.

To resolve this, you can either specify `tls.sni` in your client config, or set `tls.sniGuard` to `disable` in the server config to use the behavior before v2.5.1.

**Comment by wyx66624** [comment]
我在2.6.2也遇到了相同的问题，但是我使用的是acme获取证书和我自己的域名，域名在cloudflare中绑定的ip没有问题，本地ping域名能正常ping通，请问这是什么原因？
操作系统内核：Linux 6.8.0-48-generic

启动日志：
Aug 05 05:43:26 C20250805091907 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Aug 05 05:43:26 C20250805091907 hysteria[124893]: 2025-08-05T05:43:26Z        INFO        server mode
Aug 05 05:43:26 C20250805091907 hysteria[124893]: 2025-08-05T05:43:26Z        INFO        maintenance        started background certificate maintenance        {"cache": "0xc00017bb90"}
Aug 05 05:43:26 C20250805091907 hysteria[124893]: 2025-08-05T05:43:26Z        WARN        stapling OCSP        {"error": "no OCSP stapling for [www.claudemirror.org]: no OCSP server specified in certificate", "identifiers": ["www.claudemirror.org"]}
Aug 05 05:43:26 C20250805091907 hysteria[124893]: 2025-08-05T05:43:26Z        INFO        server up and running        {"listen": ":443"}


listen: :443

acme:
  domains:
    - xxxxxxxxxxxxxxxxx
  email: xxxxxxxxxxxxxxxxx

auth:
  type: password
  password: xxxxxxxxxxxxxxxxxxxxxxx

bandwidth:
  up: 200 mbps
  down: 200 mbps

masquerade:
  type: proxy
  proxy:
    url: https://bing.com/
    rewriteHost: true

客户端配置：
server: xxxxxxxxxxxxx:443

auth: xxxxxxxxxxxxxxxxxxxxxx(与服务端password相同)

tls:
  serverName: xxxxxxxxxxx(与服务端的domains域名相同)
  insecure: false

bandwidth: 
  up: 100 mbps
  down: 100 mbps
  
transport:
  udp:
    hopInterval: 30s
    
socks5:
  listen: 127.0.0.1:1080 

http:
  listen: 127.0.0.1:8080

v2rayN完整输出：
[Custom] [hysteria2]hy2
v2rayN - V7.13.6 - X64 | E:\v2rayN-windows-64\ | E:\v2rayN-windows-64\v2rayN.exe | Microsoft Windows NT 10.0.19045.0
启动服务 (2025/08/05 13:43:55)...
2025-08-05T13:43:57+08:00	[34mINFO[0m	client mode
Xray 25.5.16 (Xray, Penetrates Everything.) 800b8b5 (go1.24.3 windows/amd64)
A unified platform for anti-censorship.
2025/08/05 13:43:57.512615 [Info] infra/conf/serial: Reading config: &{Name:configPre.json Format:json}
**2025-08-05T13:43:57+08:00	[31mFATAL[0m	failed to initialize client	{"error": "connect error: CRYPTO_ERROR 0x150 (remote): tls: internal error"}**
[Custom] [hysteria2]hy2
2025/08/05 13:43:57.607401 [Warning] core: Xray 25.5.16 started
2025/08/05 13:43:58.569888 from tcp:127.0.0.1:11057 accepted tcp:www.google.com:443 [socks -> proxy]
2025/08/05 13:44:00.087522 from tcp:127.0.0.1:11063 accepted tcp:www.google.com:443 [socks -> proxy]
2025/08/05 13:44:01 当前延迟: -1 ms，none

美国西雅图的vps
