### ISSUE TITLE
服务端启动失败

### ISSUE THREAD

**Issue by haotian02** [apernet/hysteria#1254]
**描述问题**
服务端启动失败

**如何复现**
服务端安装脚本并修改配置文件重启后（udp监听端口已打开），域名可以正常解析，反向代理可以正常跳转，查看状态服务未启动

**预期行为**

**日志**
![image](https://github.com/user-attachments/assets/9335b6c4-1e5a-461b-a14c-69dafa38955b)

**设备和操作系统**
系统版本:        Ubuntu 22.04 LTS
Linux版本:       6.11.5-x64v3-xanmod1
CPU架构:         x86_64
CPU型号:         Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz

**额外信息**

**Comment by haruue** [comment]
您好。 您提供的日志缺少细节。

请提供你的服务端配置文件， 也就是下面这条命令的输出

```bash
cat /etc/hysteria/config.yaml
```

请使用下面这条命令获取日志， 建议复制到上一次你重启 hysteria-server 服务， 或者在重启 hysteria-server 后等至少 1 分钟让它证书维护过程结束后再获取日志。

```
journalctl --no-pager -e -u hysteria-server.service
```

将上面这条命令中的 `-e` 换成 `-f` 可看到实时日志输出。

**Comment by haotian02** [comment]
Nov 15 16:38:40 c723b9b2ed.bytevirt.com systemd[1]: Started Hysteria Server Service (config.yaml).
Nov 15 16:38:40 c723b9b2ed.bytevirt.com hysteria[8533]: 2024-11-15T16:38:40Z        INFO        server mode
Nov 15 16:38:40 c723b9b2ed.bytevirt.com hysteria[8533]: 2024-11-15T16:38:40Z        FATAL        failed to read server config        {"error": "While parsing config: yaml: line 3: mapping values are not allowed in this context"}
Nov 15 16:38:40 c723b9b2ed.bytevirt.com systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 16:38:40 c723b9b2ed.bytevirt.com systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
Nov 16 02:09:40 c723b9b2ed.bytevirt.com systemd[1]: Started Hysteria Server Service (config.yaml).
Nov 16 02:09:40 c723b9b2ed.bytevirt.com hysteria[20716]: 2024-11-16T02:09:40Z        INFO        server mode
Nov 16 02:09:40 c723b9b2ed.bytevirt.com hysteria[20716]: 2024-11-16T02:09:40Z        FATAL        failed to read server config        {"error": "While parsing config: yaml: line 3: mapping values are not allowed in this context"}
Nov 16 02:09:40 c723b9b2ed.bytevirt.com systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 02:09:40 c723b9b2ed.bytevirt.com systemd[1]: hysteria-server.service: Failed with result 'exit-code'.

**Comment by haruue** [comment]
```
While parsing config: yaml: line 3: mapping values are not allowed in this context
```

您的服务端配置文件格式不正确， 请提供你的服务端配置文件， 通常会是下面这个命令的输出

```
cat /etc/hysteria/config.yaml
```
