### ISSUE TITLE
tcp fastopen sockopt on server

### ISSUE THREAD

**Issue by its0ka** [apernet/hysteria#1255]
my server has high rtt (at least 100ms because of a vpn) and it would be nice to have tcp fastopen to minimize latency.
thanks for your work.

**Comment by haruue** [comment]
Hysteria uses a single QUIC connection for multiple proxy streams, and we have already optimised the internal protocol used in Hysteria. It now supports 1xRTT TCP and 0xRTT UDP. So there is nothing more we can do to optimise the latency between Hysteria server and client.

If you're referring to the latency between the Hysteria server and the proxy target, please note that it uses the TCP stack of your operating system. This is implemented by your operating system and not controlled by Hysteria. For example, if you are running your Hysteria server on a Linux box, you should simply enable the TFO options with `sysctl net.ipv4.tcp_fastopen=3`.

**Comment by its0ka** [comment]
@haruue "you should simply enable the TFO options with sysctl net.ipv4.tcp_fastopen=3" that's not enough, curl requires "--tcp-fastopen" argument to use it and xray requires a sockopt to use it. Hysteria doesn't use tcp fastopen and i have "net.ipv4.tcp_fastopen=3"
