### ISSUE TITLE
Server not working suddenly 

### ISSUE THREAD

**Issue by karimi12** [apernet/hysteria#1261]
I configuration a http server for authentication this feature working true but suddenly not working!!

**Expected behavior**
I configuration a http server for authentication this feature working true but suddenly not working!!

**Logs**
ERROR        HTTP reverse proxy error        {"error": "context canceled"}

**Device and Operating System**
ubuntu 2402
hysteria latest

**Additional context**

**Comment by haruue** [comment]
Hello,

Please provide your config files.

It is impossible to solve a problem without reproducing it.

**Comment by karimi12** [comment]
My http server was H2 so for this reason i get an error in hysteria i
change it to http1/1. The issue was solved.
