### ISSUE TITLE
Reverse Port Forwarding

### ISSUE THREAD

**Issue by APT-ZERO** [apernet/hysteria#1262]
Hello
My oversea-server IP is blocked by GFW, but domestic-servers can connect to it
so i use a domestic-server as relay to connect client to the oversea-server by port forwarding
`client > domestic-server > oversea-server`
but GFW blocks domestic-server outbound to my oversea IP after hours or days

I can still access the domestic-server ip from the oversea-server (domestic-server is Hy2 server and oversea-server is Hy2 client)
But Port Forwarding is not possible anymore

Could you please add Port Forwarding options for server config too? so i can forward 0.0.0.0:1000 of server to 127.0.0.1:1000 of client

**Comment by haruue** [comment]
Won't implement, pls use ssh reverse proxy instead.

**Comment by hadi-dindar** [comment]
> It's so complicated and will use more hardware resources Please add the feature to Hysteria There is many Issues asking the same thing, this can solve problem of many people like [#835](https://github.com/apernet/hysteria/issues/835)

no solution for thus problem ?

**Comment by moeinrahimi1** [comment]
@APT-ZERO did you find solution for reverse tunnel?
