### ISSUE TITLE
新版本不识别旧版本服务的配置文件

### ISSUE THREAD

**Issue by toyo2333** [apernet/hysteria#1264]
```
  proxy:
    url: https://some.site.net 
```

之前旧版本配置 是没有 **https://** 的 ，一直可以用，更新后用不了。得加上这个才可以。

**Comment by haruue** [comment]
之前不带 `https://` 仅仅是启动时不会报错而已， 伪装时会失败。
请参考 #1227 。

我们无意支持不明确指定 `https://` 的情形（要实现这个的话需要根据地址的类型来判断是 http 还是 https 更合适）， 并且我们的文档里一直以来都是带 `https://` 的。 所以我们只是修复了启动时不报错的问题。
