### ISSUE TITLE
有两个 hy2 服务器，如何做负载均衡

### ISSUE THREAD

**Issue by NEX-S** [apernet/hysteria#1266]
我有两个 hy 服务器，一个负责国内的代理，一个负责国外的代理，要如何设置？

**Comment by haruue** [comment]
hy2 客户端不支持 ACL。

请开两个 hy2 客户端， 并暴露成两个 socks5 代理。 然后使用 v2ray 或者 ZeroOmega 这种支持路由规则的工具进行分流。
