### ISSUE TITLE
访问 https://www.cloudflare-cn.com/ssl/encrypted-sni/#dns 显示 安全 SNI 未通过，这是否意味着我的VPS主机地址会被中间人探测到？

### ISSUE THREAD

**Issue by dengcong6666** [apernet/hysteria#1268]
**描述问题**
请尽量清晰精准地描述你遇到的问题。

**如何复现**
复现问题的步骤。

**预期行为**
你认为修复后的行为应该是怎样的。

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
你在用什么设备和操作系统。

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by haruue** [comment]
如果你用 Chrome ， 在 [设置-隐私和安全][1] 中打开「使用安全 DNS」， 然后随便选一个你喜欢的 DoH 提供商（「操作系统默认设置」那个通常不会工作）， 然后重启浏览器， 这个测试应该就会打勾。

[1]: chrome://settings/security

**Comment by dengcong6666** [comment]
我试了一下，好像不行，不知道是我配置问题还是 hy2 服务端不支持 ECH 扩展

**Comment by dengcong6666** [comment]
> 如果你用 Chrome ， 在 设置-隐私和安全 中打开「使用安全 DNS」， 然后随便选一个你喜欢的 DoH 提供商（「操作系统默认设置」那个通常不会工作）， 然后重启浏览器， 这个测试应该就会打勾。

按照这个设置， v2rayN 打开代理后，这个测试就没有通过。关闭代理后这个测试是打勾的

**Comment by dengcong6666** [comment]
> @dengcong6666 你的这个域名 https://www.cloudflare-cn.com 本身有问题吧，经过查询，它不是cloudflare的官方域名，而是一个中国大陆的域名，它解析的IP地址都是中国大陆的，所以出现任何的错误都不奇怪

因为本质是个VPN 通道，我在浏览器访问的几乎全部网站都是在和我的VPS通信，所以保护我的VPS主机IP地址不被中间人嗅探很重要的。我该如何配置服务器和客户端 才能有 类似客户端加密Hello （ECH）这种防护

**Comment by dengcong6666** [comment]
> @dengcong6666 你的这个域名 https://www.cloudflare-cn.com 本身有问题吧，经过查询，它不是cloudflare的官方域名，而是一个中国大陆的域名，它解析的IP地址都是中国大陆的，所以出现任何的错误都不奇怪

客户端SNI 应该填写VPS真实的域名还是填写一个伪装域名呢
