### ISSUE TITLE
"version 子命令新增工具链和 quic-go 版本信息" --- 可以把这个信息放在别的命令里面，而不是改动 version 命令的输出格式

### ISSUE THREAD

**Issue by cary-sas** [apernet/hysteria#1271]
**你的功能请求是否与某个问题有关？**
 由于我程序需要提取  `version `命令的输出， 但现在新版本里面，这个命令的输出由于多了其他的内容，导致格式变了，我的程序受到了影响，而且还不大好调整。

**描述你希望的解决方案**
希望可以把 libVersion:  信息放在别的命令里面 （类似于 多一个命令 “libVersion”），而不是改动 version 命令的输出格式。 

或者可以教我如何在源码里面自己去修改这个命令的输出，然后再自己编译二进制。

**Comment by haruue** [comment]
您好，

您可以参照这个提交来 parse `hysteria version` 命令的输出 https://github.com/apernet/hysteria/pull/1244/commits/d4a1c2b58067e9c9ff13071a028615beb97d722e

如果您希望自己编译 hysteria-core 以改变 `hysteria version` 的输出的话， 您可以更改下面的代码：
https://github.com/apernet/hysteria/blob/15e31d48a09af0835773bd5c62cedbb3fc0e351d/app/cmd/root.go#L41-L49

**Comment by haruue** [comment]
您前面说是您自己的程序， 但是又无法改 code 来调整。 可否提供更多细节以便我们为您提供帮助？

**Comment by Smallthing** [comment]
> 您前面说是您自己的程序， 但是又无法改 code 来调整。 可否提供更多细节以便我们为您提供帮助？

估计卖出去给机场了。别管他
