### ISSUE TITLE
流量统计api建议

### ISSUE THREAD

**Issue by 2413567** [apernet/hysteria#1276]
GET /online
此接口返回一个 JSON map，是当前在线的用户与其对应的连接数。这里的连接数指的是 Hysteria 客户端实例的数量（可以理解为设备数），而非代理连接数。

响应：

{
  "wang": 2,
  "joe": 1
}
# 该接口是否能增加该用户每个链接的ip信息

**Comment by haruue** [comment]
是客户端 IP 信息还是连接的网站信息？
如果是连接的网站信息的话， 请用 https://hysteria.network/zh/docs/advanced/Traffic-Stats-API/#get-dumpstreams

**Comment by 2413567** [comment]
> 是客户端 IP 信息还是连接的网站信息？ 如果是连接的网站信息的话， 请用 https://hysteria.network/zh/docs/advanced/Traffic-Stats-API/#get-dumpstreams

客户端ip，想做一个简单统计

**Comment by haruue** [comment]
加这个争议会有一点大。 中国的警察如果获取了某个机场的控制权限的话， 配合 dump/streams 可以一键获取特定国内 IP （配合国内运营商可以特定到个人）的访问记录。

建议先在 hysteria 的 telegram 群进行讨论， 取得共识后再提交此 feature request。

**Comment by 2413567** [comment]
或者是其他设备标识符也可以，我主要是想实现新设备的上线提醒，增加安全性

**Comment by haruue** [comment]
> 我主要是想实现新设备的上线提醒，增加安全性

可以试试这里的 HTTP验证 或者 命令验证
https://hysteria.network/zh/docs/advanced/Full-Server-Config/#http
