### ISSUE TITLE
Does client configuration implement multiple user names and passwords?

### ISSUE THREAD

**Issue by suixhxy** [apernet/hysteria#1280]
Dear God hello, I have a functional requirement as follows:
1.
My client profile is:
vim /etc/hysteria/owner.yaml
The contents are as follows:
socks5:
listen: 0.0.0.0:1080
username: zhangsan
password: xxxxxxx
disableUDP: false
http:
listen: 0.0.0.0:8080
username: zhangsan
password: xxxxxxx
realm: martian
2.
How do I need to configure multiple usernames and passwords in socks5 and http?

**Comment by haruue** [comment]
不支持。

对于 Hysteria 客户端的 SOCKS5 / HTTP 代理需要多用户的情况， 请考虑用 v2ray 或者 privoxy 这种软件作为下游。

另请注意， SOCKS5 / HTTP 代理都不带加密， 且认证凭据直接以明文发送， 因此仅适合在局域网内使用， 不建议用于国内中转机。

**Comment by suixhxy** [comment]
你的意思，这个证书认证是没有意义的吗？
tls: 
  cert: some.crt
  key: some.key
  如果这个证书不能起到加密作用，那还要这个证书配置干啥呢？

**Comment by haruue** [comment]
Hysteria 服务端配置中的 TLS 证书是给 Hysteria 服务端与 Hysteria 客户端之间的 QUIC 通信用的， 不是给客户端开出来的 SOCKS5 和 HTTP 代理用的。

客户端开出来的 SOCKS5 和 HTTP 代理都是不加密的。

**Comment by suixhxy** [comment]
感谢您的回复，我是不是可以这样理解，客户端和服务端的QUIC 连接UDP通讯是加密的，而客户端自身起的socks5端口和http端口 的访问是没有加密的？如果我把客户端部署在自己电脑上，我自己通过浏览器代理插件访问socks5端口和http端口，这样的话，是不是相当于客户端和服务端的通讯是加密的？

**Comment by haruue** [comment]
是的， 并且从 Shadowsocks 时代开始就是这样的设计了， 并不是 Hysteria 独创的。 如果你感觉很难理解， 你可以去网上查一下翻墙软件的原理， 或者去问问 ChatGPT。

**Comment by suixhxy** [comment]
好的，非常感谢您的回答，我对这个hysteria工具有了充分的理解，我知道该如何使用它了。
