### ISSUE TITLE
Unreliable Transmission 

### ISSUE THREAD

**Issue by radiumatic** [apernet/hysteria#1281]
**Is your feature request related to a problem? Please describe.**

The congestion control is useful when your ISP is actively messing with you, but it has really high CPU usage (lots of ACKs with multiple context switches) and on some networks performs worse than if you had a tunnel without retransmission. 

**Describe the solution you'd like**

Since most users of sing-box and clash use the TUN mode, I think an option can be added to use the QUIC Unreliable Datagrams Extension. 

```json
...
"no_congestion": true
...
```
Hysteria can get away with the QoS problem by port hopping.  

**Describe alternatives you've considered**

None really. I don't know any QUIC proxy that uses the said extension. Maybe MASQUE but I haven't looked into it. 

**Additional context**

**Comment by haruue** [comment]
Hello.

Hysteria is already utilizing the QUIC Unreliable Datagrams Extension to proxy UDP packets. And it is not possible to proxy any TCP streams without congestion control.

If you want to use the kernel's built-in congestion control, but still take advantage of Hysteria's QUIC masquerading, you can run UDP-based L3 VPNs (like WireGuard) over Hysteria's `udpForwarding` ports.

**Comment by radiumatic** [comment]
> And it is not possible to proxy any TCP streams without congestion control.

Are you sure?

Using the socks proxy yes, it's not practical. But it technically is possible?

Doesn't the situation change if you are listening on a TUN interface?

As far as I understand you theoretically can catch TCP retransmission packets by tunneled streams, then mirror it to the server. 

> If you want to use the kernel's built-in congestion control, but still take advantage of Hysteria's QUIC masquerading, you can run UDP-based L3 VPNs (like WireGuard) over Hysteria's udpForwarding ports.

I'm afraid that still does double encryption. It's not exactly more efficient.

**Comment by haruue** [comment]
> As far as I understand you theoretically can catch TCP retransmission packets by tunneled streams, then mirror it to the server.

This is just a L3 VPN over QUIC unreliable datagrams. It is possible, but very different from the current architecture of Hysteria. In other words, it would be much easier to start a new project from scratch than to add such a feature to Hysteria.

And please note the TUN mode in Hysteria (as well as sing-box and clash) is very different from L3 VPN, instead of forwarding the packet as is, the TUN mode is actually recreating the TCP streams from those packets to use the streams proxying.

**Comment by haruue** [comment]
Won't implement in Hysteria. 

Please start a new project over QUIC, or ask someone else to do this.

All Hysteria code is licensed under the MIT, feel free to copy any part (like port hopping) into your own codebase.

**Comment by haruue** [comment]
Just found a project that forwarding L3 packets with QUIC unreliable datagrams.
https://github.com/M0dEx/quincy

Maybe ask their maintainer to add the port-hopping feature?
