### ISSUE TITLE
udpdeminer, your udp client striker.

### ISSUE THREAD

**Issue by basncy** [apernet/hysteria#1283]
For hy users, if you can't connect to your domestic UDP server, try https://github.com/basncy/udpdeminer-binary

**Comment by basncy** [comment]
> For hy users, if you can't connect to your domestic UDP server, try https://github.com/basncy/udpdeminer-binary

Just a reminder, this tool does NOT change hysteria protocol and data stream, use it at your own risk for cross-border connections.
I use it ONLY on connections from mobile cellular data to domestic UDP servers.

**Comment by tobyxdd** [comment]
You didn’t explain what this tool does or how it works, and since it’s closed-source, there’s no way to verify it isn’t malicious. I’m deleting this issue for security reasons
