### ISSUE TITLE
配置文件汇中启用了限速1mbps,但开启全局在视频和测速实际测试下来并未生效

### ISSUE THREAD

**Issue by xghini** [apernet/hysteria#1286]
**描述问题**
我在配置文件汇中启用了限速1mbps,但开启全局在多个平台实际测试下来并未生效
bandwidth:
  up: 1 mbps
  down: 1 mbps
ignoreClientBandwidth: true
![image](https://github.com/user-attachments/assets/ea5bb9a6-1cd3-4c1d-9b89-18f1f3215300)
![image](https://github.com/user-attachments/assets/c46e0c17-4cd1-4459-92a3-926c6fd5008a)

看视频,测速都远超限制值

难道是我配置有误?希望能得到指导或解决🙏

**Comment by haruue** [comment]
bandwidth 的 up 和 down 仅对 brutal 拥塞控制有效， 但是在启用 `ignoreClientBandwidth: true` 的情况下， 拥塞控制一定是 bbr 。

请参阅这里的中文文档 https://hysteria.network/zh/docs/advanced/Full-Server-Config/#_6
建议阅读完整个 「带宽」 章节。

此外， 由于目前没有方案能禁止客户端通过不配置带宽来切换到 bbr 拥塞控制， 只通过 bandwidth 选项实现对客户端的强制限速是不可行的。  对于需要限速的情况， 如果你是开给自己用的话， 删除服务端的 bandwidth 选项， 在客户端配置带宽即可； 如果你无法控制客户端配置， 那你就需要使用其它工具（比如 WonderShaper）来实现限速。

**Comment by xghini** [comment]
好的,已明了,感谢指明!
目前看来是客户端配置了高速带宽,hy2目前便无法对其限速,需要配合其他工具实现
如果能够集成或内置此功能,将十分有用
