### ISSUE TITLE
请问如何在config.json中设置日志级别？

### ISSUE THREAD

**Issue by brick2008** [apernet/hysteria#278]
v2rayn自定义里加入了对hysteria的支持，但hysteria默认是debug输出，我在config.json里加入 "LOGGING_LEVEL":"info", 没有效果？求解决。

**Comment by lxhao61** [comment]
同问，怎么指定输出路径。

**Comment by fjn308** [comment]
> v2rayn自定义里加入了对hysteria的支持，但hysteria默认是debug输出，我在config.json里加入 "LOGGING_LEVEL":"info", 没有效果？求解决。

应通过环境变量指定，具体因平台而异，比如 Linux 上可以在 .service 文件中设置。因为我平时在 Windows 上自己写 autohotkey 脚本带 Hide 参数地后台启动这类软件，在这种情况下，autohotkey 可以设定不对外可见的环境变量。

**Comment by fjn308** [comment]
> 同问，怎么指定日志输出路径。

非 Linux 平台没需求没查过，Linux 上可以考虑在 .service 文件指定 StandardInput，参见：

https://www.freedesktop.org/software/systemd/man/systemd.exec.html

**Comment by brick2008** [comment]
请求在config.json里加入对LOGGING_LEVEL的支持，环境变量属实不便。

**Comment by zurica2013** [comment]
建议直接在docker里运行hysteria，在docker run的时候直接添加一条环境变量-e LOGGING_LEVEL=日志等级，docker管理日志不要太方便还能限制大小

**Comment by hedsbj** [comment]
环境变量设置了似乎没用起作用，“Linux 下用 LOGGING_LEVEL=info ./hy 启动” 这个管用但不太方便。每天日志产生的量还不小

**Comment by hedsbj** [comment]
在起动的.service文件中的service 项下加一行
EnvironmentFile=变量文件
变量文件中加入变量如LOGGING_LEVEL=info 即可

**Comment by hedsbj** [comment]
hysteria.service

[Unit]
Description=Hysteria, a feature-packed network utility optimized for networks of poor quality
Documentation=https://github.com/HyNetwork/hysteria/wiki
After=network.target

[Service]
User=root
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE
NoNewPrivileges=true
EnvironmentFile=/etc/default/hysteria
ExecStart=/usr/local/bin/hysteria -config /usr/local/etc/hysteria.json server
Restart=on-failure
RestartPreventExitStatus=1
RestartSec=5

[Install]
WantedBy=multi-user.target

将环境变量如LOGGING_LEVEL=info 加到/etc/default/hysteria中即可
