### ISSUE TITLE
用了几天，几点建议

### ISSUE THREAD

**Issue by f4nff** [apernet/hysteria#352]
1：增加负载均衡，多线路，建议采用主备，**间隔进行延时测试**，延时在设置的区间设置为可用，不符合的节点，休眠。
2：建议更换tun2socks库，[https://github.com/xjasonlyu/tun2socks](https://github.com/xjasonlyu/tun2socks)，纯go开发，交叉编译要方便很多,性能也会好很多，目前的go-tun2socks如果交叉编译，平台不通用，需要自己编译，很麻烦，比如openwrt
3：建议内部协议使用类似gost的relay协议，一个rtt即可完成握手，加快握手速度。如果猜的没错，目前内部协议采用的socks5。

**Comment by PHCSJC** [comment]
我也提一个：增加redirect模式

**Comment by f4nff** [comment]
@PHCSJC   有tun2socks，还要什么redirect，
iptables 效率太低，

**Comment by PHCSJC** [comment]
@f4nff redirect效率低？为什么这么说？我用tproxy和浏览器sock5直连hysteria，y2b速度没什么区别，纯下载也几乎一样。

tun2socks也不太好搞分流吧？配置路由容易把软路由搞死，redirect\tproxy+ipset分流就很简单且安全

**Comment by yaotthaha** [comment]
我自己用下来，hy的udp好像有问题，我本地用v2ray分流，v2ray outbound socks连接hy的socks5时，udp不工作

**Comment by yaotthaha** [comment]
hysteria socks5 不监听 udp 端口

**Comment by f4nff** [comment]
@yaotthaha  你自己的问题吧，udp本身没问题，我这边一直使用，socks5本身就不监听udp端口，需要tcp握手之后，才会开启一个udp端口，

**Comment by PHCSJC** [comment]
udp代理是用来玩游戏吗？不太理解

**Comment by notepad2** [comment]
目前有没有考虑过隐藏IP或者伪装功能？

**Comment by ctermiii** [comment]
> 我自己用下来，hy的udp好像有问题，我本地用v2ray分流，v2ray outbound socks连接hy的socks5时，udp不工作

同样问题

**Comment by PHCSJC** [comment]
建议3已经不可能了，作者说了不做
