### ISSUE TITLE
1

### ISSUE THREAD

**Issue by rkygogo** [apernet/hysteria#370]
{

}

最简配置，刚测了不通。。。哪里要改？

**Comment by haruue** [comment]
`"ipv6_only"` 选项已经移除， 请改用 `"resolve_preference": "6"` 。

**Comment by haruue** [comment]
经过我这边测试， 把你的配置里的 server 改成我的服务器地址， 其它的不变， 并配置好 `/etc/hysteria/ca.crt` 和 `/etc/hysteria/ca.key` 是可以成功连接并正常使用的。

建议检查一下你那边的网络问题。 可以按照 [Wiki 里的操作](https://github.com/HyNetwork/hysteria/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#erro-errortimeout-no-recent-network-activity) 进行排查。
