### ISSUE TITLE
[请求帮助]  服务器端出现 显示no recent network activity ,重启服务端可解决问题

### ISSUE THREAD

**Issue by xtccc** [apernet/hysteria#426]
### 问题详情

hysteria 服务器端出现 显示no recent network activity 并且客户端无法连接服务端
我重启下hy的service就又好了
不知道作者能不能加个报错自动退出的功能，我让hy.service自动重启服务
hy.service日志：
```
[ec2-user@ip-172-31-35-17 ~]$ journalctl -u hy-37777
-- Logs begin at Sun 2022-08-28 14:11:42 CST, end at Sun 2022-09-04 00:51:41 CST. --
Aug 30 13:01:40 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T13:01:40+08:00 [INFO] [src:ip:55751] Client connected
Aug 30 13:02:21 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T13:02:21+08:00 [INFO] [src:ip:55751] [error:timeout: no recent network activity] Client disconnected
Aug 30 14:15:09 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T14:15:09+08:00 [INFO] [src:ip:59212] Client connected
Aug 30 14:15:50 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T14:15:50+08:00 [INFO] [src:ip:59212] [session:0] [error:timeout: no recent network activity] UDP error
Aug 30 14:15:50 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T14:15:50+08:00 [INFO] [src:ip:59212] [error:timeout: no recent network activity] Client disconnected
Sep 04 00:22:44 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-09-04T00:22:44+08:00 [INFO] [src:ip:60689] Client connected
Sep 04 00:23:25 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-09-04T00:23:25+08:00 [INFO] [src:ip:60689] [error:timeout: no recent network activity] Client disconnected
Sep 04 00:51:40 ip-172-31-35-17.ap-northeast-3.compute.internal systemd[1]: Stopping Hysteria Server Service...
Sep 04 00:51:40 ip-172-31-35-17.ap-northeast-3.compute.internal systemd[1]: hy-37777.service: Succeeded.
Sep 04 00:51:40 ip-172-31-35-17.ap-northeast-3.compute.internal systemd[1]: Stopped Hysteria Server Service.
Sep 04 00:51:40 ip-172-31-35-17.ap-northeast-3.compute.internal systemd[1]: Started Hysteria Server Service.
Sep 04 00:51:41 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[116919]: 2022-09-04T00:51:41+08:00 [INFO] [config:{Listen::37777 Protocol:wechat-video ACME:{Domains:[mydomain] Email: DisableHTTPChallenge:false DisableTLSALPNChallenge:fa>
Sep 04 00:51:41 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[116919]: 2022-09-04T00:51:41+08:00 [INFO] Password authentication enabled
Sep 04 00:51:41 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[116919]: 2022-09-04T00:51:41+08:00 [INFO] [addr::37777] Server up and running
```

### 服务端安装信息或者一键脚本信息

hysteria version v1.2.0 2022-08-14T01:56:17.587Z 944c0ecf646324c0151b026a55752c23378b909c

### VPS 信息

aws EC2 VPC

### 服务端配置

{
  "listen": ":37777",
  "acme": {
    "domains": [
      "mydomain"
    ],
    "disable_http": false,
    "disable_tlsalpn": false
  },
  "auth": {
    "mode": "passwords",
    "config": [
      "myauthstr"
    ]
  },
  "recv_window_conn": 58982400,
  "recv_window_client": 235929600,
  "protocol": "wechat-video"
}

### 服务端日志

[ec2-user@ip-172-31-35-17 ~]$ journalctl -u hy-37777
-- Logs begin at Sun 2022-08-28 14:11:42 CST, end at Sun 2022-09-04 00:51:41 CST. --
Aug 30 13:01:40 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T13:01:40+08:00 [INFO] [src:ip:55751] Client connected
Aug 30 13:02:21 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T13:02:21+08:00 [INFO] [src:ip:55751] [error:timeout: no recent network activity] Client disconnected
Aug 30 14:15:09 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T14:15:09+08:00 [INFO] [src:ip:59212] Client connected
Aug 30 14:15:50 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T14:15:50+08:00 [INFO] [src:ip:59212] [session:0] [error:timeout: no recent network activity] UDP error
Aug 30 14:15:50 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-08-30T14:15:50+08:00 [INFO] [src:ip:59212] [error:timeout: no recent network activity] Client disconnected
Sep 04 00:22:44 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-09-04T00:22:44+08:00 [INFO] [src:ip:60689] Client connected
Sep 04 00:23:25 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[84382]: 2022-09-04T00:23:25+08:00 [INFO] [src:ip:60689] [error:timeout: no recent network activity] Client disconnected
Sep 04 00:51:40 ip-172-31-35-17.ap-northeast-3.compute.internal systemd[1]: Stopping Hysteria Server Service...
Sep 04 00:51:40 ip-172-31-35-17.ap-northeast-3.compute.internal systemd[1]: hy-37777.service: Succeeded.
Sep 04 00:51:40 ip-172-31-35-17.ap-northeast-3.compute.internal systemd[1]: Stopped Hysteria Server Service.
Sep 04 00:51:40 ip-172-31-35-17.ap-northeast-3.compute.internal systemd[1]: Started Hysteria Server Service.
Sep 04 00:51:41 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[116919]: 2022-09-04T00:51:41+08:00 [INFO] [config:{Listen::37777 Protocol:wechat-video ACME:{Domains:[mydomain] Email: DisableHTTPChallenge:false DisableTLSALPNChallenge:fa>
Sep 04 00:51:41 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[116919]: 2022-09-04T00:51:41+08:00 [INFO] Password authentication enabled
Sep 04 00:51:41 ip-172-31-35-17.ap-northeast-3.compute.internal hysteria[116919]: 2022-09-04T00:51:41+08:00 [INFO] [addr::37777] Server up and running

### 客户端安装信息

hysteria 1.2.0-1

### 客户端配置

客户端配置无问题

### 客户端运行环境（操作系统）

android

### 客户端日志

客户端无问题

**Comment by haruue** [comment]
逻辑上来说服务端每次连不上客户端就重启会严重影响体验， 如果客户端因为某些原因自动重连， 但是服务端因为连不上「之前的客户端」自动退出， 此时客户端又要等待相当长一段时间才会超时重连。

能不能提供一下你 VPS 的配置（尤其是多大内存）， 以及当客户端连不上服务端（但是服务端仍然在运行）的情况下， `ss -aupn sport = 37777` 的输出？

**Comment by xtccc** [comment]
内存信息:
```
[ec2-user@ip-172-31-35-17 ~]$ free -h
              total        used        free      shared  buff/cache   available
Mem:          802Mi       154Mi       353Mi        47Mi       294Mi       478Mi
Swap:            0B          0B          0B
```
客户端连不上服务端（但是服务端仍然在运行） 这个可遇而不可求，一个猜测是与GFW封锁ip 导致 连接断开， 一个猜测是测速导致的OOM

**Comment by haruue** [comment]
那你下次试试服务端进入这种状态的情况下， 重启客户端， 客户端是能连上服务端（但是不能上网）还是就连不上服务端（客户端侧直接显示一个 `timeout: no recent network activity` ）

你说的这两种可能性， 通过重启服务端应该都是解决不了的。

我觉得服务端可能还有别的问题（只是错误没被打印出来）

**Comment by f4nff** [comment]
我遇到的是客户端，
必须重启客户端才能恢复网络，
目前日志我开始记录，看能不能得到一些信息。

**Comment by certaintls** [comment]
Adding "protocol": "faketcp" to both your client and server configuration should resolve the issue. See more detail at https://github.com/HyNetwork/hysteria/wiki/Advanced-Usage

**Comment by vinograd-cyber** [comment]
不如xray和kcptun稳定，希望越来越稳定，我测试的经常报网络超时

**Comment by xtccc** [comment]
今天又出现一次类似的问题, 但是我找到问题原因了, 是我的vps 真的在某个时间段 网络有问题, 所以日志 才有 no recent network activity

等过个10 及分钟, vps的网络好了, hysteria 自然也就可用了,   (也许和重启服务端没啥关系, 就是到了vps网络好的时候了, 我这次就没重启部分hy 服务端,  所有的hy服务端 也都正常工作了(我在一台vps 上 装了 3个 不同的hy, 有不同的 端口 , 密码 协议啥的 ))
所以这个问题也许不是hy的问题, 我就先关闭了吧 .

**Comment by koaname** [comment]
我遇到同样的问题，我猜测是网络的问题造成的！
