### ISSUE TITLE
Hysteria支持OCSP Stapling不？

### ISSUE THREAD

**Issue by lxhao61** [apernet/hysteria#485]
当Hysteria使用外部（非自己内置ACME申请）TLS证书时，是否默认支持OCSP Stapling？即Hysteria自动检测引用证书是否更新，且自动重载更新证书。

**Comment by lbg2008** [comment]
acme sh之类的更新证书的时候可以追加命令 
……&& sudo service Hysteria restart

或者用systemctl之类的做定时器重启。
