### ISSUE TITLE
[功能请求] 关于断线重连

### ISSUE THREAD

**Issue by koolca** [apernet/hysteria#499]
### 功能描述

Client偶尔会遇到断线
[ERRO] [error:timeout: no recent network activity] 
这一项错误日志表示 Hysteria 客户端无法与服务端进行 QUIC 握手
我注意到此时上层TCP连接会断开，立即重连也能成功，有没有可能保持上层TCP连接不断开，只是底层UDP重连，就如端口跳跃一样

### 这个功能的必要性

更好的应对糟糕的网络

**Comment by tobyxdd** [comment]
断开一般是因为一段时间内 UDP 不通，QUIC 连接超时导致的。如果重连能成功的话你可以试试调大 `idle_timeout` (默认是 20s)

**Comment by koolca** [comment]
谢谢，我做了一番测试，断线时调用hop函数并不能恢复连接，只有创建新连接时QUIC才能重连，设定idle_timeout/keepalive也不能检测到掉线

**Comment by SiloRanger** [comment]
现在我也遇上了大量的断线重连, 看日志有大量的如下提示:
 [error:stream 1224 canceled with error code 306] [0mTCP error
