### ISSUE TITLE
[功能请求] 是否服务器端可以监听多个端口

### ISSUE THREAD

**Issue by liuxyon** [apernet/hysteria#503]
### 功能描述

希望能在服务器端监听多个端口, 端口段, 而不是使用iptables.

### 这个功能的必要性

因为iptables测试不成功.

**Comment by haruue** [comment]
既然 [连 BGP 都玩得起来](https://github.com/apernet/hysteria/issues/375) 的话， 再花个几分钟学学 iptables 不好么， 以后能用上的。

**Comment by liuxyon** [comment]
> 既然 [连 BGP 都玩得起来](https://github.com/apernet/hysteria/issues/375) 的话， 再花个几分钟学学 iptables 不好么， 以后能用上的。

真找不到原因,你给我远程看看怎么样?

**Comment by haruue** [comment]
> 真找不到原因,你给我远程看看怎么样?
你在 Telegram 上联系 t.me/haruue
