### ISSUE TITLE
fast_open不支持redirect吗？

### ISSUE THREAD

**Issue by PHCSJC** [apernet/hysteria#512]
升级版本到v1.3.1，在客户端加了下面的参数，就连接不通了，请问是不支持redirect吗？

  "fast_open": true,

**Comment by PHCSJC** [comment]
抱歉，原来服务端也要加，文档里目前只有客户端提示了这个参数

**Comment by haruue** [comment]
服务端不用加。 `fast_open` 是纯客户端的配置。 文档没有问题。

**Comment by PHCSJC** [comment]
果然是，可能是之前哪里配置不对，感谢！
