### ISSUE TITLE
关闭混淆 (obfs) 可以带来约 10% 的 CPU 性能提升

### ISSUE THREAD

**Issue by PHCSJC** [apernet/hysteria#516]
1.这个混淆是什么意思呢？
2.关闭混淆对安全性有什么影响吗？
3.关闭就是删除这行配置吧？
4.用auth代替混淆可以吗？（防止别人连接）
感谢！

**Comment by tobyxdd** [comment]
文档都有解释。

**Comment by PHCSJC** [comment]
文档从头看到尾，只看到这个：
  "obfs": "AMOGUS", // 混淆密码
没有其他的说明喔
