### ISSUE TITLE
Server running, socat works, client fails

### ISSUE THREAD

**Issue by maliohammad** [apernet/hysteria#518]
Server System: Ubuntu 22.04.1 LTS
Client: windows 10 home
here I replaced the actual website domain with example.com, I have a functioning domain with cloudflare dns setup. Nginx is installed but the html page is the default one still, with default settings. 
server conf: 
```json5
{
    "listen": ":666",
    "alpn": "h3",
    "cert": "/etc/letsencrypt/live/example.com/fullchain.pem",
    "key": "/etc/letsencrypt/live/example.com/privkey.pem",
    "obfs": "8ZuA2Zpqhuk8yakXvMjDqEXBwY"
}
````

client conf:
```json5
{
  "server": "example.com:666",  
  "alpn": "h3",
  "obfs": "8ZuA2Zpqhuk8yakXvMjDqEXBwY",
  "up_mbps": 100,
  "down_mbps": 100,
  "retry": 3, // Number of retries when unable to connect to the server at startup. 0 (default) = no retry. Negative value = infinite retries.
  "retry_interval": 5, // Retry interval in seconds
  "quit_on_disconnect": false, // Quit the client when disconnected from the server
  "handshake_timeout": 10, // Handshake timeout in seconds
  "idle_timeout": 60, // Idle timeout in seconds. The client will send a ping to the server every 2/5 of this value.
  "hop_interval": 120, // Port hopping interval in seconds. See port hopping page for details.
  "socks5": {
    "listen": "127.0.0.1:6666"
  },
  "http": {
    "listen": "127.0.0.1:7777"
  }
}
````

```
Nov 28 18:05:23 ubuntu systemd[1]: Stopping Hysteria, a feature-packed network utility optimized for networks of poor quality...
Nov 28 18:05:23 ubuntu systemd[1]: hysteria-server.service: Deactivated successfully.
Nov 28 18:05:23 ubuntu systemd[1]: Stopped Hysteria, a feature-packed network utility optimized for networks of poor quality.
Nov 28 18:05:23 ubuntu systemd[1]: hysteria-server.service: Consumed 2.323s CPU time.
Nov 28 18:47:01 ubuntu systemd[1]: Started Hysteria, a feature-packed network utility optimized for networks of poor quality.
Nov 28 18:47:01 ubuntu hysteria[284943]: 2022-11-28T18:47:01+08:00 [INFO] [config:{Listen::666 Protocol: ACME:{Domains:[] Email: DisableHTTPChallenge:false DisableTLSALPNChallenge:false Al>
Nov 28 18:47:01 ubuntu hysteria[284943]: 2022-11-28T18:47:01+08:00 [INFO] [addr::666] Server up and running
````

The test with socat between server and client was a success, and a connection was established and test transited between client and server /
 
Client used to crash the moment I start it, but after adding some extra lines from the advanced setup I get this 
```
2022-11-28T14:44:54+03:30←[36m [INFO] [config:{Server:example.com:666 Protocol: Up: UpMbps:100 Down: DownMbps:100 Retry:3 RetryInterval:5 QuitOnDisconnect:false HandshakeTimeout:10 IdleTimeout:60 HopInterval:120 SOCKS5:{Listen:127.0.0.1:6666 Timeout:0 DisableUDP:false User: Password:} HTTP:{Listen:127.0.0.1:7777 Timeout:0 User: Password: Cert: Key:} TUN:{Name: Timeout:0 MTU:0 TCPSendBufferSize: TCPReceiveBufferSize: TCPModerateReceiveBuffer:false} TCPRelays:[] TCPRelay:{Listen: Remote: Timeout:0} UDPRelays:[] UDPRelay:{Listen: Remote: Timeout:0} TCPTProxy:{Listen: Timeout:0} UDPTProxy:{Listen: Timeout:0} TCPRedirect:{Listen: Timeout:0} ACL: MMDB: Obfs:8ZuA2Zpqhuk8yakXvMjDqEXBwY Auth:[] AuthString: ALPN:h3 ServerName: Insecure:false CustomCA: ReceiveWindowConn:0 ReceiveWindow:0 DisableMTUDiscovery:false FastOpen:false Resolver: ResolvePreference:}] ←[0mClient configuration loaded
2022-11-28T14:45:04+03:30←[31m [ERRO] [error:timeout: no recent network activity] ←[0mFailed to initialize client
2022-11-28T14:45:04+03:30←[36m [INFO] [retry:1] [interval:5] ←[0mRetrying...
```

Any help with diagnosing this issue is appreciated

**Comment by haruue** [comment]
There is no error in your config. I tested it with my own server and it works without any problem.

I think there is some firewall problem.

Could you please provide screenshots (or a copy of the text displayed on your terminal) of the `socat` test?

**Comment by haruue** [comment]
> I opened all ports, but hysteria still can't open port listen

The default mode of Hysteria use UDP instead of TCP.

Some VPS or company firewalls might have restrictions on UDP traffic. And there are also country-level firewalls (such like Iran) that block all UDP traffic.

Could you please show us how you test the UDP port with `socat`?

We also have a `socat` testing guide at https://hysteria.network/docs/common-problems/#erro-errortimeout-no-recent-network-activity.

**Comment by maliohammad** [comment]
Thanks for the quick reply. 
This confirms the worry I had that iran's government already censored hysteria. Is there a tool to see what method they used to block hysteria udp connection but not affecting socat? (maybe they are doing DPI to block some udp traffic but not the other?)
 the socat test:
`sudo socat - UDP6-LISTEN:666,reuseaddr,fork

test from server
test from client
abcd
`
and the client `socat - UDP:example.com:666

test from server
test from client
abcd
`

**Comment by tobyxdd** [comment]
Have you tried using `"disable_mtu_discovery": true` on both server & client?

**Comment by dopaemon** [comment]
> 

i use ufw allow 1:65535/tcp | udp

and i can open all port. But not work.
( may u can reply telegram ? : https://t.me/KernelPanix )
Thks

**Comment by haruue** [comment]
> This confirms the worry I had that iran's government already censored hysteria. Is there a tool to see what method they used to block hysteria udp connection but not affecting socat? (maybe they are doing DPI to block some udp traffic but not the other?)

Did you run both socat server and client on your VPS?
You should run socat server (`socat - UDP6-LISTEN:666,reuseaddr,fork`) on your VPS, and socat client (`socat - UDP:example.com:666`) locally.

**Comment by maliohammad** [comment]
> Have you tried using `"disable_mtu_discovery": true` on both server & client?

I tried it just now and it didn't seem to make a difference, the same error still. 

> Did you run both socat server and client on your VPS? You should run socat server (`socat - UDP6-LISTEN:666,reuseaddr,fork`) on your VPS, and socat client (`socat - UDP:example.com:666`) locally.

Yes I ran the server part of the code on my vps and the client part on my local computer with local network without any vpn or proxy. 

Will experiment around with some dpi spoofing methods later and if I get a working result will update it here.

**Comment by tobyxdd** [comment]
Do you mind sharing your full hysteria server config (privately) so I can try connecting to it? You can send it to my email inbox (see my profile page)

**Comment by maliohammad** [comment]
I emailed the client configuration with the thread title as mail subject.

**Comment by haruue** [comment]
@maliohammad @dopaemon Are you different accounts of same person.

**Comment by dopaemon** [comment]
> @maliohammad @dopaemon Are you different accounts of same person.

no bro. i'm from vietnam. idk him. but Did something happen?
( afte open UDP port Follow your instructions hysteria Good work. thks u ^^ )

**Comment by dopaemon** [comment]
> @maliohammad @dopaemon Are you different accounts of same person.

Ah.  can you add SNI to the config?
- SNI doesn't work for me.  I will try again a few times before contacting you.  thank you very much

**Comment by haruue** [comment]
> Ah. can you add SNI to the config?

@dopaemon 

SNI is named `server_name` in the client config.
Check the document here https://hysteria.network/docs/advanced-usage/#:~:text=%22-,server_name,-%22%3A%20%22real

And could you please open a new issue for your questions? I was confused yesterday.
