### ISSUE TITLE
[请求帮助] Ubuntu 20.04 使用多端口，在服务器添加iptables后，重启自动加载的方法

### ISSUE THREAD

**Issue by chika0801** [apernet/hysteria#519]
### 问题详情

请问 Ubuntu 20.04 使用多端口，在服务器配置添加iptables规则后，重启能自动加载的方法。

谷歌搜索的结果 ，方法都是 https://blog.csdn.net/jeremy_yangt/article/details/48317849

测试了这方法，重启后，没有重新加载规则。

**Comment by Smallthing** [comment]
傻瓜化的iptables保存有个apt包现在

**Comment by Smallthing** [comment]
iptables-persistent 将在重新启动时自动恢复iptables 的软件包。 linuxmi@linuxmi:~/ ...

**Comment by Smallthing** [comment]
iptables-persistent 将在重新启动时自动恢复iptables 的软件包

**Comment by chika0801** [comment]
> iptables-persistent

感谢你的分享，已经搜索到这个了，学习了，谢谢你帮助。
