### ISSUE TITLE
[Help me] Server crashes occasionally

### ISSUE THREAD

**Issue by franklee628** [apernet/hysteria#521]
### Details

Freshly installed hysteria by using the official script [install_server.sh](https://github.com/apernet/hysteria/blob/master/install_server.sh) on Debian 11, crashes 3 times or 4 in last 24 hours. 

### Hysteria server information

hysteria version v1.3.1 2022-11-26 09:35:46 7a7fda67f2658dd1cad777689dcfa2bda2dcdeca

### VPS information

Bandwagon, Debian 11(bullseye), X86, Intel, 2 Cores, 1024MB RAM 

### Server config

{
"listen": ":xxxxx",
"protocol": "udp",
"acme": {
    "domains": [
    "xxxxxxx.xxx"
    ],
    "email": "xxxx@xxxxxx.xxx"
},
"disable_udp": false,
"auth": {
    "mode": "password",
    "config": {
    "password": "xxxxxxxxxxxxxx"
    }
},
"alpn": "h3",
"acl": "/etc/hysteria/acl/routes.acl",
"recv_window_conn": 11534336,
"recv_window_client": 46137344,
"max_conn_client": 4096,
"disable_mtu_discovery": true,
"resolve_preference": "46",
"resolver": "https://8.8.8.8:443/dns-query"
}

### Server logs

Dec 07 17:53:02 hysteria[481]: panic: runtime error: index out of range [0] with length 0
Dec 07 17:53:02 hysteria[481]: goroutine 3524 [running]:
Dec 07 17:53:02 hysteria[481]: github.com/apernet/hysteria/core/cs.(*defragger).Feed(0xc000112358, {0x8d0e0000, 0x22, {0xc0005c6>
Dec 07 17:53:02 hysteria[481]:         github.com/apernet/hysteria/core/cs/frag.go:50 +0x2ae
Dec 07 17:53:02 hysteria[481]: github.com/apernet/hysteria/core/cs.(*serverClient).handleMessage(0xc0001122a0, {0xc000352850, 0x>
Dec 07 17:53:02 hysteria[481]:         github.com/apernet/hysteria/core/cs/server_client.go:134 +0x112
Dec 07 17:53:02 hysteria[481]: github.com/apernet/hysteria/core/cs.(*serverClient).Run.func1()
Dec 07 17:53:02 hysteria[481]:         github.com/apernet/hysteria/core/cs/server_client.go:83 +0x32
Dec 07 17:53:02 hysteria[481]: created by github.com/apernet/hysteria/core/cs.(*serverClient).Run
Dec 07 17:53:02 hysteria[481]:         github.com/apernet/hysteria/core/cs/server_client.go:77 +0x65
Dec 07 17:53:02 systemd[1]: hysteria-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 07 17:53:02 systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
Dec 07 17:53:02 systemd[1]: hysteria-server.service: Consumed 9.685s CPU time.

### Hysteria client information

N/A

### Client config

N/A

### Client environment (operating system)

N/A

### Client logs

N/A

**Comment by haruue** [comment]
Seems like a bug in UDP related protocol design / implementation.
What client are you using?

**Comment by franklee628** [comment]
Thanks for the reply, it happens when using Shadowrocket 2.2.23(1849). For your references, it has port hopping enabled, password authentication, allow insecure turned off, UDP relay on and TCP fast open off. Do you think I should contact the author of Shadowrocket instead? It will be better if you can confirm it's a bug from Shadowrocket before I do so.

**Comment by tobyxdd** [comment]
I guess you can say it's a bug on both sides. UDP MsgID is not supposed to be 0 but the server shouldn't crash even when it is.

This will be fixed in the next release.
