### ISSUE TITLE
[功能请求] ipv6连接支持

### ISSUE THREAD

**Issue by yaoey** [apernet/hysteria#523]
### 功能描述

服务器配置可解析ipv4的域名，客户端使用该域名可正常连接。
现客户端使用只能解析ipv6的域名连接，客户端已配置server_name与服务器相同、客户端已配置resolve_preference为“6”。
已提前通过nc测试服务器udp端口可通过ipv6访问，但使用客户端连接时会报错“ [ERRO] [error:timeout: no recent network activity] Failed to initialize client”

### 这个功能的必要性

ip地址无法直接访问，只能使用ipv6访问

### 当前可用的替代方案

无

### 补充

无

**Comment by haruue** [comment]
另外确定一下你服务端配置文件里的 `"listen"` 是 `:36712` 的形式而不是 `0.0.0.0:36712` 。
建议提供完整的服务端和客户端配置文件（你可以在发上来之前把域名换成 `_hy.example.com` 把密码换成 `password` ）。

**Comment by yaoey** [comment]
服务端配置
{
  "listen": ":30000",
  "acme": {
    "domains": [
      "_hy.example.com"
    ],
    "alt_http_port": 20080,
    "alt_tlsalpn_port": 20433,
    "disable_tlsalpn": true,
    "email": "admin@example.com"
  },
  "obfs": "obfs1234567890",
  "max_conn_client": 4096
}

客户配置
{
  //这里用ipv6地址和只指向ipv6地址的域名都测试过
  "server": "[2001::1]:30000-40000", 
  "obfs": "obfs1234567890",
  //server 与 server_name 里的域名对调也测试了.
  "server_name": "_hy.example.com",
  //这个参数测试了64/6和不设置,没有效果
  "resolve_preference": "6",
  "up_mbps": 100,
  "down_mbps": 100,
  "socks5": {
    "listen": "127.0.0.1:8888"
  },
  "http": {
    "listen": "127.0.0.1:9999"
  }
}

**Comment by yaoey** [comment]
打扰了，已测试通过，感谢你花时间在我错误的问题上。不好意思。
