### ISSUE TITLE
[功能请求] 能否在服务器端的socks5_outbound里面增加DNS查询转发选项

### ISSUE THREAD

**Issue by egg1234** [apernet/hysteria#526]
### 功能描述

能否在"socks5_outbound"功能项内增加DNS查询转发选项，把客户端的DNS查询不在这台中转机落地，转发到socks5_outbound的server去解析，类似下面那样的一个选项

"socks5_outbound": {
    "server": "127.0.0.1:1080", // 本机的SOCKS5 proxy server
    "DNS forward": true, // 举例增加这个DNS转发选项
    "user": "user", // SOCKS5 proxy username
    "password": "password" // SOCKS5 proxy password
  }

### 这个功能的必要性

原因是如果服务器架设在国内作为中转机，会出现DNS查询泄漏的问题，因为中转服务器在国内，国内的DNS都懂的，但设置了"resolver": "udp://1.1.1.1:53"选项又会导致DNS查询被干扰，
即使DoH也是效果不如转到最终服务器解析的，同样因为中转服务器在国内

**Comment by Smallthing** [comment]
我这儿，客户端的dns本来就没在本地落地
就算落地 你可以搞个iptables 劫持本机对1.1.1.1:53端口的访问到127.0.0.1:5353之类的 然后建立一个非标端口的本地dns cache（上游是你国外机，可以走tls或者DoQ，速度更快。
