### ISSUE TITLE
Go work拆分带来的问题

### ISSUE THREAD

**Issue by DumAdudus** [apernet/hysteria#528]
使用了go work之后，依赖引用不再跟随Tags发布了，例如对core的引用会变成这样而不是v1.3.1

> require (
	github.com/apernet/hysteria/core v0.0.0-20221201071030-fc28c0198013

**Comment by haruue** [comment]
感谢报告这个。
研究发现这是缺少 `core/*` 的 tag 的原因， 后续发布版本将会补上这个 tag 。

**Comment by haruue** [comment]
已经增加 `core/v1.3.1` 和 `app/v1.3.1` 两个 tag， 问题应该已经解决。
