### ISSUE TITLE
[Feature Request] Does Hysteria support multi-users functionality?

### ISSUE THREAD

**Issue by mshigemoto** [apernet/hysteria#535]
### Details

Does Hysteria support multi-users functionality? If not, do you have any plans to implement it in the future?

### Value

 I want this function when using Hysteria in my company for each staffs .

**Comment by malikshi** [comment]
maybe you can lookup at https://hysteria.network/docs/advanced-usage/#server section auth.

**Comment by haruue** [comment]
Hysteria is already support multi-users as you can set multiple password.

```json5
{
  // ...
  "auth": { // Authentication
    "mode": "passwords", // Mode, supports "none" "passwords" and "external". See external authentication page for details
    "config": ["yubiyubi", "random_password2", "Мать-Россия"]
  }
}
```

Although there is no something like "username", you can simply embed the "username" as a part of the "password". For example, start a hysteria server for yourself and your three friends.

```json5
{
  // ...
  "auth": { // Authentication
    "mode": "passwords", // Mode, supports "none" "passwords" and "external". See external authentication page for details
    "config": [
      "owner:kPplDxlkMmSe3Dr",
      "alice:cJGCctHpb1Y6AHE",
      "bob:gLuUB/IpkCWUyD",
      "charlie:8OSp5VtJISMszc"
    ]
  }
}
```

Hysteria also supports external authentication. If you want to build a commercial proxy provider with hysteria, please check our document for details: https://hysteria.network/docs/external-authentication/.

**Comment by mshigemoto** [comment]
Dear malikshi and haruue
Thank you so much, your quick response.
Your informations that I needed and help me.
