### ISSUE TITLE
[功能请求] 

### ISSUE THREAD

**Issue by Hfenger** [apernet/hysteria#540]
### 功能描述

通过hysteria反代本地服务，即访问hysteria服务器 0.0.0.0:XXX端口的流量转发到客户端0.0.0.0:XXX 端口。看了下文档，目前是支持通过客户端0.0.0.0:XXX端口的流量转发到远程0.0.0.0:XXX端口，但是没有反代相关描述。

### 这个功能的必要性

现在的反代软件有一个缺陷就是跨国网络质量很差，hysteria的优势为劣质网络性能。希望可以添加类似于v2ray的反代功能，这样就可以用低价国外主机对国内主机内网穿透了，同时保障一定的带宽。

### 当前可用的替代方案

xray v2ray ngrok等软件反代功能

**Comment by haruue** [comment]
不会考虑内建反代功能。 hy 服务器架设者通常都不会希望客户端随意开启反代端口的， 因此增加此功能还需要额外的鉴权步骤。

如果需要此类功能， 请考虑转发服务端 ssh 端口到客户端， 连上 ssh 之后使用 ssh 提供的反向端口转发功能（具体请参照 [`man:ssh(1)`  -R 选项](https://man.archlinux.org/man/ssh.1#R)）。
