### ISSUE TITLE
[Help me] How run As sevice in Windows

### ISSUE THREAD

**Issue by raminmalekghasemi** [apernet/hysteria#546]
### Details

Hi Dear Friends I used this 

sc.exe create proxy-new binPath= "c:/proxy/hysteria-tun-windows-6.0-amd64.exe"

To start service get error Doonot Start Or Control On exe file

### Hysteria server information

ubuntu 16.0.4

### VPS information

1GRAM

### Server config

Server Config IS ok

### Server logs

Server No problem..

### Hysteria client information

000000

### Client config

{
  "server": "CN.NaME:2869",
  "obfs": "My.PASSWOD",
  "up_mbps": 1000,
  "down_mbps": 1000,
  "socks5": {
    "listen": "127.0.0.1:1080"
  },
  "http": {
    "listen": "127.0.0.1:1081"
  }
}

### Client environment (operating system)

windows 7

### Client logs

1053

**Comment by tobyxdd** [comment]
Not sure if you are asking a question or just sharing your solution, as it appears you've already figured out how to run it as a service on Windows. Perhaps you should post it in [Discussions](https://github.com/apernet/hysteria/discussions) instead?
