### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by PHCSJC** [apernet/hysteria#552]
环境debian10 x64：
报错：

I: Extracting liblzma5...
I: Extracting zlib1g...
[ o.k. ] Installing base system [ Stage 2/2 ]
W: Failure trying to run:  /sbin/ldconfig
W: See //debootstrap/debootstrap.log for details
[ error ] ERROR in function create_rootfs_cache [ main.sh:588 -> main.sh:549 -> debootstrap.sh:58 -> debootstrap.sh:230 -> general.sh:0 ]
[ error ] Debootstrap base system for current phicomm-n1 bullseye   no second stage failed 
[ o.k. ] Process terminated 
[ error ] unmount_on_exit() called! [ main.sh:1 -> image-helpers.sh:0 ]
[ o.k. ] Unmounting [ /mnt/phicomm-n1/.tmp/rootfs-d0087f9d-7f9e-4fb9-bca3-f0409b152b16/ ]
[ error ] ERROR in function unmount_on_exit [ main.sh:1 -> image-helpers.sh:94 -> general.sh:0 ]
[ error ] debootstrap-ng was interrupted 
[ o.k. ] Process terminated 
root@debian:/mnt/phicomm-n1# ls -l //debootstrap/debootstrap.log
ls: cannot access '//debootstrap/debootstrap.log': No such file or directory

ldconfig这个命令是存在的，大佬看看是哪里的问题呢？

**Comment by haruue** [comment]
这是在编译 Phicomm N1 的 armbian 镜像？ 
能发一下你用的哪个脚本/工具以及产生这些报错的命令吗？ 看起来只是有个参数没设置。

**Comment by PHCSJC** [comment]
错了，不是这的，抱歉，删了吧
