### ISSUE TITLE
bug动态动口模式内存占用异常在MAC端

### ISSUE THREAD

**Issue by skill7899** [apernet/hysteria#556]
### 问题详情

我是MAC M1，client直接下载release最新版本和次新版本都存在这个问题，动态端口模式，内存占很大，大约用1天，高达400MB，应该是内存泄了，我就kill。换回单口就没有问题

### 服务端安装信息或者一键脚本信息

v1.3.2

### VPS 信息

无关

### 服务端配置

无关

### 服务端日志

无

### 客户端安装信息

v1.3.1-v1.3.2

### 客户端配置

{
  "server": "xxxx:20000-50000",
  "protocol": "udp", // 留空或 "udp", "wechat-video", "faketcp"
  "up_mbps": 50,
  "alpn": "h3",
  "auth_str": "xxxx",
  "down_mbps": 500,
  "socks5": {
    "listen": "127.0.0.1:1080"
  }
}

### 客户端运行环境（操作系统）

mac m1

### 客户端日志

无

**Comment by tobyxdd** [comment]
你会配置 Go 的编译环境么？或者留个联系方式（不希望公开的话可以发我邮箱，见我账号信息）我可以发你一个能收集调试信息的版本

**Comment by skill7899** [comment]
> 你会配置 Go 的编译环境么？或者留个联系方式（不希望公开的话可以发我邮箱，见我账号信息）我可以发你一个能收集调试信息的版本

已私

**Comment by tobyxdd** [comment]
没收到。。

**Comment by skill7899** [comment]
> 没收到。。

我再发了一次了

**Comment by skill7899** [comment]
已经复现，已经发给你了，你查收一下，看有没有收到。

**Comment by tobyxdd** [comment]
Should be fixed in https://github.com/apernet/hysteria/commit/1d9fa029c2478df7f7dcce3cabdd953dc4a0568e

**Comment by skill7899** [comment]
经测试已经解决
