### ISSUE TITLE
总是会不定期的tcp error

### ISSUE THREAD

**Issue by kilvn** [apernet/hysteria#557]
### Details

不定期的tcp error

### Hysteria server information

hysteria version v1.3.2 2022-12-11 02:15:05 dd4c17972fdfef7517c22d017ec922463fb94350

### VPS information

Chuncheon, ARM64, 4 Core, 24G RAM

### Server config

{
    "listen": ":xxx",
    "protocol": "udp",
    "cert": "xxx",
    "key": "xxx",
    "obfs": "xxx",
    "up_mbps": 500,
    "down_mbps": 500,
    "alpn": "h3",
    "resolve_preference": "64",
    "disable_mtu_discovery": true
}

### Server logs

![image](https://user-images.githubusercontent.com/16423601/216495807-0addc130-2166-42da-9d23-fa19c5eb11fe.png)

### Hysteria client information

hysteria version v1.3.2 2022-12-11 02:15:05 dd4c17972fdfef7517c22d017ec922463fb94350

### Client config

{
  "server": "xxx",
  "protocol": "udp",
  "obfs": "xxx",
  "up_mbps":500,
  "down_mbps":500,
  "alpn":"h3",
  "retry":3,
  "retry_interval":5,
  "socks5": {
    "listen": "127.0.0.1:2080",
    "timeout": 300,
    "disable_udp": false
  },
  "hop_interval": 10,
  "disable_mtu_discovery": true,
  "fast_open": true,
  "resolve_preference": "64"
}

### Client environment (operating system)

ubuntu 20.04, docker

### Client logs

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/16423601/216496502-52ffd2cd-e376-4bba-8f32-7e6d7e5ed4ad.png">

**Comment by haruue** [comment]
这种应该是 Hysteria 底层的 QUIC 连接断开重连了。 
已知部分国内运营商的 NAT 有问题， 源端口和目标端口长时间不变的话会 drop 掉这个四元组的 UDP 流量（我观察到这个问题主要是影响了 WireGuard）。
你有试过开启 port hopping 吗？

**Comment by kilvn** [comment]
> 这种应该是 Hysteria 底层的 QUIC 连接超时断开并重连了。 
> 
> 已知部分国内运营商的 NAT 有问题， 源端口和目标端口长时间不变的话会 drop 掉这个四元组的 UDP 流量（我观察到这个问题主要是影响了国内连接国内的 WireGuard）。
> 
> 你有试过开启 port hopping 吗？

我还不知道什么是 port hopping 呢，还有一点忘记说了，我是 udp 的端口跳跃

**Comment by tobyxdd** [comment]
no recent network activity 是 QUIC 连接断开导致的，你这个就是老生常谈的 UDP 断流
