### ISSUE TITLE
[功能请求] 支持reverse proxy功能

### ISSUE THREAD

**Issue by aa51513** [apernet/hysteria#558]
### 功能描述

在客户端配置一个远程监听端口P和一个目标地址A（例如127.0.0.1:80），

客户端主动发起连接，连上服务端后，

在服务端监听端口P，然后把这个端口P的数据，经由客户端转发给目标地址A

### 这个功能的必要性

众所周知，Hysteria 的加速效果非常棒，
然而目前，Hysteria 只支持“客户端—>服务端”的单向访问；

实际使用中，想作为网络出口的机器，只能作为Hysteria服务端来运行；
但是网络出口的环境，并不是一定有【可被外部访问】的条件;
这就带来了冲突

我的场景而言
是在网络A中，需要访问网络B，
同时，A与B之间通信质量差，需要用Hysteria加速
但是网络B没有公网IP，
要建立连接，只能是“B—>A”的方式建立连接；

以目前的情况来看，只能是Hysteria服务端运行在A上
但是Hysteria服务端并不能主动访问Hysteria客户端

所以才有了这条Issue

恳请大佬帮忙评估一下

### 当前可用的替代方案

Hysteria+Frp
socks+stcp组合使用，会导致连不上（估计是协议格式检测出错了）
其他组合倒是没太大问题

连勉强能用都算不上

### 补充

我个人拙见：就像群里有同学说的那样，Hysteria应该定位成一种“通道”，支持双向通信，是很有必要的
大佬有空帮忙评估一下

**Comment by haruue** [comment]
这种反向的 TCP 端口转发用 SSH 即可。

1. 编辑 VPS 端 `/etc/ssh/sshd_config` ， 加上下面这条， 然后重启 sshd （一般是执行 `systemctl restart sshd`）。
  ```
  GatewayPorts clientspecified
  ```

2. Hysteria 客户端配置 `relay_tcps` 功能转发服务端 ssh 端口（通常是 22 端口）到本地任意端口（下面的示例中是 6666 端口）。
  ```json5
  "relay_tcps": [
    {
      "listen": "127.0.0.1:6666",
      "remote": "127.0.0.1:22",
      "timeout": 300
    },
  ],
  ```

3. 客户端使用 ssh 连接由 Hysteria 转发到本地的服务端 ssh 端口， 并通过 ssh 的反向转发功能把服务端 TCP 端口转发到本地， 例如要将服务端 80 端口转发到客户端的 20080 。
  ```
  ssh -NR :80:127.0.0.1:28080 root@127.0.0.1 -p 6666
  ```

进行上述操作后， 外部即可通过访问服务器 80 端口访问到本机的 28080 端口， 并且是通过 Hysteria 加速的。

注意 Hysteria 对 UDP 流量不会有加速效果， 如果你有反向转发 UDP 端口的需求， 建议使用第三层 VPN 。

**Comment by haruue** [comment]
另一个可能的方法是先用第三层 VPN 把服务端和客户端连起来， 然后通过 VPN 的内网反向开启 Hysteria 。

举个例子， 你有两台机器 A 和 B 。 
+ A 没有公网 IP 但是你希望运行 Hysteria 服务端（让它提供网络出口）。
+ B 有公网 IP 但是你希望运行 Hysteria 客户端。

这种情况下，  你可以使用 OpenVPN 或者 WireGuard 在这两台机器之间建立第三层 VPN 连接。 并给这两台机器赋予内网 IP。
+ A: 192.0.2.1
+ B: 192.0.2.2

然后就可以在 A 上运行 Hysteria 服务端。 在 B 上运行 Hysteria 客户端， 并通过 `"server": "192.0.2.1:9012"` 这样的配置通过 VPN 内网来连接 A 上运行的 Hysteria 服务端。

**Comment by aa51513** [comment]
> 另一个可能的方法是先用第三层 VPN 把服务端和客户端连起来， 然后通过 VPN 的内网反向开启 Hysteria 。
> 
> 举个例子， 你有两台机器 A 和 B 。
> 
> * A 没有公网 IP 但是你希望运行 Hysteria 服务端（让它提供网络出口）。
> * B 有公网 IP 但是你希望运行 Hysteria 客户端。
> 
> 这种情况下， 你可以使用 OpenVPN 或者 WireGuard 在这两台机器之间建立第三层 VPN 连接（只要其中一台机器有公网 IP 即可建立）。 并给这两台机器赋予内网 IP。
> 
> * A: 192.0.2.1/24
> * B: 192.0.2.2/24
> 
> 然后就可以在 A 上运行 Hysteria 服务端。 在 B 上运行 Hysteria 客户端， 并通过 `"server": "192.0.2.1:9012"` 这样的配置通过 VPN 内网来连接 A 上运行的 Hysteria 服务端。

感谢指点，WireGuard 方案确实可行，已用上

**Comment by muziling** [comment]
SSH反向能用，但是设置VPS:1080   代理就是明文的socks代理了

**Comment by haruue** [comment]
> SSH反向能用，但是设置VPS:1080 代理就是明文的socks代理了，SSH晚上连的好好的，第二天到公司发现断了，然后又连不回家里了。
@muziling 

至于服务器端变成明文 socks5 代理的问题， 可以服务器端的明文 socks5 监听 `127.0.0.1:1080` ，然后服务器端再开个 hysteria 或者 v2ray 什么的以 `127.0.0.1:1080` 作为 `socks_outbounds` 。

至于晚上连得好好的第二天断了的问题， 通常是 ssh 断了（例如你家的路由器重新拨号了）， 有个自动重连 ssh 的工具叫做 `autossh` 可以解决这个问题。

**Comment by haruue** [comment]
@muziling 

我的意思是， 先通过 ssh 反向映射， 把你家的 socks5 server 端口映射到服务器上（可以通过类似于 `-R 127.0.0.1:21080:127.0.0.1:1080` 来让 ssh 反向代理在你服务器开的端口只监听本地， 避免有人从服务器外部直接明文连上这个 socks5 代理）， 然后在服务器上再运行一个 hysteria server， 把映射上来的这个 socks5 server 端口作为 hysteria server 的 `socks_outbounds` ， 然后你在公司再去连你服务器上的 hysteria server 。 这可以解决外部访问服务器使用明文 socks5 的问题。

请注意我 **不是** 让你通过由 ssh 映射出来的 TCP 端口去连接你家的 hysteria server ，  faketcp 也不可能在这种 Layer 4 代理端口上工作的。
