### ISSUE TITLE
[功能请求] 请求开放hysteria的发包速率控制参数

### ISSUE THREAD

**Issue by aa51513** [apernet/hysteria#562]
### 功能描述

开放发包速率控制参数，允许用户在配置文件中自定义发包速率

### 这个功能的必要性

过于暴力的发包速率，会引起运营商封端口
但是每个人使用情况又不一样
最好的办法是开放这个速率控制参数
类似于kcp那样

### 当前可用的替代方案

暂无

**Comment by tobyxdd** [comment]
已经有并且必须填的 up/down 参数就是。
