### ISSUE TITLE
[Feature Request] ip spoof

### ISSUE THREAD

**Issue by cross-hello** [apernet/hysteria#577]
### Details

https://github.com/net4people/bbs/issues/159

For tcp it has ACK to cope, but udp don't need.

### Value

As title

**Comment by cross-hello** [comment]
Related resource repository: https://github.com/dimalinux/spoofsourceip

**Comment by haruue** [comment]
Technically, I don't think this is senseful. 

Most of VPS providers and ISP verify the source address of IP packet (especially for the IPv4 network) to neutralize the DDoS attack on the Internet. Just take a look at RFC 3704 and `rp_filter` sysctl on the Linux.

**Comment by tobyxdd** [comment]
Interesting read, but imo it's beyond the scope of this project. Not planning on adding it to Hysteria for now.

**Comment by cross-hello** [comment]
😌 OK

Feb 28, 2023 13:29:52 Toby ***@***.***>:
