### ISSUE TITLE
[功能请求] 可否增加一个WINDOWS的服务端呢？ 我服务器是WIN的，想在WIN下部署 hysteria

### ISSUE THREAD

**Issue by jueduilingdu2** [apernet/hysteria#578]
### 功能描述

[功能请求] 可否增加一个WINDOWS的服务端呢？ 我服务器是WIN的，想在WIN下部署 hysteria

### 这个功能的必要性

[功能请求] 可否增加一个WINDOWS的服务端呢？ 我服务器是WIN的，想在WIN下部署 hysteria

**Comment by tobyxdd** [comment]
服务端和客户端本来就是在一起的。能运行客户端的平台都能运行服务端。
