### ISSUE TITLE
[功能请求] 发布适用于openwrt的ipk安装包

### ISSUE THREAD

**Issue by Fhokud** [apernet/hysteria#579]
### 功能描述

发布适用于openwrt的ipk安装包

### 这个功能的必要性

让各种架构的openwrt用户都可以快速安装使用hysteria

### 当前可用的替代方案

新建个仓库专门用于发布openwrt-hysteria

### 补充

类似于https://github.com/yichya/openwrt-xray

**Comment by mrzeuscn** [comment]
支持

**Comment by haruue** [comment]
我们欢迎任何第三方， 在包括 OpenWRT 在内的各种 Linux 发行版/开源软件仓库 为 hysteria 创建软件包（打包）以及分发编译好的二进制文件， 只需遵守 hysteria 的开源协议即可。

如果你熟悉 OpenWRT 的打包脚本编写方式， 那么你就可以直接创建这样的仓库， 然后联系我们把这个仓库的访问方式添加到 hysteria 的 [安装文档](https://hysteria.network/zh/docs/installation/) 中。

如果你不了解该如何创建 OpenWRT 软件包， 那么你可以考虑在 OpenWRT 社群中向有经验的用户寻求帮助。
