### ISSUE TITLE
[请求帮助] racknerd的ipv6连接不上，ipv4正常。

### ISSUE THREAD

**Issue by flowiceeos** [apernet/hysteria#581]
### 问题详情

racknerd的vps，ipv4正常，ipv6连接不上。按照常见问题的说明，用socat测试UDP，ipv4双向都通，IPV6测试，客户端发服务端能收到，服务端发客户端收不到。同样的配置在其它vps用过ipv6,没问题。

### 服务端安装信息或者一键脚本信息

hysteria version v1.3.3 2023-02-08 06:12:21 a48d6ddb7c83d605ef0d7f8ebe51515438a85a3a

### VPS 信息

racknerd 512 MB KVM 1vcpu

### 服务端配置

ipv4正常应该与配置无关

### 服务端日志

连不上服务端无日志

### 客户端安装信息

hysteria version v1.3.3 2023-02-08 06:12:21 a48d6ddb7c83d605ef0d7f8ebe51515438a85a3a

### 客户端配置

ipv4正常应该与配置无关

### 客户端运行环境（操作系统）

linux

### 客户端日志

[ERRO] [error:timeout: no recent network activity] Failed to initialize client

**Comment by haruue** [comment]
> IPV6测试，客户端发服务端能收到，服务端发客户端收不到

这个状况一般是因为你服务器 IPv6 地址被墙了 UDP 。 
试试 faketcp ？

**Comment by flowiceeos** [comment]
谢谢回复，可是faketcp没有UDP快啊，结束这条吧。
