### ISSUE TITLE
[功能请求] 希望添加windows端faketcp的功能

### ISSUE THREAD

**Issue by z836454898** [apernet/hysteria#582]
### 功能描述

在windows端添加faketcp的功能，将udp流量伪装成tcp

### 这个功能的必要性

电信宽带跑udp每10分钟就阻断一次，小流量也阻断，不是限速是直接把所有数据包丢弃的那种，qos到根本无法用。而且大多数用户是windows客户端，linux服务端这样的组合，希望作者考虑一下增加这个功能

### 当前可用的替代方案

在windows跑Linux虚拟机😂

**Comment by U-Insane** [comment]
windows客户端下的faketcp可以尝试 https://github.com/wangyu-/udp2raw-multiplatform

**Comment by kilvn** [comment]
端口跳跃默认10秒换端口，没必要折腾伪装tcp了，搞他几百个端口随便跳。

**Comment by z836454898** [comment]
> 端口跳跃默认10秒换端口，没必要折腾伪装tcp了，搞他几百个端口随便跳。

尝试过换端口了，还是被封，估计是识别ip的😂

**Comment by kilvn** [comment]
> > 端口跳跃默认10秒换端口，没必要折腾伪装tcp了，搞他几百个端口随便跳。
> 尝试过换端口了，还是被封，估计是识别ip的😂

faketcp目前只有Linux可以，win和Mac别等了，实在不行试下tuic吧

**Comment by z836454898** [comment]
原来是因为dns泄露被运营商探测到我的上网行为从而被ban，细思极恐。hysteria没有对域名进行分流，也就是说无论是国内域名还是国外的google youtube twitter域名都会通过运营商提供的dns进行查询，每次查询过后随之而来就是一大段的加密流量，于是运营商就知道我在翻墙了。我改了下配置文件，添加一行   "resolver": "tls://8.8.4.4"，也就是通过谷歌的dns服务器进行tls加密查询，就不再出现阻断的问题了，希望官方在文档上提醒读者注意这个问题。顺带一提，dns泄露可以通过[https://ipleak.net/](url)这个网站进行查询，如果dns服务器里面出现国内的ip则表明dns已经泄露，关于dns泄露更多详情可以查看这个人的视频[https://www.youtube.com/watch?v=fqREM6b25SY](url)

**Comment by z836454898** [comment]
顺带一提，v2ray的内核默认会按域名进行分流，所以一般不会出现dns泄露的问题

**Comment by kilvn** [comment]
> 原来是因为dns泄露被运营商探测到我的上网行为从而被阻断，细思极恐。hysteria没有对域名进行分流，也就是说无论是国内域名还是国外的google youtube twitter域名都会通过运营商提供的dns进行查询，每次查询过后随之而来就是一大段的加密流量，于是运营商就知道我在翻墙了。我改了下配置文件，添加一行 "resolver": "tls://8.8.4.4"，也就是通过谷歌的dns服务器进行tls加密查询，就不再出现阻断的问题了，希望官方在文档上提醒读者注意这个问题。顺带一提，dns泄露可以通过https://ipleak.net/这个网站进行查询，如果dns服务器里面出现国内的ip则表明dns已经泄露，关于dns泄露更多详情可以查看这个视频https://www.youtube.com/watch?v=fqREM6b25SY

看了，DNS确实有几个ISP的IP。正在泄露，难怪偶尔会被限速

**Comment by z836454898** [comment]
- 

> > 原来是因为dns泄露被运营商探测到我的上网行为从而被阻断，细思极恐。hysteria没有对域名进行分流，也就是说无论是国内域名还是国外的google youtube twitter域名都会通过运营商提供的dns进行查询，每次查询过后随之而来就是一大段的加密流量，于是运营商就知道我在翻墙了。我改了下配置文件，添加一行 "resolver": "tls://8.8.4.4"，也就是通过谷歌的dns服务器进行tls加密查询，就不再出现阻断的问题了，希望官方在文档上提醒读者注意这个问题。顺带一提，dns泄露可以通过[https://ipleak.net/这个网站进行查询，如果dns服务器里面出现国内的ip则表明dns已经泄露，关于dns泄露更多详情可以查看这个视频https://www.youtube.com/watch?v=fqREM6b25SY](https://ipleak.net/%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E8%BF%9B%E8%A1%8C%E6%9F%A5%E8%AF%A2%EF%BC%8C%E5%A6%82%E6%9E%9Cdns%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%87%8C%E9%9D%A2%E5%87%BA%E7%8E%B0%E5%9B%BD%E5%86%85%E7%9A%84ip%E5%88%99%E8%A1%A8%E6%98%8Edns%E5%B7%B2%E7%BB%8F%E6%B3%84%E9%9C%B2%EF%BC%8C%E5%85%B3%E4%BA%8Edns%E6%B3%84%E9%9C%B2%E6%9B%B4%E5%A4%9A%E8%AF%A6%E6%83%85%E5%8F%AF%E4%BB%A5%E6%9F%A5%E7%9C%8B%E8%BF%99%E4%B8%AA%E8%A7%86%E9%A2%91https://www.youtube.com/watch?v=fqREM6b25SY)
> 
> 看了，DNS确实有几个ISP的IP。正在泄露，难怪偶尔会被限速，我想问下你在配置文件添加一行 "resolver"，指的是客户端还是服务端？我在客户端加了这个然后重启客户端，再去ipleak检查还是有ISP的IP

只需在客户端添加就可以了
