### ISSUE TITLE
X86-32位hysteria 用lede编译后不能科学上网，64位和N1正常

### ISSUE THREAD

**Issue by dfbucy090** [apernet/hysteria#583]
### 问题详情

X86-32位hysteria 用lede编译后不能科学上网，64位和N1正常

X86-32位hysteria 用lede编译后不能科学上网，64位和N1正常，从去年7月份最后编译的5.15.50版本，hysteria还可以正常使用，包括32位机器，后来编译的32位都不能用，但是其它结构的正常，是不是32位太小众了，所以没有注意？

每次编译后都用几个类型机器试用，结果去年7月份发现问题，passwall等其他几个app的hysteria插件都不能打开网页，后来认为过段时间就可以自动修复，但是目前状况还是如此。

希望大佬能尽快解决这个BUG，虽然小众，但是机器还可以用，hysteria这个插件功能也很好。

### 服务端安装信息或者一键脚本信息

32位机器

### VPS 信息

32位机器

### 服务端配置

32位机器

### 服务端日志

32位机器

### 客户端安装信息

32位机器

### 客户端配置

32位机器

### 客户端运行环境（操作系统）

32位机器

### 客户端日志

32位机器

**Comment by tobyxdd** [comment]
不能上网的具体错误是？日志里能看出异常吗？

**Comment by dfbucy090** [comment]
> 不能上网的具体错误是？日志里能看出异常吗？

日志看不出来，看着都正常，导入和设置都可以，就是打不开油管和其他外网，最好您能用32位机器亲自试一下。从去年7月初开始编译的32位版本就不能用了，以前的可以，不懂什么原因。

**Comment by dfbucy090** [comment]
x86-64位和32位编译都会成功，看着功能也齐全，但是用passwall导入hysteria节点，同样的配置，32位就不能科学，后来测试其他如vssr及ssr-plus的hysteria,也不能正常科学。但64位版本正常。自己还留有去年7月初编译的32位版本5.15.50，刷入32位路由器，hysteria使用正常。

**Comment by haruue** [comment]
由于在 x86-32 的 Linux 上直接运行 hysteria 无法复现这个问题， 我们正在搭建一个与你使用的 LEDE 一样的环境来复现这个问题。

请提供你使用的 LEDE 的版本信息， 你发的 5.15.50 应该是内核版本号。
+ 如果你是下载现成的系统镜像， 你可以直接把对应版本的下载链接（例如 GitHub Release）贴上来。 
  + 如果你使用的 Passwall 是另外下载现成的 ipk 安装的， 请同样把 ipk 的下载链接贴上来。
+ 如果你是自己编译的， 请把你使用的源代码仓库（可在编译环境下用 `git remote -v` 获取）、 具体的 commit id （可在编译环境下用 `git describe --tags --always` 获取）、 额外添加的 Passwall 仓库的 feed ， 以及编译环境下的 `.config` 文件发上来。

**Comment by haruue** [comment]
我编译了最新版的 LEDE （ coolsnowwolf/lede@bbd9ecfd9514680369e4b0cd7787f951514bb230 ）， 成功复现了这个问题。

看起来 hysteria 已经正常启动， 它的 socks5 端口是可用的， 但是 Passwall 配置的 iptables 规则似乎有问题， 导致无法上网（默认配置下， 访问国外网站一定会 `ERR_CONNECTION_RESET` ）。

我会继续研究这个问题， 不过我也建议你把这个问题提交给 passwall 仓库。

**Comment by dfbucy090** [comment]
> 经过测试， 这是 Hysteria 的 `redirect_tcp` 实现在 x86-32 下的 BUG 。
> 
> 我们将着手修复此问题， 在修复完成的版本发布之前， 你可以将 Passwall 的「高级设置」里「转发配置」下面的「TCP 代理方式」改成「TPROXY」来绕过这个问题。
太感谢您了，我也不懂怎么提交，我编译都是照葫芦画瓢，再深的东西就懵圈了，刚才测试了下您的暂时办法，确实成功了。再次感谢您一丝不苟和无私奉献的精神并希望新的完美版能早日发布！

**Comment by PHCSJC** [comment]
@haruue 大佬什么时候修复一下这个bug哈？一直在等待，经常来看看 #527
