### ISSUE TITLE
[请求帮助] acme 配置不起作用？

### ISSUE THREAD

**Issue by abcfy2** [apernet/hysteria#584]
### 问题详情

我的配置如下:

```json
{
  "listen": ":54321",
  "protocol": "udp",
  "acme": {
    "domains": [
      "<hide>"
    ],
    "email": "<hide>",
    "disable_http": false,
    "disable_tlsalpn": false,
    "alt_http_port": 8888,
    "alt_tlsalpn_port": 4433
  },
  "obfs": "<hide>",
  "auth": {
    "mode": "passwords",
    "config": ["<hide>"]
  },
  "alpn": "h3"
}
```

启动的时候直接报错:

```txt
2023-03-14T08:34:51Z [FATA] [error:<hide>: obtaining certificate: [<hide>] Obtain: [<hide>] solving challenge: <hide>: [<hide>] authorization failed: HTTP 400 urn:ietf:params:acme:error:connection - <ip_hide>: Fetching http://<hide>/.well-known/acme-challenge/dbt68ySHMavCuh4rfBQBUTrk9_7TOAlNHL3V0BUDR-M: Connection refused (ca=https://acme-v02.api.letsencrypt.org/directory)] Failed to get a certificate with ACME
```

感觉是acme客户端根本没起作用，并没有监听80端口让这个URL可访问，其次就是这个`alt_http_port`到底有什么用啊？我以为可以用其他端口验证，防止80端口被占用，但从输出的日志来看并不起作用

### 服务端安装信息或者一键脚本信息

hysteria version v1.3.3 2023-02-08 06:12:21 a48d6ddb7c83d605ef0d7f8ebe51515438a85a3a

### VPS 信息

racknerd

### 服务端配置

No

### 服务端日志

/

### 客户端安装信息

/

### 客户端配置

/

### 客户端运行环境（操作系统）

/

### 客户端日志

/

**Comment by haruue** [comment]
你没有正确理解 alt_xxx_port 的作用， 如果你的 80 端口都可用， 你只需移除这两行配置就能用了。

```
"alt_http_port": 8888,
"alt_tlsalpn_port": 4433
```

**Comment by abcfy2** [comment]
哦，我明白你的意思了，`alt_http_port`是acme客户端监听的端口对吧，但实际上letsencrypt只会通过标准端口80验证，没办法通过这个配置让letsencrypt使用自定义端口验证对吧？

似乎是我对这个参数的理解有误，我以为我的80端口被占用了，可以通过修改这个参数让acme走其他非标准端口验证呢

**Comment by tobyxdd** [comment]
acme 从设计上就是故意只能用 80 和 443 进行验证的，没有办法修改。这个选项的用途是在已经在 80 和 443 端口开了 http server 的服务器上，可以通过自行配置反代实现验证

**Comment by abcfy2** [comment]
多谢解答，我就属于80端口被占用的场景，最终改用certbot pre-hook + post-hook重启服务的方案通过certbot申请证书了

**Comment by jantacy** [comment]
> 

一个ip可能被指定了多个domain，希望支持多个文件证书，感谢～
