### ISSUE TITLE
[请求帮助] acme申请的证书提示验证失败

### ISSUE THREAD

**Issue by zazi0001** [apernet/hysteria#590]
### 问题详情

两个IP绑定两个不同的域名，通过同样的命令申请证书，写入相同的模板，两者只有“server”、"server_name"字段存在区别
bash /root/.acme.sh/acme.sh --issue -d 域名 --debug --standalone --keylength ec-256 --force --server letsencrypt 
一台机器完全正常，一台机器只有Windows客户端、IOS客户端能连接，安卓、Linux客户端提示证书错误需要导入ca后才能连接
域名都是在cf上加的二级域名
Windows,Linux客户端均为最新的1.3.4 从releases页面下载
IOS客户端为shadowrocket
安卓客户端为matsuri 配 hysteria插件

### 服务端安装信息或者一键脚本信息

hysteria version v1.3.4 2023-03-15 02:49:14 b94f8a1eaf939a1f3efb469cbca1c3442db78dbc

### VPS 信息

正常机器：olink 圣何塞as9929 单核 512M
问题机器：vultr 东京 单核 1024M

### 服务端配置

{
  "listen": ":12345",
  "protocol": "udp",
  "disable_udp": false,
  "cert": "/root/hy/test1.xxx.info.cer",
  "key": "/root/hy/test1.xxx.info.key",
  "obfs": "123456",
  "auth": {
    "mode": "passwords",
    "config": [
      "qwerty"
    ]
  },
  "alpn": "h3",
  "recv_window_conn": 15728640,
  "recv_window_client": 67108864,
  "max_conn_client": 4096,
  "disable_mtu_discovery": true,
  "resolve_preference": "46",
  "resolver": "https://8.8.8.8:443/dns-query"
}

### 服务端日志

Mar 22 07:59:58 vultr hysteria[358]: 2023-03-22T07:59:58-04:00 [INFO] [src:1.2.3.4:59940] [error:timeout: no recent network activity] Client disconnected
Mar 22 08:01:22 vultr hysteria[358]: 2023-03-22T08:01:22-04:00 [INFO] [src:1.2.3.4:60484] Client connected
Mar 22 08:02:12 vultr hysteria[358]: 2023-03-22T08:02:12-04:00 [INFO] [src:1.2.3.4:59957] [error:timeout: no recent network activity] Client disconnected
Mar 22 08:02:22 vultr hysteria[358]: 2023-03-22T08:02:22-04:00 [INFO] [src:1.2.3.4:60484] [error:timeout: no recent network activity] Client disconnected
Mar 22 08:13:42 vultr hysteria[358]: 2023-03-22T08:13:42-04:00 [INFO] [src:1.2.3.5:45599] Client connected
Mar 22 08:14:42 vultr hysteria[358]: 2023-03-22T08:14:42-04:00 [INFO] [src:1.2.3.5:45599] [error:timeout: no recent network activity] Client disconnected
Mar 22 08:14:50 vultr hysteria[358]: 2023-03-22T08:14:50-04:00 [INFO] [src:1.2.3.5:51399] Client connected
Mar 22 08:25:10 vultr hysteria[358]: 2023-03-22T08:25:10-04:00 [INFO] [src:1.2.3.4:59428] Client connected
Mar 22 08:33:48 vultr hysteria[358]: 2023-03-22T08:33:48-04:00 [INFO] [src:1.2.3.5:51399] [error:timeout: no recent network activity] Client disconnected
Mar 22 08:44:08 vultr hysteria[358]: 2023-03-22T08:44:08-04:00 [INFO] [src:1.2.3.4:49114] Client connected
Mar 22 08:59:25 vultr hysteria[358]: 2023-03-22T08:59:25-04:00 [INFO] [src:1.2.3.4:49114] [error:timeout: no recent network activity] Client disconnected

### 客户端安装信息

hysteria version v1.3.4 2023-03-15 02:49:14 b94f8a1eaf939a1f3efb469cbca1c3442db78dbc

### 客户端配置

{
  "server": "test2.xxx.info:12345", 
  "protocol": "udp", 
  "up_mbps": 50, 
  "down_mbps": 100, 
  "retry": 3, 
  "retry_interval": 5, 
  "quit_on_disconnect": false, 
  "handshake_timeout": 10, 
  "idle_timeout": 60, 
  "hop_interval": 120, 
  "http": {
    "listen": "0.0.0.0:12354, 
    "timeout": 300 
  },
  "obfs": "123456",
  "auth_str": "qwerty",
  "alpn": "h3",
  "server_name": "test2.xxx.info", 
  "insecure": false,
  "recv_window_conn": 15728640, 
  "recv_window": 67108864, 
  "disable_mtu_discovery": true, 
  "fast_open": true, 
  "resolver": "https://223.5.5.5/dns-query", 
  "resolve_preference": "46" 
}

### 客户端运行环境（操作系统）

Ubuntu 20.04.6

### 客户端日志

3月 22 20:59:02 50 systemd[1]: Started Hysteria Service.
3月 22 20:59:02 50 hysteria[2309]: 2023-03-22T20:59:02+08:00 [INFO] [config:{Server:test2.xxx.info:12345 Protocol:udp Up: U>3月 22 20:59:02 50 hysteria[2309]: 2023-03-22T20:59:02+08:00 [ERRO] [error:CRYPTO_ERROR 0x12a (local): x509: certificate signed >3月 22 20:59:02 50 hysteria[2309]: 2023-03-22T20:59:02+08:00 [INFO] [retry:1] [interval:5] Retrying...
3月 22 20:59:07 50 hysteria[2309]: 2023-03-22T20:59:07+08:00 [ERRO] [error:CRYPTO_ERROR 0x12a (local): x509: certificate signed >3月 22 20:59:07 50 hysteria[2309]: 2023-03-22T20:59:07+08:00 [INFO] [retry:2] [interval:5] Retrying...
3月 22 20:59:13 50 hysteria[2309]: 2023-03-22T20:59:13+08:00 [ERRO] [error:CRYPTO_ERROR 0x12a (local): x509: certificate signed >3月 22 20:59:13 50 hysteria[2309]: 2023-03-22T20:59:13+08:00 [INFO] [retry:3] [interval:5] Retrying...

**Comment by haruue** [comment]
客户端日志被截断了挺奇怪的， 看起来可能是 `error:CRYPTO_ERROR 0x12a (local): x509: certificate signed by unknown authority` 。

不过根据「只有Windows客户端、IOS客户端能连接，安卓、Linux客户端提示证书错误需要导入ca后才能连接」， 我猜应该是服务端使用了不完整的证书链。

如果你使用 acme.sh 申请证书， 实际上指定给 hysteria 的 cert 选项的证书文件应该是 `.acme.sh/域名/fullchain.cer` 而不是  `.acme.sh/域名/域名.cer` ， 前者是完整证书链而后者是只有叶证书。

**Comment by zazi0001** [comment]
感谢
