### ISSUE TITLE
[请求帮助] 优化建议提到的`tream receive window`和`connection receive window`是否标反了？

### ISSUE THREAD

**Issue by abcfy2** [apernet/hysteria#591]
### 问题详情

优化建议文档提到( https://hysteria.network/zh/docs/optimizations/ ):

> 建议保持 stream receive window 与 connection receive window 的比例为 2:5。

但是默认配置中却写着:

```json
...
  "recv_window_conn": 15728640, // QUIC stream receive window
  "recv_window": 67108864, // QUIC connection receive window
...
```

想问下这个注释有问题还是变量名命名有问题？后缀带有`_conn`却是stream receive window？这里的变量命名是否混淆了？

### 服务端安装信息或者一键脚本信息

。

### VPS 信息

。

### 服务端配置

。

### 服务端日志

。

### 客户端安装信息

。

### 客户端配置

。

### 客户端运行环境（操作系统）

。

### 客户端日志

。

**Comment by tobyxdd** [comment]
其实这是因为 QUIC 和 hysteria 对 connection 这个概念的定义不一样导致的，并没有标反。

Hysteria 客户端和服务端只建立一个 QUIC 连接，而被代理的 TCP 连接是这个 QUIC 连接里不同的 stream。 `recv_window` 指的是所有被代理的连接的总 window，对应的是 QUIC connection 的 window。而 `recv_window_conn` 指的是单个代理连接的 window，对应的是 QUIC stream 的 window。

**Comment by abcfy2** [comment]
原来是这样，明白了
