### ISSUE TITLE
[Help me] 用不了，日志如下

### ISSUE THREAD

**Issue by Yofo-me** [apernet/hysteria#604]
### Details

![image](https://user-images.githubusercontent.com/55388087/235491586-ae425d00-28ae-4c91-9454-490bc0aa16e8.png)

### Hysteria server information

hysteria version v1.3.4 2023-05-01 14:54:58 b94f8a1eaf939a1f3efb469cbca1c3442db78dbc

### VPS information

lastest Arch Linux, v.ps, 1H1G 15G

### Server config

`config.json`
![image](https://user-images.githubusercontent.com/55388087/235491815-1f9e4e07-e5c1-4f56-a4f6-33f4d0ae6982.png)

`systemd config`
![image](https://user-images.githubusercontent.com/55388087/235492069-c4131031-15fc-4561-a171-08e34fc64b93.png)

`working dir`
![image](https://user-images.githubusercontent.com/55388087/235492199-7aac926d-3eab-4f58-b661-fd6f188c1985.png)

很奇怪，同一个证书和key，nginx网站能用,这个不行

### Server logs

look at above info

### Hysteria client information

none

### Client config

none

### Client environment (operating system)

win11

### Client logs

nono

**Comment by haruue** [comment]
服务端启动失败了， 日志中可以看到

```
error:open /etc/hysteria/key.pem: no such file or directory
```

这表明你在服务端配置中指定了 `"key": "/etc/hysteria/key.pem"` ， 然而这个文件并不存在。 你需要修改服务端配置指定成正确的文件， 或者把你的服务端证书的 key 复制到你指定的位置。

**Comment by qist** [comment]
![image](https://user-images.githubusercontent.com/7844620/236131923-695d99fa-bd07-46a1-81e7-0a45137afb62.png)有空格把
