### ISSUE TITLE
vps重启以后端口跃迁功能就失效

### ISSUE THREAD

**Issue by soloyu** [apernet/hysteria#607]
vps重启以后端口跃迁功能就失效了，但是使用主端口有效，重新设置一遍配置以后又可以使用
用的是这两个一键，分别在不同版本的debian上，都这样
https://github.com/yonggekkk/Hysteria-yg
https://github.com/emptysuns/Hi_Hysteria

**Comment by haruue** [comment]
应该是因为一键脚本里没有配置 iptables 规则的持久化。

比如如果你的系统是 Ubuntu/Debian 的话， 可以在配置好一切之后安装 `netfilter-persistent` 这个包， 它会问你要不要持久化当前规则（选 yes）， 并自动帮你配置好所需的 systemd 服务。

**Comment by soloyu** [comment]
亲测有效，感谢！
一键脚本有待更新。
