### ISSUE TITLE
[Feature Request] Any One Use hysteria with v2board?

### ISSUE THREAD

**Issue by alirezashahrokhi** [apernet/hysteria#608]
### Details

hello every one
any one connect hysteria with v2board panel?
xrayr cant support this

### Value

add a backend support v2board panel

**Comment by shangkouyou** [comment]
> 当然，我们已经有了一个后端v2board
> 
> [https://github.com/lotusproxy/bodhi-docker/wiki/Bodhi-Deploy-instruction ](https://github.com/lotusproxy/bodhi-docker/wiki/Bodhi-Deploy-instruction)

你这 我跑起来但是没办法去订阅呀

**Comment by lotusnetwork** [comment]
> > 当然，我们已经有了一个后端v2board
> > [https://github.com/lotusproxy/bodhi-docker/wiki/Bodhi-Deploy-instruction ](https://github.com/lotusproxy/bodhi-docker/wiki/Bodhi-Deploy-instruction)
> 
> 你这 我跑起来但是没办法去订阅呀

因为v2b没写订阅的那部分, 你可以抄一下我们的patch 或者干脆直接来用lotusboard
