### ISSUE TITLE
hysteria出现以下错误，导致网页无法打开

### ISSUE THREAD

**Issue by jeson106** [apernet/hysteria#628]
V2rayN使用最新版本的hysteria插件，使用“自动配置系统代理”模式，路由使用“绕过大陆(whitelist)”，出现如下错误
[error:lookup ecs.console.aliyun.com on 192.168.1.1:53: read buffer too small] [0mHTTP error

使用vmess插件时，不会出现以上错误，因此怀疑是hysteria问题.

插件版本:  hysteria version v1.3.5 2023-06-11 23:47:46 57c5164854d6cfe00bead730cce731da2babe406

**Comment by tobyxdd** [comment]
有使用自定义 DNS 么？

**Comment by jeson106** [comment]
> 有使用自定义DNS么？

没有自定义DNS，也不知道192.168.1.1的IP哪儿来的，我本地使用的8.8.8.8, hysteria配置文件中使用的"resolver": "https://223.6.6.6/dns-query",

**Comment by royccai** [comment]
read buffer too small...通过"recv_window": 67108864, 增大缓冲区大小，hysteria使用改进后的quic协议，需调整缓冲区大小

**Comment by tobyxdd** [comment]
上面的回答是错的。去掉 resolver 应该能解决问题

**Comment by tobyxdd** [comment]
Should no longer be a problem in 2.0
