### ISSUE TITLE
安装脚本有问题.

### ISSUE THREAD

**Issue by wutongskype** [apernet/hysteria#640]
![image](https://github.com/apernet/hysteria/assets/40192806/8f1e6fd8-1434-4718-a901-4b1c37f625a6)

**Comment by haruue** [comment]
这个问题应该是触发了 GitHub API 的请求频率上限。

安装脚本会调用 GitHub API 来查询最新版本， 在不带 API Key 的情况下， GitHub API 的 ratelimit 仅为 60 次/小时。 

只需显式指定要安装的版本号， 就能避免调用 GitHub API， 从而绕过你遇到的这个问题。

例如， 要安装最新版本， 你可以先手动访问 [Hysteria 的发布页面](https://github.com/apernet/hysteria/releases/latest)， 获取最新版本号（当前是 `v1.3.5`）。

然后， 指定版本号运行这个脚本， 也就是执行
```
bash install_server.sh --version v1.3.5 
```

**Comment by wutongskype** [comment]
> 这个问题应该是触发了 GitHub API 的请求频率上限。
> 
> 安装脚本会调用 GitHub API 来查询最新版本， 在不带 API Key 的情况下， GitHub API 的 ratelimit 仅为 60 次/小时。
> 
> 只需显式指定要安装的版本号， 就能避免调用 GitHub API， 从而绕过你遇到的这个问题。
> 
> 例如， 要安装最新版本， 你可以先手动访问 [Hysteria 的发布页面](https://github.com/apernet/hysteria/releases/latest)， 获取最新版本号（当前是 `v1.3.5`）。
> 
> 然后， 指定版本号运行这个脚本， 也就是执行
> 
> ```
> bash install_server.sh --version v1.3.5 
> ```

啊, 原来是这样, 我还以为小鸡网络有问题, 折腾老半天哈, 最后手动安装的, 写了个systemd~~~
