### ISSUE TITLE
[功能请求] 能否考虑增加pinned_certchain_sha256功能

### ISSUE THREAD

**Issue by egg1234** [apernet/hysteria#643]
### 功能描述

在hysteria的server子命令或全局命令里面加入generate-certchain-hash www.yourdomain.com.pem 命令去生成自签全链证书的hash值，这个自签证书可以是自签的也可以是从cloudflare上下载的全链证书
举例命令：./hysteria server generate-certchain-hash www.yourdomain.com.pem  
生成hash值：Bxm8h1sapZPl+cTx+vAnDv3ARVLb123tB86lNnQqTj0=

然后客户端的配置文件增加如下的对应参数项
"pinned_certchain_sha256": "Bxm8h1sapZPl+cTx+vAnDv3ARVLb123tB86lNnQqTj0=",
这样客户端的配置文件就根本不需要指定ca文件，也可以使用"insecure": false,去确保服务器使用自签证书连接的安全性

以上实现可以参考下面项目，它已经完全实现了，经过测试非常实用
https://github.com/juicity/juicity  
相关的issue
github.com/juicity/juicity/issues/34

### 这个功能的必要性

可以使得客户端不需要下载相应的ca文件去确保连接的安全性，特别是移动设备将会非常方便

更进一步可以让hysteria://方式的分享连接即使是服务器使用自签证书也能分享相应的hash值，不需要通知客户端去下载相应的ca文件

**Comment by tobyxdd** [comment]
Implemented in Hy2 https://github.com/apernet/hysteria/commit/3c3c2a51a870e7bc308772d4289589ba76d38dc7

**Comment by tobyxdd** [comment]
需要注意的一点是我这个实现和 `insecure` 是各自独立的，insecure false 的情况下 pin 了证书依然会校验证书本身的有效性。因此对于自签证书依然需要 insecure true
