### ISSUE TITLE
[Feature Request] : Outbound routing

### ISSUE THREAD

**Issue by nimagp** [apernet/hysteria#646]
### Details

A feature to allow selecting socks outbount based on user auth string or somesuch.

### Value

Enabling sophisticated configuration of outbounds.

### Available alternatives

Running two different instances of Hysteria?

**Comment by tobyxdd** [comment]
Already a working in progress feature in the upcoming Hysteria 2 (https://github.com/apernet/hysteria/tree/wip-hy2)
