### ISSUE TITLE
Support go1.21.0

### ISSUE THREAD

**Issue by chenrui333** [apernet/hysteria#647]
### Bug Description

Need to bump quic-go to 0.37.4 for building with go1.21.0

relates to https://github.com/quic-go/quic-go/pull/4020
relates to https://github.com/Homebrew/homebrew-core/pull/134468

**Comment by tobyxdd** [comment]
We're currently finalizing Hysteria 2.0 (https://github.com/apernet/hysteria/tree/wip-hy2), which already addresses this issue and will be released soon. So we have no plans to make any more changes to 1.x.

**Comment by chenrui333** [comment]
Sounds good, thanks!
