### ISSUE TITLE
[功能请求]可以让 V2board前段面板去用Hysteria吗

### ISSUE THREAD

**Issue by shangkouyou** [apernet/hysteria#648]
### 功能描述

V2board前段面板去用Hysteria吗

### 这个功能的必要性

Hysteria 是我最喜欢的协议了 

### 当前可用的替代方案

没有 

### 补充

好想拥有啊

**Comment by qiumzh** [comment]
是不是来错地方了？！

**Comment by lotusnetwork** [comment]
不是, 你是不是不知道1.7.4已经支持hysteria了?
