### ISSUE TITLE
 最近封的好厉害，都封了好几个IP，差不多用1~3天就GG

### ISSUE THREAD

**Issue by gsuns** [apernet/hysteria#649]
### 问题详情
有时候是夜里很晚的时候封 有时候是早晨一大早封，还有的时候是下午封 看被封的时间段，感觉应该不是人工在做这件事。
wechat-video 
开了OBFS
证书是cerbot申请的非自签

### 服务端安装信息或者一键脚本信息

1.3.5

### VPS 信息

自用VPS 非机场

### 服务端配置

{
    "listen": ":保密",
    "protocol": "wechat-video",
    "cert": "fullchain.pem",
    "key": "privkey.pem",
    "alpn": "wechat",
    "obfs": "保密",
    "up_mbps": 256,
    "down_mbps": 256,
    "disable_udp": false,
    "recv_window_conn": 15728640,
    "recv_window_client": 67108864,
    "max_conn_client": 512,
    "disable_mtu_discovery": false,
}

### 服务端日志

none

### 客户端安装信息

1.3.5

### 客户端配置

{
    "http": {
        "listen": "127.0.0.1:10001"
    },
    "socks5": {
        "listen": "127.0.0.1:10000"
    },
    "server": "保密",
    "hop_interval": 16,
    "protocol": "wechat-video",
    "up_mbps": 256, 
    "down_mbps": 256,
    "retry": 3,
    "retry_interval": 5,
    "idle_timeout": 300,
    "alpn": "wechat",
    "obfs": "保密",
    "server_name": "保密",
    "insecure": false,
    "recv_window_conn": 15728640,
    "recv_window": 67108864,
    "disable_udp": false,
    "disable_mtu_discovery": false,
    "fast_open": false,
    "resolver": "保密",
    "resolve_preference": "64",
    "acl": "star.acl",
    "mmdb": "GeoLite2.mmdb"
}

### 客户端运行环境（操作系统）

Windows 11

### 客户端日志

none

**Comment by gsuns** [comment]
目前在用TUIC 目前看来比HY稳一点。也希望HY能给我们带来更多惊喜。感谢作者

**Comment by qiumzh** [comment]
目前使用一切正常，6台vps都没有被封的情况。我使用的是 `faketcp` 模式

**Comment by yqk100** [comment]
没被封过，但在广电宽带阻断的很频繁/规律；
阻断之后至少15分钟+以上没法使用，一直循环。

**Comment by gsuns** [comment]
抱歉，是我上面没说清楚，我补充下，被封的时候，不是所有协议 端口被封，而是hy端口被封，被封期间，是完全无法使用的，并不是阻断几秒 几分钟就能用的，而是一直不能用一段时间，被封时间长短也有所不同，有时候15分钟有时候1小时，我有4个以上ip都是这种现象，我以前的解决方法是换ip，以我个人的能力，不足以说明问题的根源，以上只是作为参考，不代表所有人都是这样，但有一点值得注意，在4月之前，我使用wechat-video很稳，一次也没被封。

**Comment by gsuns** [comment]
再补充一个现象：
我目前VPS有开了两个端口 HY 和 TUIC，HY 模式是wechat-video，配置和半年前一样，HY被封的时候我就切TUIC，TUIC是可以用的。
从结果来看，GFW是选择性的封锁（HY端口）。

**Comment by tobyxdd** [comment]
这种讨论更适合放 https://github.com/apernet/hysteria/discussions
