### ISSUE TITLE
[bug] yaml 不支持配置监听[::1]的socks5

### ISSUE THREAD

**Issue by CCCAUCHY** [apernet/hysteria#653]
yaml 不支持配置监听[::1]的socks5
`{"error": "While parsing config: yaml: line 10: did not find expected node content"}`
尚不清楚其他位置的配置v6地址时是否有bug

**Comment by haruue** [comment]
这是 yaml 的魔幻 feature 之一， 和数组语法冲突了， 用字符串包起来即可。

```yaml
socks5:
  listen: "[::1]:1080"
```
