### ISSUE TITLE
IPv6支持很差

### ISSUE THREAD

**Issue by awsawsz** [apernet/hysteria#657]
断断续续。

**Comment by tobyxdd** [comment]
这不叫 IPv6 支持很差，叫你网络的 IPv6 很差

**Comment by awsawsz** [comment]
> 这不叫 IPv6 支持很差，叫你网络的 IPv6 很差
可能有什么误解，同样网络TUIC跑起来完全没问题。
可能存在IPV6转发的什么原因？
