### ISSUE TITLE
发现hysteria1的部署脚本地址貌似失效了

### ISSUE THREAD

**Issue by chidedao** [apernet/hysteria#660]
已知目前1和2的双端完全不兼容，且新协议没有什么第三方客户端支持，可用性不高，所以希望不要删除hysteria1的部署脚本

**Comment by haruue** [comment]
可以通过下面的命令调用 hy1 安装脚本

```bash
bash <(curl -fsSL https://raw.githubusercontent.com/apernet/hysteria/hy1/install_server.sh)
```

类似于 Python 2/3 并存的情况， 现在该脚本会将 hy1 安装成 `hysteria1` 命令， 并安装 `hysteria1-server.service` 和 `hysteria1-server@.service` 两个 systemd unit ， 用于和 hy2 脚本区分。 因此用此脚本安装的 hy1 可以和 hy2 同时安装。

另外你也可以尝试通过 hy1 时代的第三方脚本安装 hy1 。 

如果你使用 Arch Linux ， 我们也创建了 [`aur/hysteria1`](https://aur.archlinux.org/packages/hysteria1) 和 [`aur/hysteria1-bin`](https://aur.archlinux.org/packages/hysteria1-bin) 可用于 hy1 的安装。

**Comment by chidedao** [comment]
感谢

**Comment by SirEnri2001** [comment]
找了好久，终于找到hy1的安装脚本地址了
