### ISSUE TITLE
config配置问题

### ISSUE THREAD

**Issue by Daohuai0913** [apernet/hysteria#661]
![图片](https://github.com/apernet/hysteria/assets/31792646/46b7de33-6844-427c-99d3-95b112cc0979)
hysteria2 如图 无论是 config.yaml 还是hysteria主程序 还是1.crt都加了x w r权限为什么还是不行啊 求解答

**Comment by Daohuai0913** [comment]
![图片](https://github.com/apernet/hysteria/assets/31792646/c5c5b7d6-d340-4fdc-9d18-7638135b1589)
权限的图片是这样的

**Comment by haruue** [comment]
```
chmod a+x /root
```
