### ISSUE TITLE
socks5 error 

### ISSUE THREAD

**Issue by wikilinux-ir** [apernet/hysteria#663]
Hello 
my config  in server is :

`listen: :444

tls:
  cert:  path/to/file
  key: path/to/file

auth:
  type: password
  password: MyStrongPassword 

outbounds:
  - name: my_outbound_2
    type: direct

`

and client config is :

`server: myServer.com:444

auth: MyStrongPassword

bandwidth:
  up: 200 mbps
  down: 200 mbps

socks5:
  listen: 127.0.0.1:1800

http:
  listen: 127.0.0.1:8000

`

but when using socks5 recivied error and connection not work: 

`2023-09-05T10:40:28Z    ERROR   SOCKS5 TCP error        {"addr": "127.0.0.1:41454", "reqAddr": "178.240.18.175:443", "error": "dial error: dial tcp4 178.240.18.175:443: i/o timeout"}
2023-09-05T10:57:13Z    ERROR   SOCKS5 TCP error        {"addr": "178.131.17.31:18922", "reqAddr": "127.0.0.1:9614", "error": "dial error: dial tcp4 127.0.0.1:9614: connect: connection refused"}

`

**Comment by tobyxdd** [comment]
This simply means your server cannot connect to the address you are trying to connect to (178.240.18.175:443), not a bug in Hysteria.
