### ISSUE TITLE
Windows clients for Hysteria2

### ISSUE THREAD

**Issue by hellofr13nd** [apernet/hysteria#666]
Thanks for the great protocol, is there any Windows Client that supports Hysteria2?
V2rayN for example seems to only support Hysteria1 for now.

**Comment by hedsbj** [comment]
> Thanks for the great protocol, is there any Windows Client that supports Hysteria2? V2rayN for example seems to only support Hysteria1 for now.

v2rayN support Hysteria v2

**Comment by hellofr13nd** [comment]
@hedsbj  In `Add a custom configuration server` in `Core Type`, we can only select hysteria, not hysteria2.
Do you use another method?

**Comment by hedsbj** [comment]
把windows平台上的新版hysteria.exe下载 放到对应 的目录 ，core type 就选hysteria 就可以 。已经 用了一段时间了

**Comment by hellofr13nd** [comment]
I use the latest version V2rayN 6.28, but I think if I replace the hysteria exe with the new version, I can't use my hysteria1 servers that I already have.

**Comment by hellofr13nd** [comment]
@hedsbj Thanks, it seems the new client exe also supports Hysteria1.

**Comment by hellofr13nd** [comment]
@hedsbj I replaced the new Hysteria client exe in the latest version of V2rayN 6.28 and Hysteria1 servers don't work anymore because Hysteria2 is fundamentally different, so I think a new Core Type(Hysteria2) should be added to V2rayN.

**Comment by hellofr13nd** [comment]
@egg1234 Interesting, I'll give it a try, I tested Nekoray a long time ago but I don't remember what it was I didn't like, maybe some random errors or dns leak... but I'll test it again, especially when 3.20 version is finalized.

**Comment by computerscot** [comment]
Another one you can try with Hysteria2 is Furious: 

https://cscot.pages.dev/2023/09/13/hysteria2-furious

**Comment by hellofr13nd** [comment]
Thanks @computerscot, That's helpful.
