### ISSUE TITLE
hysteria v2 能否也像 hysteria v1 那样添加 Docker 安装方式

### ISSUE THREAD

**Issue by yanbook** [apernet/hysteria#669]
hysteria v2 服务端能否也增加docker安装方式
在服务端使用Docker方式安装，比较方便管理，也容易迁移，希望作者能够像hysteria v1那样添加Docker安装方式，万分感谢，麻烦了。

**Comment by haruue** [comment]
hysteria 最新的 docker 镜像已经更新到 2.0.0 了。
https://hub.docker.com/r/tobyxdd/hysteria

请参考使用文档获取 docker compose 示例
https://hysteria.network/zh/docs/getting-started/Installation/#docker

**Comment by yanbook** [comment]
> hysteria 最新的 docker 镜像已经更新到 2.0.0 了。 https://hub.docker.com/r/tobyxdd/hysteria
> 
> 请参考使用文档获取 docker compose 示例 https://hysteria.network/zh/docs/getting-started/Installation/#docker

多谢，已经配置好了，开心
