### ISSUE TITLE
hysteria2 启动后只监听udp443 debian10

### ISSUE THREAD

**Issue by qsdiy** [apernet/hysteria#672]
之前在centos平台正常运行过hysteria2，换到debian10 之后同样的配置，hysteria2 只监听udb443，更改监听端口后依然是只监听udp
<img width="1102" alt="截屏2023-09-09 下午5 56 29" src="https://github.com/apernet/hysteria/assets/2499565/256af8aa-edea-4687-b20a-b50ef5af1257">

大神指点

**Comment by tobyxdd** [comment]
QUIC 就是 UDP 协议啊，监听 UDP 有什么问题吗

**Comment by yaotthaha** [comment]
建议去把计算机网络和quic协议学一遍

**Comment by qsdiy** [comment]
不是端口的问题，是证书的问题。

现在有一个疑问，服务端不需要强制配置server 字段 为域名或主机地址，但是我发现客户端是必须配置域名的，否则会报错
“{"error": "connect error: INTERNAL_ERROR (remote): no certificate available for '::'" ”
这样的话，如果该域名如果被dns污染了之后 如何处理？

**Comment by qsdiy** [comment]
而且当初反复不成功的还有一个问题是，没有配置混淆 字段，这个字段好像也是必须的，但是配置文档里没有说这个字段也是
必须配置的。

**Comment by tobyxdd** [comment]
可以用 ip 连接但是在 tls 里指定 sni
