### ISSUE TITLE
failed to initialize client	{"error": "connect error: timeout: no recent network activity"}

### ISSUE THREAD

**Issue by shamino1** [apernet/hysteria#673]
我把Server安装好了：

![image](https://github.com/apernet/hysteria/assets/144535709/7dae1053-0081-47de-ade9-b49ede4b68bc)

在execute Client的时候出现这个Error：
![image](https://github.com/apernet/hysteria/assets/144535709/de5f5a64-dc12-4387-86df-7c9a6bd3577e)

这是我server和client的config.yaml:
![image](https://github.com/apernet/hysteria/assets/144535709/4e60b0e4-b040-4796-9840-2f90b7810755)

![image](https://github.com/apernet/hysteria/assets/144535709/7d27486f-a7f5-4a66-b039-c7d2c807b9b1)

**Comment by tobyxdd** [comment]
https://v2.hysteria.network/zh/docs/advanced/Troubleshooting/

**Comment by shamino1** [comment]
好像是Port的问题。打开所有Port就可以了。除了1080和8080还需开哪些Port?

**Comment by tobyxdd** [comment]
服务端 listen 在哪个端口就开哪个端口，你的例子 443 就够了

**Comment by toplinuxsir** [comment]
I meet the same problem tool!
