### ISSUE TITLE
支持 TCP 协议作为代理链接

### ISSUE THREAD

**Issue by ghost** [apernet/hysteria#674]
从 https://github.com/v2fly/v2ray-core/discussions/2687 找过来的。

有一些封锁UDP、且不稳定的网络环境，希望能通过hysteria提供稳定的链接。hysteria的quic UDP包能安全地塞进udp over TCP里么？

**Comment by haruue** [comment]
不建议通过 UDP over TCP 使用 Hysteria （这一类问题本质上最终会变成 TCP over TCP）， 在低丢包的环境下， TCP over TCP 或许是可用的。 然而在不稳定的网络环境下， 当丢包频繁发生时， TCP over TCP 的性能会显著劣于单层 TCP + BBR 拥塞控制。 推荐阅读
+ [Why TCP Over TCP Is A Bad Idea](https://archive.li/wS6P7)
+ [What is TCP Meltdown?](https://openvpn.net/faq/what-is-tcp-meltdown/)

对于封锁 UDP 的环境， 通常可分为两种情况。

1. 你到目标机器仍然是 L3 相通， 服务商仅仅只是通过防火墙禁止了 UDP （[`ipproto`](https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers) == 0x11）流量。
   + 对于这种情况， 你可以通过 faketcp 来使用 hysteria。 当前 hy2 并未内建 faketcp 支持（后续会加）， 你可以考虑通过 [udp2raw](https://github.com/wangyu-/udp2raw) 来达成类似的目的， 或者使用 hy1 的 faketcp 模式。

2. 你到目标机器通过了一层 TCP 代理， 例如服务商使用了 haproxy 之类的方法做了用户态的 TCP 转发。
   + 对于这种情况， faketcp 不会起作用， 无法使用 hysteria 。 请使用基于 TCP 的代理。

如果你一定要测试， GitHub 上已经有不少能把 UDP 包塞进 TCP 流的项目， 例如 [mullvad/udp-over-tcp](https://github.com/mullvad/udp-over-tcp)。

**Comment by us254** [comment]
@nick008a
>hysteria能被配置为（尽可能地）在UDP over TCP隧道中工作么？比如，如何调整 recvWindow或者bandwidth？

https://github.com/apernet/hysteria/issues/644#issuecomment-1669753890
