### ISSUE TITLE
不能执行安装脚本

### ISSUE THREAD

**Issue by nkta3m** [apernet/hysteria#678]
执行以下命令：
`sudo bash <(curl -fsSL https://get.hy2.sh/)`
返回以下错误：
bash: /proc/self/fd/11: No such file or directory
请教该如何解决？谢谢

**Comment by haruue** [comment]
不要加 sudo 。

**Comment by nkta3m** [comment]
bash <(curl -fsSL https://get.hy2.sh/)
11: note: The user running this script is not root.
11: note: Re-running this script with sudo. You can also specify FORCE_NO_ROOT=1 to force this script to run as the current user.
env: ‘/proc/self/fd/11’: No such file or directory
之前就是这样的提示，才加了sudo

**Comment by haruue** [comment]
修了， 再试试呢？

**Comment by nkta3m** [comment]
Checking for installed version ... not installed
Checking for latest version ...
卡在这里不动了

**Comment by nkta3m** [comment]
curl: (28) Failed to connect to api.github.com port 443: Connection timed out
Downloading hysteria binary: https://github.com/apernet/hysteria/releases/download/app/hyservinst.PufoqTv86D: error: Failed to get the latest version from GitHub API, please check your network and try again./hysteria-linux-amd64 ...
curl: (3) bad range in URL position 84:
https://github.com/apernet/hysteria/releases/download/app/hyservinst.PufoqTv86D: error: Failed to get the latest version from GitHub API, please check your network and try again./hysteria-linux-amd64

**Comment by haruue** [comment]
看来你的服务器连不上 GitHub API 。

你可以用

```
bash <(curl -fsSL https://get.hy2.sh/) --version v2.0.0
```

**Comment by nkta3m** [comment]
解决了，谢谢
