### ISSUE TITLE
hysteria无法观看twitch，报错2000

### ISSUE THREAD

**Issue by SigmaXTH** [apernet/hysteria#686]
如题，试过清楚缓存，关闭插件等等，似乎是hysteria本身的问题，求大佬解答，非常感谢

**Comment by tobyxdd** [comment]
报错 2000 是什么意思

**Comment by SigmaXTH** [comment]
![image](https://github.com/apernet/hysteria/assets/88566005/fafc8b7b-6868-43a2-9664-1abbda7f2565)

**Comment by SigmaXTH** [comment]
大概就像这样

**Comment by tobyxdd** [comment]
发一下客户端 debug log? (https://v2.hysteria.network/zh/docs/advanced/Logging/)

**Comment by SigmaXTH** [comment]
第一次不太会用github，请问这个怎么上传log呀

**Comment by SigmaXTH** [comment]
[neko - 副本.log](https://github.com/apernet/hysteria/files/12607093/neko.-.log)

**Comment by SigmaXTH** [comment]
哦哦不好意思才发现之前摁错了我说半天找不到附件qwq
