### ISSUE TITLE
我这域名这一步过不去呢？

### ISSUE THREAD

**Issue by zhl111** [apernet/hysteria#691]
ip解析没问题啊
![image](https://github.com/apernet/hysteria/assets/29135984/3d763c65-2fe0-449e-a79e-9a678a38b81e)

**Comment by haruue** [comment]
看起来你在同一台机器上安装了 nginx ？
![Screenshot_20230916_152841](https://github.com/apernet/hysteria/assets/13131972/9d473b4d-ffac-4663-a401-9383b0e92bd2)

**Comment by haruue** [comment]
你刚打码没打全啊。。。

如果不需要 nginx 的话， 你可以先把 nginx 停用并禁用了

```
systemctl stop nginx
systemctl disable nginx
```

上面这两条命令如果出错， 说明你的系统版本比较老（nginx 1.10.3 是 2017 年的）可能不是基于 systemd 的， 这种情况下下面这种命令可能有用

```
/etc/init.d/nginx stop
/etc/init.d/nginx disable
```

等停用之后， 确认 80 端口没有被占用， 再启动 hysteria server 签署证书。
