### ISSUE TITLE
TCP Error

### ISSUE THREAD

**Issue by MaoshanDunkey** [apernet/hysteria#694]
I set the http protocol to use port 8080 in the client configuration, and YouTube can be opened. But when using the speed test website to test the speed, it shows failure. Checking the hysterica status on the server shows error, tcp error.
我在客户端配置中设置http协议使用8080端口，可以打开YouTube。但是用测速网站进行测速时，显示失败。在服务器查看hysterica状态显示error，tcp error

**Comment by tobyxdd** [comment]
日志

**Comment by MaoshanDunkey** [comment]
hysteria-server.service - Hysteria Server Service (config.yaml)
   Loaded: loaded (/etc/systemd/system/hysteria-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2023-09-17 23:46:20 EDT; 2 days ago
 Main PID: 8652 (hysteria)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/hysteria-server.service
           └─8652 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml

Sep 17 23:52:42 vps5452815.hosteons.com hysteria[8652]: 2023-09-17T23:52:42-04:00        ERROR        TCP error        {"addr": "117.173.xxx.xx:26920", "id": "user", "reqAddr": "speedtest.airlin
Sep 17 23:52:42 vps5452815.hosteons.com hysteria[8652]: 2023-09-17T23:52:42-04:00        ERROR        TCP error        {"addr": "117.173.xxx.xx:26920", "id": "user", "reqAddr": "ntp.msn.cn:443",
Sep 17 23:52:42 vps5452815.hosteons.com hysteria[8652]: 2023-09-17T23:52:42-04:00        ERROR        TCP error        {"addr": "117.173.xxx.xx:26920", "id": "user", "reqAddr": "nav-edge.smartsc
Sep 17 23:52:42 vps5452815.hosteons.com hysteria[8652]: 2023-09-17T23:52:42-04:00        ERROR        TCP error        {"addr": "117.173.xxx.xx:26920", "id": "user", "reqAddr": "rr1---sn-o097zns
Sep 17 23:52:42 vps5452815.hosteons.com hysteria[8652]: 2023-09-17T23:52:42-04:00        ERROR        TCP error        {"addr": "117.173.xxx.xx:26920", "id": "user", "reqAddr": "ads.betweendigit
Sep 17 23:52:42 vps5452815.hosteons.com hysteria[8652]: 2023-09-17T23:52:42-04:00        ERROR        TCP error        {"addr": "117.173.xxx.xx:26920", "id": "user", "reqAddr": "www.tecmint.com:
Sep 17 23:52:42 vps5452815.hosteons.com hysteria[8652]: 2023-09-17T23:52:42-04:00        ERROR        TCP error        {"addr": "117.173.xxx.xx:26920", "id": "user", "reqAddr": "rr1---sn-o097zns
Sep 17 23:52:42 vps5452815.hosteons.com hysteria[8652]: 2023-09-17T23:52:42-04:00        INFO        client disconnected        {"addr": "117.173.xxx.xx:26920", "id": "user", "error": "accepting
Sep 19 23:48:39 vps5452815.hosteons.com hysteria[8652]: 2023-09-19T23:48:39-04:00        INFO        client connected        {"addr": "117.173.xxx.xx:26738", "id": "user", "tx": 6553600}
Sep 19 23:50:38 vps5452815.hosteons.com hysteria[8652]: 2023-09-19T23:50:38-04:00        INFO        client connected        {"addr": "117.173.xxx.xx:26967", "id": "user", "tx": 6553600}

**Comment by tobyxdd** [comment]
https://www.putorius.net/export-logs-to-a-file-with-journalctl.html

**Comment by us254** [comment]
**Export All Logs with Journalctl:**
If you want to export all logs to a text file, you can use the following command:

```
sudo journalctl > all_logs.txt
```

This command redirects all logs from `journalctl` to a file named "all_logs.txt."

**Export Specific Logs from Journalctl:**
You can use various options to export specific logs based on your criteria. For example, to export NetworkManager logs since yesterday, use this command:

```
sudo journalctl -u NetworkManager -S yesterday > NetworkManager_logs_1day.txt
```

In this command:
- `-u NetworkManager` specifies the unit (service) name.
- `-S yesterday` specifies logs since yesterday.

**Formatting Output of Journalctl:**
You can format the exported logs in different ways:

- To format logs as JSON objects, use this command:

```
sudo journalctl -u NetworkManager --output=json > NetworkManager-JSON
```

- To format logs in classic syslog style (one line per entry), use this command:

```
sudo journalctl -u NetworkManager --output=short > NetworkManager.log
```

**Comment by cytown** [comment]
same issue, the following is the logs

```
Sep 24 10:22:58 mail systemd[1]: hysteria-server.service: Succeeded.
Sep 24 10:22:58 mail hysteria[813059]: 2023-09-24T10:22:58-04:00        INFO        server mode
Sep 24 10:22:58 mail hysteria[813059]: 2023-09-24T10:22:58-04:00        INFO        server up and running
Sep 24 10:30:43 mail systemd[1]: hysteria-server.service: Succeeded.
Sep 24 10:30:43 mail hysteria[814232]: 2023-09-24T10:30:43-04:00        INFO        server mode
Sep 24 10:30:43 mail hysteria[814232]: 2023-09-24T10:30:43-04:00        INFO        server up and running
Sep 24 10:30:57 mail hysteria[814232]: 2023-09-24T10:30:57-04:00        INFO        client connected        {"addr": "117.134.7.241:63796", "id": "user", "tx": 13107200}
Sep 24 10:36:05 mail hysteria[814232]: 2023-09-24T10:36:05-04:00        ERROR        TCP error        {"addr": "117.134.7.241:63796", "id": "user", "reqAddr": "api.hy2.io:443", "error": "readfrom tcp4 104.245.213.36:38144->172.67.208.246:443: timeout: no recent network activity"}
Sep 24 10:36:05 mail hysteria[814232]: 2023-09-24T10:36:05-04:00        INFO        client disconnected        {"addr": "117.134.7.241:63796", "id": "user", "error": "accepting stream failed: timeout: no recent network activity"}
Sep 24 10:36:35 mail systemd[1]: hysteria-server.service: Succeeded.
Sep 24 10:36:35 mail hysteria[815029]: 2023-09-24T10:36:35-04:00        INFO        server mode
Sep 24 10:36:35 mail hysteria[815029]: 2023-09-24T10:36:35-04:00        INFO        server up and running
Sep 24 10:37:10 mail hysteria[815029]: 2023-09-24T10:37:10-04:00        INFO        client connected        {"addr": "117.134.7.241:56635", "id": "user", "tx": 13107200}
Sep 24 12:43:21 mail hysteria[815029]: 2023-09-24T12:43:21-04:00        INFO        client disconnected        {"addr": "117.134.7.241:56635", "id": "user", "error": "accepting stream failed: timeout: no recent network activity"}
Sep 24 22:18:26 mail hysteria[815029]: 2023-09-24T22:18:26-04:00        INFO        client connected        {"addr": "120.246.52.235:55192", "id": "user", "tx": 13107200}
Sep 24 22:20:27 mail hysteria[815029]: 2023-09-24T22:20:27-04:00        INFO        client connected        {"addr": "120.246.52.235:59113", "id": "user", "tx": 13107200}
Sep 24 22:20:49 mail hysteria[815029]: 2023-09-24T22:20:49-04:00        ERROR        TCP error        {"addr": "120.246.52.235:55192", "id": "user", "reqAddr": "api.hy2.io:443", "error": "readfrom tcp4 104.245.213.36:34246->104.21.69.135:443: timeout: no recent network activity"}
Sep 24 22:20:49 mail hysteria[815029]: 2023-09-24T22:20:49-04:00        INFO        client disconnected        {"addr": "120.246.52.235:55192", "id": "user", "error": "accepting stream failed: timeout: no recent network activity"}
Sep 24 22:29:26 mail systemd[1]: hysteria-server.service: Succeeded.
Sep 24 22:29:26 mail hysteria[911475]: 2023-09-24T22:29:26-04:00        INFO        server mode
Sep 24 22:29:26 mail hysteria[911475]: 2023-09-24T22:29:26-04:00        INFO        server up and running
Sep 24 22:29:37 mail hysteria[911475]: 2023-09-24T22:29:37-04:00        INFO        client connected        {"addr": "120.246.52.235:55690", "id": "user", "tx": 13107200}
Sep 24 22:34:38 mail hysteria[911475]: 2023-09-24T22:34:38-04:00        ERROR        TCP error        {"addr": "120.246.52.235:55690", "id": "user", "reqAddr": "api.hy2.io:443", "error": "readfrom tcp6 [2402:d0c0:10:1221::1]:49140->[2606:4700:3034::6815:4587]:443: timeout: no recent network activity"}
Sep 24 22:34:38 mail hysteria[911475]: 2023-09-24T22:34:38-04:00        INFO        client disconnected        {"addr": "120.246.52.235:55690", "id": "user", "error": "accepting stream failed: timeout: no recent network activity"}
Sep 24 22:34:58 mail hysteria[911475]: 2023-09-24T22:34:58-04:00        INFO        client connected        {"addr": "120.246.52.235:63041", "id": "user", "tx": 13107200}
Sep 24 22:37:15 mail systemd[1]: hysteria-server.service: Succeeded.
Sep 24 22:37:15 mail hysteria[912506]: 2023-09-24T22:37:15-04:00        INFO        server mode
Sep 24 22:37:15 mail hysteria[912506]: 2023-09-24T22:37:15-04:00        INFO        server up and running
Sep 24 22:37:56 mail hysteria[912506]: 2023-09-24T22:37:56-04:00        INFO        client connected        {"addr": "120.246.52.235:51477", "id": "user", "tx": 13107200}
Sep 24 22:38:33 mail hysteria[912506]: 2023-09-24T22:38:33-04:00        INFO        client connected        {"addr": "120.246.52.235:64798", "id": "user", "tx": 13107200}
Sep 24 22:38:47 mail hysteria[912506]: 2023-09-24T22:38:47-04:00        ERROR        TCP error        {"addr": "120.246.52.235:51477", "id": "user", "reqAddr": "api.hy2.io:443", "error": "readfrom tcp4 104.245.213.36:50572->172.67.208.246:443: timeout: no recent network activity"}
Sep 24 22:38:47 mail hysteria[912506]: 2023-09-24T22:38:47-04:00        INFO        client disconnected        {"addr": "120.246.52.235:51477", "id": "user", "error": "accepting stream failed: timeout: no recent network activity"}
Sep 24 22:39:22 mail hysteria[912506]: 2023-09-24T22:39:22-04:00        INFO        client connected        {"addr": "120.246.52.235:51521", "id": "user", "tx": 13107200}
Sep 24 22:39:35 mail hysteria[912506]: 2023-09-24T22:39:35-04:00        ERROR        TCP error        {"addr": "120.246.52.235:64798", "id": "user", "reqAddr": "api.hy2.io:443", "error": "readfrom tcp4 104.245.213.36:56626->104.21.69.135:443: timeout: no recent network activity"}
Sep 24 22:39:35 mail hysteria[912506]: 2023-09-24T22:39:35-04:00        INFO        client disconnected        {"addr": "120.246.52.235:64798", "id": "user", "error": "accepting stream failed: timeout: no recent network activity"}
```

**Comment by cytown** [comment]
BTW, 2 days ago, it worked just fine, and without any issue, but after I update the pem files(date invalidate), it did not work anymore...

**Comment by binarri** [comment]
same issue!

`Sep 27 01:29:41 RNLAX hysteria[4305]: 2023-09-27T01:29:41-07:00        ERROR        TCP error        {"addr": "211.90.236.24:26445", "id": "user", "reqAddr": "graph.facebook.com:443", "error": "readfrom tcp4 198.148.124.4:61342->157.240.11.17:443: stream 344 canceled by remote with error code 0"}
Sep 27 01:29:41 RNLAX hysteria[4305]: 2023-09-27T01:29:41-07:00        ERROR        TCP error        {"addr": "211.90.236.24:26445", "id": "user", "reqAddr": "i-fallback.instagram.com:443", "error": "readfrom tcp4 198.148.124.4:62620->31.13.80.52:443: stream 48 canceled by remote with error code 0"}
Sep 27 01:29:41 RNLAX hysteria[4305]: 2023-09-27T01:29:41-07:00        ERROR        TCP error        {"addr": "211.90.236.24:26445", "id": "user", "reqAddr": "scontent-lax3-1.cdninstagram.com:443", "error": "readfrom tcp4 198.148.124.4:54756->31.13.70.52:443: stream 368 canceled by remote with error code 0"}
Sep 27 01:29:41 RNLAX hysteria[4305]: 2023-09-27T01:29:41-07:00        ERROR        TCP error        {"addr": "211.90.236.24:26445", "id": "user", "reqAddr": "i-fallback.instagram.com:443", "error": "readfrom tcp4 198.148.124.4:62712->31.13.80.52:443: stream 64 canceled by remote with error code 0"}
Sep 27 01:29:41 RNLAX hysteria[4305]: 2023-09-27T01:29:41-07:00        ERROR        TCP error        {"addr": "211.90.236.24:26445", "id": "user", "reqAddr": "i-fallback.instagram.com:443", "error": "readfrom tcp4 198.148.124.4:62894->31.13.80.52:443: stream 164 canceled by remote with error code 0"}
Sep 27 01:29:41 RNLAX hysteria[4305]: 2023-09-27T01:29:41-07:00        ERROR        TCP error        {"addr": "211.90.236.24:26445", "id": "user", "reqAddr": "i-fallback.instagram.com:443", "error": "readfrom tcp4 198.148.124.4:62852->31.13.80.52:443: stream 156 canceled by remote with error code 0"}
Sep 27 01:29:41 RNLAX hysteria[4305]: 2023-09-27T01:29:41-07:00        ERROR        TCP error        {"addr": "211.90.236.24:26445", "id": "user", "reqAddr": "i-fallback.instagram.com:443", "error": "readfrom tcp4 198.148.124.4:62862->31.13.80.52:443: stream 152 canceled by remote with error code 0"}`

**Comment by binarri** [comment]
same issue 🥹

**Comment by binarri** [comment]
the following is the server logs

[hysteria-server.service.log.txt](https://github.com/apernet/hysteria/files/12746163/hysteria-server.service.log.txt)

**Comment by antonavy** [comment]
So what's the solution?
