### ISSUE TITLE
客户端错误信息wsasend: An existing connection was forcibly closed by the remote host.（wsasend：现有连接被远程主机强制关闭。）

### ISSUE THREAD

**Issue by bzmjcster** [apernet/hysteria#697]
wsasend: An existing connection was forcibly closed by the remote host.（wsasend：现有连接被远程主机强制关闭。）

**Comment by bzmjcster** [comment]
+0800 2023-09-19 11:20:50 [31mERROR[0m [[38;5;45m203112948[0m] inbound/http[http]: process connection from 127.0.0.1:52762: download: readfrom tcp 127.0.0.1:10809->127.0.0.1:52762: read tcp 127.0.0.1:52764->127.0.0.1:5080: use of closed network connection | upload: readfrom tcp 127.0.0.1:52764->127.0.0.1:5080: read tcp 127.0.0.1:10809->127.0.0.1:52762: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by bzmjcster** [comment]
+0800 2023-09-19 11:23:35 [31mERROR[0m [[38;5;204m1043546300[0m] dns: lookup failed for assets.msn.cn: exchange4: context deadline exceeded | exchange6: context deadline exceeded | upstream: context deadline exceeded
+0800 2023-09-19 11:24:25 [31mERROR[0m [[38;5;50m1943054517[0m] inbound/http[http]: process connection from 127.0.0.1:64065: upload: readfrom tcp 127.0.0.1:64066->127.0.0.1:5080: read tcp 127.0.0.1:10809->127.0.0.1:64065: wsarecv: An existing connection was forcibly closed by the remote host. | download: readfrom tcp 127.0.0.1:10809->127.0.0.1:64065: read tcp 127.0.0.1:64066->127.0.0.1:5080: use of closed network connection
+0800 2023-09-19 11:24:25 [31mERROR[0m [[38;5;227m3401519323[0m] inbound/http[http]: process connection from 127.0.0.1:64063: write tcp 127.0.0.1:10809->127.0.0.1:64063: wsasend: An existing connection was forcibly closed by the remote host.
+0800 2023-09-19 11:24:41 [31mERROR[0m [[38;5;134m2867072630[0m] inbound/http[http]: process connection from 127.0.0.1:64091: download: readfrom tcp 127.0.0.1:10809->127.0.0.1:64091: read tcp 127.0.0.1:64092->127.0.0.1:5080: use of closed network connection | upload: readfrom tcp 127.0.0.1:64092->127.0.0.1:5080: read tcp 127.0.0.1:10809->127.0.0.1:64091: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by tobyxdd** [comment]
这根本不是 hysteria 的日志格式，用的哪个去哪个项目发
