### ISSUE TITLE
TCP ERROR, DATAGRAM frame too large

### ISSUE THREAD

**Issue by cateegit** [apernet/hysteria#698]
{"addr": "113.65.161.182:56813", "id": "user", "reqAddr": "35.186.224.25:443", "error": "readfrom tcp4 <server_ip>:52866->35.186.224.25:443: PROTOCOL_VIOLATION (local): DATAGRAM frame too large"}
复现：打开youtube有概率出现

**Comment by cateegit** [comment]
hysteria 2.0.2

**Comment by tobyxdd** [comment]
两边用的都是官方版？确定不是 sing-box 之类的吗

**Comment by cateegit** [comment]
> 两边用的都是官方版？确定不是 sing-box 之类的吗

ios端用的singbox，pc v2rayN似乎没遇到这个问题

**Comment by tobyxdd** [comment]
这是 sing-box 的 bug，找他们反馈

**Comment by cateegit** [comment]
> 这是 sing-box 的 bug，找他们反馈

这是已知问题？

**Comment by tobyxdd** [comment]
> > 这是 sing-box 的 bug，找他们反馈
> 
> 这是已知问题？

是 sing-box 的已知问题
