### ISSUE TITLE
tcp 错误，导致无法使用

### ISSUE THREAD

**Issue by bzmjcster** [apernet/hysteria#700]
Sep 19 23:24:42 v220230919 hysteria[42429]: 2023-09-19T23:24:42+08:00        ERROR        TCP error        {"addr": "104.28.152.167:25274", "id": "user", "reqAddr": "www.youtube.com:443", "error": "stream 12 canceled by remote with error code 0"}
Sep 19 23:25:03 v220230919 hysteria[42429]: 2023-09-19T23:25:03+08:00        ERROR        TCP error        {"addr": "104.28.152.167:25274", "id": "user", "reqAddr": "github.com:443", "error": "dial tcp4 140.82.121.4:443: i/o timeout"}
Sep 19 23:25:37 v220230919 hysteria[42429]: 2023-09-19T23:25:37+08:00        ERROR        TCP error        {"addr": "104.28.152.167:25274", "id": "user", "reqAddr": "user-images.githubusercontent.com:443", "error": "stream 24 canceled by remote with error code 0"}
Sep 19 23:25:49 v220230919 hysteria[42429]: 2023-09-19T23:25:49+08:00        ERROR        TCP error        {"addr": "104.28.152.167:25274", "id": "user", "reqAddr": "api.github.com:443", "error": "stream 32 canceled by remote with error code 0"}
Sep 19 23:26:11 v220230919 hysteria[42429]: 2023-09-19T23:26:11+08:00        ERROR        TCP error        {"addr": "104.28.152.167:25274", "id": "user", "reqAddr": "www.youtube.com:443", "error": "stream 52 canceled by remote with error code 0"}

**Comment by tobyxdd** [comment]
发服务端日志

**Comment by bzmjcster** [comment]
服务端日志  查询命令好多呢？谢谢

Toby ***@***.***> 于2023年9月20日周三 01:07写道：
