### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Biaogo94** [apernet/hysteria#702]
+0800 2023-09-19 23:55:19 [31mERROR[0m [[38;5;30m2571389966[0m 1ms] inbound/http[http]: process connection from 127.0.0.1:55993: exchange6: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it. | exchange4: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it.
+0800 2023-09-19 23:55:20 [31mERROR[0m [[38;5;85m553288773[0m 1ms] dns: lookup failed for gae2-spclient.spotify.com: exchange6: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it. | exchange4: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it.
+0800 2023-09-19 23:55:20 [31mERROR[0m [[38;5;85m553288773[0m 1ms] inbound/http[http]: process connection from 127.0.0.1:56000: exchange6: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it. | exchange4: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it.
+0800 2023-09-19 23:55:20 [31mERROR[0m [[38;5;147m3931544707[0m 1ms] dns: lookup failed for gae2-spclient.spotify.com: exchange6: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it. | exchange4: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it.
+0800 2023-09-19 23:55:20 [31mERROR[0m [[38;5;147m3931544707[0m 1ms] inbound/http[http]: process connection from 127.0.0.1:56007: exchange6: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it. | exchange4: dial tcp 127.0.0.1:7090: connectex: No connection could be made because the target machine actively refused it.

参考不良林的教程配置，报错如上

https://bulianglin.com/archives/hysteria2.html

服务器配置：
listen: :443 #监听端口

#使用自签证书
tls:
  cert: /etc/hysteria/server.crt
  key: /etc/hysteria/server.key

auth:
  type: password
  password: huang@123 #设置认证密码

masquerade:
  type: proxy
  proxy:
    url: https://bing.com #伪装网址
    rewriteHost: true

客户端配置：
server: xxx.xxx.xxx.xxx:443
auth: huang@123

bandwidth:
  up: 50 mbps
  down: 50 mbps
  
tls:
  sni: bing.com
  insecure: true #使用自签时需要改成true

socks5:
  listen: 127.0.0.1:7090
http:
  listen: 127.0.0.1:8080

**Comment by Phascolarctos** [comment]
### 你先看看你的端口开没开，然后看dns配置
`
resolver:
  type: udp
  tcp:
    addr: 8.8.8.8:53
    timeout: 10s
  udp:
    addr: 8.8.4.4:53
    timeout: 10s
  tls:
    addr: 1.1.1.1:853
    timeout: 4s
    sni: cloudflare-dns.com
    insecure: false
  https:
    addr: 1.1.1.1:443
    timeout: 4s
    sni: cloudflare-dns.com
    insecure: false
`

**Comment by shunia** [comment]
哈哈哈哈一样的问题：
- 用的acme证书
- 服务器`listen: :443`
- 启动log一切正常
- `netstat`看根本没有443端口占用

**Comment by tobyxdd** [comment]
http inbound 端口错了，跑到 socks5 的了

**Comment by Biaogo94** [comment]
> http inbound 端口错了，跑到 socks5 的了

这个教程，v2rayN的配置就是到socks5端口的

**Comment by catcheru** [comment]
Is the problem solved?

**Comment by Biaogo94** [comment]
> Is the problem solved?

Not yet...

**Comment by catcheru** [comment]
1. Make sure the server hysteria has root privileges

**Comment by shunia** [comment]
> I seem to have solved the problem.
> 
>     1. Make sure the server hysteria has root privileges
> 
>     2. Make sure the udp ingress  rule in the server's security list is turned on.

+1哈，应该和我一样是Oracle吧，最终解决办法是在Oracle的网络设置里打开443的upd ingress。

Same here, if you are on Oracle don't forget to add an ingress rule for 443 udp.

**Comment by Biaogo94** [comment]
> > I seem to have solved the problem.
> > ```
> > 1. Make sure the server hysteria has root privileges
> > 
> > 2. Make sure the udp ingress  rule in the server's security list is turned on.
> > ```
> 
> +1哈，应该和我一样是Oracle吧，最终解决办法是在Oracle的网络设置里打开443的upd ingress。
> 
> Same here, if you are on Oracle don't forget to add an ingress rule for 443 udp.

![Uploading image.png…]()

我这样设置了，还是不行

**Comment by shunia** [comment]
> > > I seem to have solved the problem.
> > > ```
> > > 1. Make sure the server hysteria has root privileges
> > > 
> > > 2. Make sure the udp ingress  rule in the server's security list is turned on.
> > > ```
> > 
> > 
> > +1哈，应该和我一样是Oracle吧，最终解决办法是在Oracle的网络设置里打开443的upd ingress。
> > Same here, if you are on Oracle don't forget to add an ingress rule for 443 udp.
> 
> ![image](https://user-images.githubusercontent.com/44315262/269953652-d758c983-52b6-4349-9100-49fd38b94d91.png)
> 
> 我这样设置了，还是不行

那有没有可能你还和我一样用的是ubuntu22+？那就需要在机器上 `sudo ufw allow 443 ; sudo ufw enable`

**Comment by xiaosaaaa** [comment]
我的之前都是正常的，用了BitTorrent之后会出现这个问题。

**Comment by us254** [comment]
ensuring the server has `root` privileges and that the `UDP ingress rule` in the `server's security list` is turned on.

If you're using `Oracle`,  adding an `ingress rule for port 443 in Oracle's network settings`. Additionally, if you're using Ubuntu 22 or later, you might need to allow port 443 on your machine with the command `sudo ufw allow 443` and then enable it with `sudo ufw enable`.

**Comment by ModulanteHYL** [comment]
我的已经解决了
昨天刚部署的hysteria2，也是跟着不良林的步骤弄的，过了一晚上，今天再看v2rayN就各种refused it了，报错跟你的一模一样。

1. 重启电脑，如果重启电脑能解决，说明是进程占用端口问题
2. 重启电脑也解决不了的，先确定服务端没问题后，去到hysteria客户端存放的目录，用cmd运行hysteria，查看报错信息来推断配置哪里有问题。记得运行前先把配置文件放到hysteria目录下，命名为config.yml

我遇到的问题是server配置的ip和域名的问题，我发现hysteria服务端如果用的是ca证书，那客户端的server就不能是ip:端口格式，不然会报错说客户端初始化失败，得改成域名:端口格式。别人我不知道，我用ip就报错，改域名后好了

**Comment by AHGGG** [comment]
我开启全部端口就好了, 最后发现是UDP的443只要放开就行

**Comment by sggtong1** [comment]
请问解决了吗？遇到同样的问题折腾了很久还是不行
