### ISSUE TITLE
Does hysteria support multiple network cards? Similar to mptcp. Or is it mpquic?

### ISSUE THREAD

**Issue by suyuan168** [apernet/hysteria#711]
Does hysteria support multiple network cards? Similar to mptcp.
Or is it mpquic?

**Comment by tobyxdd** [comment]
Multipath QUIC is indeed a thing apparently (https://datatracker.ietf.org/doc/draft-ietf-quic-multipath/), but it's not yet supported by any QUIC implementation as far as I know. We will have it when quic-go adds it.
