### ISSUE TITLE
不知道什么原因实在是无法正常使用找个大佬

### ISSUE THREAD

**Issue by wanxiaochao** [apernet/hysteria#712]
我的服务端配置文件
listen: :6379
tls:
  cert: /server.crt 
  key: /server.key 
auth:
  type: password
  password: ********************
masquerade:
  type: proxy
  proxy:
    url: https://pan.aaaab3n.moe/
    rewriteHost: true
resolver:
  type: udp
  tcp:
    addr: 8.8.8.8:53 
    timeout: 4s 
  udp:
    addr: 8.8.4.4:53 
    timeout: 4s
  tls:
    addr: 1.1.1.1:853 
    timeout: 10s
    sni: cloudflare-dns.com 
    insecure: false 
  https:
    addr: 1.1.1.1:443 
    timeout: 10s
    sni: cloudflare-dns.com
    insecure: false 
bandwidth:
  up: 200 mbps
  down: 200 mbps
outbounds:
  - name: v4_only
    type: direct
    direct:
      mode: 4
  - name: v6_only
    type: direct
    direct:
      mode: 6
  - name: zhuzhai_proxy
    type: socks5
    socks5:
      addr: **********:***
      username: **********
      password: **********
acl:
  inline: 
    - zhuzhai_proxy(whoer.net)
    - zhuzhai_proxy(tiktok.com)
    - zhuzhai_proxy(*.tiktok.com)
    - zhuzhai_proxy(openai.com)
    - zhuzhai_proxy(*.openai.com)
    - reject(all, udp/443)
    - reject(all, tcp/25)
    - reject(geoip:cn)
    - reject(geoip:kp)
    - direct(all)

客户端配置
server:***********:20000-30000
auth: ***********

bandwidth:
  up: 200 mbps
  down: 200 mbps
  
tls:
  sni:***********
  insecure: false

socks5:
  listen: 127.0.0.1:10808
http:
  listen: 127.0.0.1:10809

v2rayn中有很多下面这种失败的日志

2023-09-26T10:06:04+08:00	[31mERROR[0m	HTTP CONNECT error	{"addr": "127.0.0.1:28953", "reqAddr": "api.codelife.cc:443", "error": "dial error: rejected"}

2023-09-26T10:06:25+08:00	[31mERROR[0m	HTTP CONNECT error	{"addr": "127.0.0.1:28986", "reqAddr": "www.googleadservices.com:443", "error": "read tcp 127.0.0.1:10809->127.0.0.1:28986: wsarecv: An established connection was aborted by the software in your host machine."}

**Comment by tobyxdd** [comment]
你发的第一条日志是 `api.codelife.cc` 匹配上 ACL 里哪条规则被拒绝了，第二条是你浏览器关闭了一个连接，没看出来有什么错误。无法正常使用是怎么无法正常使用法

**Comment by wanxiaochao** [comment]
打开网站很卡，总是没断网，speedtest.net测速也没法测
