### ISSUE TITLE
ignoreClientBandwidth可能不能正确工作

### ISSUE THREAD

**Issue by CCCAUCHY** [apernet/hysteria#715]
**描述问题**
设置ignoreClientBandwidth: true并删除双方的bandwidth配置后, 只有server->client表现出正确的bbr行为(用iftop查看, server端发送速率与client接收速率差不多), 而client->server似乎直接套用了brutal和bandwidth默认值1g(见截图)

**如何复现**
speedtest.net测速

**预期行为**
任务管理器显示的发送速率应该与浏览器看到的差不多

**日志**
无有价值的日志

**设备和操作系统**
Windows 22H2

**额外信息**
![image](https://github.com/apernet/hysteria/assets/55306290/7b4d0366-7152-42cd-a39f-2785ba330843)

**Comment by tobyxdd** [comment]
确实能够复现，正在调查原因。并不是因为用了 Brutal，Brutal 也不存在什么 "默认值 1g"，不写带宽一定就是用 BBR，这个问题在于 BBR 的实现有 bug
