### ISSUE TITLE
TCP error

### ISSUE THREAD

**Issue by darkaaa** [apernet/hysteria#726]
It was working fine yesterday,but today it had tcp error problem.

Oct 04 08:06:41 localhost systemd[1]: Started Hysteria Server Service (config.yaml).
Oct 04 08:06:41 localhost hysteria[3504]: 2023-10-04T08:06:41+08:00        INFO        server mode
Oct 04 08:06:41 localhost hysteria[3504]: 2023-10-04T08:06:41+08:00        INFO        server up and running
Oct 04 08:06:56 localhost hysteria[3504]: 2023-10-04T08:06:56+08:00        INFO        client connected        {"addr": "123.32.122.213:23061", "id": "user", "tx": 39321600}
Oct 04 08:07:36 localhost hysteria[3504]: 2023-10-04T08:07:36+08:00        ERROR        TCP error        {"addr": "123.32.122.213:23061", "id": "user", "reqAddr": "abcgames.com:443", "error": "resolve error: lookup abcgames.com on 205.185.112.69:53: read udp x.x.x.x:36026->205.185.112.69:53: i/o timeout"}
Oct 04 08:07:57 localhost hysteria[3504]: 2023-10-04T08:07:57+08:00        ERROR        TCP error        {"addr": "123.32.122.213:23061", "id": "user", "reqAddr": "abcgames.com:443", "error": "resolve error: lookup abcgames.com on 205.185.112.69:53: read udp x.x.x.x:57206->205.185.112.69:53: i/o timeout"}
Oct 04 08:08:18 localhost hysteria[3504]: 2023-10-04T08:08:18+08:00        ERROR        TCP error        {"addr": "123.32.122.213:23061", "id": "user", "reqAddr": "abcgames.com:443", "error": "resolve error: lookup abcgames.com on 205.185.112.69:53: read udp x.x.x.x:47919->205.185.112.69:53: i/o timeout"}
Oct 04 08:08:38 localhost hysteria[3504]: 2023-10-04T08:08:38+08:00        ERROR        TCP error        {"addr": "123.32.122.213:23061", "id": "user", "reqAddr": "abcgames.com:443", "error": "resolve error: lookup abcgames.com on 205.185.112.69:53: read udp x.x.x.x:35978->205.185.112.69:53: i/o timeout"}
Oct 04 08:09:04 localhost hysteria[3504]: 2023-10-04T08:09:04+08:00        ERROR        TCP error        {"addr": "123.32.122.213:23061", "id": "user", "reqAddr": "contile-images.services.mozilla.com:443", "error": "resolve error: lookup contile-images.services.mozilla.com on 205.185.112.69:53: read udp x.x.x.x:36590->205.185.112.69:53: i/o timeout"}
Oct 04 08:09:24 localhost hysteria[3504]: 2023-10-04T08:09:24+08:00        ERROR        TCP error        {"addr": "123.32.122.213:23061", "id": "user", "reqAddr": "contile-images.services.mozilla.com:443", "error": "resolve error: lookup contile-images.services.mozilla.com on 205.185.112.69:53: read udp x.x.x.x:42285->205.185.112.69:53: i/o timeout"}

**Comment by darkaaa** [comment]
What the hell, it works again. So confused.

**Comment by tobyxdd** [comment]
This simply means the DNS server you were using was down. Not a bug.
