### ISSUE TITLE
whatsapp call disconnect

### ISSUE THREAD

**Issue by boss1819** [apernet/hysteria#731]
**Describe the bug**
whatsapp call from ios/shadowrocket (udp relay working) works for some seconds, then voice stops on receiving side, then call breaks.

**To Reproduce**
make a whatsapp call from a device connected to hysteria server with no censorship restrictions, call works for ~20 seconds then call breaks.

**Expected behavior**
call continues as long as client to server connection not interrupted

**Logs**
will be provided in case needed and issue not known already

**Device and Operating System**
ios 16.7 
shadowtocket 2.2.37
hysteria server v2.0.4

**Additional context**
tested with different outbounds
socks5: never works
direct: works but breaks as described above

**Comment by tobyxdd** [comment]
You should probably raise this issue with Shadowrocket instead unless you can confirm the same problem exists on the official client

**Comment by boss1819** [comment]
thanks. you are probably right. I think the issue is in general with udp, because speedtest gives very low results and breaks occasionally in upload.
I tried another setup:

ios <--shadowrocket socks5--> local_server_hysteria_client <--hysteria2--> vps_hysteria_server

in this case, speedtest works fine and whatsapp call works fine. unfortunately this is not a very portable solution. I see there is an issue for a lack of a reliable client on ios, which is a very important use case.
clash/stash still does not support hysteria2, tested it
singbox not well documented config for ios and seems still experimental
streisand, seems to have very basic implementation and poor performance, worse than shadowrocket

thanks

**Comment by tobyxdd** [comment]
It was indeed a bug on Shadowrocket's end, and he claimed to have fixed it (in the latest testflight version). Can you confirm this?

**Comment by boss1819** [comment]
Good news thanks for confirmation. I think I need a redeem code for that which i dont know. I hope they can release the official version soon, looking forward to test it

**Comment by boss1819** [comment]
Just to update you. After long wait, they released the official version today. Unfortunately still the same issue with udp. I moved to sing-box. It is a bit more difficult to setup for the first time, but works as expected.

**Comment by cute** [comment]
> Just to update you. After long wait, they released the official version today. Unfortunately still the same issue with udp. I moved to sing-box. It is a bit more difficult to setup for the first time, but works as expected.

Could you please provide the diagnostic VPN logs?
You can enable logging in Shadowrocket by going to Settings > Diagnostics > Enable Logging.
Please enable logging and send the VPN logs to buginapp@gmail.com

**Comment by cute** [comment]
> **Describe the bug** whatsapp call from ios/shadowrocket (udp relay working) works for some seconds, then voice stops on receiving side, then call breaks.
> 
> **To Reproduce** make a whatsapp call from a device connected to hysteria server with no censorship restrictions, call works for ~20 seconds then call breaks.
> 
> **Expected behavior** call continues as long as client to server connection not interrupted
> 
> **Logs** will be provided in case needed and issue not known already
> 
> **Device and Operating System** ios 16.7 shadowtocket 2.2.37 hysteria server v2.0.4
> 
> **Additional context** tested with different outbounds socks5: never works direct: works but breaks as described above

Please goto Shadowrocket - Settings - UDP - Increase Timeout to 300

**Comment by boss1819** [comment]
> > Just to update you. After long wait, they released the official version today. Unfortunately still the same issue with udp. I moved to sing-box. It is a bit more difficult to setup for the first time, but works as expected.
> 
> Could you please provide the diagnostic VPN logs? You can enable logging in Shadowrocket by going to Settings > Diagnostics > Enable Logging. Please enable logging and send the VPN logs to [buginapp@gmail.com](mailto:buginapp@gmail.com)

thank you for your attention and reply. let me actually correct my previous statement to provide you better feedback to fix the problem. the original issue of whatsapp call disconnect is fixed. also another symptom was that speedtest upload was failing in the middle, that is also fixed.

currently however I still see much lower upload speed than maximum expected (1/5). probably an indirect effect of that is that I had less quality in whatsapp voice/video calls, compared to other client SW using the same hy2 server. 
in some tests however the speed of upload gets higher. I think could be something in the BBR implementation, not sure...

I believe you will be able to test this very easily with an ios device and speedtest app. 
thanks
