### ISSUE TITLE
acme client error

### ISSUE THREAD

**Issue by Darvyn** [apernet/hysteria#734]
**Describe the bug**
![image](https://github.com/apernet/hysteria/assets/26133254/190eb356-3c36-487b-ad19-8ab869a8aff5)

**To Reproduce**
Restart the service, always get the acme error as in the picture above, DNS is ok, and the 80 443 ports are open

**Device and Operating System**
ubuntu

**Comment by tobyxdd** [comment]
Please send full logs so we can see what the error was. This is most likely not a bug but a misconfiguration.

**Comment by gogoing1092** [comment]
出现同样问题 acme签名限制

**Comment by Darvyn** [comment]
> 出现同样问题 acme签名限制

请问解决了吗？

**Comment by nobut** [comment]
我也是这个问题

**Comment by Darvyn** [comment]
确实是配置的问题，我这里是因为nginx服务占用了80端口，导致了acme没办法验证
