### ISSUE TITLE
ERROR TCP error

### ISSUE THREAD

**Issue by zfygood** [apernet/hysteria#736]
hysteria[1622245]: 2023-10-11T07:27:17+01:00        ERROR        TCP error        {"addr": "115.204.209.57:63739", "id": "user", "reqAddr": "www.youtube.com:443", "error": "readfrom tcp4 xxx.xxx.xxx.xxx:60386->74.125.200.93:443: stream 788 canceled by remote with error code 0"}
 hysteria[1622245]: 2023-10-11T07:27:42+01:00        ERROR        TCP error        {"addr": "115.204.209.57:63739", "id": "user", "reqAddr": "rr2---sn-npoe7ns7.googlevideo.com:443", "error": "readfrom tcp4 xxx.xxx.xxx.xxx:40860->173.194.51.103:443: stream 812 canceled by remote with error code 0"}
 
 想请教下这是什么原因？

**Comment by tobyxdd** [comment]
正常现象不是错误
