### ISSUE TITLE
freebsd版本有些bug

### ISSUE THREAD

**Issue by CCCAUCHY** [apernet/hysteria#737]
**描述问题**
不能用ipv4访问, 即使配置写成`Listen: 0.0.0.0:65535`, 也是监听udp46, 只能用ipv6访问
```
root@freebsd:/home/ec2-user # sockstat -l
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     hysteria-f 1212  3  udp46  *:65535               *:*
```
不确定是否有freebsd内置防火墙问题, 在freebsd上直接使用客户端连接也连不上
```
root@freebsd:/home/ec2-user # ./hysteria-freebsd-amd64-avx -c client.yaml
2023-10-11T08:46:29Z    INFO    client mode
2023-10-11T08:46:29Z    FATAL   failed to initialize client     {"error": "connect error: INTERNAL_ERROR (local): write udp [::]:65366->127.0.0.1:65535: sendmsg: invalid argument"}
```
**如何复现**
开启AWS LS 的FreeBSD, 直接下载hy, 配置并启动

**预期行为**
v4能访问

**日志**
无有价值日志, 一点反应都没有

**设备和操作系统**
FreeBSD freebsd 12.4-RELEASE-p6 FreeBSD 12.4-RELEASE-p6 GENERIC  amd64

**额外信息**
无

**Comment by tobyxdd** [comment]
Duplicate of https://github.com/apernet/hysteria/issues/693
