### ISSUE TITLE
New release binary was found virus.

### ISSUE THREAD

**Issue by duskNNNN** [apernet/hysteria#748]
**Describe the bug**
New release binary was found virus which checked by Microsoft Defence.

**To Reproduce**
download `hysteria-windows-amd64-avx.exe` from release page 

**Device and Operating System**
OS: Win11 23H2
CPU: Intel 12400
GPU: NVIDIA 2080TI

**Additional context**
![image](https://github.com/apernet/hysteria/assets/94543546/0bcdaad8-04b2-463d-a90b-3f4258a320ab)

**Comment by tobyxdd** [comment]
What version did you download? I have scanned `hysteria-windows-amd64-avx.exe' from the latest v2.1.0 with MS Defender but it shows no threat found.

**Comment by duskNNNN** [comment]
Both v2.1.0，but check result is different. 
MS, i love you.
![image](https://github.com/apernet/hysteria/assets/94543546/d47c3ca3-789c-4b1a-ae58-e71e3945c4d4)
