### ISSUE TITLE
a6da40df110f94bd684c720540f034fd1db1f85e

### ISSUE THREAD

**Issue by momohnasirumuri** [apernet/hysteria#751]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by momohnasirumuri** [comment]
Run

**Comment by tobyxdd** [comment]
> Run

https://youtu.be/mw2kKyJu9gY?si=dlSLBRm4o2gHpJP-&t=130
