### ISSUE TITLE
Request this tool to be executed directly instead of in the cmd.exe shell

### ISSUE THREAD

**Issue by kx001001** [apernet/hysteria#762]
**直接运行工具得到如下提示：**
This is a command line tool.
You need to open cmd.exe and run it from there.

运行环境： Windows 11

**你的功能请求是否与某个问题有关？**
工具无法直接运行，必须在cmd或其他shell里运行，希望与Hysteria1代保持一致，能够直接运行

**描述你希望的解决方案**
与Hysteria1保持一致，能够直接运行

**有没有其他替代方案**
暂时没有

**额外信息**
无

**Comment by B1gCarr0t** [comment]
已经更新可用了。
https://github.com/apernet/hysteria/releases/tag/app%2Fv2.1.1
