### ISSUE TITLE
不支持win8吗？

### ISSUE THREAD

**Issue by willsilicon** [apernet/hysteria#763]
**描述问题**
在win8上不行，同样配置和exe在win10上ok，日志显示x509认证错误。证书是acme的。

**如何复现**
.\hysteria-windows-amd64.exe client
config.yaml配置：
server: domain:port
auth: pass
bandwidth: 
  up: 20 mbps
  down: 20 mbps
lazy: true
socks5:
  listen: 0.0.0.0:9080
http:
  listen: 0.0.0.0:9081

**预期行为**
配置socks代理后可以访问Google

**日志**
2023-10-21T00:22:21+08:00       [31mERROR[0m  SOCKS5 TCP error        {"addr":
 "127.0.0.1:63556", "reqAddr": "accounts.google.com:443", "error": "connect erro
r: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certific
ate signed by unknown authority"}

**设备和操作系统**
x86-64 windows8

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by tobyxdd** [comment]
这只能说明你服务器的证书不在 win8 的信任列表里

**Comment by haruue** [comment]
如果你用 letsencrypt ， 他们可能会使用 [ISRG Root X2](https://crt.sh/?id=3335562555) 这个根证书为你签发证书。 该根证书自 2020 年 9 月 4 日生效。 

然而很不幸的是， 微软已于已于 2016 年 1 月 12 日终止对 Windows 8 的支持， 在无法进行更新的前提下， 不可能包含该根证书。

这不被视为 hysteria 的 bug 。

**Comment by haruue** [comment]
请提供一下 `winver` 所显示的版本号， 以方便我们进行进一步的验证。

**Comment by willsilicon** [comment]
> 请提供一下 `winver` 所显示的版本号， 以方便我们进行进一步的验证。

不能贴图，手打，windows8.1企业版 版本6.3（内部版本9600） 装的是msdn itellyou上的镜像
