### ISSUE TITLE
v2.1.1版本windows下报挖矿病毒

### ISSUE THREAD

**Issue by forrestsocool** [apernet/hysteria#765]
**描述问题**
[v2.1.1](https://github.com/apernet/hysteria/releases/tag/app%2Fv2.1.1) [hysteria-windows-amd64-avx.exe](https://github.com/apernet/hysteria/releases/download/app%2Fv2.1.1/hysteria-windows-amd64-avx.exe)在windows10下会被WindowsDefender报挖矿病毒，并自动删除exe文件

**如何复现**
1.使用V2rayN调用Hysteria作为第三方客户端，设置好配置, 启动正常使用。
2.重启操作系统，再次启动V2rayN的Hysteria配置，发现启动不了，二进制被windows删除了

**预期行为**
删除挖矿相关代码，或让windows defender不报毒

**日志**
(V2rayN)
[Custom] 新加坡Hysteria
启动服务(2023/10/22 11:47:34)...
2023/10/22 11:47:34 系统代理设置改变
An error occurred trying to start process 'C:\Users\T800\AppData\Local\Programs\v2rayN\bin\hysteria\hysteria.exe' with working directory 'C:\Users\T800\AppData\Local\Programs\v2rayN\guiConfigs'. 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。

(Windows)
![image](https://github.com/apernet/hysteria/assets/3960433/a81164a8-05ab-4709-82b6-706e0c6f33ae)

**设备和操作系统**
windows 10

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by forrestsocool** [comment]
搞错了，报的不是挖矿病毒，是Trojan:Win32/Wacatac.H!ml 这个类型

**Comment by tobyxdd** [comment]
感谢反馈，已经把误报文件上报给 Windows Defender 了
