### ISSUE TITLE
hysteria v2.1.1 windows amd64 avx版被windows defender AM_Delta_Patch_1.399.1119.0拦截

### ISSUE THREAD

**Issue by showgood163** [apernet/hysteria#766]
**描述问题**
hysteria v2.1.1 windows amd64 avx被windows defender AM_Delta_Patch_1.399.1119.0拦截
https://github.com/apernet/hysteria/releases/download/app%2Fv2.1.1/hysteria-windows-amd64-avx.exe

提示病毒类型：HackTool:Win64/Malgent!MSR
按道理HackTool不是病毒，算是误报吧

**如何复现**
下载相应hysteria二进制文件
更新windows defender

**预期行为**
hysteria二进制文件不应该被查杀

**设备和操作系统**
windows 10

**Comment by zazi0001** [comment]
刚遇到，上周下载来没这个问题

**Comment by tobyxdd** [comment]
Analyst comments:

We have determined that the files meet our criteria for malware. At this time the detection will remain in place.

More detailed information about the approach and criteria categories currently used by the Microsoft researchers are available here:
https://docs.microsoft.com/windows/security/threat-protection/intelligence/criteria

Thank you for contacting Microsoft.

反馈给微软以后他们的回复是 Hysteria 符合他们对恶意软件的定义。。所以估计不会解决了
