### ISSUE TITLE
DATAGRAM frame too large

### ISSUE THREAD

**Issue by smukee** [apernet/hysteria#767]
I'm using Hysteria Version:	v2.1.0
The problem is when using it to send Images or Videos over WhatsApp, It won't.
Here are the logs:

> 2023-10-23T09:27:35Z	INFO	client connected	{"addr": "clientip:51769", "id": "user", "tx": 0}
> 2023-10-23T09:27:39Z	ERROR	TCP error	{"addr": "clientip:51769", "id": "user", "reqAddr": "157.240.201.61:5222", "error": "readfrom tcp4 srvaddr:54170->157.240.201.61:5222: PROTOCOL_VIOLATION (local): **DATAGRAM frame too large**"}
> 2023-10-23T09:27:39Z	INFO	client disconnected	{"addr": "clientip:51769", "id": "user", "error": "accepting stream failed: PROTOCOL_VIOLATION (local): **DATAGRAM frame too large**"}

What does "DATAGRAM frame too large" mean ?

**Comment by tobyxdd** [comment]
This is a singbox bug that should have been fixed by now. What version are you using

**Comment by smukee** [comment]
So you're saying it's the client problem?
I'm using this iOS client: https://apps.apple.com/us/app/streisand/id6450534064

**Comment by tobyxdd** [comment]
Yes. Please report to them instead.
