### ISSUE TITLE
能否和caddy共用端口443

### ISSUE THREAD

**Issue by kmephistoh** [apernet/hysteria#768]
```shell
root@tokyo:~# ss -lnup |grep 443
UNCONN 0      0                       *:443             *:*    users:(("caddy",pid=12726,fd=8))
UNCONN 0      0                       *:8443            *:*    users:(("hysteria",pid=12855,fd=3))
root@tokyo:~# caddy version
v2.7.5 h1:HoysvZkLcN2xJExEepaFHK92Qgs7xAiCFydN5x5Hs6Q=
```
新版本的caddy已默认开启http3支持，占用udp 443端口， hysteria 只能选其它端口(8443)，怕8443可能被一些中间防火墙什么的过滤，有什么方式能二者用一个端口443。caddy上有网站在运行，需要http3支持。

**Comment by yyu0378** [comment]
共用443是不可能的，但caddy可以把对应的请求发给hysteria

**Comment by kmephistoh** [comment]
> 共用443是不可能的，但caddy可以把对应的请求发给hysteria
怎么操作，方便给个示例吗？

**Comment by tobyxdd** [comment]
是不行的，caddy 也不可能转发 hysteria。但是可以 caddy 关掉 h3，hysteria 用 proxy 模式反代 caddy 的网站

**Comment by kmephistoh** [comment]
之前用这个xray回落  https://xtls.github.io/document/level-1/fallbacks-with-sni.html#caddy-%E9%85%8D%E7%BD%AE 方案，因为挂在Cloudflare后面，各种问题，不是证书不能自动更新，就是网站挂了

**Comment by kmephistoh** [comment]
> 是不行的，caddy 也不可能转发 hysteria。但是可以 caddy 关掉 h3，hysteria 用 proxy 模式反代 caddy 的网站

caddy上面跑了2个网站，不太想去掉h3支持

**Comment by yyu0378** [comment]
我的方案是，在caddy配置虚拟主机，至针对网站开始http3的支持，转发代理不开启，这样应该是可以的

**Comment by tobyxdd** [comment]
> > 是不行的，caddy 也不可能转发 hysteria。但是可以 caddy 关掉 h3，hysteria 用 proxy 模式反代 caddy 的网站
> 
> caddy上面跑了2个网站，不太想去掉h3支持

用 hysteria 反代就提供 h3 支持了呀，效果是一样的

**Comment by kmephistoh** [comment]
```shell
{
	acme_dns cloudflare xxx
	storage file_system /data/tls
	servers :443 {
		protocols h1 h2 h2c
	}
}
```
```shell
root@tokyo:~# ss -lnp |grep :443
udp   UNCONN 0      0                                               *:443                    *:*    users:(("hysteria",pid=14103,fd=3))                                                                              
tcp   LISTEN 0      4096                                            *:443                    *:*    users:(("caddy",pid=14008,fd=7))     
```
我通过关掉caddy的h3处理了， 刚好cloudflare 的CDN带http3支持。

**Comment by B1gCarr0t** [comment]
> ```shell
> {
> 	acme_dns cloudflare xxx
> 	storage file_system /data/tls
> 	servers :443 {
> 		protocols h1 h2 h2c
> 	}
> }
> ```
> 
> ```shell
> root@tokyo:~# ss -lnp |grep :443
> udp   UNCONN 0      0                                               *:443                    *:*    users:(("hysteria",pid=14103,fd=3))                                                                              
> tcp   LISTEN 0      4096                                            *:443                    *:*    users:(("caddy",pid=14008,fd=7))     
> ```
> 
> 我通过关掉caddy的h3处理了， 刚好cloudflare 的CDN带http3支持。

好像cf的cdn不支持h3回源

**Comment by tobyxdd** [comment]
https://v2.hysteria.network/zh/docs/misc/CDN/
