### ISSUE TITLE
v2.1.1被Windows 10内置杀毒报了

### ISSUE THREAD

**Issue by UJX6N** [apernet/hysteria#769]
**描述问题**
Win 10内置微软杀毒报HackTool:Win64/Malgent!MSR

**如何复现**
在启用微软内置杀毒的机器下载v2.1.1的hysteria-windows-amd64-avx.exe

**预期行为**
最好不被报毒

**日志**

**设备和操作系统**
Windows 10 22H2

**额外信息**

**Comment by tobyxdd** [comment]
Duplicate of https://github.com/apernet/hysteria/issues/766
