### ISSUE TITLE
是否存在对特定ip的udp阻断？

### ISSUE THREAD

**Issue by B1gCarr0t** [apernet/hysteria#773]
我有两台vps，用了相同的hy2配资文件；
一台位于美国的vps可以正常使用Hysteria2；
另一台位于新加坡的一直都正常的，刚刚突然就无法连接了，而且仅限于相同局域网下的设备，如果用5G连接就没问题；
刚开始考虑是家宽被UDP阻隔了，但是如果是UDP阻隔，我同样配置的美国vps又不会被阻隔，同样都是443端口；
也不是被墙了，因为使用其他的网络接入，是可以直达的，甚至我用这个无法连接的端口仍然可以正常ping通vps；
那是否存在对特定ip的udp阻断呢？
我是被运营商阻断了还是被云服务阻断了？

**Comment by tobyxdd** [comment]
这里不是运营商工单系统 没法回答你这种问题

**Comment by adzcsx2** [comment]
现在似乎大面积出现这个问题。我3vps，美国一个，香港2个。香港的经常出现，美国偶尔出现。

**Comment by DavidYaonanZhu** [comment]
同样问题
