### ISSUE TITLE
QUIC协议疑问

### ISSUE THREAD

**Issue by geekotaku** [apernet/hysteria#774]
**描述问题**
Docker容器中跑的客户端，在路由器端抓包，使用wireshark查看。
和服务端显示的连接协议全部都是UDP，没有一个QUIC，抓到的其他包有正常显示QUIC的。
这个算正常吗？还是需要求特别的设置？

**预期行为**
显示QUIC协议

**额外信息**
服务端配置：
acme:
  domains:
    - abc.com
  email: media@abc.com

auth:
  type: password
  password: abc

masquerade:
  type: proxy
  listenHTTP: :80
  listenHTTPS: :443
  forceHTTPS: true
  proxy:
    url: https://abc.com/
    rewriteHost: true

**Comment by tobyxdd** [comment]
我这里正常。这个就算是 bug 也是 Wireshark 的 bug 吧

**Comment by xymeng16** [comment]
根据https://stackoverflow.com/questions/63290913/wireshark-doesnt-show-quic-protocol，手动在wireshark中设置quic的端口即可。
