### ISSUE TITLE
请教作者带宽设置问题

### ISSUE THREAD

**Issue by itdsgithub** [apernet/hysteria#779]
首先感谢作者文档写的很详细，但是带宽设置我还是有点不明白。
我们就说实际场景，如果要利用到Brutal协议功能，就需要服务器+客户端同时设置数值。
对于大部分人和大多数的服务器来说，服务器带宽上行和下行基本都是1gbp，那就服务器配置文件里加进去就行。
对于客户端，假如我日常网络带宽是500m，那客户端配置文件里，上行下行都设置500m就行了吗？
假如公司500m带宽，回家家里才200m带宽，那原本设置的500m的参数，回家上网时候，又拖慢速度或者浪费资源了？

原文：Brutal 如果带宽设置低于实际最大值也能正常运行；相当于限速。重要的是不要将其设置得高于实际最大值，否则会因为补偿机制导致连接速度慢、不稳定，且浪费流量。

**Comment by tobyxdd** [comment]
> 我们就说实际场景，如果要利用到Brutal协议功能，就需要服务器+客户端同时设置数值。

首先这个就不对，服务端不需要设置数值

如果你的网络是 500m 对等就都设 500m。回家不一样的话是得用两个配置

**Comment by itdsgithub** [comment]
> > 假如公司500m带宽，回家家里才200m带宽，那原本设置的500m的参数，回家上网时候，又拖慢速度或者浪费资源了？
> 
> 对，因为这会以 2.5 (500/200) 倍速发包

那这个有点不太智能呢，公司宽带，家里宽带，平时手机流量上网，都三个不同带宽场景了。
请教作者，那我统一设置成500m，影响大吗？或者在保证高效连接的前提下，有什么建议吗？

**Comment by tobyxdd** [comment]
可以不设速度用 BBR

**Comment by itdsgithub** [comment]
> 可以不设速度用 BBR

好的，我换成不设速的，用一阵试试

**Comment by yjd** [comment]
最近使用上，非上网高峰用BBR比较稳反而Brutal协议会降速，在晚上高峰丢包时用Brutal协议更好yt的缓冲进度条明显更快，但测试过几次，Brutal协议用久了就被QOS几率比较大。目前干脆直接用BBR了
