### ISSUE TITLE
Using UDP connection only from listen port . 

### ISSUE THREAD

**Issue by ellahmezar** [apernet/hysteria#784]
Hi my dear friend .
Is it a way to use UDP Connection (Not TCP) from listening port ?
I found that if I put "disableUDP" in "true" mode , Hysteria will listen to only one port ( listen port ) , but the Connection is in TCP mode .
What should I do ?
Many thanks 
![Screenshot_20231029_125224_Samsung Internet](https://github.com/apernet/hysteria/assets/129280842/d39b40ef-fcce-421f-99da-ea637a3bd057)

**Comment by tobyxdd** [comment]
Are you saying you want a "disableTCP" mode where the server can only forward UDP traffic? This has nothing to do with what port or protocol the Hysteria server listens on btw. Not sure if I understand what you are asking or if you understand what this option does
