### ISSUE TITLE
分流解锁流媒体出错

### ISSUE THREAD

**Issue by twamix** [apernet/hysteria#786]
**描述问题**
用hy2分流功能解锁流媒体，PC端用nekobox，正常解锁，安卓端用nekobox就解锁不了

**如何复现**
outbounds:
  - name: my_outbound 
    type: direct
  - name: some_proxy
    type: socks5
    socks5:
      addr: 27.0.x.x
      username: 
      password: 

acl:
  file: /etc/hysteria/some.txt

some.txt:
some_proxy(ipinfo.io)

PC访问ipinfo.io显示ip是27.0.x.x，手机端访问ipinfo.io显示ip还是原来的vps的ip

请问这个是怎么了？

总不至于是nekobox的问题吧，同样的nekobox用x-ui的方式解锁流媒体就不会出现这样的情况。

**Comment by tobyxdd** [comment]
应该就是 nekobox 的问题，看下 log nekobox 发送的请求用的是域名还是解析后的 IP，IP 匹配不上域名规则

**Comment by wanxiaochao** [comment]
nekobox打开fakedns模式就可以了

**Comment by twamix** [comment]
> nekobox打开fakedns模式就可以了

打开fakedns模式的确是可以解锁了，但是奈飞app打开缺看不了电影啦

**Comment by LiXianYua** [comment]
确实是nekobox的问题，我用Clash Meta for Android没有这个问题，用nekobox就会
