### ISSUE TITLE
Hysteria2突然无法连接, TUIC还是能用

### ISSUE THREAD

**Issue by Doutianbao** [apernet/hysteria#787]
RT

**Comment by leic4u** [comment]
你可以补充下服务端配置、客户端配置、服务端日志、客户端报错信息。

光是「无法连接」一句话没有人能帮你判断是什么问题。

**Comment by npc-25** [comment]
同样突然无法连接了，  之前一直可以使用。

**Comment by npc-25** [comment]
vps使用非hy 方式还是可以正常使用，  hy突然无法使用了，pc、手机端都无法连接

**Comment by WilliamCui31** [comment]
> vps使用非hy 方式还是可以正常使用， hy突然无法使用了，pc、手机端都无法连接

知道上面原因吗？解决了吗

**Comment by WilliamCui31** [comment]
> vps使用非hy 方式还是可以正常使用， hy突然无法使用了，pc、手机端都无法连接

找到原因了吗？解决了吗？

**Comment by npc-25** [comment]
> > VPS使用非hy 方式还是可以正常使用， hy突然无法使用了，PC、手机端都无法连接
> 
> 找到原因了吗？解决了吗？

貌似是装了很多 不知道某个引起的冲突，删掉重新装就好了
