### ISSUE TITLE
日志输出问题

### ISSUE THREAD

**Issue by wansenlyt** [apernet/hysteria#789]
**描述问题**
hysteria2.1.1版
问题一：Debian11 VPS服务端、windows10客户端和android13客户端日志输出级别默认为info，而实际输出级别好像为error。均为自己用命令号启动。
问题二：windows10客户端直接在CMD内输入启动命令如： .\hysteria-windows-amd64-avx.exe -c config.yaml > C:\Temp\hyts.log，则日志不会输出到 C:\Temp\hyts.log，而是还在CMD窗口内显示默认日志级别。

**额外信息**
以上问题不影响使用，可对软件问题的测试造成一定麻烦；当然，这个问题也不是什么非常重要或紧急的，若方便时请查看下。感谢开发者的辛勤付出，谢谢！

**Comment by wansenlyt** [comment]
再报告一个关于android客户端上一个问题：当用命令行启动，如.\hysteria-android-arm64 -c config.yam时，配置文件内如果是域名，提示错误:no such host；将域名改为ip则正常。

**Comment by zazi0001** [comment]
info的信息量应该是包含error吧

**Comment by tobyxdd** [comment]
> 而实际输出级别好像为error

你的意思是实际不会输出 info，只显示 error？没遇到过这个问题

> 则日志不会输出到 C:\Temp\hyts.log

尝试 `> log.txt 2>&1`

**Comment by volansz** [comment]
同样的情况，只有 error 有日志。怎么从客户端启动参数中添加日志级别的参数呢？

**Comment by wansenlyt** [comment]
> 同样的情况，只有 error 有日志。怎么从客户端启动参数中添加日志级别的参数呢？

我目前在用的方法：

VPS如果是按官方脚本搭建的，编辑/etc/systemd/system/clash.service,添加：
......
[Service]
......
StandardOutput=append:/var/log/hyserver.log
[Install]
......

VPS如果是命令行启动：
./hysteria-linux-amd64 server --config ./hyserver.yaml > /var/log/hyserver.log 2>&1 & 

win10及以上系统：
.\hysteria-windows-amd64.exe -c hysteria.yaml -l debug 2> X:\xxx\hysteria.log

android13及以上系统命令行启动：
./hysteria-android-arm64 -c ./hysteria.yaml -l debug > /xxx/hyserver.log 2>&1 & 

以上命令供参考，注意路径需要根据你的情况进行修改。
