### ISSUE TITLE
TUN模式什么时候加入？

### ISSUE THREAD

**Issue by cloudheap** [apernet/hysteria#790]

**Comment by wanxiaochao** [comment]
为什么到处都在让加这个TUN模式...无论是核心还是gui工具，都在让加TUN...

**Comment by kastanientorte** [comment]
因为TUN是一定程度上能实现完美代理的解决方案

**Comment by wanxiaochao** [comment]
但是sb之类的客户端不是已经有了

**Comment by its0ka** [comment]
sb = sing-box? sing-box tun has issues and dev doesn't care, he banned me because i asked why he closed my issue

**Comment by wanxiaochao** [comment]
> sb = sing-box? sing-box tun has issues and dev doesn't care, he banned me because i asked why he closed my issue

Yes, sb = single-box, the developer of sb heard that is the case, haha.

**Comment by oborrm** [comment]
> sb = sing-box? sing-box tun has issues and dev doesn't care, he banned me because i asked why he closed my issue

Same here. The developer of SB may suffer from mental illness. He banned me because I was helping answer some of the questions the other guy asking.

**Comment by yueguobin** [comment]
尝试esp over hy2 udp proxy 实现ip tunnel？
