### ISSUE TITLE
[请求帮助]hysteria2如何检测端口被封？

### ISSUE THREAD

**Issue by adzcsx2** [apernet/hysteria#794]
因为最近经常发现连不上的情况，之前换了端口又可以连接上了，但是今天换什么端口都没用，所以如何判断端口被封还是配置问题。

连不上的时候，v2ray日志会出现：
inbound/http[http]: process connection from 127.0.0.1:57313: dial tcp 127.0.0.1:1080: connectex: No connection could be made because the target machine actively refused it.
之前用UDP测试过端口，无论是能连上还是不能连上udp连接测试都是失败的。可能是我方法的问题，希望哪个哥们能告诉一个方法测试端口问题。谢谢！
ps：我用的默认配置，平时能正常使用，偶尔不能使用之后改端口之后也能使用，但是今天不行了。有配置20000-50000的端口跳跃。

**Comment by muziling** [comment]
服务端iptables的问题
