### ISSUE TITLE
请问怎么设置hysteria二级代理

### ISSUE THREAD

**Issue by YaYaSilverwing** [apernet/hysteria#795]
我想在一台能够解锁netflix但是ip被封的落地VPS上搭建hysteria节点，然后将一台ip没被封的中转VPS上访问netflix的请求走落地机的hysteria节点，其他访问请求仍然走中转VPS。请问怎么设置中转VPS的ACL和出站规则呢？因为是代码小白，虽然作者写的文档很详细，但是我尝试好多次搭建二级代理失败后只好来gittub求助了。谢谢！

**Comment by tobyxdd** [comment]
你应该在 IP 没被封的机器上搭建 hysteria 吧，IP 被封但能解锁 netflix 的机器上跑个 socks5/http proxy 然后用 ACL outbound 发送 Netflix 流量到上面

**Comment by YaYaSilverwing** [comment]
> 你应该在 IP 没被封的机器上搭建 hysteria 吧，IP 被封但能解锁 netflix 的机器上跑个 socks5/http proxy 然后用 ACL outbound 发送 Netflix 流量到上面

谢谢，已经 

> 假设你这台中转VPS作为能够解锁netflix但是ip被封的落地VPS上的hysteria的服务器端的hysteria客户端，然后最简单的办法是在这台中转VPS上装xray-core做分流，访问netflix的所有流量outbound到本机hysteria客户端的socks5 inbound，其他访问流量在本地中转VPS直接出局
> 
> 你作为用户访问这台中转VPS上的xray就好了，至于xray配置什么访问协议你随意

谢谢！

**Comment by YaYaSilverwing** [comment]
> 你应该在 IP 没被封的机器上搭建 hysteria 吧，IP 被封但能解锁 netflix 的机器上跑个 socks5/http proxy 然后用 ACL outbound 发送 Netflix 流量到上面

谢谢，我按照这种方法已经成功解锁Netflix了。不过在设置acl的过程中我发现了两个问题，请问是哪里有问题吗？不好意思，打扰了。
（1）按照官方文档，acl支持inline和file两种设置方式。我在config.yaml中按inline的格式设置acl规则时没有任何问题，但是如果是按file格式设置就会导致hysteria2服务出错。

------------------------------------------------------------------------------------------------------------------
inline格式设置代码：

outbounds:
  - name: out_1 
    type: direct
  - name: some_proxy
    type: socks5
    socks5:
      addr:  
      username:  
      password: 

acl:
  inline:
    - some_proxy(*.netflix.com)
    - some_proxy(*.netflix.com.edgesuite.net)
    - some_proxy(*.netflix.net)
    - some_proxy(*.netflixdnstest.com)
    - some_proxy(*.netflixdnstest0.com)
    - some_proxy(*.netflixdnstest1.com)
    - some_proxy(*.netflixdnstest2.com)
    - some_proxy(*.netflixdnstest3.com)
    - some_proxy(*.netflixdnstest4.com)
    - some_proxy(*.netflixdnstest5.com)
    - some_proxy(*.netflixdnstest6.com)
    - some_proxy(*.netflixdnstest7.com)
    - some_proxy(*.netflixdnstest8.com)
    - some_proxy(*.netflixdnstest9.com)
    - some_proxy(*.fast.com)
    - direct(all) 

------------------------------------------------------------------------------------------------------------------
file格式设置代码：

outbounds:
  - name: out_1 
    type: direct
  - name: some_proxy
    type: socks5
    socks5:
      addr:  
      username:  
      password: 

acl:
  file: /etc/hysteria/acl.txt

alc.txt文档中的代码：
v4_only(*.google.*)
some_proxy(*.ipinfo.io)
some_proxy(*.netflix.com)
 some_proxy(*.netflix.com.edgesuite.net)
some_proxy(*.netflix.net)
some_proxy(*.netflixdnstest.com)
some_proxy(*.netflixdnstest0.com)
some_proxy(*.netflixdnstest1.com)
some_proxy(*.netflixdnstest2.com)
some_proxy(*.netflixdnstest3.com)
some_proxy(*.netflixdnstest4.com)
some_proxy(*.netflixdnstest5.com)
some_proxy(*.netflixdnstest6.com)
some_proxy(*.netflixdnstest7.com)
some_proxy(*.netflixdnstest8.com)
some_proxy(*.netflixdnstest9.com)
some_proxy(*.fast.com)
direct(all) 

------------------------------------------------------------------------------------------------------------------

（2）按照官方文档设置geosite格式的acl规则也会出现错误。
acl:
   inline:
      - some_proxy(geosite:netflix)

**Comment by tobyxdd** [comment]
域名格式错误，是 `*.netflixdnstest.com`

**Comment by tobyxdd** [comment]
> 但是如果是按file格式设置就会导致hysteria2服务出错。

什么错误？发日志上来

**Comment by szdosar** [comment]
v2.2支持GeoSite后我直接这样用方便多了。
`acl:
  inline:
    - some_proxy(geosite:netflix)`
