### ISSUE TITLE
关于ACL里域名的写法问题

### ISSUE THREAD

**Issue by toyo2333** [apernet/hysteria#802]
我希望将openai的请求走一个warp的socks5代理出站，看了文档写法，我不得不给每个域名写两行，一个是带通配符的一个是不带的。

 ```
   - warp_out(*.ai.com)
    - warp_out(ai.com)
    - warp_out(*.auth0.com)
    - warp_out(auth0.com)
    - warp_out(*.challenges.cloudflare.com)
    - warp_out(challenges.cloudflare.com)
    - warp_out(*.client-api.arkoselabs.com)
    - warp_out(client-api.arkoselabs.com) 
    - warp_out(*.events.statsigapi.net)
    - warp_out(events.statsigapi.net)
    - warp_out(*.featuregates.org)
    - warp_out(featuregates.org)
    - warp_out(*.identrust.com)
    - warp_out(identrust.com)
    - warp_out(*.intercom.io)
    - warp_out(intercom.io)
    - warp_out(*.intercomcdn.com)
    - warp_out(intercomcdn.com)
    - warp_out(*.openai.com)
    - warp_out(openai.com)
    - warp_out(*.openaiapi-site.azureedge.net)
    - warp_out(openaiapi-site.azureedge.net)
    - warp_out(*.sentry.io)
    - warp_out(sentry.io)
    - warp_out(*.stripe.com)
    - warp_out(stripe.com)
    - direct(all)
```

这个不能像其他工具那样做到只写一个么？比如某工具这样：

```
                "domain":[
                    "domain:ai.com",
                    "domain:auth0.com",
                    "domain:challenges.cloudflare.com",
                    "domain:client-api.arkoselabs.com",
                    "domain:events.statsigapi.net",
                    "domain:featuregates.org",
                    "domain:identrust.com",
                    "domain:intercom.io",
                    "domain:intercomcdn.com",
                    "domain:openai.com",
                    "domain:openaiapi-site.azureedge.net",
                    "domain:sentry.io",
                    "domain:stripe.com"
                ]
```

**Comment by tobyxdd** [comment]
这确实是目前 ACL 语法的设计问题但不算 bug，我还在想怎么解决

**Comment by szdosar** [comment]
难懂不是这样写吗？
`outbounds:
  - name: default 
    type: direct
    direct:
      mode: auto
      bindDevice: ens4
  - name: ipv6_only
    type: direct
    direct:
      mode: 6  

acl:
  inline: 
    - ipv6_only(geosite:openai)`

**Comment by toyo2333** [comment]
> 难懂不是这样写吗？
> 
> `outbounds:
> 
>   - name: default 
> 
>     type: direct
> 
>     direct:
> 
>       mode: auto
> 
>       bindDevice: ens4
> 
>   - name: ipv6_only
> 
>     type: direct
> 
>     direct:
> 
>       mode: 6  
> 
> 
> 
> acl:
> 
>   inline: 
> 
>     - ipv6_only(geosite:openai)`

这确实是另外一种写法。但这个你得保证geosite里的数据准确且及时更新。我以前用geosite出现过几次因为缺少域名导致分流失败，最后还是得自己来。我这一套用了很久了没什么问题。 这里主要是是反馈我这种写法下语法繁琐的问题，作者已经确认并考虑后续优化。

**Comment by onlymechen** [comment]
为什么我在更新到2.2.0的时候acl失效了？
我原来使用的file，file 内容如下：
my_ibm1(ip.gs)
my_ibm1(*.openai.com)
my_ibm1(*openai.com)
my_ibm1(*netflix*)
direct(all)
其中 my_ibm1 是我本地的一个sock5代理，但是升级到2.2.0之后发现分流失效了。

于是我重写了内置的规则如下

outbounds:
  - name: my_out1
    type: direct
  - name: my_ibm1
    type: http
    http:
      url: http://127.0.0.1:2083
      insecure: false
acl:
    inline:
      - my_ibm1(ip.*)
      - my_ibm1(*.openai.com)
      - my_ibm1(*openai.com)
      - my_ibm1(*netflix*)
      - direct(all)
写上ip.gs 主要是检测一下分流是否生效。
但是不生效

**Comment by onlymechen** [comment]
我明白了，比如我测试ip.gs 得写成 *ip.gs*

**Comment by onlymechen** [comment]
/*ip.gs/*

**Comment by toyo2333** [comment]
已经在2.2.2里使用新的后缀写法了。acl精简了很多。目前一切正常。
