### ISSUE TITLE
app/2.20 hysteria-linux-arm64 bug

### ISSUE THREAD

**Issue by spaceice0304** [apernet/hysteria#806]
华硕 rt-ax86u 路由器，梅林系统，arm64。之前版本没问题。而hysteria-linux-armv5 app/2.20 在rt-ac68u梅林系统上没问题。

2023-10-31T16:58:13+08:00	ERROR	TCP redirect error	{"addr": "192.168.50.132:54510", "reqAddr": "142.251.43.14:443", "error": "connect error: INTERNAL_ERROR (local): write udp [::]:53008->x.x.x.x:8443: sendmsg: invalid argument"}

**Comment by tobyxdd** [comment]
用 `QUIC_GO_DISABLE_GSO` 环境变量能解决吗

**Comment by spaceice0304** [comment]
export QUIC_GO_DISABLE_GSO=true 或 export QUIC_GO_ENABLE_GSO=true 都不能解决。

**Comment by spaceice0304** [comment]
export QUIC_GO_DISABLE_ECN=true 解决

**Comment by spaceice0304** [comment]
quic-go 0.40.0 fix the issue https://github.com/quic-go/quic-go/pull/4127

**Comment by spaceice0304** [comment]
quic-go 0.40.0 依然没有解决 ECN 的问题，仍然需要设置QUIC_GO_DISABLE_ECN。

**Comment by wen-long** [comment]
GL-AXT1800 上 v2.2.1 hysteria-linux-arm 和 hysteria-linux-armv5 也有类似问题, 现象为无数据处理日志, 无回包.
export QUIC_GO_DISABLE_ECN=true 解决
