### ISSUE TITLE
用json配置文件，将lazy的值设为非true，程序启动client模式报错

### ISSUE THREAD

**Issue by AmberisMyShiba** [apernet/hysteria#820]
**Describe the bug**
使用json配置文件，将lazy设置为false或者删除lazy这个键值，程序启动会报错，出错信息为：
FATAL   failed to initialize client     {"error": "connect error: timeout: no recent network activity"}

**To Reproduce**
Steps to reproduce the behavior.
1. 使用json配置（YAML没试过）
2. linux-amd64版本的二进制文件
3. 将lazy的键值删除或者设为false
4. 运行命令 hysteria client -c config.json报错
5. 将lazy的键值设置为true,运行hysteria client -c config.json正常。

**Expected behavior**
lazy的键值设置，不应该影响程序的启动
**Logs**
no logs

**Device and Operating System**
gentoo linux-61 and immortalWRT 21.02

**Additional context**

**Comment by tobyxdd** [comment]
这个错误表示连不上服务器，按照这里排查：https://hysteria.network/zh/docs/advanced/Troubleshooting/#failed-to-initialize-client-connect-error-timeout-no-recent-network-activity

没开启 lazy 会在启动时立即尝试连接，开启 lazy 会在有传入连接时才尝试连接。lazy 的设置必然会影响程序的启动，是预期行为。

**Comment by haruue** [comment]
在 Linux 上， 这种情况通常出现于使用 WiFi 连接， 并且配了开机自启的情况。

依照你使用的网络管理器的具体实现， systemd 是有可能在网络可以正常使用之前（ `After=network.target nss-lookup.target` ）启动 hysteria 的， 这时候启动 hysteria 就会因为上述原因启动失败。 解决方法通常有下面两个。

+ 启用 `lazy` 选项。 在 hysteria v1 时代曾经有个 `retry` 选项， 就是专门为解决这个问题添加的。 而在 hysteria v2， `retry` 选项的功能被整合进了 `lazy` 选项。 只需启用 `lazy` 选项， 就能让 hysteria 只在接受了第一个代理请求后才开始连接， 并且不会在初次连接失败后退出而是继续重试。 如果未启用 `lazy` 选项， hysteria 会在启动后立即尝试连接服务器， 并且会在第一次连接失败之后报错退出。

+ 尝试使用 `After=network-online.target` 。 基于各种原因， 我们非常不愿意在 systemd unit 中设置 `After=network-online.target`。 这是因为与简单的启动失败比起来， 类似于「我明明 enable 了某个服务， 而 systemd 却没有启动它」的问题往往更能让用户感到迷惑。 如果你清楚地知道自己在干什么， 当然可以 `systemctl edit hysteria@.service` 并根据提示加上
   ```
   [Unit]
   After=network-online.target
   ```
