### ISSUE TITLE
openwrt使用hy2断流

### ISSUE THREAD

**Issue by iamjimmycheng** [apernet/hysteria#822]
passwall/openclash挂载hy2节点，每隔一段时间就会无法访问，疑似断流，更换tuic节点测试也是使用一段时间后断流，这是否被营运商QoS了？

我更换xray节点就一切正常，长时间使用都不会断流。

这是针对UDP工具实施的断流行为吗？

**Comment by a308667911** [comment]
福州移动 udp 已经开始 qos了 ，也是hy2

**Comment by tobyxdd** [comment]
是
