### ISSUE TITLE
SSL有BUG

### ISSUE THREAD

**Issue by Phfebb** [apernet/hysteria#823]
正常使用了两天，什么也没做，今天突然连不上，使用systemctl 查看日志，一直提示：

INFO  maintenance  started background certificate maintenance

和

http: TLS handshake error from

重启也没用，3台机器里都这样，什么都没做，就是用着用着就这样了

**Comment by haruue** [comment]
看起来像是 acme 无法续签证书。 但是你的日志不完整， 我们无法判断。

请发送完整的日志。 你可以使用 `journalctl --no-pager -e -u hysteria-server.service` 以方便进行复制。

**Comment by qsdiy** [comment]
遇到了和你一样的问题，经测试，已经丧心病狂了嘛？还是我测试的有问题，任何地址的任何udp端口都是通的。。。
<img width="320" alt="udptest" src="https://github.com/apernet/hysteria/assets/2499565/47ad4a78-04bd-4be1-a964-490e9fc3f519">

**Comment by qsdiy** [comment]
客户端已经开了端口跳跃，范围为30000-39000，现在客户端还是连不上。。你的客户端端口跳跃如何配置的？

**Comment by qsdiy** [comment]
应该是测试的问题，很奇怪任何地址任何端口都是succeeded。。。。。。根本问题是我的服务器端的iptables Nat 规则失效了。。。
