### ISSUE TITLE
哈米直播断流

### ISSUE THREAD

**Issue by TeamBBC12345** [apernet/hysteria#827]
**描述问题**
在观看哈米直播时，tcp error，在播10分钟左右后会直接断流，要重新打开app才再播放

**日志**
hysteria[29742]: 2023-11-19T19:44:02+08:00        ERROR        TCP error        {"addr": "ip:50667", "id": "user", "reqAddr": "hls-hamivideo.cdn.hinet.net:443", "error": "readfrom tcp4 192.168.100.77:55808->203.66.34.6:443: stream 56 canceled by remote with error code 0"}

**设备和操作系统**
iOS 17.1.1, tvOS 17.1(21K69)

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by tobyxdd** [comment]
这个日志只能说明连接是浏览器/app主动断开的
