### ISSUE TITLE
Windows11打开安装包闪退

### ISSUE THREAD

**Issue by ChungyuCheung** [apernet/hysteria#829]
**描述问题**
Windows11打开安装包闪退

**如何复现**
新下载的安装文件， 在Windows11下，双击安装包，只闪现一个命令行界面，无法进行安装

**预期行为**
能正常安装

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
Windows 11

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by haruue** [comment]
hysteria core 和 v2ray 类似， 是纯命令行的程序， GitHub Release 提供的 .exe 文件即为软件本体（可以理解为是绿色版）， 不需要安装。 用鼠标双击之后「闪退」是因为没有找到配置文件所以直接退出了。

如果你需要图形化界面， 请访问下面的链接寻找第三方客户端。
https://hysteria.network/zh/docs/getting-started/3rd-party-apps/

**Comment by ChungyuCheung** [comment]
GitHub Release 提供的 .exe 文件即为软件本体（可以理解为是绿色版），那应该如何运行它呢？ 我双击它就闪退了

**Comment by haruue** [comment]
你说的「闪退」是因为命令行程序就是这么工作的， 它会显示一条错误信息， 但是没等你看清楚就直接退出了（因为在 Windows 上命令行程序退出， 窗口也会直接被关闭）。 需要从命令行（比如 PowerShell 或者 cmd）运行才能看到这条错误信息。

如果你完全没用过命令行， 那么我建议你使用第三方代理应用， 它们有图形化界面， 并且能一键配置系统级别代理。 只需 [Google 搜索 “Hysteria 2 配置教程 Windows”](https://www.google.com/search?q=Hysteria+2+%E9%85%8D%E7%BD%AE%E6%95%99%E7%A8%8B+Windows) ， 就能找到不少热心网友们编写的基于 v2rayN / sing-box / nekobox 的 图文/视频 教程， 它们都非常详细， 只要一步步跟着做就能学会配置和使用 Hysteria 2 了。
