### ISSUE TITLE
hysteria2 无规则的断流，请求方案

### ISSUE THREAD

**Issue by vbskycn** [apernet/hysteria#834]
如题，江西电信

甲骨文巴黎区arm,断流的时候换到arm2号机正常，过几分钟切换回来也会正常
openwrt  passwall最新版 

目前passwall的负载均衡好像配置不了多台  hy2节点，如果可以请大佬指点一下

passwall的自动切换节点功能也被砍了，实在想不通为什么呀

**请教各位大佬有什么好的方案**

其他协议完全跑不动呀，hy2 晚高锋油管随便5W+

**Comment by niuniudada** [comment]
可以尝试使用端口跳跃
[端口跳跃](https://hysteria.network/zh/docs/advanced/Port-Hopping/)

**Comment by tobyxdd** [comment]
这里不是 passwall 讨论区
