### ISSUE TITLE
是否可以添加一个生成分享链接的功能？

### ISSUE THREAD

**Issue by MiniKoro** [apernet/hysteria#838]
**你的功能请求是否与某个问题有关？**
无关

**描述你希望的解决方案**
现在用的都是官方版本，手机客户端添加节点每次都需要手动输入，可不可以像juicity一样可以一键生成一个分享链接。

**有没有其他替代方案**

**额外信息**
像nokebox客户端配置好后分享节点ios小火箭也可以直接扫码导入

**Comment by haruue** [comment]
官方 **客户端** 启动的时候会输出一条 `use this URI to share your server` 日志， 后面的 hysteria2:// 链接就是标准的分享链接。

你也可以在启动官方客户端的时候带个 `--qr` 的参数， 会在终端里显示能用手机扫描的分享二维码。

为了生成这个链接， 你需要一个能正常连接的客户端配置。 目前不支持从服务端配置文件生成客户端分享链接， 因为服务端配置文件缺少必要的信息。

**Comment by MiniKoro** [comment]
我没注意看过客户端配置 谢谢
