### ISSUE TITLE
关于使用hy2，IP必被命中为vpn

### ISSUE THREAD

**Issue by allmors** [apernet/hysteria#856]
**描述问题**
使用hy2，通过ip2location检测，IP必命中被识别为vpn，在chatgpt检测vpn使用的情况下，在iOS端（pc端此命中不影响）只要IP被命中为vpn，那么gpt客户端就无法使用，会给出使用vpn tips，经过测试几台新开服务器干净IP测试，均出现此问题

**如何复现**
找一个干净的服务商并且干净IP，在部署hy2之后，一段时间（一星期为基准）通过ip2location检测，IP必命中为vpn

**预期行为**
无vpn特征

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
客户端ios 小火箭
服务端debian11

**额外信息**
经过 复现步骤，均使用vmess vless trojan wireguard等做以一周为周期的对等测试，发现hy2在ip2location检测下为vpn，其他均无

**Comment by tobyxdd** [comment]
你的对比测试 样本数量是多少 时长多久

**Comment by mritd** [comment]
我觉得这个测试没什么意义... 核心问题在于 **如何定义 "干净的 IP"**

**Comment by mritd** [comment]
我觉得这个测试没什么意义... 核心问题在于 **如何定义 "干净的 IP"**

**Comment by wy15** [comment]
> > 我觉得这个测试没什么意义... 核心问题在于 **如何定义 "干净的 IP"**
> 
> 为什么没有意义，我花钱拿的isp ip，不够干净吗。。。实践是校验真理的唯一途径

你跑个测试脚本测下就知道了。基本就是你的ip被ban了。
我这边客户端sing-box，服务端hysteria2，没问题。
再多一句嘴，你这样说话，真的不太想回答你的问题。

**Comment by Alex-Joe-Lee** [comment]
我也遇到了相同的问题，使用hy的时候，手机上使用chatgpt app，提示：Something went wrong. You may be connected to a disallowed ISP. If you are using VPN, try disabling it.Otherwise try a different Wi-Fi network or data connection.  同样的节点，同样的代理工具，换成vless后就没有问题，用网页登录chatgpt也没有问题，是不是chatgpt app做了什么特殊的检测，hy刚好被检测到？

**Comment by Alex-Joe-Lee** [comment]
> > 我也遇到了相同的问题，使用hy的时候，手机上使用chatgpt app，提示：Something went wrong. You may be connected to a disallowed ISP. If you are using VPN, try disabling it.Otherwise try a different Wi-Fi network or data connection. 同样的节点，同样的代理工具，换成vless后就没有问题，用网页登录chatgpt也没有问题，是不是chatgpt app做了什么特殊的检测，hy刚好被检测到？
> 
> 你这种，在客户端加一条dns规则，query_type是HTTPS的禁掉就好了。

如何加呢？andriod推荐用什么客户端？谢谢老哥

**Comment by wy15** [comment]
@Alex-Joe-Lee 我用的sing-box。在dns rules里加。我是因为使用了fake ip，如果不使用，应该不会有这问题。

**Comment by ddwinhzy** [comment]
请教怎么操作呢

**Comment by meike1233** [comment]
确实是这样,同一个IP,
vmess + ws下,chatgpt ios 端和网页端都正常使用,
换了hysteria2后,网页端正常 , chatgpt ios 端无法使用.
提示：Something went wrong. You may be connected to a disallowed ISP. If you are using VPN, try disabling it.Otherwise try a different Wi-Fi network or data connection.

**Comment by Giant-Li** [comment]
> 确实是这样,同一个IP, vmess + ws下,chatgpt ios 端和网页端都正常使用, 换了hysteria2后,网页端正常 , chatgpt ios 端无法使用. 提示：Something went wrong. You may be connected to a disallowed ISP. If you are using VPN, try disabling it.Otherwise try a different Wi-Fi network or data connection.

我服务器用的是hiddify manager，手机用的是小火箭，默认代理是hy2因为速度比较快。hy2打开chatgpt就提示检测到VPN，看到你的贴子后切换到vless协议就能链接。非常感谢。

**Comment by GhostBone** [comment]
我也是，非常容易被识别出来是代理

**Comment by RyanRaw** [comment]
我的VPS用ip2location也检测出是VPN代理，欺诈99分，android手机 用V2RAYNG可以正常使用GPT，并没有什么问题，所以ip2location的检测就像欢乐表一样？用ping0.cc检测的IP倒是很纯净。
