### ISSUE TITLE
Hysteria2的UDP游戏转发问题

### ISSUE THREAD

**Issue by lovexiaofan123** [apernet/hysteria#860]
在singbox上看了几个关于HY2游戏UDP的lssues，反复确认是hy2本身存在UDP转发的问题。
1.测试NAT确实是FullCone（返回真实VPS IP），多次测试一致。
2.但在玩部分针对NAT要求过强的游戏就进不去。(问题可复现)
3.继续测试了hy1和tuic，进游戏秒进，之前hy2进不去的游戏都可以进了。
4.以上经过本人反复测试过，服务端配置文件都是默认，没有任何修改。

测试环境：客户端openclash， 服务端debian10

我也搜了整个hy的lssues 很少提这样的，可能是比较小众。

**Comment by Alex-Joe-Lee** [comment]
玩地平线4进去匹配就掉线

**Comment by tobyxdd** [comment]
请先确认是 你用的第三方客户端对 Hysteria UDP 支持的问题，还是 Hysteria 服务端自身的问题。后者我反复测试过，也有专门的 test cases，并未发现有什么问题。

**Comment by lovexiaofan123** [comment]
> 请先确认是 你用的第三方客户端对 Hysteria UDP 支持的问题，还是 Hysteria 服务端自身的问题。后者我反复测试过，也有专门的 test cases，并未发现有什么问题。

客户端是clashmeta alpha最新，也用passwall2的singbox alpha内核最新，都测试过，这个问题已经在singbox的issues提到过几次了，meta也是一样的问题，如果不嫌弃，请用pubg端游测试，这个更直观也玩得最多，以及minecraft进公众服务器。虽然测试NAT确实是FullCone，但确实是有问题存在。

**Comment by tobyxdd** [comment]
> > 请先确认是 你用的第三方客户端对 Hysteria UDP 支持的问题，还是 Hysteria 服务端自身的问题。后者我反复测试过，也有专门的 test cases，并未发现有什么问题。
> 
> 客户端是clashmeta alpha最新，也用passwall2的singbox alpha内核最新，都测试过，这个问题已经在singbox的issues提到过几次了，meta也是一样的问题，如果不嫌弃，请用pubg端游测试，这个更直观也玩得最多，以及minecraft进公众服务器。虽然测试NAT确实是FullCone，但确实是有问题存在。

把你的联系方式发到我邮箱（profile 里有），用我的服务器测试

**Comment by gcp0912** [comment]
openwrrt路由器上的passwall，舊版跑Hysteria 1.35時，tcp、udp節點都開啟，
vowifi (Wifi Calling)沒問題。
升級後的passwall只能跑Hysteria2，單開啟tcp 節點能翻，若再開啟udp節點會
直接無法翻牆。不知哪邊問題，只能先都退回舊版。

**Comment by Alex-Joe-Lee** [comment]
> 跑

不能吧，我开启了udp并且使用域名，是正常的呀

**Comment by gcp0912** [comment]
> > 跑
> 
> 不能吧，我开启了udp并且使用域名，是正常的呀
目前遇到是passwall的問題，改用passwall2預設開啟udp，能使用域名翻牆。

**Comment by Natsuki-Kaede** [comment]
Dead By Daylight connection lost.
sing-box + clash meta 1.16.0

**Comment by tobyxdd** [comment]
> 把你的联系方式发到我邮箱（profile 里有），用我的服务器测试

等了两周也没收到回复
