### ISSUE TITLE
banned by huawei router,note that with same server,vless can use

### ISSUE THREAD

**Issue by end-china-communist-party** [apernet/hysteria#864]
**Describe the bug**
banned by huawei router,note that with same server,vless can use

**To Reproduce**
maybe you need to have a ccp military grade huawei router...

**Expected behavior**
usable

**Logs**

[hysteria2 client log.txt](https://github.com/apernet/hysteria/files/13648326/hysteria2.client.log.txt)

**Device and Operating System**
win10 Windows 10 Education 22H2

**Additional context**
this uses w.免费机场.com,if you want to test vless and hysteria on one server you can use https://web.fscloud.cc

<img width="927" alt="fscloud" src="https://github.com/apernet/hysteria/assets/136224357/dfef400f-7efd-47fd-b5e5-39959508125d">

<img width="939" alt="log's server ip" src="https://github.com/apernet/hysteria/assets/136224357/d304b20d-647c-4a4e-85f3-f99556304f46">

**Comment by tobyxdd** [comment]
What is a "CCP military grade Huawei router"? How do you know Hysteria is banned that? And do you have one?

This feels like a disguised ad for your 免费机场.
