### ISSUE TITLE
wireguard over udpForwarding is very slow

### ISSUE THREAD

**Issue by its0ka** [apernet/hysteria#871]
**Describe the bug**
i get full network speed of 20mbit/s when i use tcpForwarding -> nginx with test file,
but downloading the same file over wireguard -> udpForwarding -> nginx gives me only ~1mbit/s, i lowered wireguard mtu to 1280 but it didn't help

**To Reproduce**
client conf: https://pastebin.com/hUXJLjfT
server conf: https://pastebin.com/gTePdEkP

**Logs**
no errors in logs with HYSTERIA_LOG_LEVEL=debug

**Device and Operating System**
arch amd64

**Additional context**
client has public ip, server has public ip with nat (port 80 is forwarded over nat), mtu is 1500 on both. [udpspeeder](https://github.com/wangyu-/UDPspeeder) gives much better speed ~14mbit/s with default settings. direct wireguard is also better and gives at least 5mbit/s

**Comment by its0ka** [comment]
upd: speed increases to almost full when i use "sysctl -w net.ipv4.tcp_congestion_control=bbr" but that's not a solution because i plan to use wireguard tunnel to access the internet, so "sysctl -w net.ipv4.tcp_congestion_control=cubic" was used for testing

**Comment by its0ka** [comment]
iperf3 sender: https://pastebin.com/s6N4EiNr
iperf3 reciever: https://pastebin.com/JkE8HFGf

**Comment by its0ka** [comment]
actually, the speed is low only in one direction: downloading from hysteria client to the hysteria server is fast ~10mbit/s, downloading from server to the client is slow ~1mbit/s

**Comment by boss1819** [comment]
i face the same issue. speed is slow only in 1 direction.

**Comment by w123456w30w** [comment]
wireguard  based on udp, read the document [About HTTP/3](https://v2.hysteria.network/docs/misc/About-HTTP3/)

**Comment by its0ka** [comment]
@w123456w30w oh, thanks
