### ISSUE TITLE
想在自己的k3s集群中使用

### ISSUE THREAD

**Issue by zhangjunjie6b** [apernet/hysteria#872]
尝试了ingresses和NodePort 2种方式

理论ingresses属于反向代理不成功是在预期内的。

NodePort 我不是很确定，但是也是不行的。

好奇能在k3s中跑起来吗

**Comment by mritd** [comment]
ingress 只是个 Object, 具体实现取决于 ingress controller; 理论上支持 4 层的 ingress controller 应该也是可以的; NodePort 肯定是没问题, 因为不做特殊处理的话 NodePort 只是端口映射规则; 需要明确的是 Hysteria 是 UDP,  你可能需要在 SVC 中定义好协议.

**Comment by zhangjunjie6b** [comment]
> ingress 只是个 Object, 具体实现取决于 ingress controller; 理论上支持 4 层的 ingress controller 应该也是可以的; NodePort 肯定是没问题, 因为不做特殊处理的话 NodePort 只是端口映射规则; 需要明确的是 Hysteria 是 UDP, 你可能需要在 SVC 中定义好协议.

NodePort配置上UDP的确能跑起来，但是速度很慢。
ingresses我用的[Traefik](https://traefik.io/) 研究了一下午任然没搞明白

**Comment by mritd** [comment]
Traefik 的话我记得你需要首先定一个自己的 endpoint(cli `--entrypoints.<name>`), 然后通过 ingressrouter 之类的服务发现方式 把 svc 4 层挂上去; k3s 自带的 traefik 配置我记得是在一个目录里, 需要自己调整或者直接关掉重新 Helm 安装.

**Comment by mritd** [comment]
UDP 配置部分你可以参考这里 https://doc.traefik.io/traefik/routing/routers/#configuring-udp-routers, k8s 里的话推荐使用它自己的 CRD 来实现复杂定义.

**Comment by zhangjunjie6b** [comment]
> UDP 配置部分你可以参考这里 https://doc.traefik.io/traefik/routing/routers/#configuring-udp-routers, k8s 里的话推荐使用它自己的 CRD 来实现复杂定义.

经过测试是不可行，我的操作步骤类似
https://cloud.tencent.com/developer/article/1768566

hy2是tcp通过后再进行的udp吧

**Comment by zhangjunjie6b** [comment]
k3s才开始自学不是很熟悉，所以没能立马验证。
经过一周的学习我想我已经掌握了它。

我决定关闭这个issues, 因为我自己认为hy2是没法在k3s中运行的。

---

原因可能是（猜想）


k3s中CRD IngressRouteTCP和IngressRouteUDP 遵守的TCP/UDP报文格式，HY2属于魔改版。
k3s中 TCP握手完成后就一直用规定内的报文传输数据
HY2会在握手完成后调用UDP，而这个操作是k3s中没法识别的

Ingress本质还是代理，也就是Ingress controller监听443再路由到其他地方

**Comment by Winson-030** [comment]
> k3s才开始自学不是很熟悉，所以没能立马验证。 经过一周的学习我想我已经掌握了它。
> 
> 我决定关闭这个issues, 因为我自己认为hy2是没法在k3s中运行的。
> 
> 原因可能是（猜想）
> 
> k3s中CRD IngressRouteTCP和IngressRouteUDP 遵守的TCP/UDP报文格式，HY2属于魔改版。 k3s中 TCP握手完成后就一直用规定内的报文传输数据 HY2会在握手完成后调用UDP，而这个操作是k3s中没法识别的
> 
> Ingress本质还是代理，也就是Ingress controller监听443再路由到其他地方
> 
> 期待大佬们的补充

你需要使用 hostnetwork 的网络模式而不是 traefik，我成功在k3s上部署了hy2的server，稳定使用。
