### ISSUE TITLE
为什么显示已经在监听的端口，本地都Telent不通的？

### ISSUE THREAD

**Issue by EricKong1985** [apernet/hysteria#876]
![屏幕截图 2023-12-19 193255](https://github.com/apernet/hysteria/assets/8405704/8bc9c417-6fe2-4bc1-ad0a-e35dd2777b4c)

**Comment by haruue** [comment]
在你的例子中， Hysteria 监听的是 UDP 的 10443 端口， 而 telnet 连接的是 TCP 的 10443 端口。 这不是同一个东西。
