### ISSUE TITLE
hy2节点无法发X，切换其他节点如vless后就可以了，多种客户端测试，包括sfi、小火箭等。

### ISSUE THREAD

**Issue by lifeva** [apernet/hysteria#880]
**描述问题**
请尽量清晰精准地描述你遇到的问题。

**如何复现**
复现问题的步骤。

**预期行为**
你认为修复后的行为应该是怎样的。

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
你在用什么设备和操作系统。

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by liszt188** [comment]
小学生？
