### ISSUE TITLE
QvPlugin-Hysteria2

### ISSUE THREAD

**Issue by Kelro-Lay** [apernet/hysteria#881]
首先感谢Hysteria的开发者们的幸苦劳作，同时也对开发者们提一个小小的请求：
现在用Qv2ray的用户依旧仍有很多，比较喜欢他的界面，此前有用户开发出了第一代[QvPlugin-hysteria]
(https://github.com/trulyliu/QvPlugin-Hysteria) 效果还不错
希望Hysteria的开发者同时也可以针对Qv2ray的用户开发出QvPlugin-hysteria2

再此表示感谢！！！！

**Comment by w123456w30w** [comment]
这个你应该去原本的插件repo中提，而且Qv2ray已经停止更新多年建议换个客户端
如果实在想用，你可以自行配置Hy2开放一个socks5代理，将Qv2ray的outbound指定到Hy2的socks5上一样使用
