### ISSUE TITLE
win7系统使用最新版本V2.2.3时报错，无法启动

### ISSUE THREAD

**Issue by AndersonGhost** [apernet/hysteria#891]
如题所述，win7系统使用最新版本V2.2.3的hysteria-windows-amd64.exe时，无法启动，V2rayN中的报错日志如下所示：

`启动服务(2024/1/3 20:40:18)...
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
	runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x46ca95
rax     0x0
rbx     0x1224d00
rcx     0x12793e0
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x124ac98
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x12246a0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b`

win10系统使用最新的版本无任何问题。
win7 系统使用V2.2.2的版本无任何问题。

**Comment by tobyxdd** [comment]
Go 1.21 不再支持 Windows 7，这是正常现象

**Comment by AndersonGhost** [comment]
> Go 1.21 不再支持 Windows 7，这是正常现象

好的，感谢大佬~~  看自己能否去编译个

**Comment by AndersonGhost** [comment]
> Go 1.21 不再支持 Windows 7，这是正常现象

大佬，您好~ 我在系统中安装了go 1.20，Python 3.12.1 并尝试进行编译，但是没有编译通过，如下是报错日志：
`root@Debian-11:~/hysteria# python hyperbole.py build
/root/hysteria/hyperbole.py:179: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  app_date = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
Building for linux/amd64...
go: downloading github.com/mholt/acmez v1.0.4
go: downloading github.com/caddyserver/certmagic v0.17.2
go: downloading github.com/spf13/cobra v1.7.0
go: downloading github.com/spf13/viper v1.15.0
go: downloading go.uber.org/zap v1.24.0
go: downloading github.com/txthinking/socks5 v0.0.0-20230325130024-4230056ae301
go: downloading github.com/apernet/go-tproxy v0.0.0-20230809025308-8f4723fd742f
go: downloading github.com/mdp/qrterminal/v3 v3.1.1
go: downloading github.com/apernet/quic-go v0.40.1-0.20231112225043-e7f3af208dee
go: downloading github.com/stretchr/testify v1.8.4
go: downloading golang.org/x/crypto v0.17.0
go: downloading github.com/babolivier/go-doh-client v0.0.0-20201028162107-a76cff4cb8b6
go: downloading github.com/miekg/dns v1.1.55
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/klauspost/cpuid/v2 v2.1.1
go: downloading github.com/libdns/libdns v0.2.1
go: downloading golang.org/x/net v0.17.0
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.9.3
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading go.uber.org/atomic v1.11.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading github.com/hashicorp/golang-lru/v2 v2.0.5
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/txthinking/runnergroup v0.0.0-20210608031112-152c7c4432bf
go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
go: downloading rsc.io/qr v0.2.0
go: downloading github.com/quic-go/qpack v0.4.0
go: downloading golang.org/x/exp v0.0.0-20221205204356-47842c84f3db
go: downloading golang.org/x/sys v0.15.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/stretchr/objx v0.5.0
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/subosito/gotenv v1.4.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.7
go: downloading github.com/pelletier/go-toml/v2 v2.0.6
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/quic-go/qtls-go1-20 v0.4.1
# github.com/apernet/hysteria/core/internal/congestion/bbr
core/internal/congestion/bbr/bandwidth_sampler.go:634:28: undefined: min
core/internal/congestion/bbr/bandwidth_sampler.go:641:18: undefined: max
core/internal/congestion/bbr/bandwidth_sampler.go:666:17: undefined: max
core/internal/congestion/bbr/bandwidth_sampler.go:668:18: undefined: max
core/internal/congestion/bbr/bandwidth_sampler.go:671:43: undefined: min
core/internal/congestion/bbr/bandwidth_sampler.go:822:21: undefined: min
core/internal/congestion/bbr/bbr_sender.go:392:10: undefined: min
core/internal/congestion/bbr/bbr_sender.go:585:9: undefined: max
core/internal/congestion/bbr/bbr_sender.go:835:20: undefined: max
core/internal/congestion/bbr/bbr_sender.go:843:17: undefined: max
core/internal/congestion/bbr/bbr_sender.go:843:17: too many errors
note: module requires Go 1.21
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.9.3
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading go.uber.org/atomic v1.11.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading github.com/hashicorp/golang-lru/v2 v2.0.5
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/txthinking/runnergroup v0.0.0-20210608031112-152c7c4432bf
go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
go: downloading rsc.io/qr v0.2.0
go: downloading github.com/quic-go/qpack v0.4.0
go: downloading golang.org/x/exp v0.0.0-20221205204356-47842c84f3db
go: downloading golang.org/x/sys v0.15.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/stretchr/objx v0.5.0
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/subosito/gotenv v1.4.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.7
go: downloading github.com/pelletier/go-toml/v2 v2.0.6
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/quic-go/qtls-go1-20 v0.4.1
# github.com/apernet/hysteria/core/internal/congestion/bbr
core/internal/congestion/bbr/bandwidth_sampler.go:634:28: undefined: min
core/internal/congestion/bbr/bandwidth_sampler.go:641:18: undefined: max
core/internal/congestion/bbr/bandwidth_sampler.go:666:17: undefined: max
core/internal/congestion/bbr/bandwidth_sampler.go:668:18: undefined: max
core/internal/congestion/bbr/bandwidth_sampler.go:671:43: undefined: min
core/internal/congestion/bbr/bandwidth_sampler.go:822:21: undefined: min
core/internal/congestion/bbr/bbr_sender.go:392:10: undefined: min
core/internal/congestion/bbr/bbr_sender.go:585:9: undefined: max
core/internal/congestion/bbr/bbr_sender.go:835:20: undefined: max
core/internal/congestion/bbr/bbr_sender.go:843:17: undefined: max
core/internal/congestion/bbr/bbr_sender.go:843:17: too many errors
note: module requires Go 1.21
Failed to build for linux/amd64
`
系统可否在go 1.20的情况下编译通过，并支持win7呢？感谢~~

**Comment by crazypeace** [comment]
实验结果, 能在 go 1.20 编译通过的只有 v2.0.2
