### ISSUE TITLE
打个rpm包

### ISSUE THREAD

**Issue by TDYQ-Liu** [apernet/hysteria#894]
**你的功能请求是否与某个问题有关？**
安装

**描述你希望的解决方案**
给redhat系打个rpm包方便安装

**有没有其他替代方案**
请尽量清晰精准地描述你认为可能的替代方案。

**额外信息**
redhat系都默认启用seliux，使用二进制要自己用 semodule， restorecon改，挺麻烦的

**Comment by haruue** [comment]
Linux 发行版打包不应该是上游开发者的工作， 我们不可能了解所有发行版的特性， 也不可能为发行版的特定问题提供解决方案。

如果你是 RHEL 订户， 联系你的 [客户支持人员](https://www.redhat.com/zh/services) 让他们提供帮助。
否则， 联系你熟悉的 RedHat 社群或者第三方软件仓库维护人员， 让他们帮你打包。 

此外， 我们的安装脚本已经过测试， 能在 Google Cloud Platform 提供的 CentOS 7/8/9 和 Fedora 上正确安装。
