### ISSUE TITLE
客户端解析配置文件的时候出错

### ISSUE THREAD

**Issue by chijiao** [apernet/hysteria#895]
server:  www.baidu.com:24443 # 你的服务端域名和端口

auth: 123456 # 你的服务端密码

bandwidth: # 带宽限制，本文未修改，更多信息请查看官方文档
  up: 20 mbps
  down: 100 mbps

socks5: # socks5代理，本文未修改，更多信息请查看官方文档
  listen: 0.0.0.0:1080 

http: # http代理，本文未修改，更多信息请查看官方文档
  listen: 0.0.0.0:1089

**描述问题**
作为客户端模式,解析配置文件的时候, 配置文件如上,在Android环境下,就是在Android代码中调用hysteria的时候, 提示如下错误.

Output from libhysteria.so: 2024-01-06T05:17:07Z	[31mFATAL[0m	failed to initialize client	{"error": "invalid config: server: lookup www.baidu.com on [::1]:53: read udp [::1]:37774->[::1]:53: read: connection refused"}

提示解析域名失败. 看日志应该是连接dns服务器失败了, 连接的是 127.0.0.1 这个dns服务器. 但是在安卓手机中, dns服务器并不是这个. 或许是程序查找dns服务器的时候, 默认使用了 127.0.0.1 这个作为dns服务器.

**如何复现**
在Android中调用 Linux 64 的二进制程序. 运行此程序,就会出现这个错误

**预期行为**
修复获取dns服务器的流程,或者手动指定解析服务器的地址

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
Android armv8

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by tobyxdd** [comment]
Android 有 android build

**Comment by chijiao** [comment]
Android build 不能在程序中用Java来直接调用.

**Comment by chijiao** [comment]
这个貌似不是运行平台的问题, 是程序可以运行,但是解析不了 服务器的域名. 用ip则可以.

**Comment by chijiao** [comment]
经过重新测试, 运行 Android build 的确可以解析服务器域名了
