### ISSUE TITLE
不能用Hysteria游玩Vrchat

### ISSUE THREAD

**Issue by modimobeikete** [apernet/hysteria#898]
**描述问题**
我在尝试游玩Vrchat的时候，发现这个协议无法正常连接，但是在换成ssr协议之后就能正常连接了。

**如何复现**
在启动Tun模式下（或者通过Openwrt连接）

**预期行为**
Vrchat能正常连接
**日志**
+0000 2024-01-14 10:57:22 INFO [813661126 0ms] outbound/hysteria2[HIZMcAnX]: outbound packet connection to 5.5.5.5:55555
+0000 2024-01-14 10:57:22 DEBUG [1124937554 11.71s] inbound/tproxy[tproxy_udp]: connection closed: upload: message too large (maximum: 1197 bytes) | download: io: read/write on closed pipe
+0000 2024-01-14 10:57:23 INFO [1094176050 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection from 192.168.6.231:54432
+0000 2024-01-14 10:57:23 INFO [1094176050 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:23 INFO [1094176050 0ms] outbound/hysteria2[HIZMcAnX]: outbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:23 DEBUG [816796972 0ms] inbound/tproxy[tproxy_udp]: connection closed: upload: message too large (maximum: 1197 bytes) | download: io: read/write on closed pipe
+0000 2024-01-14 10:57:23 INFO [1436806147 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection from 192.168.6.231:54432
+0000 2024-01-14 10:57:23 INFO [1436806147 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:23 INFO [1436806147 0ms] outbound/hysteria2[HIZMcAnX]: outbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:23 DEBUG [1545227515 0ms] inbound/tproxy[tproxy_udp]: connection closed: upload: message too large (maximum: 1197 bytes) | download: io: read/write on closed pipe
+0000 2024-01-14 10:57:23 INFO [497050110 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection from 192.168.6.231:54432
+0000 2024-01-14 10:57:23 INFO [497050110 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:23 INFO [497050110 0ms] outbound/hysteria2[HIZMcAnX]: outbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:23 DEBUG [1475748671 0ms] inbound/tproxy[tproxy_udp]: connection closed: upload: message too large (maximum: 1197 bytes) | download: io: read/write on closed pipe
+0000 2024-01-14 10:57:23 INFO [3071335026 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection from 192.168.6.231:54817
+0000 2024-01-14 10:57:23 INFO [3071335026 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection to 5.5.5.5:55555
+0000 2024-01-14 10:57:23 INFO [3071335026 0ms] outbound/hysteria2[HIZMcAnX]: outbound packet connection to 5.5.5.5:55555
+0000 2024-01-14 10:57:23 INFO [2254339554 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection from 192.168.6.231:54818
+0000 2024-01-14 10:57:23 INFO [2254339554 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection to 5.5.5.5:55555
+0000 2024-01-14 10:57:23 INFO [2254339554 0ms] outbound/hysteria2[HIZMcAnX]: outbound packet connection to 5.5.5.5:55555
+0000 2024-01-14 10:57:23 INFO [3322946116 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection from 192.168.6.231:54432
+0000 2024-01-14 10:57:23 INFO [3322946116 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:23 INFO [3322946116 0ms] outbound/hysteria2[HIZMcAnX]: outbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:23 DEBUG [2799075012 0ms] inbound/tproxy[tproxy_udp]: connection closed: upload: message too large (maximum: 1197 bytes) | download: io: read/write on closed pipe
+0000 2024-01-14 10:57:24 INFO [1696920371 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection from 192.168.6.231:54432
+0000 2024-01-14 10:57:24 INFO [1696920371 0ms] inbound/tproxy[tproxy_udp]: inbound packet connection to 91.199.81.50:5055
+0000 2024-01-14 10:57:24 INFO [1696920371 0ms] outbound/hysteria2[HIZMcAnX]: outbound packet connection to 91.199.81.50:5055

**设备和操作系统**
路由器为红米AX6000，系统为专业版win11

**额外信息**
这个连不上去的问题比较奇怪，在一些游戏（如使命召唤）没有问题，但有的游戏像Resonite就会偶尔掉线，而Vrchat就是完全连游戏都进不去。

**Comment by JsonSong89** [comment]
是不是udp的原因?

**Comment by lovexiaofan123** [comment]
我猜你一定是用了meta和singbox内核，用原版的hy2的客户端UDP是很正常的。之前我也发了个issues跟你的情况一样，后来我直接在op上部署了hy2原版客户端就一切正常了，后来我忘记回复作者了也关了issues。所以我现在能100%确定是对hy2支持的客户端的问题，还有不明白的是sb和meta也迟迟不弄hy2的端口跳跃的问题。

**Comment by modimobeikete** [comment]
@JsonSong89 游戏的话肯定是udp

**Comment by modimobeikete** [comment]
@lovexiaofan123 也就是说只能等sing-box作者解决这个问题？但我除了op我也用nekoray之类的。

**Comment by lovexiaofan123** [comment]
@modimobeikete 不用等了，大概率是不会解决这个问题的，连HY2端口跳跃都不会支持，甚至meta（mihomo）作者都说了以后不会支持端口跳跃，更别说这个了，用原版HY2客户端的ACL也一样可以做到分流，用passwall也可以，也是支持hy2原版客户端的

**Comment by tobyxdd** [comment]
你这个 log 是来自 singbox 的，还是向 singbox 反馈吧

**Comment by OXERIS** [comment]
> 我猜你一定是用了meta和singbox内核，用原版的hy2的客户端UDP是很正常的。之前我也发了个issues跟你的情况一样，后来我直接在op上部署了hy2原版客户端就一切正常了，后来我忘记回复作者了也关了issues。所以我现在能100%确定是对hy2支持的客户端的问题，还有不明白的是sb和meta也迟迟不弄hy2的端口跳跃的问题。

确实，我换hy2后能连上了，但是，我用hy2的话，不能在vrchat里播放视频链接，但是shadowsocks可以。
