### ISSUE TITLE
tproxy里的几个mark id必须一样吗？

### ISSUE THREAD

**Issue by muziling** [apernet/hysteria#900]
1、ip rule add fwmark 0x1 lookup 100
2、iptables -t mangle -A HYSTERIA -p tcp -m socket --transparent -j MARK --set-mark 0x1
3、iptables -t mangle -A HYSTERIA -p tcp -j TPROXY --on-port 2500 --on-ip 127.0.0.1 --tproxy-mark 0x1
4、iptables -t mangle -A HYSTERIA_MARK -p tcp -j MARK --set-mark 0x1

比如第1，3，4的mark id值必须一样？  2可以不一样？
必须设置为1吗？

**Comment by haruue** [comment]
不是一定都要设置为 0x1 ， 但是必须都一样。
