### ISSUE TITLE
对于流量监控的小小改进

### ISSUE THREAD

**Issue by stqfdyr** [apernet/hysteria#909]
![屏幕截图 2024-01-24 064750](https://github.com/apernet/hysteria/assets/89149493/8da0a067-ca43-4b3c-b17d-4dc059c660bf)
这样的流量统计有点不那么不人性化，对吧

希望写个小工具类，将流量自动转化为合适的单位，比如 hutool 的
![屏幕截图 2024-01-24 064537](https://github.com/apernet/hysteria/assets/89149493/a526dc6e-3199-4c7d-a192-c55f7b07ea8d)
![屏幕截图 2024-01-24 064551](https://github.com/apernet/hysteria/assets/89149493/4fbdd2e4-4da4-4515-a41f-3c80d14bee15)
 DataUnit.UNIT_NAMES 是一个 数组 ["B", "KB", "MB", "GB", "TB", "PB", "EB"]
感谢！

**Comment by HynoR** [comment]
这个接口用最低的byte单位，是方便其他程序获取后处理的，而不是纯给人查看的。
你可以在对接的程序上调用本体去处理byte的单位的流量然后自己再转换成想要的格式。
如果本体实现了自动转换单位的话，其他人编写对接程序的时候还需要额外去查询是什么单位并转换成自己的单位，这样就很麻烦了。

**Comment by stqfdyr** [comment]
> 这个接口用最低的byte单位，是方便其他程序获取后处理的，而不是纯给人查看的。 如果本体实现了自动转换单位的话，其他人编写对接程序的时候还需要额外去查询是什么单位并转换成自己的单位。同时还需要考虑到精度和浮点数的问题。这样就很麻烦了。
> 
> 你这种想法是适用于在需要人交互的面板上，就应该像你的代码那样让交互程序去拿原始数据转换给人看，而不是优先想到让本体去适配转换。

收到这么耐心的解释，不胜惶恐
我考虑的不够全面，没考虑到数据可以被其它程序获取并处理这一点，以为只是单纯给人看的，直接在源头处理了，那对接下来的各种其它操作确实是一个灾难
最后再次感谢，我会关闭此 issue

**Comment by w9315273** [comment]
随便写个Python脚本自动换算就行了

import requests

def bytes_to_readable(bytes):
    if bytes < 1024:
        return f"{bytes} B"
    elif bytes < 1024**2:
        return f"{bytes / 1024:.2f} KB"
    elif bytes < 1024**3:
        return f"{bytes / 1024**2:.2f} MB"
    else:
        return f"{bytes / 1024**3:.2f} GB"

url = "http://127.0.0.1:39999/traffic"
headers = {"Authorization": "Token"}
response = requests.get(url, headers=headers)

if response.status_code == 200:
    data = response.json()
    formatted_data = {}
    for key, values in data.items():
        formatted_data[key] = {
            "上传": bytes_to_readable(values["tx"]),
            "下载": bytes_to_readable(values["rx"])
        }
    for key, value in formatted_data.items():
        print(f"{key}: 上传 {value['上传']}, 下载 {value['下载']}")
else:
    print("请求失败，状态码：", response.status_code)

**Comment by stqfdyr** [comment]
> 随便写个Python脚本自动换算就行了
> 
> ```
> import requests
> 
> def bytes_to_readable(bytes):
>     if bytes < 1024:
>         return f"{bytes} B"
>     elif bytes < 1024**2:
>         return f"{bytes / 1024:.2f} KB"
>     elif bytes < 1024**3:
>         return f"{bytes / 1024**2:.2f} MB"
>     else:
>         return f"{bytes / 1024**3:.2f} GB"
> 
> url = "http://127.0.0.1:39999/traffic"
> headers = {"Authorization": "Token"}
> response = requests.get(url, headers=headers)
> 
> if response.status_code == 200:
>     data = response.json()
>     formatted_data = {}
>     for key, values in data.items():
>         formatted_data[key] = {
>             "上传": bytes_to_readable(values["tx"]),
>             "下载": bytes_to_readable(values["rx"])
>         }
>     for key, value in formatted_data.items():
>         print(f"{key}: 上传 {value['上传']}, 下载 {value['下载']}")
> else:
>     print("请求失败，状态码：", response.status_code)
> ```

https://github.com/apernet/hysteria/discussions/972#discussion-6349735
