### ISSUE TITLE
首先感谢Hysteria的开发者们的幸苦劳作，同时也对开发者们提一个小小的请求： 现在用Qv2ray的用户依旧仍有很多，比较喜欢他的界面，此前有用户开发出了第一代[QvPlugin-hysteria] (https://github.com/trulyliu/QvPlugin-Hysteria) 效果还不错 希望Hysteria的开发者同时也可以针对Qv2ray的用户开发出QvPlugin-hysteria2  再此表示感谢！！！！

### ISSUE THREAD

**Issue by khaiCybersec** [apernet/hysteria#913]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
Attach logs from the client/server when the error occurs.

**Device and Operating System**
What are you using it on.

**Additional context**

**Comment by stqfdyr** [comment]
你把这归类为 bug ?

**Comment by tobyxdd** [comment]
抱歉，目前没有这个计划
