### ISSUE TITLE
Is there anyway to be nominated on Hall of Fame?

### ISSUE THREAD

**Issue by Catboy96** [apernet/hysteria#916]
I've donated $30 to support this project. Is there anyway to be nominated on the Hall of Fame of the donation webpage? Or, is there anyway to contact the author?

Again, thanks for the hardworking you guys have made to defend the rights of free Internet.

**Comment by tobyxdd** [comment]
Yes, absolutely - just send an email to the address in my profile, including what you want me to put on the page and optionally a link.
