### ISSUE TITLE
Possible bug with the operation

### ISSUE THREAD

**Issue by MyVanitar** [apernet/hysteria#918]
Hello,
Thank you for your work, everything is fine except for two cases with Hysteria 2

1) if you simply browse for websites and consume normal traffic, it's fine, but if you try to download files using a Download Manager or similar (high traffic rate), the data suddenly drops to zero and you have to disconnect/connect again

2) it has problems with some websites, such as Google Analytics (does not load the website)

**Comment by tobyxdd** [comment]
> does not load the website

See if the latest version fixes this for you

> but if you try to download files using a Download Manager or similar (high traffic rate), the data suddenly drops to zero and you have to disconnect/connect again

I suspect this is some kind of throttling by your ISP rather than a problem with the code. Are you using Brutal (by specifying bandwidth values) or BBR? What speed do you usually get?

**Comment by MyVanitar** [comment]
I confirm the first issue is not related to Hysteria, and it was happening because of the VPS throttling. 

However, I still could not fix the second problem

![2024-01-27_07-28-17](https://github.com/apernet/hysteria/assets/18719591/a31665ed-59b0-4b92-82cb-d59792d6ecc2)

**Comment by MyVanitar** [comment]
The problem with the download was bandwidth throttling of the VPS
the problem with Google Analytics was I was using a Hysteria 2 installer with an older versions, as you mentioned

Thank you very much for your exceptional work
