### ISSUE TITLE
配置都正常但是还是连接不了 failed to initialize client (connect error: timeout: no recent network activity)

### ISSUE THREAD

**Issue by ZHAN2006** [apernet/hysteria#929]
**描述问题**
服务端和客户端都能正常启动但就是访问不了
以前能用，但是上个月服务器没流量断网几天后重启这个月恢复就用不了了

**日志**
客户端
2024-02-01T20:20:00+08:00       INFO    client mode
2024-02-01T20:20:00+08:00       INFO    use this URI to share your server       {"uri": "hysteria2://111111aA@*.*.*.*:8044/?insecure=1"}
2024-02-01T20:20:00+08:00       INFO    HTTP proxy server listening     {"addr": "127.0.0.1:1081"}
2024-02-01T20:20:00+08:00       INFO    SOCKS5 server listening {"addr": "127.0.0.1:1082"}
2024-02-01T20:20:10+08:00       ERROR   HTTP CONNECT error      {"addr": "127.0.0.1:52055", "reqAddr": "bing.com:443", "error": "connect error: timeout: no recent network activity"}

服务器端
2024-02-01T20:15:36+08:00       INFO    server mode
2024-02-01T20:15:36+08:00       INFO    server up and running   {"listen": "0.0.0.0:8044"}

**配置**

客户端

server: *.*.*.*:8044

auth: 111111aA
lazy: true

socks5:
  listen: 127.0.0.1:1082

http:
  listen: 127.0.0.1:1081
  
tls:
  insecure: true
  ca: *.*.*.*(ssl).crt

服务器端

listen: 0.0.0.0:8044

tls:
  cert: *.*.*.*(ssl).crt
  key: *.*.*.*(ssl).key
  insecure: true
auth:
  type: password
  password: 111111aA
masquerade:
  type: proxy
  proxy:
    url: https://zhansmpc.cn/
    rewriteHost: true
bandwidth:
  up: 512 mb
  down: 512 mb
ignoreClientBandwidth: false

**设备和操作系统**
系统 CentOS Linux 7
内核 CentOS Linux (6.6.2-1.el7.elrepo.x86_64) 7 (Core)

**额外信息**
服务器抓包的 *.*.*.* 是客户端  zhansmpc.cn.8044是服务端
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
20:24:35.390883 IP (tos 0x28, ttl 113, id 51789, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.olsv > zhansmpc.cn.8044: UDP, length 1252
20:24:35.482114 IP (tos 0x28, ttl 113, id 51790, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.olsv > zhansmpc.cn.8044: UDP, length 1252
20:24:35.482328 IP (tos 0x28, ttl 113, id 51791, offset 0, flags [DF], proto UDP (17), length 1280)
  *.*.*.*.olsv > zhansmpc.cn.8044: UDP, length 1252
20:24:36.288692 IP (tos 0x28, ttl 113, id 51800, offset 0, flags [DF], proto UDP (17), length 1280)
   *.*.*.*.olsv > zhansmpc.cn.8044: UDP, length 1252
20:24:36.288847 IP (tos 0x28, ttl 113, id 51801, offset 0, flags [DF], proto UDP (17), length 1280)
 *.*.*.*.olsv > zhansmpc.cn.8044: UDP, length 1252
20:24:37.903046 IP (tos 0x28, ttl 113, id 51823, offset 0, flags [DF], proto UDP (17), length 1280)
   *.*.*.*.olsv > zhansmpc.cn.8044: UDP, length 1252
20:24:37.903117 IP (tos 0x28, ttl 113, id 51824, offset 0, flags [DF], proto UDP (17), length 1280)
 *.*.*.*.olsv > zhansmpc.cn.8044: UDP, length 1252

**Comment by WoaShieShei** [comment]
https://v2.hysteria.network/zh/docs/advanced/Troubleshooting/

**Comment by ZHAN2006** [comment]
我的内核是更新了的内核 CentOS Linux (6.6.2-1.el7.elrepo.x86_64) 7 (Core)，但是上个月服务器没流量断网几天后重启这个月恢复之后就用不了了

**Comment by WoaShieShei** [comment]
https://1.1.1.1/ 
能进去吗

**Comment by ZHAN2006** [comment]
> https://1.1.1.1/ 能进去吗

服务器还是本地访问？

本地无法访问
服务器可以访问

**Comment by WoaShieShei** [comment]
本地不挂代理，直接使用浏览器访问服务端的这个端口，查看能不能显示反代的页面，另外可以尝试起一个正常的nginx看看是不是被墙端口了

**Comment by ZHAN2006** [comment]
可以访问

**Comment by ZHAN2006** [comment]
我尝试更换端口也不行

**Comment by WoaShieShei** [comment]
@ZHAN2006 先根据这个issue确定一下udp能不能通
https://github.com/apernet/hysteria/issues/747#issuecomment-1762000208
还有就是HTTP/3 QUIC 是否被阻断等问题(可以用nginx测试)，假设配置和hysteria软件版本都没有变更
那么首先需要排除链路上是否存在问题

**Comment by ZHAN2006** [comment]
udp HTTP/3 QUIC 都能连通

**Comment by WoaShieShei** [comment]
`HYSTERIA_LOG_LEVEL=debug /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml`
根据实际所在目录进行修改，随后客户端配置中把lazy去掉，观察服务端的日志行为

**Comment by ZHAN2006** [comment]
服务端 
2024-02-01T23:19:36+08:00       INFO    server mode
2024-02-01T23:19:36+08:00       INFO    server up and running   {"listen": "0.0.0.0:8044"}
2024-02-01T23:19:36+08:00       DEBUG   checking for updates    {"version": "v2.2.4", "platform": "linux", "arch": "amd64", "channel": "release"}
2024-02-01T23:19:36+08:00       DEBUG   no update available

客户端
2024-02-01T23:20:45+08:00       INFO    client mode
2024-02-01T23:20:50+08:00       FATAL   failed to initialize client     {"error": "connect error: timeout: no recent network activity"}

**Comment by ZHAN2006** [comment]
[root@vps ~]# tcpdump -i eth0 port 8044 -v
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
23:20:47.332404 IP (tos 0x28, ttl 113, id 4065, offset 0, flags [DF], proto UDP (17), length 1280)

    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252
23:20:47.536066 IP (tos 0x28, ttl 113, id 4066, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252
23:20:47.536397 IP (tos 0x28, ttl 113, id 4067, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252
23:20:47.937836 IP (tos 0x28, ttl 113, id 4071, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252
23:20:47.938295 IP (tos 0x28, ttl 113, id 4072, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252
23:20:48.751731 IP (tos 0x28, ttl 113, id 4074, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252
23:20:48.751793 IP (tos 0x28, ttl 113, id 4075, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252
23:20:50.354603 IP (tos 0x28, ttl 113, id 4079, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252
23:20:50.355314 IP (tos 0x28, ttl 113, id 4080, offset 0, flags [DF], proto UDP (17), length 1280)
    *.*.*.*.mpc-lifenet > zhansmpc.cn.8044: UDP, length 1252

通过抓包,服务器接收到了客户端的udp数据包但是服务端没有反应

**Comment by WoaShieShei** [comment]
把客户端的配置丢服务端上，然后在服务端上开客户端连接，看下行不行，rhel9目前暂时没法复现，明天开台Centos7试试

**Comment by ZHAN2006** [comment]
服务端
2024-02-02T00:14:46+08:00       INFO    server mode2024-02-02T00:14:46+08:00       INFO    server up and running   {"listen": "0.0.0.0:8044"}
2024-02-02T00:14:46+08:00       DEBUG   checking for updates    {"version": "v2.2.4", "platform": "linux", "arch": "amd64", "channel": "release"}
2024-02-02T00:14:46+08:00       DEBUG   no update available

客户端
2024-02-02T00:18:40+08:00       INFO    client mode
2024-02-02T00:18:40+08:00       FATAL   failed to initialize client     {"error": "connect error: INTERNAL_ERROR (local): write udp [::]:30561->127.0.0.1:8044: sendmsg: invalid argument"}

证书使用的是https://zerossl.com/的ip证书

**Comment by WoaShieShei** [comment]
@ZHAN2006 
`HYSTERIA_LOG_LEVEL=debug QUIC_GO_DISABLE_GSO=true QUIC_GO_LOG_LEVEL=DEBUG /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml` 
抱歉再打扰你一下，如果现在方便的话可以用这个命令再开一次服务端，还是一样客户端和服务端放同一物理机上
观察一下输出吗

我这里已经成功复现了
客户端为Windows
看起来问题和quic-go有关
服务端日志：
```
server GSO failed when sending to xxxx:52832
server Destroying connection with error: write udp [::]:443->xxxxx:52832: sendmsg: invalid argument
```

**Comment by WoaShieShei** [comment]
@ZHAN2006
根据这个 issue https://github.com/quic-go/quic-go/issues/3911
添加 QUIC_GO_DISABLE_ECN=true 环境变量后即可恢复正常
@tobyxdd 可以看一下吗

**Comment by WoaShieShei** [comment]
另外再次使用 `uname -a` 确认一下内核版本号，确定当前引导的内核版本

**Comment by ZHAN2006** [comment]
成功解决，非常感谢

当前系统内核
Linux vps 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

0 : CentOS Linux (6.6.2-1.el7.elrepo.x86_64) 7 (Core)
1 : CentOS Linux (3.10.0-1160.102.1.el7.x86_64) 7 (Core)
2 : CentOS Linux (3.10.0-1160.42.2.el7.x86_64) 7 (Core)
3 : CentOS Linux (0-rescue-114054dc5a87478f99adbbed6027eea0) 7 (Core)

之前升级系统内核之后没有重启，可能是我设置 grub 的引导顺序有问题

**Comment by ZHAN2006** [comment]
> 成功解决，非常感谢
> 
> 当前系统内核 Linux vps 3.10.0-1160.102.1.el7.x86_64 #1 SMP 2023 年 10 月 17 日星期二 15：42：21 UTC x86_64 x86_64 x86_64 GNU/Linux
> 
> 0：CentOS Linux （6.6.2-1.el7.elrepo.x86_64） 7（核心）1 ： CentOS Linux （3.10.0-1160.102.1.el7.x86_64） 7 （核心）2：CentOS Linux （3.10.0-1160.42.2.el7.x86_64） 7 （核心）3：CentOS Linux（0-rescue-114054dc5a87478f99adbbed6027eea0）7（核心）
> 
> 之前升级系统内核之后没有重启，可能是我设置 grub 的引导顺序有问题，这次务器没流量断网几天后我意外重启服务器才发现问题，非常感谢

我发现感情是服务器商家官方的重启系统会重启到原本的内核，但是如果在服务器用命令重启系统才会重启到自己设定的内核，无语了

**Comment by tobyxdd** [comment]
> @ZHAN2006
> 根据这个 issue https://github.com/quic-go/quic-go/issues/3911
> 添加 `QUIC_GO_DISABLE_ECN=true` 环境变量后即可恢复正常
> @tobyxdd 可以看一下吗

https://github.com/quic-go/quic-go/issues/4178

**Comment by WoaShieShei** [comment]
@tobyxdd 查询这个文件的内容就行了 `/proc/sys/net/ipv4/tcp_ecn` 当这个文件的内容为2的时候开启ECN

**Comment by WoaShieShei** [comment]
@ZHAN2006 3.x内核执行这个 `cat /proc/sys/net/ipv4/tcp_ecn` 显示是什么，可以看一下吗，我这里改动过了

**Comment by ZHAN2006** [comment]
> @ZHAN2006 3.x内核执行这个 `cat /proc/sys/net/ipv4/tcp_ecn` 显示是什么，可以看一下吗，我这里改动过了

[root@vps ~]# cat /proc/sys/net/ipv4/tcp_ecn
2
