### ISSUE TITLE
这样是启动成功了吗

### ISSUE THREAD

**Issue by YcccByHe** [apernet/hysteria#936]
root@ip-172-31-34-229:~# systemctl status hysteria-server.service
○ hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; disabled; preset: enabled)
     Active: inactive (dead)
root@ip-172-31-34-229:~# systemctl start hysteria-server.service
root@ip-172-31-34-229:~# systemctl status hysteria-server.service
● hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; disabled; preset: enabled)
     Active: active (running) since Sun 2024-02-04 07:53:06 UTC; 1s ago
   Main PID: 2456 (hysteria)
      Tasks: 4 (limit: 1141)
     Memory: 22.6M
        CPU: 59ms
     CGroup: /system.slice/hysteria-server.service
             └─2456 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml

Feb 04 07:53:06 ip-172-31-34-229 systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Feb 04 07:53:06 ip-172-31-34-229 hysteria[2456]: 2024-02-04T07:53:06Z        INFO        server mode
Feb 04 07:53:06 ip-172-31-34-229 hysteria[2456]: 2024-02-04T07:53:06Z        INFO        server up and running        {"listen": ":12443"}
这样是启动成功了吗，客户端还是无法连接

**Comment by stqfdyr** [comment]
看样子是启动成功了，参考如下试试
https://github.com/apernet/hysteria/issues/925#issuecomment-1917946953
