### ISSUE TITLE
hysteria2能和nginx共用443端口么？

### ISSUE THREAD

**Issue by hb-0** [apernet/hysteria#941]
**你的功能请求是否与某个问题有关？**
我知道nginx不能转发hysteria，而hysteria2的伪装功能可以将流量转发到一个后端网站。

可以将这个https站配置到本机nginx上的一个443x端口的站点，这就意味着一台机器上，只能有hysteria2和nginx中一个server可以共享443端口，而且这一https server的域名也必须和hysteria2使用的域名一致。

但nginx自己是支持根据ssl_preread_server_name来判断回落到不同端口的https server的，能否hysteria2和这一机制完美共存？

**描述你希望的解决方案**
当hysteria2发现443端口的请求进来，但使用的ssl域名不一致时，可以直接将流量转发到本机的nginx上的stream层监听的端口，由nginx来根据ssl_preread_server_name回落对应的https server。

**Comment by haruue** [comment]
我知道 nginx 可以通过 stream 匹配 sni 来把整个 TCP 连接转发到另一个端口来做 sniproxy， 但是 quic 并不是简单地把 TLS 用 UDP 发送， 而是一个全新的协议不可能把 TLS 流给 extract 出来， 所以不太行。

我个人的建议是 hysteria 启用伪装但是不要开 listenHTTP/listenHTTPS 和 acme 功能（这样 hysteria 就只会监听 UDP 443）， 然后你自己用 nginx 监听 TCP 80/443 手动配置伪装站点， 这样是不会冲突的， 证书的话可以用 acme.sh 签。

**Comment by haruue** [comment]
喔你的想法是用 nginx 的 stream 的 sniproxy 去反向代理 hysteria2 的伪装站， 这应该是可以的， 我会进行测试， 感觉应该还能通过 hysteria 的 acme 的 HTTP challenge。
