### ISSUE TITLE
启动没有日志打印

### ISSUE THREAD

**Issue by liulisanwan** [apernet/hysteria#948]
**描述问题**
启动了，但是没有看到server up 防火墙是关闭状态
![微信截图_20240222131129](https://github.com/apernet/hysteria/assets/87683535/9fafcb60-3dd1-483f-80fc-68d4a8117427)
![微信截图_20240222131040](https://github.com/apernet/hysteria/assets/87683535/7fbab667-9fea-4116-a0c4-d30180b4892d)
![微信截图_20240222131230](https://github.com/apernet/hysteria/assets/87683535/6f97dee5-a07f-495e-8abf-991434cf6ee6)

**如何复现**
复现问题的步骤。

**预期行为**
你认为修复后的行为应该是怎样的。

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
你在用什么设备和操作系统。

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by haruue** [comment]
你的截图显示服务应该已经启动， 用下面这条命令查看日志试试呢？

```bash
journalctl -e -u hysteria-server.service
```
