### ISSUE TITLE
命令行客户端用一段时间就报错退出

### ISSUE THREAD

**Issue by e7** [apernet/hysteria#949]
**描述问题**
用一段时间就退出

**如何复现**
没有确切的步骤，用一会就退了，时间长短不一

**预期行为**
每次重启客户端又可以继续使用，说明节点没问题，是可以恢复的错误，为何要退出呢？

**日志**
2024-02-23T11:28:06+08:00       ERROR   SOCKS5 TCP error        {"addr": "127.0.0.1:6463
3", "reqAddr": "static.dash.cloudflare.com:443", "error": "read tcp 127.0.0.1:50045->127
.0.0.1:64633: wsarecv: An established connection was aborted by the software in your hos
t machine."}

**设备和操作系统**
windows，命令行启动的客户端

**额外信息**

**Comment by haruue** [comment]
这个日志无法说明出了什么问题。 你可以试试不要双击 hysteria-windows-amd64.exe 启动客户端， 而是先在 hysteria-windows-amd64.exe 所在的文件夹， 按住 Shift 右键「在此处打开 PowerShell 窗口」， 然后通过 `.\hysteria-windows-amd64.exe` 启动 hysteria 客户端。 这样当 hysteria 客户端退出时， 就能看到实际上的报错。

**Comment by e7** [comment]
> 这个日志无法说明出了什么问题。 你可以试试不要双击 hysteria-windows-amd64.exe 启动客户端， 而是先在 hysteria-windows-amd64.exe 所在的文件夹， 按住 Shift 右键「在此处打开 PowerShell 窗口」， 然后通过 `.\hysteria-windows-amd64.exe` 启动 hysteria 客户端。 这样当 hysteria 客户端退出时， 就能看到实际上的报错。

是这么启动的，有时候一下午都不退，有时候几分钟就退了，怀疑是安全软件或者操作系统杀的

**Comment by haruue** [comment]
如果是安全软件杀的， 那不属于我们可以控制的范围， 你可以尝试把程序加入你使用的安全软件的白名单中。

如果真的是因为程序崩溃而退出的情况， Go 程序崩溃时， 通常都会输出调用栈（stacktrace）信息， 格式和正常的 log 有显著不同。 只要你是通过上述提及的方式启动 Hysteria 的， 那么程序退出后窗口就不会消失， 有调用栈的话应该是能看到的。

总之， 我们需要足够的信息来了解实际上发生了什么， 甚至需要在我们的设备上复现这个问题， 才可能解决它。

**Comment by hezhaozhao-git** [comment]
@haruue 
我也遇到了类似的问题，我在使用我自己包装的GUI（https://github.com/fagao-ai/kitty/releases）时，发现了这个问题，同样都是子进程启动，xray就不会自动退出，hysteria就会退出。尤其是M1 mac退出触发很频繁
