### ISSUE TITLE
[请求帮助] 使用代理后, hosts文件列表中阻止的域名都失效了

### ISSUE THREAD

**Issue by Davider-code** [apernet/hysteria#950]
对代理使用不太熟悉, 请路过的大佬指导, 谢谢
我是用的github上免费的梯子, 使用的hysteria和hysteria2的代理, 
我的是win10系统, hosts文件中有一些域名列表设置了阻止防问外网, 没开代理的时候, 阻止一切正常, 开代理后, 那些hosts列表中域名都开放了, 造成了很大的麻烦, 假设hosts文件中有下面的域名列表, 我应该怎样配置

0.0.0.0 api.think.com
0.0.0.0 think.com
127.0.0.1 www.sap.com
127.0.0.1 api.sap.com

**Comment by haruue** [comment]
这个仓库所提供的客户端自身没有图形界面或者能一键配置 Windows 全局代理的功能， 请问你是如何使用 hysteria 的？

如果你啥都不懂， 请把你使用的客户端窗口截图贴上来（可以给关键信息打码， 上传图片时请等待 Uploading XXX… 的提示消失后再提交）， 或许我们能提供更多帮助。

**Comment by Davider-code** [comment]
> 这个仓库所提供的客户端自身没有图形界面或者能一键配置 Windows 全局代理的功能， 请问你是如何使用 hysteria 的？
> 
> 如果你啥都不懂， 请把你使用的客户端窗口截图贴上来（可以给关键信息打码， 上传图片时请等待 Uploading XXX… 的提示消失后再提交）， 或许我们能提供更多帮助。
用这个批处理命令启动的 start %~dp0App\chrome.exe --proxy-server="socks5://127.0.0.1:1080"
截图如下
![s2](https://github.com/apernet/hysteria/assets/6350504/f40af57f-fa1f-4fb6-8787-f3c4f9494e38)
配置如下

{
  "server": "64.110.25.11:33337",
  "auth": "dongtaiwang.com",
  "tls": {
    "sni": "www.bing.com",
    "insecure": true
  },
  "quic": {
    "initStreamReceiveWindow": 16777216,
    "maxStreamReceiveWindow": 16777216,
    "initConnReceiveWindow": 33554432,
    "maxConnReceiveWindow": 33554432
  },
  "socks5": {
    "listen": "127.0.0.1:1080"
  },
  "transport": {
    "udp": {
      "hopInterval": "30s"
    }
  }
}

**Comment by haruue** [comment]
然后你是如何配置系统/浏览器代理的呢？ 浏览器里装 switchyomega 插件吗？

**Comment by Davider-code** [comment]
> start %~dp0App\chrome.exe --proxy-server="socks5://127.0.0.1:1080"

用下面这个命令启动浏览器后, 直接就可以用代理上网上了
 start %~dp0App\chrome.exe --proxy-server="socks5://127.0.0.1:1080"

**Comment by haruue** [comment]
直接让 chrome 使用 socks5 的情况下， 域名不会在本地解析， 也不会读取 hosts。

考虑到现在的 hysteria 不支持客户端测 acl。 
你可以给 chrome 安装一个 switchyomega 插件， 添加三个情景模式：

1. 代理。 填写 hysteria 的 socks5 （127.0.0.1:1080）， 另一个是
2. 代理。 这个要弄成无效的， 比如 socks5 255.255.255.254:23333。
3. 自动切换。 这个是分流， 把你要屏蔽的域名分流到上述第二项无效代理的情景模式。 最后添加一条规则把所有流量分流到上述第一项的 hysteria。

**Comment by haruue** [comment]
如果你不希望安装浏览器扩展程序， 那么你可以额外下载一个 v2ray， 配置成 inbounds 和 outboubds 都是 [socks](https://www.v2fly.org/config/protocols/socks.html)， 其中 outbound 配置到 hysteria 客户端的 socks5 地址。 然后使用 v2ray 的 [路由功能](https://www.v2fly.org/config/routing.html#routingobject) 配合 blackhole outbound 对你要屏蔽的域名进行屏蔽。

**Comment by haruue** [comment]
是的， v1 支持 acl ， 并且你的需求很容易编写。

你可以浏览 v1 的 acl 文档。
https://v1.hysteria.network/zh/docs/acl/

简单地说， 比如你通过 hosts 屏蔽以下域名

```
0.0.0.0 api.think.com
0.0.0.0 think.com
127.0.0.1 www.sap.com
127.0.0.1 api.sap.com
```

把前面这些 IP 地址换成 block domain 或者 block domain-suffix 即可。

```
block domain api.think.com
block domain think.com
block domain www.sap.com
block domain api.sap.com
```

**Comment by Davider-code** [comment]
> 是的， v1 支持 acl ， 并且你的需求很容易编写。
> 
> 你可以浏览 v1 的 acl 文档。 https://v1.hysteria.network/zh/docs/acl/
> 
> 简单地说， 比如你通过 hosts 屏蔽以下域名
> 
> ```
> 0.0.0.0 api.think.com
> 0.0.0.0 think.com
> 127.0.0.1 www.sap.com
> 127.0.0.1 api.sap.com
> ```
> 
> 把前面这些 IP 地址换成 block domain 或者 block domain-suffix 即可。
> 
> ```
> block domain api.think.com
> block domain think.com
> block domain www.sap.com
> block domain api.sap.com
> ```

多谢大佬, 谢在下面配置中的什么地方, 我没找到完整的示例配置文件, 太菜了...
{
    "server": "51.158.54.46:55396",
    "protocol": "udp",
    "up_mbps": 11,
    "down_mbps": 55,
    "http": {
        "listen": "127.0.0.1:1081",
        "timeout": 250,
        "disable_udp": false
    },
    "socks5": {
        "listen": "127.0.0.1:1080",
        "timeout": 250,
        "disable_udp": false
    },
    "obfs": "",
    "auth_str": "dongtaiwang.com",
    "alpn": "h3",
    "server_name": "youku.com",
    "insecure": true,
    "recv_window_conn": 115343360,
    "recv_window": 461373440,
    "disable_mtu_discovery": true,
    "resolver": "https://223.5.5.5/dns-query",
    "retry": 3,
    "retry_interval": 3,
    "quit_on_disconnect": false,
    "handshake_timeout": 15,
    "idle_timeout": 30,
    "fast_open": true,
    "hop_interval": 120
}

**Comment by haruue** [comment]
你需要把 acl 写在单独的文件里， 例如命名成 acl.txt 并保存在配置文件同一个目录下面， 然后在配置文件里， 像这样引用 acl 的文件。

```
"acl": "acl.txt",
```

hysteria 的所有选项都有中文说明。
https://v1.hysteria.network/zh/docs/advanced-usage/#%e5%ae%a2%e6%88%b7%e7%ab%af

**Comment by Davider-code** [comment]
> 你需要把 acl 写在单独的文件里， 例如命名成 acl.txt 并保存在配置文件同一个目录下面， 然后在配置文件里， 像这样引用 acl 的文件。
> 
> ```
> "acl": "acl.txt",
> ```
> 
> hysteria 的所有选项都有中文说明。 https://v1.hysteria.network/zh/docs/advanced-usage/#%e5%ae%a2%e6%88%b7%e7%ab%af

你好, 能再请教一个问题吗? 再次感谢
我的一个软件设置了如下图的hysteria代理后, 软件内部执行http的get请求会失败, 例如访问: http://localhost:4455/abc
![cc](https://github.com/apernet/hysteria/assets/6350504/7dc15f86-07e2-4abc-b9bc-1636467d91f5)
不设代理访问就没事, 因为我还需要在该软件中调用localhost本机的一些端口的服务

**Comment by haruue** [comment]
ACL 里加两行就可以了

```
direct domain localhost
direct cidr 127.0.0.0/8
```

参照 ACL 文档， 是中文的 https://v1.hysteria.network/zh/docs/acl/

**Comment by us254** [comment]
The environment variables you set in PowerShell should be in uppercase. Modify your code as follows:

# Set HTTP proxy
$env:HTTP_PROXY = "http://127.0.0.1:1081"
$env:HTTPS_PROXY = "http://127.0.0.1:1081"

# Set SOCKS5 proxy
$env:ALL_PROXY = "socks5://127.0.0.1:1080"

**Comment by us254** [comment]
For SOCKS5 proxy, set the socks_proxy variable instead of all_proxy:
`$env:socks_proxy = "socks5://127.0.0.1:1080"`

After setting the proxy variables, try this command to test access:
`Invoke-WebRequest -Uri "https://www.google.com" -UseBasicParsing`

. As an alternative test, try using curl with the socks5 proxy to rule out any PowerShell specific issues:
`curl --socks5 127.0.0.1:1080 https://www.google.com`
