### ISSUE TITLE
也許在QUIC中可以做到關閉SNI這個選項？

### ISSUE THREAD

**Issue by mkevinstever** [apernet/hysteria#951]
**你的功能请求是否与某个问题有关？**
在一些由中國大陸廠商提供的商業級別網路防火牆設備中，已經可以做到屏蔽QUIC的SNI了。並且在這些設備所構成的特定網路環境中，如果提供關閉SNI功能興許可以逃過特定策略的白名單限制。

**描述你希望的解决方案**
希望Hysteria作爲Client進行連線時，主程式配置檔中提供「關閉QUIC SNI」 這一選項。

**有没有其他替代方案**
開啓混淆效果並不好，發送無特徵的數據包和連接在中國大陸特定ISP干擾會十分嚴重。

**额外信息**
無

**Comment by haruue** [comment]
连 [OpenGFW](https://github.com/apernet/OpenGFW) 都支持识别 QUIC 的 SNI 了， 用不上中国大陆厂商提供的商业级别的防火墙。

在 Hysteria 客户端配置中的 `server` 选项中使用 IP 地址连接， 并且不要提供 `tls.sni` 这个选项， 那么 QUIC 的 ClientHello 中就没有 `server_name` 扩展。 TLS（TCP）也是这样。 因此不需要专门的「关闭 QUIC SNI」选项。
