### ISSUE TITLE
傳輸UDP的做法可以更好

### ISSUE THREAD

**Issue by ghost** [apernet/hysteria#952]
**你的功能请求是否与某个问题有关？**
目前Hysteria對於TCP的加速效果已經做的很不錯了，不過加速UDP的效果可以再優化。
目前，由於採取與轉發TCP流量同樣的傳輸機制，所以目前UDP傳輸的效果很差。

**描述你希望的解决方案**
個人認爲以下是對於傳輸UDP更好的做法，有幾個做法可以選擇，這幾種做法都可以提升UDP轉發的效果和速度：
1.對UDP的流量不使用任何加速機制，封裝在QUIC通道中，按「原樣」轉發，做法類似於當時的TUIC程式
2.對UDP的流量使用類似於kcp的機制進行加速，封裝在QUIC通道中

**有没有其他替代方案**
將UDP封裝在QUIC通道中，使用類似於FEC的機制確保該QUIC通道的傳輸可靠性，個人認爲這是最好的辦法，但是要想實現幾乎是不可能的，或者需要投入很大的開發成本

**额外信息**
優化UDP傳輸效能後，將可以極大提升使用者的體驗，同時也能確保能與大多數UDP應用所相容。

**Comment by haruue** [comment]
现时 Hysteria 对 UDP 的做法就是阁下提到的「1.對UDP的流量不使用任何加速機制，封裝在QUIC通道中，按『原樣』轉發」。

对 UDP 加 FEC 的做法开发组讨论过多次， 但是结论是不采用， 原因如下：

1. 绝大部分情况下， 中间路由器对 UDP 的丢包是将包作为一个整体丢弃， 而不是包内容进行修改或者截断。 因此， 在一个 UDP 包内做 FEC 是没有意义的。
2. 如果要用上 FEC 的话， 需要等待多个 UDP 包， 进行 FEC 算法之后重新分散到多个 UDP 包中再发送， 对于不少用例来说， 这会增加额外的延迟。

如果有需要的话用户可以自行套用 udpspeeder 这类工具。 至少现时我们不会考虑把 UDP FEC 内置于 Hysteria 中。

**Comment by lovexiaofan123** [comment]
@haruue 
如此这样的话，不如像类似于tuic那样，UDP分两种模式转发，一种楼主提到的UDP原生模式，给需要用到这部分的用户增强体验，虽然可能会有多开销，但不可舍取（在某些情况下可能利大于弊）。二种模式就是目前现有的方式进行传输，虽然不会额外的开销增加延迟，但UDP传输速度确实过慢，会导致部分用户问题。
还有个问题就是套了udpspeeder会丢失HY2本身对UDP封包加密，从而可能导致某些不可逆转的情况。
