### ISSUE TITLE
为什么设置了流量统计，但是请求：域名/traffic  一直显示404 page not found，还需要什么额外的操作吗？

### ISSUE THREAD

**Issue by sfindme** [apernet/hysteria#964]
我是刚刚使用的，对比其他的，真的很稳定和很好用，感谢大佬分享这么好的代码。

使用过程中我有个问题：
为什么设置了流量统计，但是请求：域名/traffic  一直显示404 page not found。
已经是验证通过了，如果验证不通过，会提示：unauthorized

这是我的服务器配置文件：

listen: :443
 
# 以下 acme 和 tls 字段，二选一
# 有域名部署的选择 acme ，无域名的选择 tls
# 选择 acme，必须注释掉 tls，反之一样
 
acme:
  domains:
    - 这是我的域名        # 域名
  email: your@email.com   # 邮箱，格式正确即可
  
auth:
  type: http
  http:
    url: 验证地址，这里我已经能认证了，并且返回了对应的用户信息 
    insecure: false 
   command: /etc/some_command  
  
//这里我也开启了监听地址，并且也是能监听到的，也通过授权authorized了
trafficStats:
  listen: :9999  
  secret: 1234

masquerade:
  type: proxy
  proxy:
    url: https://bing.com # 伪装网站
    rewriteHost: true
	
	

以上是可以正常使用的，就是请求接口获取不到流量统计的信息
请求：域名/traffic  
一直显示404 page not found。

请问是还需要什么额外的操作吗？
再次感谢大佬。

**Comment by haruue** [comment]
不是请求 `域名/traffic` 。

例如配置成

```yaml
trafficStats:
  listen: 127.0.0.1:9999 
  secret: ed9da2b7-676d-49d0-927a-eb78f319992b
```

要获取流量统计， 应该访问 trafficStats.listen 的端口。

```sh
curl -vv -H 'Authorization: ed9da2b7-676d-49d0-927a-eb78f319992b' http://127.0.0.1:9999/traffic
```

**Comment by sfindme** [comment]
感谢大佬答疑解惑，是只能在本机上获取是吧？如果要持久化，那还是需要做一个程序部署在机器上，然后获取流量信息之后，把他存入远程数据库中，是这样吗？

**Comment by sfindme** [comment]
trafficStats:
  listen: 127.0.0.1:9999 
  secret: ed9da2b7-676d-49d0-927a-eb78f319992b


能不能把127.0.0.1:9999 改成：我的web网站的地址:80，这样呢？直接把数据发送到我的接口上

**Comment by sfindme** [comment]
好的，了解了，感谢，我自己在本地服务器机器上写一个定时获取的发送到自己的接口上

**Comment by haruue** [comment]
> 能不能把127.0.0.1:9999 改成：我的web网站的地址:80，这样呢？直接把数据发送到我的接口上

Hysteria 2 不支持推送式的流量统计 API， `trafficStats.listen` 是监听一个 TCP 端口， 在这个端口上启动 HTTP 服务， 提供 [文档][1] 所述的统计 API。

请参考 Hysteria 2 的 [流量统计 API 文档][1]， 是中文的。

[1]: https://hysteria.network/zh/docs/advanced/Traffic-Stats-API/

> 是只能在本机上获取是吧？

不一定要本机上获取， 可以将 `trafficStats.listen` 设置为一个非 `127.0.0.1` 的地址， 例如使用下面的配置文件， 就可以直接通过 `http://服务器公网IP:9999/traffic` 访问流量统计。

```yaml
trafficStats:
  listen: :9999
  secret: ed9da2b7-676d-49d0-927a-eb78f319992b
```

请注意流量统计端口的请求不加密， 直接通过公网访问会将密码在公网上明文传输产生安全隐患。 对于通常的用户， 我个人建议监听环回地址 `127.0.0.1`。 如果对于机场用户， 可以考虑先用 WireGuard 之类的 VPN 软件把所有节点组网互通， 然后将 `trafficStats.listen` 设置为 WireGuard 接口的 IP 地址， 控制节点通过 WireGuard 访问 Hysteria 的流量统计 API。

> 如果要持久化，那还是需要做一个程序部署在机器上，然后获取流量信息之后，把他存入远程数据库中，是这样吗？

是的。 如果要持久化， 是必须在获取流量信息之后， 自行存入数据库的。 Hysteria 统计的流量会在每一次服务端重启或者访问 `/traffic?clear=1` 后重置。

**Comment by sfindme** [comment]
不一定要本机上获取， 可以将 trafficStats.listen 设置为一个非 127.0.0.1 的地址， 例如使用下面的配置文件， 就可以直接通过 http://服务器公网IP:9999/traffic 访问流量统计。

上面的说的，我用http://服务器公网IP:9999/traffic 访问流量统计。提示404 page not found

**Comment by sfindme** [comment]
配置要写成
trafficStats:
  listen: 服务器公网IP:9999
  secret: ed9da2b7-676d-49d0-927a-eb78f319992b

这样吗？

**Comment by sfindme** [comment]
可以了，不好意思，我地址打错了，非常感谢。

**Comment by sfindme** [comment]
感动落泪，真的太感谢您的帮助了

**Comment by us254** [comment]
@sfindme  https://github.com/apernet/hysteria/discussions/972
