### ISSUE TITLE
hysteriav2 tls: failed to verify certificate: x509: certificate signed by unknown authority when using CA cert 

### ISSUE THREAD

**Issue by repliqa** [apernet/hysteria#966]
**Describe the bug**
I want to setup a hysteriav2 server with a self signed certificate, without using a domain name. I want the connection to be secure, not prone to MITM attacks. So I setup a self signed CA and server following https://v1.hysteria.network/docs/custom-ca/. I copied the CA cert to the client and tried to connect to the server, however I'm getting TLS error saying the certificate is signed by unknown authority.

**To Reproduce**
https://v1.hysteria.network/docs/custom-ca/ on hysteria2

**Expected behavior**
Not getting TLS errors, client being able to proxy through hysteriav2 server.

**Logs**
Nekoray's client side logs:
`[Warning] [4156035736] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 4
tcp:127.0.0.1:60440 accepted tcp:34.117.118.44:80 [socks-in -> proxy]
ERROR	SOCKS5 TCP error	{"addr": "127.0.0.1:43416", "reqAddr": "34.117.118.44:80", "error": "connect error: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority"}`

Server logs: none

**Device and Operating System**
OpenBSD VPS running on VMD

**Comment by haruue** [comment]
Please add the following lines to your client configuration file

```yaml
tls:
  insecure: true
```

If the problem persists, please provide your server & client config for further assistance.

**Comment by repliqa** [comment]
@haruue 
I did add that line, in which case it does work. But won't the certificate be ignored and the client would just connect to the server without verifying if I do? (I did test with a wrong certificate and the connection is still established). Sorry if this question seems stupid but I didn't find the docs that answer it.

**Comment by haruue** [comment]
You can specify your own CA file for TLS verification in the client configuration file:

```yaml
tls:
  ca: custom_ca.crt
```

You can also pin the server certificate's SHA-256 fingerprint. 

```yaml
tls:
  pinSHA256: BA:88:45:17:A1:...
```
+ The fingerprint is generated by
  ```sh
  openssl x509 -noout -fingerprint -sha256 -in server.crt
  ```

Please refer to our document for details: 
https://hysteria.network/docs/advanced/Full-Client-Config/#tls

**Comment by haruue** [comment]
![Hysteria-website-annotation](https://github.com/apernet/hysteria/assets/13131972/d998d2b3-1708-484b-80ac-af3175dbc8b2)
