### ISSUE TITLE
Hysteria log is populated with these ERROR messages: "Application error 0x0 (remote)"

### ISSUE THREAD

**Issue by solus-hq** [apernet/hysteria#988]
Hello! While inspecting my hysteria docker container I came across lots of repeating ERROR messages of this type:  

```
ERROR	TCP error	{"addr": "xxx.xxx.65.177:46996", "id": "user", "reqAddr": "xxx.xxx.74.74:443", "error": "readfrom tcp4 xxx.xxx.110.88:46278->xxx.xxx.74.74:443: Application error 0x0 (remote)"}
```

I'd like to know if it's regular behaviour or not.

**Comment by tobyxdd** [comment]
Are you using a 3rd-party app on the client side? Some 3p client implementations are known to cause this, but it's not really a problem
