### ISSUE TITLE
Enhancing Security: Customization of TLS Versions, Cipher Suites, and Headers

### ISSUE THREAD

**Issue by Sortnz** [apernet/hysteria#990]
**Is your feature request related to a problem? Please describe.**
Yes, the current implementation of the ACME protocol stack in hysteria2 supports TLS versions 1.3, 1.2, 1.1, and 1.0. However, this broad support raises concerns regarding security best practices and modern standards. Specifically, the inclusion of TLS 1.1 and 1.0, which are considered outdated and less secure, could potentially expose users to vulnerabilities. Additionally, the inability to customize TLS version values and Cipher suite values limits the flexibility for users who may require specific configurations for compliance or security reasons.

**Describe the solution you'd like**
I propose two potential solutions to address these concerns:
1. Enable the customization of TLS version values and Cipher suite values within hysteria2's ACME protocol stack. This would allow users to specify their preferred and required configurations, ensuring both compliance and security.
2. If customization is not feasible, I suggest updating the default configuration to align with security best practices. This would involve disabling support for TLS 1.1 and 1.0, as well as the TLS 1.2 Cipher suites `TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA` and `TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA`, which are no longer recommended.

**Describe alternatives you've considered**
An alternative would be to maintain the current support for all TLS versions but provide clear documentation and warnings about the risks associated with using deprecated TLS versions and Cipher suites. This approach would educate users on the potential security implications while still offering the flexibility to choose their configurations.

**Additional context**
In the context of hysteria2's obfuscation mode, the Headers currently only support `Strict-Transport-Security` and `X-Content-Type-Options`. I would like to see support for custom Headers to enhance security further. If custom Headers are not an option, the default configuration should include robust security headers such as `Content-Security-Policy`, `X-Frame-Options`, `Referrer-Policy`, and `Permissions-Policy`, which are essential for protecting web applications from common vulnerabilities.

**Comment by tobyxdd** [comment]
Thanks for your feedback, but at this time we are not accepting issues from ChatGPT
